### ISSUE TITLE
Migrar o repositório do Gitlab para cá

### ISSUE THREAD

**Issue by avaloni** [culturagovbr/salic-minc#1]
## MIGRAÇÃO SALIC

- SEGURANÇA
 -- ARQUIVOS COM SENHAS E DADOS SIGILOSOS

- META
 -- Atualização do ambiente de desenvolvimento e homologação

## Arquivos
 - Application.ini_exemplo
 - Buscar arquivos que conectam diretamente na receita.
 - 

## GIT

- [x] Criar repositório no github (verificar repositório existente)
- [x] git clone para a máquina
- [x] Pra Adicionar um remote pra cada branch para fazer checkout delas no novo repositório
- [x] Sobrescrever commits de arquivos que não desejamos que sejam visíveis
- [x] Push de cada branch para versionar as branchs no 

## Jenkins

- [x] Alterar a url do repositórios para os dois serviços
- [x] Testar

## Comunicação

- [x] Comunicar para os devs que à partir da migração será utilizado o novo repositório no github
- [x] Orientar equipe sobre a nova forma de trabalhar com Issues e Project

## Github

- [x] Acessar Confirações do github de cada usuário
- [x] Acessar os e-mails vinculados a conta
- [x] Adicionar um e-mail secundário à conta.
    * E-mail por extenso: nome.sobrenome@cultura.gov.br 
    * CPF: 01569364984@@cultura.gov.br 
- [x] Confirmar e-mail de confirmação enviado pelo github

**Comment by vinnyfs89** [comment]
Concluímos as Atividades dessa Issue.
