### ISSUE TITLE
[HOTFIX] - COMPROVAÇÃO FINANCEIRA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1001]
**PROBLEMA**

O mesmo item orçamentário  existe  em duas etapas diferentes. 

O proponente lança na  etapa **Pré-Produção / Preparação**  e aparece também na etapa **Execução**, veja a tela abaixo.

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/69281a08-272a-4caf-8892-d3428c9a93cc)

**SOLUÇÃO**

Incluir mais duas restrições nas cláusula where : 

	 AND cdEtapa = [codigo da etapa]

	 AND cdUF  = [código da uf]

Segue a query ajustada

SELECT vwComprovacaoFinanceiraProjetoPorItemOrcamentario.*,vwComprovacaoFinanceiraProjetoPorItemOrcamentario.nmFornecedor AS Descricao, 
vwComprovacaoFinanceiraProjetoPorItemOrcamentario.nrCNPJCPF AS CNPJCPF, vwComprovacaoFinanceiraProjetoPorItemOrcamentario.dsJustificativaProponente AS dsJustificativa, 
vwComprovacaoFinanceiraProjetoPorItemOrcamentario.dsOcorrenciaDoTecnico AS ocorrencia, vwComprovacaoFinanceiraProjetoPorItemOrcamentario.tpDocumento AS tipoDocumentoNome, 
vwComprovacaoFinanceiraProjetoPorItemOrcamentario.nrcnpjcpf AS CNPJCPF 
FROM SAC.dbo.vwComprovacaoFinanceiraProjetoPorItemOrcamentario 
WHERE    cdProduto = '19' 
     AND idPlanilhaItem = '6329' 
	 **AND cdEtapa** = '1'
	 **AND cdUF**  = '35'
	 AND cdCidade = '355030' 
	 AND IdPRONAC = '208835'

**PRONAC PARA TESTAR**

PRONAC 170720 

PROPONENTE - IMM LIVE LTDA

**Comment by clebersantos** [comment]
Disponível para homologação.

**Comment by pauli10** [comment]
Homologado.

**Comment by clebersantos** [comment]
@romulomb, pode subir?

**Comment by romulomb** [comment]
**HOMOLOGADO.**

PODE SUBIR.

MUITO OBRIGADO.
