### ISSUE TITLE
[Prestação de contas] Visualização de Demandas Prioritarias Prestação de contas

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1003]
Incluir em todos painel o campos **Prioridades**

Ao clicar no link Prioridades mostrar a informações das Prioridades.

![Controle.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2271fdcc-dbb2-48b5-9453-ae114cd8c9d3)

![controle_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bf869998-2727-4035-8736-f34c2659ef84)

![Controle_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/4594866c-9a7c-4f94-8aa9-c9304b201cd7)

**Comment by romulomb** [comment]
Pedrinho por favor estimar depois de analisar tecnicamente.

**Comment by Pedro-Philipe** [comment]
@romulomb poderia me passar as querys e os dados dessas consultas para eu poder estimar?

**Comment by romulomb** [comment]
Segue a query conforme solicitado

SELECT idDemanda,idPronac,PRONAC,NomeProjeto,Proponente,cdSituacao,Situacao,DtSituacao,ProvidenciaTomada,Orgao,Sigla,Controladores,DocumentoSolicitacao,NrDocumentoSolicitacao,DtSolicitacao,
       Constatacao,DocumentoResposta,NrDocumentoResposta,DtResposta,Resposta,vlAprovado,vlCaptado,vlComprovado
  FROM SAC.dbo.vwDemadasDeOrgaoDeControle
 WHERE idPronac = 207087

**Comment by Pedro-Philipe** [comment]
issue pausada para verificações no salic mobile

**Comment by romulomb** [comment]
@Pedro-Philipe Ok

**Comment by romulomb** [comment]
HOMOLOGADO
