### ISSUE TITLE
Solicitação de Desarquivamento 

### ISSUE THREAD

**Issue by donbarata** [culturagovbr/salic-minc#1007]
A outra issue foi fechada, mas o problema persiste no sistema. Preciso desse acesso o quanto antes. Alguém pode me ajudar?

![e969fdcd-93a6-4eba-8f45-d98d2b3e5976](https://user-images.githubusercontent.com/40779099/42425144-d2157fce-82ee-11e8-9335-059e771b278b.png)

**Comment by wouerner** [comment]
Qual seria o problema que está relatando? Não carrega as propostas arquivadas?

**Comment by romulomb** [comment]
Quem disse que o.problrma existe?

**Comment by Pedro-Philipe** [comment]
@donbarata O problema persiste? Poderia confirmar se ainda está ocorrendo esse problema, pois fizemos algumas alterações que provavelmente já corrigiu. Obrigado.

**Comment by romulomb** [comment]
**DEMANDA NÃO PODERÃO SER FEITAS PELOS PROPONENTES.**
