### ISSUE TITLE
[Assinatura] Readequação - Corrigir Orgao Superior

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#1008]
Eu como Analista de Sistemas identifiquei que o orgão superior definido para o identificador do tipo de ato administrativo 653 está definido como 251 e o correto é 92. 
Por gentileza verificar.

**Comment by romulomb** [comment]
@vinnyfs89  Vini está correto.  Começa na vinculada e termina na Secretaria.

Veja a figura abaixo.

![Ato.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d86e20a1-3bf0-4b0a-aae0-734bfbf16d3f)

**Comment by vinnyfs89** [comment]
@romulomb Mas você mencionou o orgao do assinante, estou me referindo ao orgao superior

**Comment by romulomb** [comment]
@vinnyfs89 Qual ´órgão superior?


Até a 3ª assinatura o órgão superior é o da vinculada, no exemplo é 92.

A 4ª e a 5º assinatura o órgão superior é o da secretaria no exemplo  é 251.

**Comment by romulomb** [comment]
Sempre é o ´órgão superior de quem estiver logado.

**Comment by vinnyfs89** [comment]
@romulomb Nao... voce n entendeu... a issue foi aberta porque no banco no ato administrativo o orgao superior no ambiente de homologação esta como 251 e deveria ser 92

**Comment by romulomb** [comment]
@vinnyfs89  UFA, entendido e corrigido na homologação
