### ISSUE TITLE
Diligência Todos os itens

### ISSUE THREAD

**Issue by RuanHerculano** [culturagovbr/salic-minc#1013]
**Check List**
- [ ] Novo layout
- [ ] Nova consulta

**Comment by marcusvinicus** [comment]
Essa issue está relacionada com qual ??? @RuanHerculano @wouerner

**Comment by wouerner** [comment]
@marcusvinicus Essa é uma issue que criei como melhoria para processo de diligencia. mas essa melhoria e opcional.
