### ISSUE TITLE
Novo Cadastro de fornecedor

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#1015]
Novo Cadastro de fornecedor

**Comment by volthier** [comment]
Conforme verificação durante andamento do desenvolvimento do cadastro constatou-se que:

- Referencia de localidades em bases distintas com informações discrepantes;
- Necessidade de validação de Informação atualizada;
- Convergência das informações para uma das bases como necessário para consulta da aplicação.

As Bases identificadas foram:

-> AGENTES > tabela UF

```SELECT "uf"."iduf" AS "id", "uf"."sigla" AS "descricao" FROM "AGENTES"."dbo"."uf"```

-> BDDNE > schema scnDNE > VIEW(VW_ENDERECO) 

```SELECT "vw_endereco"."cep", "vw_endereco"."logradouro", "vw_endereco"."tipo_logradouro",
  "vw_endereco"."bairro", "vw_endereco"."cidade", "vw_endereco"."uf", "vw_endereco"."idcidademunicipios",
  "vw_endereco"."dscidademunicipios", "vw_endereco"."idcidadeuf",
  "vw_endereco"."dscidademunicipios" AS "dscidadeuf" FROM "bddne"."scdne"."vw_endereco" WHERE (cep = '69960000')```

**Comment by volthier** [comment]
Após verificação com área técnica, o desenvolvimento se dará com o apontamento para a base 
-> BDDNE > schema scnDNE  para os assunto referentes a localidade.

**Comment by romulomb** [comment]
@volthier Porque usar o banco BDNE?

**Comment by wouerner** [comment]
Segundo o Herom e banco correto, que teria os dados mais atualizados, segundo dados dos correios.

**Comment by romulomb** [comment]
**AJUSTE**

Quando o fornecedor não existir na nossa base de dados, a aplicação deverá buscar os dados na receita federal por meio do web service.

**PRIORIDADE ZERO**

**Comment by romulomb** [comment]
**CONTINUA COM O MESMO RELATADO ANTERIORMENTE**

Quando o fornecedor não existir na nossa base de dados, a aplicação deverá buscar os dados na receita federal por meio do web service.

**Comment by wouerner** [comment]
Demanda em impedimento, até reunião que vai ser marcado pelo Romulo.

**Comment by romulomb** [comment]
**PASSO 1**
![Passo_1.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f10b5f68-c7ca-4545-8337-46bbb168e91a)

**PASSO 2**

![Passo_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/cdbac00a-dbb6-4321-8f2e-76b85365b068)

**PASSO 3**

![Passo_3.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6d6b5251-c52d-4938-bee8-cf628061a4e8)

**Comment by romulomb** [comment]
**PODE VIR AGORA NA SEDE, ESTOU ESPERANDO, PORQUE ESSA ISSUE É PRIOTÁRIA**

**Comment by wouerner** [comment]
Analise efetuada, encontrei pontos divergentes nesse cadastro, estou seguindo o modelo de cadastro do proponente (administrativo>> cadastrar proponente).

**Comment by romulomb** [comment]
**A aplicação está perdendo o usuário logado**

1. No cadastro de fornecedor como demonstrado no passo 3 do comentário acima;

2.  Na sequencia de telas abaixo.

![comprovacao_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b2c2c0bc-993e-4575-b09b-ac64d4e90f53)

![comprovacao_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/cf21c46a-d223-406f-af5a-39aa9c83bae6)

**Comment by wouerner** [comment]
Estou analisando.

**Comment by wouerner** [comment]
Romulo identifiquei e estou resolvendo.

**Comment by romulomb** [comment]
Ainda há alguns pequenos ajustes para finalizarmos.

**Comment by romulomb** [comment]
**AJUSTES**

**NACIONAL**

Passo 1 - descrito na figura abaixo.

![Passo_1.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/40ebceda-6967-4e33-a015-ea8db8ac5534)

Passo 2 -  descrito na figura abaixo

![Passo_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/69d46131-d017-4edf-8f61-be436ff9c222)


**INTERNACIONAL**

Descrito na figura abaixo.

![Passo_3.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3df6e3e1-b226-48b5-9c7f-92a9071bce76)

**Comment by wouerner** [comment]
Problemas reolvidos, esperando feedback.

**Comment by romulomb** [comment]
**AJUSTES**

**NACIONAL**

Passo 1 - **ATENDIDO**

------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------

**AINDA PENDENTES**

Passo 2 -  descrito na figura abaixo

![Passo_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/69d46131-d017-4edf-8f61-be436ff9c222)


**INTERNACIONAL**

Descrito na figura abaixo.

![Passo_3.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3df6e3e1-b226-48b5-9c7f-92a9071bce76)
