### ISSUE TITLE
Erro botão voltar Modulo de prestação de contas

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#1055]
O botão voltar no modulo de prestação de contas financeira esta apresentando comportamento anormal, trocando entre telas de comprovação inicial e analise do tecnico de prestação de contas.

**Comment by pauli10** [comment]
@wouerner 
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/c84d4a27-8401-487d-9603-7c69c609430a)

**Comment by pauli10** [comment]
O erro persiste.

**Comment by wouerner** [comment]
Por favor, testar novamente.

**Comment by romulomb** [comment]
**Continua com o mesmo problema**

Para testar:

1. clique em um item para comprovar,

2. dentro da tela do item a comprovar clique no botão voltar 

3. após voltar para a tela anterior clique novamente no botão voltar.

4. deveria voltar para a tela de consultar dados do projeto.
