### ISSUE TITLE
[PRESTAÇÃO DE CONTAS] - FINALIZAR AVALIAÇÃO FINANCEIRA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1065]
**PERFIL DO TÉCNICO  DE PRESTAÇÃO DE CONTAS**

Ao clicar no ícone  **Finalizar** a aplicação deverá disponibilizar ao usuário a tela **Avaliação Financeira - Emissão de Parecer** para que o técnico redija o parecer técnico da avaliação financeira.

A tela a ser disponibilizada deverá conter a informações e as disposições dos campos conforme figura anexada abaixo.

**OBS:**

Tipo de Avaliação (Todos os comprovantes ou por amostragem)

Manifestação deverá ser:

Codigo = R para Reprovação;
Codigo = A para Aprovação;
Codigo = P para Aprovação com ressalva.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/409b4cfa-629a-4e18-ac69-163cd1c290ae)

**Segue a query que retornará as informações a ser renderizadas na tela.**

sql
' SELECT IdPronac,Pronac,NomeProjeto,CnpjCpf,Proponente,qtTotalComprovante,qtComprovantesValidadosProjeto,qtComprovantesRecusadosProjeto,
        qtComprovantesNaoAvaliados,vlComprovadoProjeto,vlComprovadoValidado,vlComprovadoRecusado,vlNaoComprovado
 FROM sac.dbo.vwResultadoDaAvaliacaoFinanceira WHERE IdPRONAC = [idPronac]'

Ao informações do parecer emitido pelo técnico deverão ser inseridas no banco SAC na tabela **tbAvaliacaoFinanceira** e seus atributo deverão ser carregados conforme descrito abaixo:

idAvaliacaoFinanceira = autoincremento
idPronac                    = idPronac do projeto
dtAvaliacaoFinanceira = getdate()
tpAvaliacaoFinanceira = 0 para todos comprovantes ou 1. para amostragem
siManifestacao            = A - Aprovado; P - Aprovado com ressalvas; R - Reprovado
dsParecer                   = Parecer digitado pelo técnico
idUsuario                    = id do usuário logado

Após a emissão do parecer, a aplicação deverá gerar o documento para assinatura  conforme a template abaixo.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2728df32-167c-4696-9d78-b57226f6ebb3)

O ato administrativo para essa assinatura o ¨¨622 - Parecer de Avaliação Financeira**

Após a assinatura o projeto deverá ser encaminhado ao **Coordenador de Prestação de Contas¨¨ para avaliação.

Ao ser encaminhado ao Coordenador as informações abaixo na tabela **Projetos** deverão ser alteradas.

Situacao = E91
ProvidenciaTomada = Análise financeira concluída
dtSituacao = getdate()
Logon = id do usuario logado

--------------------------------------------------------------------------------------------

**F L U X O   D A   A V A L I A Ç Ã O   F I N A N C E I R A**

[https://app.zenhub.com/files/104502087/f5808b22-3d53-484b-b548-37c8d198b52e/download](https://app.zenhub.com/files/104502087/f5808b22-3d53-484b-b548-37c8d198b52e/download)

----------------------------------------------------------------------------------------------

**SITUAÇÕES**

**PARA FILTRO Aguardando Análise**

Situação : **E68**

**PARA FILTRO Em análise**

Situação : **E27**
Providência Tomada : 'Inicia-se análise financeira.'

Situação : **E17**
Providência Tomada : 'Diligenciado na análise financeira.'

Situação : **E20**
Providência Tomada : 'Inadimplente por não responder diligência financeira.'

**PARA FILTRO Analisados**

Situação : **E91**
Providência Tomada : 'Encaminhado para o Coordenador  de Avaliação Financeira'

Situação : **E92**
Providência Tomada : 'Encaminhado para o Coordenador - Geral de Avaliação de Resultados'

**Comment by wouerner** [comment]
@romulomb , @Romulo_Menho , Essa demanda não estava nesse pacote, temos alguma prioridade aqui?

**Comment by romulomb** [comment]
**Sim tem prioridade**.

A issue 1065 especifica parte do que foi solicitado na demanda da issue 815. 

O que está especificado acima se refere a finalização da análise financeira executada pelo técnico  e da validação do parecer técnico pelo coordenador de prestação de contas .

Existe um outra especificação que subirei em uma nova issue que tratará do Laudo Final de Avaliação Resultado.

**Comment by romulomb** [comment]
Fiz um pequeno ajuste na definição.

Troquei os valores do código da manifestação técnico para igual a manifestação da avaliação do objeto.

Portanto ficou conforme demonstrado abaixo.

**ERA ASSIM**

Manifestação deverá ser:

Codigo = 1 para Desfavorável;
Codigo = 2 para Favorável;
Codigo = 3.para Favorável com ressalva.

**FICOU ASSIM**

Manifestação deverá ser:

Codigo = R para Reprovação;
Codigo = A para Aprovação;
Codigo = P para Aprovação com ressalva.

**Comment by romulomb** [comment]
**RETIRA LINK DO MENU SUPERIOR  E ALTERAR O NOME DO LINK DO MENU SUPERIOR**

Conforme a figura  abaixo.

![Avaliacao.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c7bf5521-573c-4241-88f9-65b969aebbcf)
