### ISSUE TITLE
[FIX] Erro ao transformar proposta em projeto

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1067]
Foi reportado pela @AdmissibilidadeSAV que o sistema apresenta erro ao transformar a proposta 277330 em projeto.

Obs: O erro ocorre apenas na proposta informada.

Ambiente: Produção
Navegador: Google Chrome
Url: salic.cultura.gov.br/
Perfil: Coordenador-Geral de Admissibilidade e Aprovação (Vicente)
Unidade: SEFIC/GEAAP/SUAPI/DIAAPI 

Print do erro: ![photo_2018-07-13_17-20-53.jpg](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/e7b4b47a-c849-4f9e-a67a-581499f3643c)

**Comment by clebersantos** [comment]
O erro ocorre devido ao cadastro do proponente estar com idUsuario igual à zero. Verifiquei também que este problema é recorrente. 

Sugestões para resolver definitivamente:
- [ ] na admissibilidade, criar uma validação que verifica se o proponente possui usuário válido antes de transformar a proposta em projeto, se não tiver, o sistema deve apresentar opção para o técnico/coordenador vincular um usuário para o proponente
  - quando for pessoa física, disponibiliza a opção de um usuário com o mesmo CPF do proponente.
 - quando for pessoa jurídica, disponibiliza a lista de dirigentes e o técnico seleciona o dirigente que será o usuário responsável pelo proponente.

- [ ] criar chave estrangeira e tornar o campo `Usuario` obrigatório na tabela `agentes`.

- [ ] mapear todos os formulários que salvam na tabela `agentes`.

**Comment by boletocosta** [comment]
Só para acrescentar que estou com o mesmo erro na proposta 277330.

E esse erro é mesmo recorrente...

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV e @boletocosta, disponibilizei no ambiente de homologação uma funcionalidade que permite a correção do Agente que não tem usuário cadastrado. 

Forcei as propostas 276765 e 272578 (SEFIC DIAPPI) a terem o mesmo problema da 277330 
para vocês homologarem a funcionalidade.

Façam a análise de admissibilidade normalmente.

**Comment by boletocosta** [comment]
Oi Cleber. A ferramenta disponibilizada em homologação está funcionando.

**Comment by romulomb** [comment]
HOMOLOGADO

**Comment by boletocosta** [comment]
Esse fix vai subir na próxima atualização?

**Comment by boletocosta** [comment]
@clebersantos Bom dia! Mesmo após versão 5 continuo sem conseguir transformar essa proposta (277330)  em projeto, pois a ferramenta que permite a correção do agente que não tem usuário cadastrado não disponibiliza nenhum usuário ao realizar o procedimento. No campo usuário só aparece a opção "selecione" e ao clicar não oferece nenhuma outra opção.

Além dessa proposta também não estou conseguindo transformar em projetos as propostas 283425 e 282972. Após clicar no botão transformar nada acontece. 

Pode verificar, por gentileza?

Obrigado.
