### ISSUE TITLE
[Login] - Ajustes de layout com pequeno impacto de acordo com estudos do Lappis/UNB

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1077]
Eu como Analista de sistemas do SALIC, identifiquei que é possível executar parcialmente os ajustes  propostos pelo relatório de Detalhamento da avaliação heurística do cadastro de proposta realizado pelo laboratório Lappis - UNB.

As alterações de pequeno impacto são:

### Tela de login
 - [x] Substituir "Login" por uma frase do tipo "Entre" ou "Entre no SALIC"
 - [x] Nos links "Não sou Cadastrado" e "Esqueci a senha" usar verbos de ação no infinitivo para melhorar a clareza dos botões. Exs.: "Cadastrar-se" e "Recuperar senha"
- [x] (Se possível) Reposicionar o campo "Recuperar senha" para abaixo do campo de senha
- [x] Nas labels "Login" e "Nova senha" melhorar o contraste entre as cores
- [x] Na opção de recuperar senha acrescentar uma frase explicando o processo. Exs.: "Preencha o formulário para receber sua senha no e-mail cadastrado", "Identifique-se para gerar uma nova senha".
- [x] Na opção de recuperar senha e cadastro substituir "Já sou cadastrado" por "Voltar"
- [x] Criar opção do usuário visualizar a senha

Este estudo é referente à [Etapa I do projeto Lappis - UNB](https://github.com/lappis-unb/EcossistemasSWLivre/wiki#etapa-1---e1). Relatório completo disponível [aqui](https://github.com/lappis-unb/EcossistemasSWLivre/blob/master/Relatorios/R1/anexos/Detalhamento%20da%20avalia%C3%A7%C3%A3o%20heur%C3%ADstica%20do%20cadastro%20de%20proposta.pdf).

Os outros ajustes serão cadastrados em uma nova issue.

**Comment by FernandaLA** [comment]
@romulomb, foram realizados ajustes na tela de login de acordo com os estudos do Lappis/UNB. Você pode homologar?

**Comment by romulomb** [comment]
Homologado.
