### ISSUE TITLE
Ajusta na tela de comprovantes de pagamento

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#1080]
![pc-nova-tela-comprovantes.png](https://images.zenhubusercontent.com/5a5656d44b5806bc2bc23d4a/020e27d7-eef6-4178-ab49-9deed05c860d)

**Comment by romulomb** [comment]
**AJUSTES**

**Na inclusão do comprovante formatar os campos  de data com o formato data   e valor do item como moeda**

![comprovacao_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/dca76b9e-3c84-4b45-b325-84c869c4d3d6)

**Edição  ajustar o posicionamento dos campos, formatar como moeda o valor do item e mostrar toda a justificativa**

O campo de justificativa quando tem mais uma linha só aparece a 1º linha. Para descobrir que tem mais linhas é necessário  dar um enter no campo.

![comprovacao_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c4b09c53-97ef-47d5-936e-21dac3e582e4)

**Comment by RuanHerculano** [comment]
@romulomb Entrei em contato no Telegran para tirar uma dúvida referente ao alinhamento, onde não foi possível abstrair a disposição dos elementos segundo as informações supracitadas.

**Comment by wouerner** [comment]
Ajuste realizados e em homologação.
