### ISSUE TITLE
[BUG] [Readequação] Quebra de tela na planilha orçamentária

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1099]
Thais: 
Bom dia pessoal, estou tentando fazer uma readequação de planilha orçamentária no ambiente de hmg e apareceu a tela abaixo:![photo_2018-08-02_14-45-31.jpg](https://images.zenhubusercontent.com/5a5d055d4b5806bc2bc2d309/076e3b8e-5ee0-43e0-a996-89fff607fe21)

**Comment by AdmissibilidadeSAV** [comment]
Homologado.
