### ISSUE TITLE
Roteiro de Implantação - Produção

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#1102]
Nós como time desenvolvimento que atua no projeto Salic, identificamos a necessidade da criação de um conjunto de passos para que possamos atualizar o ambiente de produção aplicando o conjunto de alterações realizadas tanto de estrutura, quanto de código-fonte.

Critérios de aceitação:
**OBS: Os passos abaixo precisam ser executados nos nós do ambiente de produção**
**OBS 2: Como medida de segurança, para que os passos abaixo sejam executados, um dos nós deve estar desabilitado pelo F5 enquanto as alterações são realizadas.**
- [x] Execução de scripts de banco de dados
- [x] Utilização de imagem atual do Salic à partir do registry hub.docker (culturagovbr/salic-web:1.7), já utilizando o PHP na versão 7
```shell
$ git pull
$ docker pull culturagovbr/salic-web:1.7
$ docker-compose down
$ docker-compose up -d
```

- [x] Atualizar as dependências através do Composer 
```
composer update
``` 
ou
 
```
composer dumpautoload
```
- [x] Fazer download de imagem Node e Gerar build dos arquivos Vue da pasta 'front'
```
  docker run -t --rm --name salic-front-build -v "$PWD":/home/node/app -w /home/node/app node:9 sh -c "npm install --silent && npm run build
```

**Comment by decko** [comment]
Galera, alguns pontos

1. ```composer update``` atualizaria todas as dependências do projeto? Existem dependências com versão fixa? Será q fixar as versões das principais bibliotecas nos evitaria surpresas ao realizar o deploy?

2. O ```composer dumpautoload``` não poderia rodar durante a geração da imagem docker?

3. A execução do container que constrói os arquivos de frontend tb não poderia ser conectado ao processo de build da imagem docker contendo os arquivos também do backend?

Me deem um toque se eu estiver viajando.

**Comment by vinnyfs89** [comment]
@decko sobre os pontos que você comentou:
1. Como no ambiente de produção já existem dependências baixadas automaticamente o composer verifica apenas se houve alguma novidade e gera os novos autoloads utilizando como referência os namespaces definidos no `composer.json`.
2. Já coloquei para esses comandos serem executados automaticamente ontem na nova imagem do salic quando atualizei o entrypoint, porém isso é gerado na utilização de uma nova imagem. No nosso plano de implantação, pensamos em utilizar o código que já existe no ambiente de produção e alterar apenas a imagem.
3. Exatamente. Eu até comentei mais cedo com o @clebersantos que poderíamos evoluir nossa imagem para já embutir a construção do **front** dentro dessa imagem, porém precisamos encontrar uma maneira melhor de construir o pacote para que possamos jogar dentro da imagem. Atualmente geramos um build utilizando uma imagem docker. Podemos pensar em uma maneira de evoluir esse processo, até porque todo o código utilizado para a construção de imagem já está centralizado no mesmo repositório da aplicação.
