### ISSUE TITLE
Assinatura - Homologar projeto

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#1103]
Conforme solicitado pelo @romulomb foi solicitado que o ajuste abaixo fosse realizado à partir da issue #666:

**AJUSTES**

1. Geração do documento está pegando a informações incorreta. Nesse caso  necessitamos de uma nova templete;

![Assinatura_666.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/89a4728b-00fa-411e-84dd-76cec0e91ed0)

2. Segue a query para pegar a informação correta

Sql
 SELECT idHomologacao,idPronac,dtHomologacao,
       CASE
	     WHEN stDecisao = 1 THEN 'Desfavorável'
	     WHEN stDecisao = 2 THEN 'Favorável'
	   END stDecisao,dsHomologacao 
FROM sac.dbo.tbHomologacao WHERE IdPRONAC = 209751'

3.  a aplicação deverá gerar o documento que será assinado pelo Coordenador-geral de Admissibilidade e Aprovação, também deverá mudar a situação do projeto para D51 e a providência tomada para Projeto aguardando análise para homologação de execução.

**Comment by vinnyfs89** [comment]
Desenvolvimento da Issue completo e disponível no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
@romulomb acho que o documento ficou incompleto está trazendo apenas o texto do parecer de homologação (aquele que o coordenador faz o encaminhamento para assinaturas) e deveria trazer todas as informações da tela de homologar projetos.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/0da0a54d-6678-420a-be22-81486ff3bff1)

**Comment by romulomb** [comment]
@AdmissibilidadeSAV @admissibilidadeSav Thais resolvi simplificar, as outras informações já estão nos outros documentos assinados
