### ISSUE TITLE
Readequação de planilha - permitir que readequação seja realizada múltiplas vezes

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#111]
Alteração na camada de proponente
* período de execução vigente
* captação mínima de 20%
* conta bancária liberada
* não pode existir um remanejamento 50% sem finalizar ou readequação em análise (
tbReadequacao (idTipoReadequacao=1|| idTipoReadequacao=2) e stEstado =1)

* [x] alterar fnLiberarLinks
* [x] adaptar funcionalidade existente e alterar lógica considerando tbReadequacao e stEstado
* [x] adaptar readequação à projetos IN2017 e não pertencentes à IN2017
* [x] substituir códigos de órgãos e permissões por chamadas a constantes
* [x] substituir códigos de idTipoReadequacao por chamadas a constantes
* [x] corrigir caracteres com problemas de codificação

**Comment by romulomb** [comment]
Homologado.
