### ISSUE TITLE
Problema durante a inserção de uma diligência

### ISSUE THREAD

**Issue by Pedro-Philipe** [culturagovbr/salic-minc#1112]
Foi apresentado pelo @romulomb um erro que ao inserir uma diligência, ocorre um erro apontando o drive errado de banco de dados:![Diligencia.png](https://images.zenhubusercontent.com/5a58ea374b5806bc2bc288bf/129b2cfc-dd54-47ae-800e-834cf14b6f9d)

**Comment by vinnyfs89** [comment]
Corrigimos. Correção disponível no ambiente de homologação.
