### ISSUE TITLE
[Readequação] Assinatura digital - Parecer Técnico de Readequação/ajuste

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#1114]
Foi constatado a necessidade dos documentos gerados para assinatura digital para os atos 653, 654 e 655 de Parecer Técnico de Readequação de Projeto conste o Tipo de Solicitação, visto que são vários tipos de solicitações de readequações/ajustes e é de suma importância essa informação para o assinante até mesmo para saber o que está sendo solicitado e também para depois de assinados ser facilmente identificados quando se consulta o projeto no sistema e acessa os documentos assinados. 

![74fdc02b-f51d-452c-8ba6-596b2f4b1ebb.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/7a01268d-6e4a-420c-8c60-3b661a7ce98b)

**Comment by AdmissibilidadeSAV** [comment]
@AdmissibilidadeSAV @vinnyfs89 conforme solicitado.

**Comment by vinnyfs89** [comment]
Prezados,

Conforme solicitado, o template para geração do Documento de Assinatura para os Tipos de Ato administrativo **653**, **654** e **655** foi modificado, adicionando a informação "Tipo de Solicitação", que é obtida à partir do identificador da Readequação.

Além disso o título do documento foi modificado.

As modificações realizadas estão disponíveis no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
Ato 653 sem o tipo de solicitação no documento:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/8b3b0ff1-fd7f-4fbc-80fd-83ea2de4aa3e)

Ato 654 sem o tipo de solicitação no documento:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/89fded32-ee12-4157-b49c-9098e6a02eac)

Ato 655 sem o tipo de solicitação no documento:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/e5363a5a-4a16-416d-90cf-88a7475188e6)

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Conforme informei diretamente ontem de noite no chat particular, houve uma divergência ao atualizar o ambiente de homologação ontem com essa informação que fiz em conjunto com o @clebercsantos. Hoje verificaremos o motivo pelo qual nao foi possível atualizar o ambiente e tentaremos tornar disponível as atualizações criadas de acordo com o que foi solicitado .

**Comment by vinnyfs89** [comment]
Prezados,

O @clebersantos e eu conseguimos identificar a falha no ambiente de homologação e já corrigimos.

Segue abaixo uma imagem de um novo documento gerado já com o novo campo solicitado.

![Captura de tela de 2018-08-07 13-36-03.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/8600ce47-4a62-40de-a56e-32e831a6dc9d)

Só lembrando que a partir do momento que um documento é gerado, ele não pode ser modificado. Portanto para visualizar as modificações é necessário gerar um novo documento de assinatura.

Qualquer dúvida estamos à disposição.

**Comment by AdmissibilidadeSAV** [comment]
Homologada.
