### ISSUE TITLE
[Admissibilidade]  listagem de propostas

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1125]
Conforme pedido do @romulomb transcrevo aqui dois erros encaminhados por um proponente por e-mail:

"Prezada(o), bom dia
Ontem após cadastrar no SALIC a proposta intitulada 'PONTE PARA A COMUNIDADE' de NR 285760, fui deslogada automaticamente e após logar novamente no SALIC, não consegui ter acesso a proposta cadastrada para finalizá-la. Como demonstrado nos prints de tela que seguem anexos, o SALIC apresenta erros quando solicito a busca das propostas do meu proponente. Como proceder para sanar o problema supramencionado?
Att,
Nádia Husein"

![erro na tela de propostas.jpg](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/a4081b23-cc12-4d8a-a355-b397f327df08)

**Comment by clebersantos** [comment]
Estou editando a issue, tendo em vista que o problema de listagem de solicitações é o mesmo da issue #1440 e está corrigido em produção.

**Comment by clebersantos** [comment]
Fechando esta issue tendo em vista que o mesmo problema foi reportado e solucionado na issue #1740.
