### ISSUE TITLE
[ASSINATURA] - PROBLEMAS NA ASSINATURA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1126]
**CORREÇÕES**

**Perfil do Secretário**

1 . Projetos da SAV no painel do Secretário da SEFIC e vice e versa.

![Assinatura_1.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/63b42831-6663-490c-abfe-8d80256d73e4)

2 .  O  Secretário assina e os projetos não estão sendo movimentos para a área de portaria. 
Os projetos deveriam ter a sua  situação alterada de B04 para D27 e o órgão deveria ser alterado de 251 para 272 no caso da SEFIC e de 160 para 166 no caso da SAV

![Assinatura_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d7c1cee8-9156-46b3-a527-d3fdea52aedb)

3 . No perfil do Secretário só aparecem projetos para serem assinados no módulo específico de admissibilidade, quando deveriam também aparece no módulo genérico.

![Assinatua_3.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3751d1ca-7378-4c5f-9b93-3ac7b597e0fc)

4 . Não inclui os registro na tabela aprovação

**Comment by vinnyfs89** [comment]
Prezados, verificarei o ocorrido logo então realizarei uma análise de impacto, estimativa de pontos e iniciarei o atendimento.

**Comment by romulomb** [comment]
**PERFIL DE PARECERISTA**

A tela quebra ao tentar assinar

![Assinatua_4.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d3581706-2713-4664-8e90-8d1b614e39c5)

**Comment by romulomb** [comment]
**PERFIL DO SECRETÁRIO**

Não incluiu os registro na tabela de aprovação.

**AS FUNCIONALIDADES DO BOTÃO FINALIZAR NÃO FORAM EXECUTADAS**

**Comment by romulomb** [comment]
**PERFIL DO DIRETOR**

**ADMISSIBILIDADE**

Projetos assinados não estão sendo movimentados para o perfil do Secretário

![Assinatura_5.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/33b3fc71-c204-4167-b805-db12fc20472f)

**Comment by vinnyfs89** [comment]
Todos os itens mencionados foram corrigidos e já estão disponíveis no ambiente de homologação.
Assim que testarem e darem a Issue como homologada, enviarei o conjunto de informações para produção.

**Comment by AdmissibilidadeSAV** [comment]
Testei o fluxo da admissibilidade do enquadramento da proposta até a assinatura do Parecer de Aprovação Preliminar pelo Secretário está tudo ok.

Já no perfil de parecerista quando tenta gerar documento para assinatura (clicando no ícone de conclusão) apareceu a tela abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/55ca5138-2401-4340-8448-373b32aa6de5)

**Comment by romulomb** [comment]
@AdmissibilidadeSAV Essa correção é urgente porque teremos CNIC na semana que vem e os pareceristas não estão conseguindo assinar. Acho que acontecerá o mesmo com a CNIC.

**Comment by romulomb** [comment]
@vinnyfs89  Quem implementou as do parecerista e dos componentes da CNIC foi o Fernão. Talvez ele possa entender o que está ocorrendo.

**Comment by boletocosta** [comment]
Por mim homologado.

Mas falta o teste  da @AdmissibilidadeSAV no perfil de parecerista quando tenta gerar documento para assinatura.

**Comment by romulomb** [comment]
**FECHADA vamos trabalhar nas novas issues abertas**
