### ISSUE TITLE
[Consultar Projeto] - HOTFIX

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1127]
Ao consultar um projeto na tela principal do usuário interno os projetos antigos não aparecem na consulta.

**Comment by romulomb** [comment]
**Projetos antigos não aparecem na consulta**

**Comment by clebersantos** [comment]
@romulomb poderia informar quais são as colunas que não estão somando? 
Por exemplo: Na planilha de homologação, as colunas Vl. Solicitado, Vl. Sugerido e Vl. Aprovado jã estão com o total no final da listagem.

Segue imagem:
![screen shot 2018-08-08 at 11 21 25](https://user-images.githubusercontent.com/2494751/43843341-b2352ea8-9afd-11e8-9754-972329055254.png)

**Comment by clebersantos** [comment]
Sobre a consulta de projetos antigos, estou abrindo uma nova issue. Tendo em vista que são funcionalidades diferentes.

**Comment by clebersantos** [comment]
@romulomb correção feita em produção. Conforme conversado, estou renomeando e fechando a issue.

**Comment by romulomb** [comment]
**Faltou o total geral**

![Planilha.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b84c756b-b706-4051-84b0-d65bfcec9e8f)

**Comment by clebersantos** [comment]
@romulomb, estamos misturando funcionalidades diferentes na mesma issue. Mas vamos lá.

Conforme imagem abaixo, o valor total fica na parte de cima, já informando o total do município.

![b84c756b-b706-4051-84b0-d65bfcec9e8f.jpeg](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/42bd615a-3143-422f-8a4a-b685fb456b52)

**Comment by clebersantos** [comment]
Nesta imagem mostra todos os valores, com os itens fechados.

![Screen Shot 2018-08-08 at 14.26.50.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/af43ef84-de35-4734-a3f4-83dc9f858197)
