### ISSUE TITLE
[HOTFIX] TRANSFORMAR PROPOSTA EM PROJETO

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#1128]
@boletocosta  #1067

@clebersantos Bom dia! Mesmo após versão 5 continuo sem conseguir transformar essa proposta (277330) em projeto, pois a ferramenta que permite a correção do agente que não tem usuário cadastrado não disponibiliza nenhum usuário ao realizar o procedimento. No campo usuário só aparece a opção "selecione" e ao clicar não oferece nenhuma outra opção.

Além dessa proposta também não estou conseguindo transformar em projetos as propostas 283425 e 282972. Após clicar no botão transformar nada acontece.

Pode verificar, por gentileza?

Obrigado.

**Comment by marcusvinicus** [comment]
Criei uma issue nova como hotfix, e linkei com a issue antiga que já tava fechada.

**Comment by clebersantos** [comment]
@boletocosta, nas propostas 283425 e 282972, a tela fica apenas congelada? Você consegue transformar outras propostas em projeto?

**Comment by boletocosta** [comment]
Deu certo! Valeu! Pode fechar a issue
