### ISSUE TITLE
[COMPROVAÇÃO FINANCERIA]  - HOTFIX

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1131]
Ao clicar no botão **VER PROJETO** conforme figura abaixo

![comprovacao_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/ea2c587c-c445-4b6a-9b75-3cda8d92cfb4)

O sistema monta corretamente a consulta conforme figura abaixo

![comprovacao_4.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/e616656b-fe68-4bce-8416-bc66726c0cd5)

Ao clicar no botão **VOLTAR** da consulta dados do projeto a tela fica em branco

![comprovacao_5.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c5ca3d1e-18a8-4505-9f8e-15757a25caae)

**Comment by romulomb** [comment]
**TODOS OS PROBLEMAS ACIMA RELATADOS ESTAVAM CORRETOS NO AMBIENTE DE HOMOLOGAÇÃO ANTES DA SUBIDA DO PACOTE PARA PRODUÇÃO**

**Comment by wouerner** [comment]
Em analise.

**Comment by DouglasMinC** [comment]
Homologado.

**Comment by romulomb** [comment]
**HOMOLOGADO pela área técnica.

**SUBIR PARA PRODUÇÃO, por gentileza**
