### ISSUE TITLE
[CONSULTAR DADOS DO PROJETO]

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1132]
### Planilhas Orçamentárias (15 pontos) - Cleber

Colocar os totais gerais das fontes de recurso das colunas(detalhadas abaixo), em todas as planilhas, conforme segue abaixo:
 - Planilha Inicial da Proposta
    * Valor Solicitado
 - Planilha Aprovada para Captação
    * Valor Solicitado
    * Valor aprovado
 - Planilha Adequada à Execução do Projeto
    * Valor Solicitado
 - Planilha Readequada pelo Proponente
    * Valor aprovado
    * Valor comprovado
 - Planilha homologação
   * Valor Solicitado
   * Valor Sugerido
   * Valor Aprovado

- Problema de charset na justificativa

###  Menu lateral de projeto de convênio(FNC) (3 pontos)

**Incluir os itens de menu abaixo**

1 . Dados do Projeto

2 . Proponente

3 . Outras Informações

     a) Certidões Negativas

     b) Documento Anexados

     c) Diligência do Projeto

     d) Providência Tomada

     e) Tramitação

4 . Execução
  
    a) Dados da Fiscalização

5) Solicitações

### Menu suspenso (2 pontos)consultar
 - Adicionar uma seta que faça scroll para baixo

### Formatar campos em dados do projeto (5 pontos)
  - adicionar traço na agência
  - formatar número das contas de movimentação e bloqueadas, tirando os zeros à esquerda e adicionar traço no último dígito
 - Corrigir bug do botão voltar da página que lista projetos por cpf(conforme comentário abaixo)

### Transferência de recursos (32 pontos) - Ruan
  - Criar modal com listagem de recursos transferidos do projeto (conforme comentário abaixo)
  - Criar modal com listagem de recursos recebidos do projeto (conforme comentário abaixo)

### Proposta (30 pontos) - Guilherme
 - Inserir um link no número da proposta
 - Ao clicar no link criado o sistema deverá mostrar um resumo da proposta cadastrada. (Terá que migrar os componentes vuejs criados para análise de adequação à realidade)

**Comment by clebersantos** [comment]
@romulomb Qual Pronac com proponente inabilitado?

**Comment by romulomb** [comment]
**TRANSFERÊNCIA DE RECURSOS ENTRE PROJETOS**

**1. Na tela de consultar projetos ao clicar no link do valor TRANSFERIDO, a aplicação deverá disponibilizar  as informações dos valores transferidos.**

![Trans_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/458991a0-e1c9-4dd9-8ea9-a35f7f3550c5)

O formato da redenrização das informações segue na figura abaixo. A renderização deverá ser em uma modal.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8a8868be-d759-4744-a2a4-9115077082d4)

A query que trará as informações para a renderização segue abaixo

Sql 
'SELECT idPronacTransferidor,PronacTransferidor,NomeProjetoTranferidor,idPronacRecebedor,PronacRecebedor,NomeProjetoRecedor,dtRecebimento,vlRecebido
 FROM sac.dbo.vwTransferenciaRecursosEntreProjetos
 WHERE idPronacTransferidor = [ID DO PRONAC QUE ESTÁ SENDO CONSULTADO]

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**2. Na tela de consultar projetos ao clicar no link do valor RECEBIDO, a aplicação deverá disponibilizar as informações dos valores recebidos.**

![Trans_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/933d971c-c7a5-4190-a8d7-dbe15f389466)

O formato da redenrização das informações segue na figura abaixo. A renderização deverá ser em uma modal.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8a8868be-d759-4744-a2a4-9115077082d4)

A query que trará as informações para a renderização segue abaixo

Sql 
'SELECT idPronacTransferidor,PronacTransferidor,NomeProjetoTranferidor,idPronacRecebedor,PronacRecebedor,NomeProjetoRecedor,dtRecebimento,vlRecebido
 FROM sac.dbo.vwTransferenciaRecursosEntreProjetos
 WHERE idPronacRecebedor= [ID DO PRONAC QUE ESTÁ SENDO CONSULTADO]

-----------------------------------------------------------------------------------------------------------

**O toque de criatividade fica por sua conta**

-----------------------------------------------------------------------------------------------------------

**Comment by clebersantos** [comment]
teste

**Comment by clebersantos** [comment]
Teste bot

**Comment by clebersantos** [comment]
Disponível para homologação os valores totais das planilhas e a coluna Unidade. Último item pendente desta issue.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**PODE SUBIR PARA PRODUÇÃO**

**OBRIGADO**
