### ISSUE TITLE
[PROJETO] Migrar proponente para Vue

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#1135]
(projeto/proponenteRest(idPronac) -> agente/agenteRest(idAgente)
   controller
 - module/projeto/proponente/get/(idPronac)
  service
  - $proponente = $tbAgentes->obterAgente($projeto->idAgente)
      - $proponente->enderecos
      - $proponente->emails
      - $proponente->telefones
  - $procuradores = $tbProcurador->obterProcuradores($projeto->idPronac)
  - $dirigentes = $tbDirigentes->obterDirigentes($projeto->idProjeto)
  - $natureza 
/modules/agente/agente(idAgente, tipo)
 - endereco
 - email
 - telefones
/modules/agente/endereco
/projeto/procurador/idPronac/123

**Comment by FernandaLA** [comment]
@romulomb, a tela do proponente foi migrada para Vue. Você pode homologar?

**Comment by romulomb** [comment]
Só um pequeno ajuste na formatação do cep.

Está assim **73.030.000** e deverá ficar assim **73.030-000**.

**PARABÉNS FICOU EXCELENTE**
