### ISSUE TITLE
[HOTFIX] Exibir informações importantes

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1153]
Em consultar dados do projeto, o sistema deve mostrar as seguintes informações:
- Quando o proponente está inabilitado
- O percentual captado, mesmo quando for zero
- No menu lateral, prestação de contas, mostrar a opção relação de pagamentos
- Atualizar regra para exibir mensagem de análise pela CNIC(tarja)

**Comment by clebersantos** [comment]
Correções em produção.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**OBRIGADO FIQUEI EXCELENTE**

**Comment by romulomb** [comment]
**CORRIGINDO FICOU EXCELENTE**.

**Comment by romulomb** [comment]
**AJUSTE**

Ativar a tarja vermelha para projetos em análise técnica e incluir na regra situação D50.

**Comment by clebersantos** [comment]
Query utilizada para mostrar mensagem quando está para análise da CNIC:

```
SELECT "a"."IdPRONAC", "a"."NumeroReuniao" FROM "SAC"."dbo"."Parecer" AS "a" INNER JOIN "SAC"."dbo"."tbReuniao" AS "b" ON a.NumeroReuniao = b.NrReuniao WHERE (b.stEstado = 0) AND (a.AnoProjeto+a.Sequencial = '172029')

```

**Comment by clebersantos** [comment]
Sugestão para nova query:

```
SELECT "a"."IdPRONAC", "a"."NumeroReuniao" FROM "SAC"."dbo"."Parecer" AS "a" INNER JOIN "SAC"."dbo"."tbReuniao" AS "b" ON a.NumeroReuniao = b.NrReuniao INNER JOIN "SAC"."dbo"."Projetos" AS "c" ON a.IdPRONAC= c.IdPRONAC WHERE (b.stEstado = 0) AND (a.AnoProjeto+a.Sequencial = '172029') AND (c.Situacao = 'D50');
```

**Comment by romulomb** [comment]
@clebersantos Não vai funcionar

**Comment by clebersantos** [comment]
by @romulomb (https://github.com/romulomb)

Sugestão da query para a tarja

sql 
' SELECT a.IdPRONAC, a.NumeroReuniao 
FROM SAC.dbo.Parecer AS a 
INNER JOIN SAC.dbo.tbReuniao AS b ON a.NumeroReuniao = b.NrReuniao 
INNER JOIN SAC.dbo.Projetos AS c ON a.IdPRONAC= c.IdPRONAC 
WHERE     b.stEstado = 0 
      AND a.AnoProjeto+a.Sequencial = [ pronac]

  AND c.Situacao in ('A14','A16','A17','A20','A23','A24','A41','A42','D02','D14','D50')
"
Adicionei as situações inseridas na query que não estavam no escorpo da issue.

Disponível para teste no ambiente de homologação.

**Comment by romulomb** [comment]
Só conseguiremos validar na produção, quando abrirmos a reunião da CNIC

**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**
