### ISSUE TITLE
[ASSINATURA] - ADMISSIBILIDADE

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1156]
**AJUSTE**

Ao finalizar as assinaturas, perfil de Secretário o projeto deverá ser encaminhado automaticamente para a área de elaboração de portaria.

Para que isso ocorra basta seguir os passo abaixo.

Tabela Projetos

Alterar o atributo **Situacao** de **D03** para **D27**
Alterar o atributo **ProvidenciaTomada** de **Projeto aprovado - aguardando análise documental** para **Projeto encaminhado para elaboração de portaria**
Alterar o atributo **DtSituacao** para a **Data Atual**
Alterar o atributo **Logon** para o código do último assinante**

Alterar o atributo **Orgao** 
  No caso da SEFIC de **251** para **272**;
  No caso da SAV    de **160** para **171**.

-------------------------------------------------------------------------------------------------------------------

**Com esse ajustes estabilizaremos a assinatura na admissibilidade**

**PARABÉNS VINI ESTÁ FICANDO MUITO LEGAL**

**Comment by vinnyfs89** [comment]
Alterações  realizadas e já disponíveis no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
Homologado.

**Comment by AdmissibilidadeSAV** [comment]
Checando agora novamente o fluxo de assinaturas da Admissibilidade hoje, considero essa issue homologada e apta para subir para produção.
