### ISSUE TITLE
[ASSINATURA] - PARECERISTA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1157]
**PERFIL DE PARECERISTA**

**Parecerista da FUNARTE**

CPF: 008.443.097-45

SENHA: 123456

--------------------------------------------------------------------------------------------------------------------

Ao acionar o botão gerar o documento.

![Parecerista_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/df546784-7687-4343-b615-1d6b6736f1ca)

A tela quebra

![Parecerista_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/62713a1e-ee43-4e50-a8ca-ca59a7702683)

**Comment by romulomb** [comment]
--------------------------------------------------------------------------------------------------------------------

**URGENTÍSSIMO  CNIC COMEÇA NA TERÇA**

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Pode informar por gentileza o CPF e os passos executados para chegar nessa tela?

**Comment by AdmissibilidadeSAV** [comment]
o CPF é o 01444542117, no perfil SAV - Presidente de unidade vinculada, no menu Análise - Gerenciar Pareceres, após ter assinado o documento não apareceu a opção de concluir.

**Comment by romulomb** [comment]
@vinnyfs89  

Ao finalizar as assinaturas, no perfil do presidente da vinculada o projeto deverá ser encaminhado automaticamente para o MinC.

Para que isso ocorra basta seguir os passo abaixo.

Tabela Projetos

Alterar o atributo Orgao
Se o codigo do Orgao for igual a 160 para 171 senão para 262

Situacao = 'C20'
ProvidenciaTomada = "Análise técnica concluída'
DtSituacao = data atual
Logon =código do usuário logado.

**Comment by vinnyfs89** [comment]
Adição de ação ao Finalizar Assinaturas que altera o Órgão atual do projeto, Providência tomada além da Situação do projeto.

Para os projetos que já foram finalizados antes desse ajuste, essa alteração solicitada pelo Rômulo não ficará disponível. Sugiro que devolva o projeto e reinicie o fluxo para que a ação de Finalização seja acionada.

Os ajustes estão disponíveis no ambiente de homologação.

**Comment by vinnyfs89** [comment]
@romulomb @Romulo_Menho como obtenho o "idDistribuirParecer" ?

**Comment by romulomb** [comment]
Para esse caso específico

SELECT idDistribuirParecer FROM tbDistribuirPARECER WHERE IdPRONAC = idpronac AND stEstado = 0 and stPrincipal = 1

**Comment by vinnyfs89** [comment]
Modificações realizadas e já disponíveis no ambiente de homologação.

**Comment by romulomb** [comment]
@vinnyfs89 
Perfil do presidente da vinculada

![Tela.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d1d95828-761a-4eca-a9de-d02eba0d5f50)

**Comment by vinnyfs89** [comment]
Não comprendi o print anexado.
Quais ações você tentou fazer?

**Comment by romulomb** [comment]
@vinnyfs89 

**Repito a regra que está descrita acima e não foi implementada**

Ao finalizar as assinaturas, no perfil do presidente da vinculada o projeto deverá ser encaminhado automaticamente para o MinC.

Para que isso ocorra basta seguir os passo abaixo.

Tabela tbDistribuirParecer

alterar o atributo FecharAnalise para 1
alterar o atributo DtRetorno de null para data atual
alterar o atributo ** idUsuario** para o código do usuario logado

Somente no produto principal

O produto principal é identificado pelo atributo stPrincipal = 1


**Esse é o HOTFIX mais urgente que temos**

**Comment by romulomb** [comment]
Despreze o print  acima.

**Comment by romulomb** [comment]
Preciso da subida desse hotfix agora pela manha, mesmo sem resolver a solicitação acima.

Obrigado

**Comment by AdmissibilidadeSAV** [comment]
O pacote que subiu quando o parecerista finaliza a assinatura o projeto muda para situação de C20 e não aparece para o coordenador de parecer e presidente da vinculada para assinatura.

**Comment by romulomb** [comment]
Pessoal  comunicação através de issue está resolvendo nada, só está criando mais problemas.

Na parte da tarde estarei aí com Thais para resolvermos pessoal.

**Comment by vinnyfs89** [comment]
Itens corrigidos e testados em conjunto com o @romulomb .
