### ISSUE TITLE
[ASSINATURA]  - COMPONENTE DA COMISSÃO 

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1158]
**PERFIL DE COMPONENTE DA COMISSÃO**

Parecerista da FUNARTE

CPF: 038.384.218-25

SENHA: 123456

Ao clicar no link conforme a tela abaixo.
![Componente_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/97688b8e-ef48-4793-86fa-65c31caf08a5)

Segue a tela
![Componente_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/4dd583f2-1ca8-4b3b-b1df-0a0c0757d04f)

A tela quebra
![Componente_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/fded8cad-891e-4f33-b00f-241b9998495d)

--------------------------------------------------------------------------------------------------------------------

**URGENTÍSSIMO  CNIC COMEÇA NA TERÇA**

**Comment by vinnyfs89** [comment]
Gilberto - 782.588.717-49 Senha 123456

**Comment by vinnyfs89** [comment]
![Captura de tela de 2018-08-13 10-05-28.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/12b6be75-1aaa-43f6-8c7b-cba2cb88b958)

Sem projetos para essa classificação. Pode atribuir algum projeto no ambiente de homologação, por gentileza?

**Comment by vinnyfs89** [comment]
No ambiente de produção esse erro não ocorre.

Verificando o motivo pelo qual ocorre no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
No perfil Componente da Comissão, CPF: 038.384.218-258, Senha: 123456, após a emissão do parecer quando clica no botão gerar documento para assinatura aparece a tela abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/dc526981-c117-406c-8d8c-09f270ab89ab)

**Comment by vinnyfs89** [comment]
Identificamos que o módulo de assinatura para análise da CNIC tinha sido desenvolvido de uma forma incompatível com o que é requirido para o módulo de assinatura atual.

Recriamos o que era necessário e testamos. Funcionou tudo corretamente. 

Pode verificar no ambiente de homologação por gentileza?

**Comment by romulomb** [comment]
Ao assinar no perfil do componente da comissão o projeto deverá sair automaticamente do painel do componente.

Para que isso ocorra basta seguir os passo abaixo.

Tabela Projetos

Situacao = 'D50'
ProvidenciaTomada = "PROJETO APRECIADO PELO COMPONENTE DA COMISSÃO NA REUNIÃO DA CNIC.'
DtSituacao = data atual
Logon =código do usuário logado.

**Comment by vinnyfs89** [comment]
Ok, então adicionarei essa regra na Ação de Finalizar.

**Comment by vinnyfs89** [comment]
Já movi essa Issue para a Guia `Fazendo`

**Comment by vinnyfs89** [comment]
Conforme solicitado, foi realizada uma adição de ação ao finalizar a assinatura para que seja alterada a situação e providência tomada do projeto. 

@romulomb Alteração realizada e disponível no ambiente de homologação. Por gentileza, verificar.

**Comment by romulomb** [comment]
HOMOLOGADO

**SUBIR PARA PRODUÇÃO**
