### ISSUE TITLE
[HOMOLOGAR PROJETOS] - FINALIZAR HOMOLOGAÇÃO

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1159]
**PERFIL DE COORDENADOR DE ANÁLISE**

•  Na opção “homologar” deverá inserir o botão para finalizar a homologação.

•  A aplicação não deverá permitir que o usuário finalize ou inicie o fluxo de assinaturas se não houver nenhuma informação inserida no campo de Parecer de homologação. Caso contrário irá gerar um documento com posicionamento não definido e parecer em branco conforme tela abaixo:

![Homol_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/1a50f86e-0ce0-40b8-b50e-f5832439be36)

•  Ao acionar o botão de iniciar o fluxo de assinatura a aplicação deverá verificar se o valor homologado é igual ao valor adequado à realidade de execução, nesse caso o projeto deverá mudar a situação para D52 - Projeto encaminhado para homologação, o documento será gerado e aparecerá no painel de assinaturas do perfil de Coordenador-geral de Admissibilidade e Aprovação. 

•  Caso o valor homologado seja diferente do valor adequado à realidade de execução, a situação do projeto deverá mudar para D51 - Projeto avaliado - Aguardando a superação do prazo recursal e a aplicação deverá abrir ao proponente a opção de apresentar recurso e o fluxo de assinaturas só poderá iniciar quando o proponente desistir do prazo recursal ou quando o prazo recursal expirar. Quando isso ocorrer a situação do projeto deverá ser alterada para D52 - Projeto encaminhado para homologação e o documento será gerado e aparecerá no painel de assinaturas do perfil de Coordenador-geral de Admissibilidade e Aprovação. 

**PERFIL DO SECRETÁRIO**

Após a última assinatura :

1 . Se **não houver** alteração entre o valor autorizado a captar e ou valor homologado para execução, a aplicação deverá encaminhar o projeto para a área de execução da secretaria correspondente do projeto.

Para que isso ocorra basta seguir os passo abaixo.

Tabela **Projetos**

Alterar o  atributo **Situacao**  para **E12**
Alterar o atributo **ProvidenciaTomada** para **Homologado a execução do projeto cultural**
Alterar o atributo **DtSituacao** para a **Data Atual**
Alterar o atributo **Logon** para o código do último assinante**

Alterar o atributo **Orgao** 
  No caso da SEFIC de **251** para **272**;
  No caso da SAV    de **160** para **166**.

2 . **Havendo** alteração entre o valor autorizado a captar e ou valor homologado para execução, ao finalizar as assinaturas,  no perfil de Secretário o projeto deverá ser encaminhado automaticamente para a área de elaboração de portaria.

Para que isso ocorra basta seguir os passo abaixo.

**Tabela Projetos**

Se o valor homologado para executar for **maior** do que o valor autorizado, significa complementação de valor ou seja:
Alterar o atributo **Situacao**  para **D28**
Alterar o atributo **ProvidenciaTomada**  para **Projeto encaminhado para elaboração de portaria de complementação orçamentária**
Alterar o atributo **DtSituacao** para a **Data Atual**
Alterar o atributo **Logon** para o código do último assinante**

Alterar o atributo **Orgao** 
  No caso da SEFIC de **251** para **272**;
  No caso da SAV    de **160** para **171**.

Se o valor homologado para executar for **menor** do que o valor autorizado, significa redução  de valor ou seja:
Alterar o atributo **Situacao**  para **D29**
Alterar o atributo **ProvidenciaTomada**  para **Projeto encaminhado para elaboração de portaria de redução orçamentária**

Alterar o atributo **DtSituacao** para a **Data Atual**
Alterar o atributo **Logon** para o código do último assinante**

Alterar o atributo **Orgao** 
  No caso da SEFIC de **251** para **272**;
  No caso da SAV    de **160** para **171**.

**Para identificar se houve alteração entre o **valor autorizado a captar** e ou **valor homologado para execução** basta executar o script  abaixo.

sql
'SELECT SAC.DBO.fnVlAutorizadoACaptarIncentivo(idPronac) - 
             SAC.DBO.fnVlHomologadoIncentivo(idPronac) '

3 . Sempre que houver alteração de valores, uma nova portaria deverá ser publicada, para tanto será necessário gerar um registro na tabela **Aprovacao** conforme descrito abaixo.

**Atributo da tabela Aprovacao**
    IdPRONAC = id pronac do projeto
   AnoProjeto = AnoAprojeto
   Sequencial  = Sequencial
   TipoAprovacao = 2 se for complementação ou 4 se for redução,
   DtAprovacao = data atual
   ResumoAprovacao = VALOR DO ATRIBUTO DSHOMOGACAO DA TABELA TBHOMOLOGAO
   AprovadoReal  = SAC.DBO.fnVlHomologadoIncentivo(idPronac) 
  Logon = ID USUARIO LOGADO

**Comment by AdmissibilidadeSAV** [comment]
@romulomb Minha sugestão para essa funcionalidade de Homologar projetos é:

•  Na tela de Homologar inserir o botão de finalizar.
•  O botão de iniciar o fluxo de homologação não poderá ser habilitado enquanto o coordenador não clicar em finalizar a homologação.

**Comment by romulomb** [comment]
@vinnyfs89 

A assinatura está ok.

**Comment by romulomb** [comment]
O ajuste será com quem desenvolveu a funcionalidade

**Comment by clebersantos** [comment]
@romulomb, pode atualizar a descrição dessa issue? Está misturando com as funcionalidades de assinatura causando confusão.

**Comment by romulomb** [comment]
@clebersantos Fique a vontade

**Comment by romulomb** [comment]
Não entendi

**Comment by clebersantos** [comment]
@romulomb Preciso que vc detalhe a issue com as alterações que devem ser realizadas. O que vc me passou tá diferente do que está detalhado na issue.

O resumo do que você me passou é:
Criar um botão para finalizar a homologação e iniciar o fluxo de assinatura somente se o valor homologado for igual ao valor solicitado.
Se o valor homologado for diferente, abrirá a opção de recurso para o proponente e o fluxo de inciar assinatura só estará disponível, se:
  - o proponente recusar o recurso
  - o proponente responder o recurso
  - o prazo para recurso expirou

Atualmente:
Os projetos que aparecem na listagem estão na situação D50
Os projetos com recurso estão na situação D20
Os projetos com fluxo inicializados na situação D51

No fluxo desenhado que você me entregou os projetos para assinatura estão na situação D52.

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos na tela de Homologar Parecer necessito que corrija o campo **"Apreciação do Comissionário Relator"** para **"Apreciação do Comissário Relator"**.

https://hmg.salic.cultura.gov.br/projeto/homologacao

![Homologar.jpg](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/6729a46d-915f-47d0-aa20-68a549bfb6fc)

**Comment by clebersantos** [comment]
@thais_mendess a funcionalidade de homologar projeto está disponível no ambiente de homologação. Estou apenas finalizando a parte do recurso que está na issue #606

**Comment by AdmissibilidadeSAV** [comment]
Os ajustes referentes ao Parecer de Homologação estão ok, aguardando a finalização da parte do recurso e do fluxo de assinatura para testar toda a funcionalidade.

**Comment by clebersantos** [comment]
Foi disponibilizado no ambiente de homologação as alterações que devem acontecer ao finalizar o bloco de assinatura. @AdmissibilidadeSAV pode testar essa parte?

**Comment by AdmissibilidadeSAV** [comment]
Desculpe-me pela demora em verificar, estava de licença médica e voltei no final da semana passada. Mas enfim, testei e observei o seguinte:

Quando o valor homologado é diferente do valor adequado à realidade de execução, na tela de finalizar a homologação está trazendo a seguinte mensagem _"Tem certeza que deseja finalizar a homologação desse projeto? Após finalização o projeto terá a seguinte situação: D52 - Projeto encaminhado para homologação."_, a mensagem deveria ser diferente, visto que nesse caso a situação do projeto deverá ser alterada D51 - Projeto avaliado - Aguardando a superação do prazo recursal.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/88b63c60-a9aa-4cdf-8b10-c8d33a360e19)

Após a finalização da homologação constatei que o projeto foi alterado para a situação correta D51, no entanto, a nomenclatura da situação e providência tomada não foram alteradas de "Projeto apreciado pela CNIC - Aguardando análise documental" para "Projeto avaliado - Aguardando a superação do prazo recursal", acredito que isso seja com o @romulomb né?!

Já o teste realizado com projeto que os valores são iguais (adequado e homologado) notei a situação do projeto deveria ter sido alterada para D52 conforme mensagem exibida na tela de finalizar a homologação abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/258c85e0-4edc-4a75-8f9c-68f3b0ec5ae7)

No entanto a situação foi alterada para D51 quando deveria ser D52.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/629bfc57-bc95-4c9a-9dfd-66a0b4f3aa6c)

Ao finalizar as homologações de projetos cujo o valor homologado seja diferente do valor adequado à realidade de execução a aplicação só deverá gerar o documento para assinatura após a superação do prazo recursal ou desistido de apresentar recurso, e, caso o proponente tenha apresentado recurso não deverá nem gerar o documento para assinatura, visto que o projeto deverá passar por uma nova análise.

O projeto abaixo teve cortes na planilha orçamentária, abriu prazo recursal, o proponente encaminhou recurso, no entanto o documento aparece no painel do Coordenador-geral para assinatura.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/cae2538e-a848-47d5-b8f3-0b4d3170fc4f)

O Pronac 178977 desistiu do prazo recursal e a situação do projeto não foi alterada para D52.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/aaeb4812-5960-4e82-a096-29fe5a0a8c56)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/71214747-c63c-493b-82a1-553029ea6196)

Encontrei o projeto no filtro Pós Recurso e apareceu a tela para finalizar novamente a homologação, acredito que deveria ter só um botão que encaminhasse o documento para assinatura ao invés de finalizar a homologação novamente ou melhor que projetos que irão abrir prazo recursal somente tenha a situação alterada para D51 e a finalização da homologação só ocorra quando tenha finalizado o prazo recursal ou em caso de desistência de apresentação de recurso.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/27639ad4-9f53-4e6d-9006-3d7583cf0647)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV pontuei suas observações.
1 - Corrigido.
2 - A providência tomada é alterada mas a descrição da situação o @romulomb que deve atualizar
3 - Corigido.
4 - Não consegui reproduzir esse erro, acredito que o projeto era antigo e já estava com uma assinatura aberta.
5 - O fluxo de recurso não foi alterado nesta issue, mas nas regras atuais o sistema não altera a situação do projeto quando o proponente desiste do recurso.
6 - Não entendi. Atualmente a lista de `Pós Recurso` mostra os projetos que já tiveram o recurso encerrado, de acordo com o recurso o avaliador deve fazer nova análise da homologação e encaminhar para assinatura.

Fiz diversos ajustes e disponibilizei para homologação novamente.

**Comment by AdmissibilidadeSAV** [comment]
Todos os apontamentos levantados foram corrigidos, portanto, considero homologada.
