### ISSUE TITLE
[ASSINATURA] - PARECER TÉCNICO DE READEQUAÇÃO DE PROJETO - MINC

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1160]
**AJUSTE**

Ao finalizar as assinaturas, no perfil de Secretário o projeto deverá ser encaminhado automaticamente para a área de elaboração de portaria.

Para que isso ocorra basta seguir os passo abaixo.

Tabela Projetos

Alterar o atributo **Orgao** 
  No caso da SEFIC de **251** para **272**;
  No caso da SAV    de **160** para **171**.

Tabela **tbReadequacao**
Alterar os atributos
stEstado para **1**
siEncaminhamento para **9**

**Comment by vinnyfs89** [comment]
@romulomb Esse seria o último passo da assinatura? (finalização) ????

**Comment by romulomb** [comment]
Nesse tipo de assinatura sim

**Comment by vinnyfs89** [comment]
Alterações realizadas e disponíveis no ambiente de homologação.
Por gentileza verificar.

**Comment by AdmissibilidadeSAV** [comment]
Acabei de testar a assinatura com o Pronac: 164550
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/3c683c91-5282-423e-a197-8ce25c124cf2)

Após a última assinatura (perfil do Secretário) o projeto não retornou para a localização de origem, permaneceu no órgão que assinou por último.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/87ae52c4-3ce2-4c4d-9604-6572a0d093fb)
