### ISSUE TITLE
[ASSINATURA] - PARECER TÉCNICO DE AJUSTE DE PROJETO

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1161]
Assinou corretamente, mas não executou as rotinas de  finalização da ação.

**Comment by romulomb** [comment]
A aplicação não está executando as atualizações solicitadas após a finalização.

São 17 tipos de readequações.

Nesse caso vamos testar cada uma para dizer o que deveria ser alterado.

**Comment by vinnyfs89** [comment]
Com as informações definidas não é possível reproduzir o erro mencionado. Necessito de mais detalhamento e prints, perfil e CPF de preferência.

**Comment by romulomb** [comment]
@vinnyfs89  A aplicação não está executando as ações do botão finalizar.

Vou criar uma sp para executar as funções  do botão finalizar, Então assina e  a sp faz as atualizações necessárias.

**Comment by vinnyfs89** [comment]
@romulomb Não. Sem sp. Vou verificar o motivo pelo qual não funcionou.

**Comment by vinnyfs89** [comment]
@romulomb solicitou que esse item fosse encaminhado para guia de homologação.
