### ISSUE TITLE
[ASSINATURA] - PARECER TÉCNICO DE READEQUAÇÃO DE PROJETO - VINCULADAS

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1162]
Consigo assinar até o Presidente da vinculada, após aplicação não está disponibilizando o documento para o diretor e secretario.

**Comment by vinnyfs89** [comment]
A issue contém poucas informações para eu consiga reproduzir e identificar o ajuste solicitado.

Por gentileza, é possível adicionar prints com o passo a passo realizado, perfil e CPF do usuário logado?

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89 é o mesmo problema relatado na issue #896.

O CPF utilizado é o 008.443.097-45, perfis: Parcerista, Coordenador de Parecer e Presidente de unidade vinculada. Teste por favor: 172343 sem perfil de Presidente de unidade vinculada. E depois de assinar consulte a localização do projeto para ver se permanece na vinculada.

**Comment by romulomb** [comment]
@AdmissibilidadeSAV @vinnyfs89 Esqueci de fechar a 896, fecharei agora.

**Comment by vinnyfs89** [comment]
Correção realizada, testada e disponível no ambiente de homologação.

Por gentileza, verificar.
