### ISSUE TITLE
Transferência de recursos: ajustes

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1167]
Referências: #775

AJUSTES

1) Está permitindo gravar várias solicitações na tabela readequação para o mesmo pedido de transferência de recursos.

2) Ao tentar subir o arquivo em PDF a aplicação entra em loop a não faz o upload.

3) Não está liberando a opção para escolher o projeto ou projetos que deverão receber os aportes tranferidos.
    Nesse caso, na minha opinião deveríamos abrir caixa de texto e deixar o proponente digitar os Pronacs. Assim atenderá a regra de transferir recursos para projetos de outro proponente também,

**Comment by fernao** [comment]
Continua valendo a regra de que projetos da área de patrimônio e memória podem repassar para múltiplos projetos e os de outras áreas apenas para um ?

**Comment by romulomb** [comment]
@fernao Não, como já disse anteriormente, o proponente vai escolher por meio da digitação do pronac os projetos que receberam os recursos. Nesse momento optamos para que o técnico no momento da análise valide as regras.

**Comment by romulomb** [comment]
**AJUSTE**

1 . Ajuste de tela.

![Tela_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/5064c1d7-4518-4a1c-ae41-ccbeff0eee23)

2 Não está apagando os registro na tabela tbSolicitacaoTransferenciaRecursos, a aplicação exibe a mensagem de registro excluído com sucesso.

![Tela_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/7b337bb7-0122-4e20-88cf-882970bde7bb)


**Pronac para Teste**

Transferir do 164793 para os pronac 181542 e 180543

3. O botão finalizar está sem ação.

![Tela_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/e3c39bf6-50e6-40ad-bd30-816f675c4eed)

4. Não consigo excluir o arquivo anexado.

![Tela_4.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/72973be3-6de8-4567-a429-bb341169b31c)

**Comment by fernao** [comment]
Funcionalidades corrigidas no dia 14/08, desde quando está para homologação. Favor homologar e confirmar se a funcionalidade está correta ou se necessita de mais ajustes.

**Comment by romulomb** [comment]
Tela quebrou na assinatura do Coordenador-Geral de Acompanhamento

![Transferencia_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/49025556-e3c4-4f3f-8c65-f76ae7257c61)

**Comment by Paulinhoibti** [comment]
Para verificar o erro, enviamos uma transferência de recursos e assinamos os dois primeiros passos de uma assinatura de 4 passos. No terceiro, já deu problema e finalizou.

* parecerista ok, 
* coordenador vinculada ok,
* presidente: deu problema
* coord geral (nem chegamos)

**Comment by Paulinhoibti** [comment]
Constatamos que:
- a trilha de readequação (653) possui um órgao superior da assinatura 4 diferente do órgão superior do assinante. Isso gera uma inconsistência pois o sistema não consegue obter o código do órgão superior da próxima assinatura na forma pela qual está implementado.

**Comment by Paulinhoibti** [comment]
@romulomb , eu, @fernao e @vinnyfs89 conversamos sobre esse problema e percebemos que precisamos tirar a dúvida com você sobre a forma de resolver este problema, referente a trilhas de assinatura com mais de um órgão superior (ex: idTipoDoAto = 653)

**Comment by romulomb** [comment]
Se desejarem por demonstrar como resolver esse problema facilmente.

**Comment by romulomb** [comment]
Para ajudar preciso ver as querys que estão sendo utilizadas

**Comment by fernao** [comment]
Atualmente, a tabela sac.dbo.tbAtoAdministrativo pode conter um mesmo ato atribuído a diferentes órgãos superiores. 

Caso do idAto 630 (análise inicial): há fluxos de assinatura para:
* IPHAN/PRONAC
* FUNARTE
* FBN
* FCP
* FCRB
* SAVand 
* IBRAM
Todos eles estão identificados sob o idAtoAdministrativo = 630, mas diferenciados pelo órgão superior. Sete fluxos, com um órgão cada, cada um no seu órgão.

No entanto, para a assinatura do fluxo de readequação (idAtoAdministrativo = 653), há apenas um fluxo via Funarte (92) e que finaliza em SEFIC (251). Ou seja, um fluxo apenas mas com dois órgãos no mesmo.

Ou seja: caso utilizemos o método de obtenção do próximo órgão a assinar (passando um órgão superior), nos retorna uma lista vazia;

Exemplo: estou no ato 653 (readequação), já assinaram parecerista, coord. parecer e presidente da funarte. O próximo órgão deve ser Sefic (251). Possuo o órgão atual (92), que será passado para a query como  a abaixo:

```
SELECT
    idOrgaoSuperiorDoAssinante	
FROM
	"sac"."dbo"."tbatoadministrativo"
WHERE
	( idTipoDoAto in ( 653)) 
AND
	idOrdemDaAssinatura > 3
AND
       idOrgaoSuperiorDoAssinante = 92
```

Essa consulta retornará vazia, pois não há assinaturas para 92 acima da terceira assinatura. Uma aparente solução seria remover a checagem pelo órgão superior.

Entretanto, como isso é feito numa função genérica, ela precisa funcionar para atender aos casos em que há mais de um idAtoAdministrativo para diferentes órgãos, como a 630 (análise inicial).

Exemplos:

Sem órgão superior
```
SELECT
        idOrgaoSuperiorDoAssinante	
FROM
	"sac"."dbo"."tbatoadministrativo"
WHERE
	( idTipoDoAto in ( 630)) and 
	idOrdemDaAssinatura > 2
```

[retornam 8 resultados, e não apenas a próxima assinatura].

Com órgão superior, obtenho o resultado correto:
```
SELECT
        idOrgaoSuperiorDoAssinante	
FROM
	"sac"."dbo"."tbatoadministrativo"
WHERE
	( idTipoDoAto in ( 630)) and 
	idOrdemDaAssinatura > 2
	and idOrgaoSuperiorDoAssinante = 92
```

# Proposta de solução #

Adicionar o campo "grupo" à tabela sac.dbo.tbAtoAdministrativo. Sendo assim, a cada ato seria atribuído um campo grupo, com valores como 'A', 'B', 'C' etc. No caso relatado, ficaria:

```
idAtoAdministrativo    orgaoSuperior     ordemAssinatura    grupo
  630                    92                     1              A
  630                    92                     2              A
  630                    92                     3              A
  630                    93                     1              B
  630                    93                     2              B
  630                    93                     3              C
...
  631                    92                     1              A
  631                    92                     2              A
  631                    92                     3              A
  631                   251                     4              A
```

Essa solução ao nosso ver (@vinnyfs89, @Paulinhoibti e @fernao ) resolveria o problema, mas demandaria refatorações no núcleo do código.

**Comment by fernao** [comment]
--PASSO 1 - CHECAR CREDENCIAIS
SELECT Tabelas.dbo.fnValidaSenha('23969156149','123456'),usu_codigo, usu_orgao, usu_nome, usu_senha, usu_status
  FROM Tabelas.dbo.usuarios
 WHERE usu_identificacao = '23969156148'
--Mensagem de erro
--Se retornar usu_status = 0 a aplicação deverá enviar a mensagem : Cadastro do Usuário Desativado
--Se não retornar nenhum registro a aplicação deverá retornar a mensagem : Usuário inválido

-- PASSO 2 - Recuperar órgão, órgão superior e perfil inicial autorizado
SELECT TOP 1 usu_orgao, usu_orgaolotacao, uog_orgao, org_siglaautorizado, org_nomeautorizado, gru_codigo, gru_nome, org_superior, uog_status
  FROM Tabelas.dbo.vwUsuariosOrgaosGrupos
 WHERE     usu_codigo = 236 
       AND sis_codigo = 21
ORDER BY org_siglaautorizado,gru_nome 
--Mensagem de erro
--Se não retornar nenhum registro a aplicação deverá retornar a mensagem : Usuário NÃO credenciado no sistema
--Se retornar usu_status = 0 a aplicação deverá enviar a mensagem : CUsuário NÃO Habilitado a utilizar o Sistema

-- PASSO 3 - Carregar variáveis globais
  {glo_org_nome}         = usu_orgaolotacao;
  {glo_org_codigo}       = uog_orgao;
  {glo_org_superior}     = org_superior
  {glo_orgao}            = trim(org_siglaautorizado . gru_nome)
  {glo_org_nomecompleto} = org_nomeautorizado
  {glo_usu_perfil}       = gru_codigo
  {glo_nome_perfil}      = gru_nome

Essa é a maneira que sempre foi utilizada para logar o sistema e pegar os valores das variaveis globais.

Isso é fundamental para o fluxo de assinatura funcionar
Toda a ideía do fluxo de assinatura depende desse funcionamento

**Comment by fernao** [comment]
Movendo tarefa de refatoração da assinatura para #1302.

A finalização desta tarefa depende da #1302

**Comment by fernao** [comment]
Foi pensado em conjunto com @romulomb numa solução que evitaria a refatoração proposta na #1302:

Um ato administrativo está relacionado a um órgão superior. Caso haja mais de um, outro ato será criado para dar conta deste outro órgão. Sendo assim, somente existirão atos administrativos iguais para órgãos diferentes quando estes remeterem a trilhas de assinatura diferentes.

Caso essa regra não for observada e um ato administrativo possuir mais de um órgão superior, encontraremos falhas.

**Comment by fernao** [comment]
Alterei o modo de definição da próxima assinatura e joguei para hmg - 0e81076a446f764431cf4408ac68a427bd561ce7

**Comment by fernao** [comment]
Dependência: alterar tipo do ato para remover órgão superior SEFIC da primeira parte da assinatura

**Comment by fernao** [comment]
Criação dos novos atos administrativos libera continuidade da demanda. Assinatura será implementada SEM assinatura da SEFIC.

Caso seja necessário adicionar uma assinatura por parte da SEFIC, é preciso criar novo ato administrativo somente com uma assinatura.

**Comment by fernao** [comment]
Implementando alteração que adiciona grupos em #1522
