### ISSUE TITLE
[DADOS PROJETO] TRANSFERÊNCIA DE RECURSOS ENTRE PROJETOS

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1175]
**1. Na tela de consultar projetos ao clicar no link do valor TRANSFERIDO, a aplicação deverá disponibilizar  as informações dos valores transferidos.**

![Trans_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/458991a0-e1c9-4dd9-8ea9-a35f7f3550c5)

O formato da redenrização das informações segue na figura abaixo. A renderização deverá ser em uma modal.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8a8868be-d759-4744-a2a4-9115077082d4)

A query que trará as informações para a renderização segue abaixo

Sql 
```
'SELECT idPronacTransferidor,PronacTransferidor,NomeProjetoTranferidor,idPronacRecebedor,PronacRecebedor,NomeProjetoRecedor,dtRecebimento,vlRecebido
 FROM sac.dbo.vwTransferenciaRecursosEntreProjetos
 WHERE idPronacTransferidor = [ID DO PRONAC QUE ESTÁ SENDO CONSULTADO]
```
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

**2. Na tela de consultar projetos ao clicar no link do valor RECEBIDO, a aplicação deverá disponibilizar as informações dos valores recebidos.**

![Trans_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/933d971c-c7a5-4190-a8d7-dbe15f389466)

O formato da redenrização das informações segue na figura abaixo. A renderização deverá ser em uma modal.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8a8868be-d759-4744-a2a4-9115077082d4)

A query que trará as informações para a renderização segue abaixo

Sql 
```
'SELECT idPronacTransferidor,PronacTransferidor,NomeProjetoTranferidor,idPronacRecebedor,PronacRecebedor,NomeProjetoRecedor,dtRecebimento,vlRecebido
 FROM sac.dbo.vwTransferenciaRecursosEntreProjetos
 WHERE idPronacRecebedor= [ID DO PRONAC QUE ESTÁ SENDO CONSULTADO]
```
-----------------------------------------------------------------------------------------------------------

**PRONACs PARA TESTAR**

Transferidor pronac 10 10776

Recebedores :

pronac 14 7163 e 17 0480

-----------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------

**O toque de criatividade fica por sua conta**

-----------------------------------------------------------------------------------------------------------

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**PARABÉNS FICOU ÓTIMO**
