### ISSUE TITLE
[Dados Projeto] Criar componente para visualização da proposta

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1177]
## Dados do projeto
 - Inserir um link no número da proposta
 - Ao clicar no link criado o sistema deverá mostrar toda a proposta cadastrada, conforme a proposta é visualizada no perfil de coordenador de análise, menu análise -> avaliar adequação de projeto
 - deverá reaproveitar os componentes vuejs já existentes.

**Comment by guiamado** [comment]
Issue estimada na pontuação de 25 pontos, devido à quantidade de componentes no módulo.

**Comment by romulomb** [comment]
HOMOLOGADO

**SUBIR PARA PRODUÇÃO**
