### ISSUE TITLE
[LISTAR PROJETO] - HOTFIX

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1183]
**PERFIL DO PROPONENTE**

Os projetos em  apreciação da CNIC não poderão ter a situação visível proponente.

Sugestão da query para a tarja

' SELECT a.IdPRONAC, a.NumeroReuniao 
FROM SAC.dbo.Parecer AS a 
INNER JOIN SAC.dbo.tbReuniao AS b ON a.NumeroReuniao = b.NrReuniao 
INNER JOIN SAC.dbo.Projetos AS c ON a.IdPRONAC= c.IdPRONAC 
WHERE     b.stEstado = 0 
      AND a.AnoProjeto+a.Sequencial = [ pronac]

  AND c.Situacao in ('A14','A16','A17','A20','A23','A24','A41','A42','D02','D14','D50')

![Tarja.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/ec07a37c-bec2-4646-99df-b7b2b8ffc153)

**Comment by clebersantos** [comment]
@romulomb O que mudou?

**Comment by clebersantos** [comment]
@clebersantos Pode me passar um número de pronac de produção para eu verificar?

**Comment by romulomb** [comment]
Alteração na definição da issue.

**Comment by AdmissibilidadeSAV** [comment]
Testei e está tudo certinho.

![Tela inicial.JPG](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/1a6f81d3-2681-4ca0-91cf-542423e2bb77)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/fb9d61ac-47d1-450d-ba98-b8fee26fd0fe)

Homologada!
