### ISSUE TITLE
[AVALIAÇÃO DE RESULTADOS] - HOTFIX

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1196]
**AJUSTES**

**1 . A aplicação não está trazendo informações da comprovação conforme figura abaixo.**

![Avaliacao_1.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bdcb4579-c316-4ad0-9494-7ca1185b5366)

**OBS: Na máquina de homologação está ok**

--------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------

**2 . A aplicação está apresentado mensagem de erro ao tentar salva a analise da comprovação, conforme a figura abaixo.**

![Avaliacao_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/9791a049-68d2-4701-86fc-9db11dca5ebd) 

--------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------

**3 .  A aplicação está mostrando o mesmo comprovante em etapas diferentes, A informação da comprovação destacada na figura corresponde a Midia Radiofônica de outra etapa**

![Avaliacao_3.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/1e2bbec1-43c6-4c49-9735-76356fa16390)

--------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------

**4 . Totalização equivocada no painel do analista, conforme demonstra a figura abaixo.**

![Avaliacao_4.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/0389e3de-d286-4599-9cc5-b3ce066f3f8d)

--------------------------------------------------------------------------------------------------------------------

--------------------------------------------------------------------------------------------------------------------

**5 .  Não está trazendo a informação, conforme figura abaixo.**

![Avaliacao_5.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/76990717-84c9-4d47-a6b0-52fc8186be74)

**Comment by romulomb** [comment]
**Por gentileza, dê prioridade a essa solicitações**

**Comment by wouerner** [comment]
em andamento.

**Comment by wouerner** [comment]
Finalizado.
