### ISSUE TITLE
[ASSINATURA] - COORDENADOR DE PARECER - HOTFIX

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1197]
Verificar o fluxo de assinatura.

**Constatação**

Após o parecerista assinar o parecer, a aplicação está enviando o parecer diretamente ao MinC. 

Quando deveria enviar para o coordenador de parecer e finalizar com a assinatura do presidente da vinculada.

**Comment by vinnyfs89** [comment]
Bom dia, tudo bom?
O @fernao  e @Paulinhoibti  estão trabalhando em conjunto comigo nesta issue para que todos tenham o mesmo conhecimento referente ao módulo de assinatura.

Precisamos saber as seguintes informações para que possamos identificar o erro mencionado:
- Qual o tipo do ato administrativo utilizado
- Não ficou claro para nós o seu comentário a seguir `Após o parecerista assinar o parecer, a aplicação está enviando o parecer diretamente ao MinC.` , você poderia evidenciar utilizando prints e links?
- `Quando deveria enviar para o coordenador de parecer e finalizar com a assinatura do presidente da vinculada` , nesse trecho você quis dizer que com o perfil de parecerista, ao invés de encaminhar para o coordenador de parecer já está executando a ação de finalizar?

**Comment by AdmissibilidadeSAV** [comment]
Boa tarde @vinnyfs89!

- O Ato Administrativo é  **Análise Técnica para Homologação de Projeto**.

- Acredito que o ambiente de homologação não esteja igual a produção, pois em homologação o parecerista não consegue nem consolidar a análise, muito menos assinar o parecer, mas segue os prints das telas, o pronac utilizado foi o 181162, CPF: 00844309745, Perfil: Parecerista, visando demonstrar como é o fluxo de análise técnica do parecerista.

Ao salvar a análise do produto secundário na tela abaixo:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/f22e56f4-2725-45b1-8107-92818c83dd0c)

https://hmg.salic.cultura.gov.br/analisarprojetoparecer/produto?idPronac=218818&idProduto=3&stPrincipal=0&idD=901917

Quando retorno para o painel de Análise Técnica Inicial não está aparecendo o ícone de conclusão da análise do produto. 

![parec.jpg](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/072a91b6-c80f-454c-9f69-cba681feff1e)

https://hmg.salic.cultura.gov.br/parecer/analise-inicial

Não sei se é por esse motivo, mas quando clico para fazer a análise do produto principal, após salvar a análise de conteúdo e análise de custos, logo abaixo do campo Dados dos Produtos Secundários, não está aparecendo a Consolidação da Análise.

![Parece.jpg](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/c6300b97-144c-4793-8d56-34a946aff1fd)

https://hmg.salic.cultura.gov.br/analisarprojetoparecer/produto?idPronac=218818&idProduto=51&stPrincipal=1&idD=901918

- Quanto a última dúvida _"ao invés de encaminhar para o coordenador de parecer já está executando a ação de finalizar?"_, no ambiente de produção após o parecerista assinar o documento o projeto deveria continuar na situação B11 e entrar no perfil de Coordenador de Parecer, menu Análise - Gerenciar Pareceres - Filtro Em validação, para que possa verificar se a análise está ou não em conformidade, concluir a análise dos produtos e assinar a análise do produto principal (https://hmg.salic.cultura.gov.br/parecer/gerenciar-parecer?tipoFiltro=em_validacao&pronac=), para ser encaminhado para assinatura no perfil de Presidente da Unidade Vinculada, no entanto, após a assinatura do parecerista a situação do projeto está sendo alterada para C20 e a análise está indo direto para o perfil de Coordenador de Análise, menu Análise - Gerenciar Pareceres. 

**OBS: Qualquer dúvida coloco-me a disposição.**

**Comment by romulomb** [comment]
Quanto a última dúvida "ao invés de encaminhar para o coordenador de parecer já está executando a ação de finalizar?", no ambiente de produção após o parecerista assinar o documento o projeto deveria continuar na situação B11 e entrar no perfil de Coordenador de Parecer, menu Análise - Gerenciar Pareceres - Filtro Em validação, para que possa verificar se a análise está ou não em conformidade, concluir a análise dos produtos e assinar a análise do produto principal (https://hmg.salic.cultura.gov.br/parecer/gerenciar-parecer?tipoFiltro=em_validacao&pronac=), para ser encaminhado para assinatura no perfil de Presidente da Unidade Vinculada, no entanto, após a assinatura do parecerista a situação do projeto está sendo alterada para C20 e a análise está indo direto para o perfil de Coordenador de Análise, menu Análise - Gerenciar Pareceres.

@vinnyfs89 A observação acima está correta, é isso mesmo que deveria acontecer. No entanto já tenho dois projetos da funarte e um da SAV que não aconteceu como relatado.

O parecerista assinou parecer, o projeto entrou na situação C20 e foi encaminhado ao MinC.

Os pronacsn 180745 e 181509 são exemplos relatados pela funarte no dia 20/08/2018.

**Comment by fernao** [comment]
Olás,

Sobre a frase:
"Acredito que o ambiente de homologação não esteja igual a produção, pois em homologação o parecerista não consegue nem consolidar a análise, muito menos assinar o parecer, mas segue os prints das telas, o pronac utilizado foi o 181162, CPF: 00844309745, Perfil: Parecerista, visando demonstrar como é o fluxo de análise técnica do parecerista."

Até onde eu conheço, um produto secundário não possui fluxo de assinatura, apenas o primário. A relação do produto secundário com a assinatura é que somente quando todos os produtos secundários tiverem sido analisados, o botão é liberado.

**Comment by AdmissibilidadeSAV** [comment]
@fernao Isso mesmo o produto secundário não possui fluxo de assinatura, só ilustrei o passo a passo da análise do parecerista até chegar a assinatura, detalhando que é necessário concluir primeiro os produtos secundários, quando houver, para depois conseguir analisar o produto principal e assinar, porém no ambiente de homologação não estou conseguindo reproduzir o que está acontecendo no ambiente de produção. Talvez se a HMG fosse atualizada conforme está em produção em conseguiria passar os prints para melhor entendimento de vocês.

**Comment by vinnyfs89** [comment]
Prezados,

Após exaustiva investigação, nós @avaloni , @fernao e @Paulinhoibti , identificamos que a alteração da situação não foi realizada à partir do módulo de assinatura. Foi constatado que o único momento no qual a situação é modicada para 'C20' é durante a ação de finalizar, que ocorre após a assinatura do terceiro assinante para o tipo do ato administrativo **630**.

Identificamos que existe uma funcionalidade dentro do sistema que atualmente altera a situação do projeto para **C20** ao concluir um parecer dentro de Gerenciar Pareceres. 

Conforme identificador de Projeto Cultural informado na Issue, utilizamos as queries abaixo para identificar que a situação foi modificada após atualizar um registro na tabela **tbDistribuirParecer**.

```
select dtassinatura from sac..tbAssinatura where idpronac = 219162 and iddocumentoassinatura = 10363;
```
```
select dtdevolucao from tbDistribuirParecer where idPRONAC = 219162;
```

Quando o documento foi gerado, a situação do Projeto já estava como "C20", conforme trecho de código abaixo:

Arquivo: [GerenciarParecerController.php](https://github.com/culturagovbr/salic-minc/tree/master/application/modules/parecer/controllers/GerenciarParecerController.php#L256)

```
if ($tipoFiltro == 'validados' || $tipoFiltro == 'devolvida') {
    $projeto->alterarSituacao($idPronac, null, 'C20', 'Anlise t&eacute;cnica conclu&iacute;da');
} elseif ($tipoFiltro == 'em_validacao') {
    $projeto->alterarSituacao($idPronac, null, 'B11', 'Aguardando valida&ccedil;&atilde;o do parecer t&eacute;cnico');
}
```

**Comment by fernao** [comment]
Solução: adicionamos uma verificação extra antes de finalizar, para os casos em que o código do usuário na sessão vem dos dados do usuario e não do agente.

O erro acontecia quando um usuário com codigo órgão diferente do perfil da sessão tentava assinar. Ex: um usuário inicialmente lotado na RR/RJ mas com perfil FUNARTE. Logo, o órgão não aparecia na lista de órgãos da trilha da assinatura.

**Comment by fernao** [comment]
A trilha funcionou corretamente e foi homologada até a parte de executar a ação de finalizar no momento correto. 

Mas foi constatado que os projetos finalizados não estão aparecendo na tela do Coordenador de Análise - DIAAPI. O projeto não retorna ao órgão de origem, permanencendo aonde está (projetos.orgao, ao invés de receber o valor de projetos.OrgaoOrigem). Estou investigando porque ele não consegue alterar o código

**Comment by fernao** [comment]
Adicionada correção que permitiu a correta finalização do projeto. O fluxo da assinatura de um projeto Funarte chegou até o final - painel de coordenador de análise

**Comment by AdmissibilidadeSAV** [comment]
Testado e homologado.
