### ISSUE TITLE
Erros nos valores aprovados dos comprovantes

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#1203]

**Comment by pauli10** [comment]
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/8073510a-7613-422e-bdcf-fdd123d27eae)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/3033d008-88fa-4d1e-95b5-2388095bd2e3)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/1a909076-595d-481b-b0d1-8d4deffab496)

A tela quebra ao clicar nos itens em destaque.

**Comment by romulomb** [comment]
Se precisar de ajuda é entrar em contato.
