### ISSUE TITLE
[ DADOS DO PROJETO ] Formatar campos - melhorias

### ISSUE THREAD

**Issue by FernandaLA** [culturagovbr/salic-minc#1206]
Parcial Issue #1132

Menu suspenso (2 pontos)
 - Adicionar uma seta que faça scroll para baixo

Formatar campos em dados do projeto (5 pontos)
 - adicionar traço na agência
 - formatar número das contas de movimentação e bloqueadas, tirando os zeros à esquerda e adicionar traço no último dígito
 - Corrigir bug do botão voltar da página que lista projetos por cpf

**Comment by AdmissibilidadeSAV** [comment]
Testado e homologado.

**Comment by romulomb** [comment]
**PARABÉNS FERNANDA**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**

**Comment by romulomb** [comment]
**CORREÇÃO**

1 . Colocar um traço no nº da agência;

2 . O Nº da conta da movimento está incorreto.

![Conta.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/44f88f19-400c-4a06-a893-1507b69edda2)

**Comment by clebersantos** [comment]
Formato das contas atualizado.

**Comment by romulomb** [comment]
**PARABÉNS FERNANDA**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
