### ISSUE TITLE
[DADOS DO PROJETO] Menu lateral convenio - melhorias

### ISSUE THREAD

**Issue by FernandaLA** [culturagovbr/salic-minc#1217]
Parcial da issue #1132

Menu lateral de projeto de convênio(FNC) (3 pontos)
Incluir os itens de menu abaixo
1 . Dados do Projeto
2 . Proponente
3 . Outras Informações
 a) Certidões Negativas

 b) Documento Anexados

 c) Diligência do Projeto

 d) Providência Tomada

 e) Tramitação
4 . Execução
 a) Dados da Fiscalização
5 . Solicitações

**Comment by romulomb** [comment]
Homologado.
