### ISSUE TITLE
Erro no cadastro de proponente com email .com.br

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#1226]
Ao tentar cadastrar novo proponente na rota "http://salic.cultura.gov.br/agente/agentes/incluiragente", ele retorna "E-mail inválido!"
![screenshot from 2018-08-22 10-19-14](https://user-images.githubusercontent.com/1541692/44467091-603ec900-a5f8-11e8-8d51-6e35d7779918.png)

Olhando rápido, parece uma treta no agentes.js, na função 'validaAgenteNovo':
```
if (
        $3('#exibirEmail').val() == 's'
        && (
            ($3('#email').val().indexOf("@") < 1)
            || ($3('#email').val().lastIndexOf(".") <= $3('#email').val().indexOf("@"))
            || ($3('#email').val().indexOf("@") == $3('#email').val().length)
            || !(/^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{3,3})+$/.test($3('#email').val()))
        )
    ) {
        alertar("E-mail inv&aacute;lido!", "email");
        exibirMsgErro('email','erroEmail');
        return;
```

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA A PRODUÇÃO**
