### ISSUE TITLE
[ Hotfix ] Visão Agentes

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1236]
Na visão do perfil Gestor Salic, ao tentar ver tela de visão do agente.

**Comment by guiamado** [comment]
![image](https://user-images.githubusercontent.com/28310065/44483421-6d23e280-a621-11e8-93a3-60af1bddb038.png)

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO POR GENTILEZA**

**OBRIGADO**

**Comment by clebersantos** [comment]
Já está em produção.
