### ISSUE TITLE
[ HOTFIX ] Proponentes não conseguem enviar proposta

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1237]
Prezados,

Vários proponentes com cadastrados preenchidos de maneira correta ao tentarem enviar propostas ao MinC recebem a seguinte mensagem de erro: **"O solicitante não tem perfil de proponente cadastrado."**

Alguns exemplos para vocês testarem: 286254, 279625, 284942, 275227, 284562, 286214, 285340 ..... e a lista continua....

Obrigado.

**Comment by clebersantos** [comment]
@boletocosta André, a mensagem aparece para todos usuários?

**Comment by boletocosta** [comment]
@clebersantos, não sei se são para todas.. creio que não...  mas depois da versão 5 do SALIC essa reclamação subiu muito e está acontecendo com bastante frequência.

**Comment by clebersantos** [comment]
Seguindo o comentário da @AdmissibilidadeSAV(Thais), disponibilizei para o proponente a opção de corrigir a inconsistência. 

Quando ele for enviar a proposta receberá a mensagem: "O solicitante não tem perfil de proponente cadastrado." com o link para adicionar o perfil. Conforme imagens abaixo.

Tela mostrando a inconsistência.
![Screen Shot 2018-08-22 at 17.47.45.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/f93afd5d-b1f8-4e99-b5bd-622ccf82e3c4)

Tela para corrigir.
![Screen Shot 2018-08-22 at 17.50.04.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/7060370a-3954-4091-adab-c5b3d7b9fcd0)

Vai subir para produção na próxima release.
