### ISSUE TITLE
Campo "Justificativa do Proponente" em branco

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1257]
Após a resposta à diligência pelo proponente, o campo "Justificativa do Proponente" aparece em branco para o técnico de prestação de contas. 

Durante a resposta à diligência, o proponente preenche o campo "Justificativa":
![image](https://user-images.githubusercontent.com/37881003/44605017-37683080-a7be-11e8-8b61-88be2a1d9a3c.png)

Após finalizada a resposta à diligência e ela ser enviada para o técnico de prestação de contas, o campo "Justificativa do Proponente" aparece em branco:

![image](https://user-images.githubusercontent.com/37881003/44605151-a6de2000-a7be-11e8-8fa2-c5d2e6b0f2c8.png)

**Comment by pauli10** [comment]
O técnico faz a análise e coloca as ocorrências em cada item descrevendo o motivo do documento ser impugnado. Quando ele envia ao proponente, esta ocorrência deve aparecer logo abaixo a justificativa do proponente. Não está aparecendo.
![image](https://user-images.githubusercontent.com/39531450/44675169-1b56d000-aa06-11e8-9572-f2b64e1e9b0a.png)

Quando o proponente visualiza a diligência, o botão voltar está inativo.
![image](https://user-images.githubusercontent.com/39531450/44675212-3de8e900-aa06-11e8-9465-5f53d2193561.png)

![image](https://user-images.githubusercontent.com/39531450/44675301-830d1b00-aa06-11e8-89d4-fa9ee84170fd.png)
![image](https://user-images.githubusercontent.com/39531450/44675375-c10a3f00-aa06-11e8-947b-77ce275f09d6.png)
![image](https://user-images.githubusercontent.com/39531450/44675470-fca50900-aa06-11e8-93d9-32f80a679f29.png)

**Comment by pauli10** [comment]
Quando o proponente edita um comprovante, mesmo ele mantendo as datas, elas aparecem como inválidas.
![image](https://user-images.githubusercontent.com/39531450/44676078-9f11bc00-aa08-11e8-8216-5c944eb9d37e.png)

O campo de justificativa do proponente continua aparecendo em branco para o técnico.
![image](https://user-images.githubusercontent.com/39531450/44676343-59092800-aa09-11e8-8646-25c539354b55.png)
