### ISSUE TITLE
[Admissibilidade] Destacar as propostas que enviaram recurso contra o enquadramento ou que desistiram do prazo recursal

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1259]
Destacar as propostas que enviaram recurso contra o enquadramento ou que desistiram do
prazo recursal

Tarja as propostas.

Sugestão incluir filtro de recurso

**Comment by fernao** [comment]
Estamos adicionando uma marcação em azul para as propostas que:
* possuem recurso OU desistiram do prazo recursal

**Comment by boletocosta** [comment]
Testei e está funcionando. Mas também gostaria que a marcação em azul aparecesse para as propostas que esgotaram o prazo de 10 dias para recurso. Pode ser?

**Comment by fernao** [comment]
Adicionar marcação em azul para propostas esgotadas do prazo.

**Comment by fernao** [comment]
@romulomb ficou de verificar query, que não estava muito performática. A funcionalidade está pronta e pronta para ir para homologação.

**Comment by boletocosta** [comment]
@fernao, conseguiu  adicionar a marcação em azul para propostas esgotadas do prazo? Não temo como testar isso né? Mas a issue está homologada sim, pois as funcionalidades pedidas inicialmente foram implementadas! =)

**Comment by fernao** [comment]
Sim, adicionamos com prazo expirado. Vou publicar

**Comment by boletocosta** [comment]
Prezados, 

Apesar de homologada, estamos com um problema. 

Na descrição da issue e nos comentários foi pedido para que a marcação em azul aparecesse *somente* em 03 casos:
1 - quando o proponente entrasse com recurso
2 - quando o proponente desistisse do recurso
3 - quando o prazo de 10 dias do recurso se esgotasse

Contudo, apesar de não estar da descrição da issue, atualmente a marcação em azul também ocorre em um quarto caso: quando o prazo recursal é aberto. Isso não faz o menor sentido, pois dessa forma tudo fica azul. A ideia é que as 03 situações anteriores ficassem em azul para diferenciar exatamente da situação de quando o prazo recursal é aberto. 

Dessa forma, não deveríamos ter homologado a issue. Podemos reabrir para ajustar ao que foi descrito na issue? Obrigado.

**Comment by boletocosta** [comment]
Bom dia pessoal.

Alguma posição sobre meu comentário feito dia 31/08?

Podemos reabrir a issue, por gentileza?

Obrigado...

**Comment by boletocosta** [comment]
Homologado!!!
