### ISSUE TITLE
[Admissibilidade] Ao transformar em projeto gerar o documento a ser assinado.

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1260]
Ao transformar em projeto gerar o documento a ser assinado

Gerar o documento automaticamente e colocar o projeto na situação B04

Iniciar o fluxo na transformação

**Comment by fernao** [comment]
@romulomb :  dúvidas:

1) Qual é o idAtoAdministrativo associado?assinatura 

2) O documento será gerado ao iniciar o processo de transformação, deixando uma assinatura pendente. A proposta sairá da calha atual e irá para outras listagens, de projeto. Como conduzir o coordenador de admissibilidade até o local da assinatura ? Via aba assinaturas?

3) O projeto é gerado e posto na situação B04, com documento gerado aguardando assinatura. Ao assinar, existe algum procedimento adicional?

**Comment by romulomb** [comment]
@fernao Acho que a demanda  não foi entendida.  Amanhâ tentarei esclarecer com maiores detalhes

**Comment by fernao** [comment]
Como coordenador geral de admissibilidade:

* [ ] ao apertar botão transformar, jogar projeto para B04.
* [ ] ao apertar botão transformar, gerar documento para assinar

**Comment by AdmissibilidadeSAV** [comment]
Homologado.

**Comment by boletocosta** [comment]
Homologado.

**Comment by vinnyfs89** [comment]
@boletocosta Não tive tempo pra acompanhar esse item, mas uma sugestão é utilizar o método “iniciarFluxo” localizado no serviço dentro do módulo de admissibilidade, mantendo o padrão do que foi desenvolvido :)

**Comment by boletocosta** [comment]
Pode subir para prod já ou vamos esperar algum pacote?
