### ISSUE TITLE
[Admissibilidade] Somente abrir prazo para recursos quando alterar o enquadramento

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1261]
Somente abrir prazo para recursos quando alterar o enquadramento 

Somente se o artigo for diferente.
A regra atual abre prazo recursal se o segmento solicitado for diferente do sugerido

Enquadramento de acordo com o artigo

**Comment by fernao** [comment]
Quando um enquadramento ocorre num artigo diferente, um recurso é aberto.

Ao realizar um novo enquadramento sob o mesmo artigo, é necessário inativar os recursos anteriores.

**Comment by AdmissibilidadeSAV** [comment]
Por mim está tudo ok. Homologado.
