### ISSUE TITLE
Pessoa não encontrada no cadastro de proponente

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#1273]
Na URL http://salic.cultura.gov.br/agente/agentes/incluiragente , ao inserir o cpf de uma pessoa, algumas vezes ele funciona, outras ele apresenta a mensagem "pessoa não encontrada" na interface.

Exemplos abaixo:

![screenshot from 2018-08-28 20-43-25](https://user-images.githubusercontent.com/1541692/44758631-06646480-ab0c-11e8-88ce-41413165469a.png)

![screenshot from 2018-08-28 20-43-36](https://user-images.githubusercontent.com/1541692/44758632-08c6be80-ab0c-11e8-981a-a423d00383cd.png)

**Comment by clebersantos** [comment]
O serviço da receita estava apresentando problemas. Após a estabilização do serviço, fiz alguns testes e o problema não ocorreu novamente.
