### ISSUE TITLE
[Hotfix] - Recurso enquadramento de proposta

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1275]
Bom dia pessoal.  

De acordo com as regras estabelecidas nas issues #647 e #834, o proponente pode entrar com recurso quanto ao enquadramento da proposta no máximo por duas vezes. Se o recurso for negado pela segunda vez o proponente não pode entrar com mais pedidos e o botão transformar em projeto precisa ser liberado.

Contudo, o comportamento em produção difere do acordado. Após o segundo pedido de recurso quanto ao enquadramento ser negado o botão para transformar em projeto não é liberado e o proponente pode entrar com um terceiro pedido de recurso quanto ao enquadramento.  

Proposta com o erro em produção : nº 281020 (já está no terceiro pedido de recurso quando ao enquadramento).

**Comment by vinnyfs89** [comment]
@boletocosta Esse erro deveria ser mapeado na fase de homologação e na época na qual foi desenvolvida ele não foi reportado, portanto pode ter sido ocasionado devido à evoluções e ajustes dentro do sistema.

**Comment by fernao** [comment]
Eu e @AdmissibilidadeSAV investigamos e nos demos conta que o botão de "Transformar em Projeto" funciona corretamente. O que ocorreu foi que o coordenador geral de análise criou um novo enquadramento, o que abriu a possibilidade de o proponente realizar dois novos recursos. Sendo assim, a funcionalidade está funcionando conforme o previsto.
