### ISSUE TITLE
[LIBERAR LINK DE PLANILHA] - HOTFIX

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1294]
Quando o proponente inicia um readequação de planilha o link desaparece.

**Comment by fernao** [comment]
Não consegui reproduzir o erro relatado.

Quando o proponente inicia uma planilha orçamentária, as outras opções são fechadas e permanece apenas o link de planilha orçamentária. 

Quando ele inicia um remanejamento de 50%, os outros links são inibidos e permanece apenas o link de remanejamento 50%.

Possui alguma tela?

**Comment by fernao** [comment]
Achei um caso

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO POR GENTILEZA**

**OBRIGADO, FERNÃO**

**vOCÊ É  O CARA**.
