### ISSUE TITLE
Perfil proponente - Retirar possibilidade de recurso quanto ao enquadramento na fase de projeto

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1301]
Prezados,

Os proponentes conseguem entrar com recurso contra o enquadramento após a proposta ser transformada em projeto. A opção de recurso abre para o proponente quanto o projeto está na seguinte situação: "B02	Projeto enquadrado após avaliação técnica".

Contudo, recurso de enquadramento estão sendo aceitos SOMENTE na fase de proposta. Ou seja, a funcionalidade de entrar com recurso quanto ao enquadramento na fase de projeto não pode estar disponível para o proponente.

**Comment by fernao** [comment]
A princípio, com a resolução da #1300, esse problema será corrigido. Verifcar

**Comment by boletocosta** [comment]
Problema corrigido em virtude da resolução da 1300. Pode fechar o card.
