### ISSUE TITLE
[Proposta] Desarquivamento com formatação quebrada

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1305]
Todos os textos dos pedidos de desarquivamento estão com caracteres "estranhos".. dá para ver na imagem do erro o texto do pedido todo "desconfigurado".

**Comment by fernao** [comment]
![cd88b8a8-ad3e-4b7d-b585-481ed35e0c3a.png](https://images.zenhubusercontent.com/5a5d055d4b5806bc2bc2d309/922e2bfd-7fea-4c1f-9c09-3598f5b049d3)

**Comment by boletocosta** [comment]
Não consigo testar em homolg porque quando entro como proponente para listar as propostas arquivadas e pedir um desarquivamento o sistema retorna a mesagem: DataTables warning: table id=tabelaAnaliseFinal - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/1

**Comment by fernao** [comment]
Não consegui reproduzir. Você consegue mandar uma tela ?

**Comment by boletocosta** [comment]
tá ai:

![erro.png](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/755fe07c-a59c-4dda-bae0-f83fd680aa7b)

**Comment by boletocosta** [comment]
Bom dia pessoal. Alguma novidade? Não consigo testar para homologar porque o erro relatado acima permanece. Obrigado.

**Comment by Paulophmp** [comment]
@boletocosta, poderia testa-la novamente, corrigimos o erro.

**Comment by boletocosta** [comment]
Testei e o erro da formatação quebrada continua.

Segue o print:

![Capturar.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/c076125d-88a2-424d-854c-10a2c2781a7b)

**Comment by boletocosta** [comment]
Bom dia pessoal!

Alguma novidade? 

Obrigado...

**Comment by Paulophmp** [comment]
@boletocosta boa tarde, poderia testá-la novamente.

**Comment by Paulophmp** [comment]
@boletocosta boa tarde, poderia testá-la novamente, corrigimos o erro =).

**Comment by boletocosta** [comment]
Homologado!  Só um detalhe: quando o proponente escreve o pedido de desarquivamento e clica no botão enviar o sistema não retorna a informação que o pedido foi enviado.. é necessário dar o refresh  na página para saber que o pedido está em análise.

**Comment by Paulophmp** [comment]
@boletocosta, corrigido o problema de refresh da página.
