### ISSUE TITLE
[Dados Projeto] Migração de tela de Convênio Para VUE

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1313]
Como analista de sistemas identifiquei a necessidade de migrar a tela que mostra dados do Convênio par VueJs com objetivo de reutilizar componentes utiizados em projetos para incentivo fiscal.

**Comment by clebersantos** [comment]
Tela migrada, disponível em homologação. Agora independente do mecanismo o sistema aponta para a mesma url. URL + /projeto/#/idPronac

**Comment by romulomb** [comment]
**HOMOLOGADO**


**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
