### ISSUE TITLE
[Solicitações] Histórico de solicitações da propostas na consulta da proposta

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1318]
## Adicionar na lista de itens da proposta em VueJS ao consultar projeto
- [x] Adicionar Histórico de solicitações ( /solicitacao/mensagem/index/idPreProjeto/282175  -> /projeto/#/incentivo/216941/proposta ), Obs.: Colocar Data Table e paginação ( a definir );
- [x] Adicionar Histórico de Enquadramentos ( Assim como o campo na Parte de Análise da Proposta Coordenador de Análise -> Admissibilidade -> Avaliação );
- [x] Colocar a Planilha Orçamentária como último item da listagem;
- [ ] Colocar novo modelo de visualização da proposta na parte de Análise da Proposta ( Coordenador de Admissibilidade -> Admissibilidade -> Avaliação ). -> foi redirecionada para outra issue #1360.

**Comment by boletocosta** [comment]
Bom dia.

O histórico de enquadramento e de solicitações não traz as informações corretas:

![Capturar.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/bcaf82a1-4763-4814-b231-773cc8a6c047)

**Comment by RuanHerculano** [comment]
Disponível em Homologação. @boletocosta @romulomb

**Comment by boletocosta** [comment]
homologado

**Comment by clebersantos** [comment]
@boletocosta, na listagem "Histórico de sugestões de enquadramento" são exibidas as seguintes colunas Data, Avaliador,	Unidade,	Área, Segmento, Enquadramento e Parecer. Todas colunas são necessárias? Existe alguma restrição ou o proponente pode visualizar todas informações?

**Comment by boletocosta** [comment]
Pode visualizar todas as informações
