### ISSUE TITLE
[READEQUAÇÃO] AJUSTES NO PAINEL DE READEQUAÇÕES  ANALISADAS

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1330]
**BREVE DESCRIÇÃO**
Ajustar, corrigir e melhorar a utilização do painel de **readequações analisadas**, facilitando o trabalho do coordenador de acompanhamento.

**Perfil: Coordenador de Acompanhamento**

**ATIVIDADES**

**1 . BOTÃO DEVOLVER**
   a . Alterar o label da coluna  'Encaminhar' para 'Devolver' - FEITO
   b . Alterar direção da seta 'devolver' - FEITO
   **c. Regras do botão Devolver**
        c1 . ao clicar no botão 'devolver', apagar/inativar o documento da assinatura FEITO
        c2 . Habilitar o botão devolver somente quando o atributo siEncaminhamento for igual a: 
 **6 - Solicitação devolvida ao MinC pela unidade de análise; FEITO
10 - Solicitação devolvida para o coordenador pelo técnico; FEITO
21 -	Solicitação devolvida ao coordenador pelo coordenador-geral; FEITO
22 -	Solicitação devolvida ao coordenador pelo diretor; FEITO
23 -	Solicitação devolvida ao coordenador pelo secretário.** FEITO
        c3 . Ao devolver o parecer para nova análise o atributo siEncaminhamento da tabela tbReadequacao deverá ser alterado conforme abaixo descrito:
**quando  for  6** - Solicitação devolvida ao MinC pela unidade de análise  **para  3** - Solicitação encaminhada a  unidade de análise pelo MinC ou  FEITO
**quando  for  10**  - Solicitação devolvida para o coordenador pelo técnico  **para  4** -Solicitação encaminhada ao parecerista /  técnico. FEITO

**2 . BOTÃO ASSINAR**    
   a.  Alterar  o link do botão assinar para janela de assinatura numa modal (adicionar idDocumentoAssinatura à listagem) FEITO
   **c . Regras do botão Assinar**
        c1 .  ao clicar no botão 'Assinar', abrir a modal de assinatura no próprio painel do coordenador
        c2 .  Habilitar o botão Assinar somente quando o atributo siEncaminhamento for igual a: 6 - Solicitação devolvida ao MinC pela unidade de análise ou 10 - Solicitação devolvida para o coordenador pelo técnico - FEITO
        c3 . Ao assinar o parecer alterar na tabela tbReadequacao  o atributo siEncaminhamento para **18 - Solicitação encaminhada ao coordenador-geral**  - FEITO

**BOTÃO CNIC**
 Remover do painel de coordenador a funcionalidade de envio de parecer para CNIC. - FEITO

**BOTÃO FINALIZAR**
 a . Remover as funcionalidades de finalizar da última assinatura para os atos administrativos 653, 654 e 655. FEITO para os outros tipos de ato (esses foram cancelados)
b . Adicionar as funcionalidades de finalizar para os atos administrativos 653, 654 e 655 no **botão FINALIZAR**. - (653, 654 e 655 cancelados) FEITO para os atos corretos 
**c . Regras do botão Finalizar**
Habilitar o botão Finalizar somente quando o atributo siEncaminhamento for igual a 26 - Solicitação devolvida ao Coordenador após completar o ciclo de assinaturas - FEITO

**ÚLTIMA ASSINATURA**
1 . Após a última assinatura for efetuada alterar, na tabela tbReadequacao, o  atributo siEncaminhamento for igual a 26 - Solicitação devolvida ao Coordenador após completar o ciclo de assinaturas. FEITO

2 . Após a última assinatura for efetuada alterar, na tabela tbDocumentoAssinatura, **os atributos cdSituacao para 2 e o atributo stEstado para 1**. FEITO

===================================================================

**QUERY PARA MONTAR O PAINEL**

**A query abaixo contém todos os atributos necessários para atender as regras acima descritas.**
sql
' SELECT idPronac,idReadequacao,PRONAC,NomeProjeto,dtEnvio,dtDistribuicao,dtDevolucao,qtDiasDistribuir,qtDiasAvaliar,
       qtTotalDiasAvaliar,tpReadequacao,idTecnicoParecerista,nmTecnicoParecerista,idOrgao,sgUnidade,idOrgaoOrigem,siEncaminhamento,
	   idDocumentoAssinatura
FROM vwPainelCoordenadorReadequacaoAnalisados WHERE idOrgaoOrigem = [ÓRGÃO DO USUÁRIO  LOGADO]'

**Comment by fernao** [comment]
Botão assinar aparece para projetos que não tem assinatura. Apenas exibir quando possuir assinatura no passo.

**Comment by romulomb** [comment]
@fernao coloquei as regras na definição da issue, qualquer dúvida é só avisar.

**Comment by romulomb** [comment]
@fernao Incluido o idDocumentoAssinatura na View.

**Comment by romulomb** [comment]
@fernao  **Ajustei a definição no corpo da issue**.

**ÚLTIMA ASSINATURA**
1 . Após a última assinatura for efetuada alterar, na tabela tbReadequacao, o  atributo siEncaminhamento for igual a 26 - Solicitação devolvida ao Coordenador após completar o ciclo de assinaturas.

2 . Após a última assinatura for efetuada alterar, na tabela tbDocumentoAssinatura, **os atributos cdSituacao para 2 e o atributo stEstado para 1**.

**Comment by romulomb** [comment]
**Complementação de regra de negócio no corpo da issue**.

**Comment by fernao** [comment]
Em impedimento conjuntamente com a #1332; deve aguardar definição de solução técnica junto à área.

**Comment by romulomb** [comment]
@fernao 

Solicitação atendida na issue 1332.

**Comment by fernao** [comment]
Problema encontrado nas assinaturas de readequação: ao obter nova assinatura baseada no modelo novo de assinaturas separadas por tipo de readequação, a função 
 Assinatura_Model_DbTable_TbAtoAdministrativo->obterAtoAdministrativoAtual() retorna não uma, mas 5 próximos passos (uma vez que são as mesmas para vários atos).

Novamente, isso seria resolvido conforme já foi apontado anteriormente utilizando-se dos grupos de assinatura (https://github.com/culturagovbr/salic-minc/issues/1167#issuecomment-416319033).

Isso gera grande impasse pois a assinatura não está se comportando corretamente uma vez que o atoAdministrativo escolhido está errado.

**Comment by fernao** [comment]
[https://app.zenhub.com/files/104502087/5bf7923f-b254-46fe-8e77-3ef785a217bf/download](https://app.zenhub.com/files/104502087/5bf7923f-b254-46fe-8e77-3ef785a217bf/download)

**Comment by fernao** [comment]
Movida para homologação, favor testar

**Comment by fernao** [comment]
A adoção de assinaturas paralelas acarretou num problema quanto ao encaminhamento dos projetos, uma vez que não seria possível utilizar a alteração de órgão. Sendo assim, definiu-se por ato administrativo qual o método de encaminhamento. O tratamento à questão foi dado na issue #1646.
