### ISSUE TITLE
[READEAQUAÇÃO] PAINEL DE ASSINATURA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1332]
Perfis : Coordenador de Geral de Acompanhamento e Execução e Diretor.

**1 . Ajustar o painel conforme figura anexada abaixo.**
![PainelReadequacaoAssinatura.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/43fca8dd-05b7-42b4-aad6-87a4dd153597)

**2 . Substituir a query de montagem do painel  pela view abaixo.**

SQL
 'SELECT Pronac,NomeProjeto,dsTipoDoAtoAdministrativo,dsReadequacao,idPronac,Orgao,idDocumentoAssinatura,idTipoDoAtoAdministrativo,QtdeDePessoasQueFaltamAssinar,
       QtdeDePessoasQueAssinaramDocumento,QtdeAssinaturasPorAtoAdministrativo,idOrdemDaAssinatura,idAtoAdministrativo,idPerfilDoAssinante,idOrgaoDoAssinante,
	   idOrgaoSuperiorDoAssinante,OrdemDaProximaAssinatura
  FROM sac.dbo.vwPainelDeDocumentosDeReadequacaoAguardandoAssinatura
  WHERE     idPerfilDoAssinante = [PERFIL DO USUÁRIO LOGADO]
	    AND idOrgaoDoAssinante = [ÓRGÃO DO USUÁRIO LOGADO]
ORDER BY idTipoDoAtoAdministrativo,NomeProjeto '

**3 . Corrigir a funcionalidade do botão devolver.**
Ao devolver alterar o siEncaminhamento da tabela tbReadequação conforme abaixo:
 **6 - Solicitação devolvida ao MinC pela unidade de análise;
10 - Solicitação devolvida para o coordenador pelo técnico;
21 -	Solicitação devolvida ao coordenador pelo coordenador-geral;
22 -	Solicitação devolvida ao coordenador pelo diretor;
23 -	Solicitação devolvida ao coordenador pelo secretário.**

**Comment by Paulophmp** [comment]
@romulomb, eu e o @fernao terminamos e esta pronto pra teste em hmg.

**Comment by romulomb** [comment]
@Paulophmp Faltou a correção do botão Devolver.

**3 . Corrigir a funcionalidade do botão devolver.**
Ao devolver alterar o siEncaminhamento da tabela tbReadequação conforme abaixo:
6 - Solicitação devolvida ao MinC pela unidade de análise;
10 - Solicitação devolvida para o coordenador pelo técnico;
21 - Solicitação devolvida ao coordenador pelo coordenador-geral;
22 - Solicitação devolvida ao coordenador pelo diretor;
23 - Solicitação devolvida ao coordenador pelo secretário.

**Comment by fernao** [comment]
Olás,

Devemos fazer o tratamento indicado acima apenas para idAtoAdminisrtativo 655 ou fazer também para 653 e 654 ?

**Comment by romulomb** [comment]
Sim para todos os atos administrativo 653,654 e 655.

**Comment by fernao** [comment]
Foi encontrado um problema que gerou um impasse:

Todo o funcionamento da assinatura está baseada em dois itens: **idPronac** e **idTipoDoAtoAdminsitrativo**. Isso quer dizer que não pode haver sobreposição de atos em um mesmo ato. _Um ato administrativo diz respeito a uma ação apenas_.

Isso tem impacto severo no caso das readequações. Tomando um caso comum: um projeto possui 3 readequações (nome do projeto, resumo e plano de distribuição), no caso do exemplo, para uma vinculada (id ato 653). O proponente envia as 3. As solicitações de readequação são recebidas pelo MinC e distribuídas. Um/a parecerista realiza uma avaliação e, após finalizada, cria um documento e assina. No entanto, ao repetir o mesmo passo para uma segunda readequação, o primeiro documento é inativado, pois o sistema de assinaturas foi especificado para somente possuir um documento ativo para cada idPronac e idTipoDoAtoAdminstrativo.

Deste modo, a única forma de a assinatura funcionar é bloquear qualquer atividade de assinatura para readequação enquanto uma assinatura estiver tramitando (o fluxo de assinaturas para diferentes  readequações passa a ser sequencial, uma por vez).

A melhor alternativa vislumbrada é criar um ato adminsitrativo para cada tipo de readequação e incluir esta lista de atos nas telas de readequação. Isso permitiria o funcionamento correto e em paralelo de diferentes tipos de readequações.

Como analista, não recomendo que seja feita uma adaptação diretamente no módulo de assinatura, uma vez que isso vai contra um princípio fundamental definido para a assinatura, isto é, unicidade entre idPronac / idAtoAdministrativo por vez. Uma alteração desse porte implicaria praticamente num _fork_ da assinatura para que as readequações consigam cumprir esta função, sob risco de gerar bugs em todo o sistema de assinaturas uma vez que o **core** seria alterado.

**Comment by romulomb** [comment]
@fernao 

A melhor alternativa vislumbrada é criar um ato adminsitrativo para cada tipo de readequação e incluir esta lista de atos nas telas de readequação. Isso permitiria o funcionamento correto e em paralelo de diferentes tipos de readequações.

**CONCORDO  TOTALMENTE**

**Segue abaixo os novos atos criados**

Ato	        Descrição	
656	        Readequação - Planilha Orçamentária	
657		Readequação - Alteração de Razão Social	
658	       Readequação - Agência Bancária	
659		Readequação - Sinópse da Obra	
660		Readequação - Impacto Ambiental	
661		Readequação - Especificação Técnica	
662		Readequação - Estratégia de Execução	
663		Readequação - Local de Realização	
664		Readequação - Alteração de Proponente	
665		Readequação - Plano de Distribuição	
667		Readequação - Nome do Projeto	
668		Readequação - Período de Execução	
669		Readequação - Plano de Divulgação	
670		Readequação - Resumo do Projeto	
671		Readequação - Objetivos	
672		Readequação - Justificativa	
673		Readequação - Acessibilidade	
674		Readequação - Democratização de Acesso	
675		Readequação - Etapas de Trabalho	
676		Readequação - Ficha Técnica	
677		Readequação - Saldo de Aplicação	
678		"Readequação - Transferência de recursos entre projetos
Transferência de recursos entre projetos"

**Comment by fernao** [comment]
Dúvidas

* a partir da criação destas regras, as anteriores (653, 654, 655) ficam completamente invalidadas?
* os atos administrativos foram criados com idOrgaoSuperiorDoAssinate = -1, o que impede que eles sejam listados corretamente na página "gerir atos administrativos". Posso setar todos como 274 (SAI) ?

**Comment by romulomb** [comment]
@fernao 

Os ajustes nos atos administrativos já foram efetuados.

**Comment by fernao** [comment]
Itens que são repassados para análise por vinculadas:
* Planilha orçamentária - 656
* Plano de distribuição - 665
* Local de realização - 663

@romulomb : Para idTipoDoAto (663, 665 e 656): será necessário criar a trilha para cada vinculada?

@romulomb : será necessário criar

**Comment by fernao** [comment]
@romulomb :
Encontrei dois problemas nos atos criados:
- atos 656 a 670: dados da coluna idCargoDoAssinante trocada com idOrgaoDoAssinante; estou aplicando um patch (UPDATE) para trocar valores
- atos 671 a 678: dados das colunas idCargoDoAssinante e idOrgaoDoAssinante repetidos

**Comment by fernao** [comment]
[update-tbAtoAministrativo-atos-readequacao.sql.txt](https://github.com/culturagovbr/salic-minc/files/2429834/update-tbAtoAministrativo-atos-readequacao.sql.txt)

**Comment by fernao** [comment]
Outro problema: dados não condizentes com a realidade nas colunas idPerfilDoAssinante e idOrdemDaAssinatura. Dados de idPerfilDoAssinante estão presentes na coluna idOrdemDaAssinatura. Esta por sua vez (que deveria ter dados como "1,2,3" não possui fonte declarada, apenas podendo ser inferida por análise visual).

**Comment by fernao** [comment]
Atualização necessária (idTipoDoAto > 655)
-- idOrgaoDoAssinante com dado de idPerfilDoAssinante;
-- idPerfilDoAssinante com idOrdemDaAssinatuta
-- idOrdemDaAssinatura: manual

**Comment by fernao** [comment]
Segunda atualização necessária de ser rodada em produção:

[update2-tbAtoAministrativo-atos-readequacao.sql.txt](https://github.com/culturagovbr/salic-minc/files/2429953/update2-tbAtoAministrativo-atos-readequacao.sql.txt)

**Comment by fernao** [comment]
Correção funcionou: botão de assinar apareceu no projeto; falta corrigir para que ele apareça na listagem de assinaturas

**Comment by fernao** [comment]
@romulomb Identifiquei que as trilhas possuem dois órgãos também, diferente do anteriormente conversado sobre separar as trilhas com mais de um órgão. Ex: 656, órgãos 92 e 251.

**Comment by romulomb** [comment]
Dúvidas

* a partir da criação destas regras, as anteriores (653, 654, 655) ficam completamente invalidadas?

**SIM**

* os atos administrativos foram criados com idOrgaoSuperiorDoAssinate = -1, o que impede que eles sejam listados corretamente na página "gerir atos administrativos". Posso setar todos como 274 (SAI) ?

**Já foi corrigido, não existe mais nenhum ato com órgão superior a 1**

**Comment by fernao** [comment]
Alteração realizada: quando parecerista salva o parecer, altera o órgão do projeto para o atual. Isso corrige a listagem de projetos para o parecerista.

**Comment by fernao** [comment]
Estou trabalhando na devolução dos projetos e reparei que apenas 5 tipos de assinaturas possuem 4 passos:

656	Readequação - Planilha Orçamentária
657	Readequação - Alteração de Razão Social
664	Readequação - Alteração de Proponente
667	Readequação - Nome do Projeto
670	Readequação - Resumo do Projeto

Estes passos não são os mesmos dos tipos em que o projeto é encaminhado para vinculada:

656	Readequação - Planilha Orçamentária
665	Readequação - Plano de Distribuição
663	Readequação - Local de Realização

Gostaria de confirmar tais informações para correta implementação da issue
