### ISSUE TITLE
[Admissibilidade] Listar propostas: corrigir 'dias em análise'

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1342]
Perfil: coordenador de admissibilidade
Menu: admissibilidade / avaliação

Descontar dos dias em análise quando a proposta estiver em diligência com o proponente.

**Comment by fernao** [comment]
DiasEmAnalise = Hoje  -  [Diligências   dtResposta - dtEnvio] - DtEnvioProposta

Para cada diligência, somar os dias em que a proposta esteve em diligência (dtResposta - dtEnvio)

**Comment by Paulophmp** [comment]
branch: f/listar-propostas/ajustes

**Comment by Paulophmp** [comment]
@boletocosta, estamos com um dúvida na tela de "Admissibilidade de propostas", perfil "coordenador de admissibilidade":

Ao verificar o histórico de avaliações da proposta na página da proposta, verificamos que o campo Dt Admissão da listagem não coincide com a data de envio da proposta. Quando uma proposta é avaliada, a data da proposta é atualizada para a data corrente. Isto está correto ? Ou se trata de outro tipo de data?

**Comment by boletocosta** [comment]
Não entendi. 

No campo histórico de avaliações o sistema sempre traz as seguintes datas nessa ordem:

1. Data do envio inicial da proposta ao MinC pelo proponente
2. Data em que a proposta foi avaliada pelo MinC pela primeira vez
3. Data em que a proposta foi enviada ao MinC pela segunda vez após primeira análise

E assim sucessivamente se tiverem mais análises... 

Deu para entender?

**Comment by boletocosta** [comment]
Na verdade tanto faz a informação na coluna "dt admissão" .. O que importará para nós mesmo é a a coluna "dias em análise".  Mas na minha opinião o mais correto seria a coluna "dt admissão" trazer a data de envio inicial da proposta, ou seja, quando ela foi enviada pela primeira vez. Nesse sentido a data da coluna "dt admissão" seria sempre fixa.

**Comment by Paulophmp** [comment]
@boletocosta, terminamos e ja esta disponível pra teste.

**Comment by Paulophmp** [comment]
@boletocosta, terminamos e ja esta disponível pra teste .

**Comment by boletocosta** [comment]
Contagem está errada.  Exemplo: proposta 278908.  Coluna mostra 21 dias em análise, mas na verdade ficou apenas 05 dias em análise.

**Comment by Paulophmp** [comment]
@boletocosta, boa tarde, eu e o @fernao corrigimos algumas coisas, poderia refazer os testes para saber se o cálculo está correto agora.

**Comment by boletocosta** [comment]
Está quase.  A contagem ainda está errada quando uma proposta é arquivada. 

Exemplos:  

proposta 280613 - contagem negativa...

proposta  278920 - era para aparecer 13 dias em análise, mas aparece 154

**Comment by fernao** [comment]
Disponível para homologação

**Comment by boletocosta** [comment]
Quando clico em dias análise para ordenar a coluna por data aprece o erro:

DataTables warning: table id=tabelaAnaliseFinal - Invalid JSON response. For more information about this error, please see http://datatables.net/tn/

Olhando o console (f12 network) para verificar o erro de forma detalhada temos o seguinte: 

Exceção
Descrição: SQLSTATE[HY000]: General error: 1038 An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name. [1038] (severity 15) [(null)], query was: SELECT TOP 10 "vwPainelAvaliarPropostas".*, coalesce(distribuicao_avaliacao_proposta.avaliacao_atual, '0') AS "avaliacao_atual", coalesce(distribuicao_avaliacao_proposta.id_distribuicao_avaliacao_proposta, '0') AS "quantidade_distribuicoes", DATEDIFF(d, distribuicao_avaliacao_proposta.data_distribuicao, GETDATE()) AS "dias_corridos_distribuicao", "sugestao_enquadramento"."id_area", "sugestao_enquadramento"."id_segmento", "sugestao_enquadramento"."id_sugestao_enquadramento", CASE WHEN Segmento.tp_enquadramento = 1 THEN 'Artigo 26' WHEN Segmento.tp_enquadramento = 2 THEN 'Artigo 18' END AS "enquadramento", "Segmento"."Descricao" AS "descricao_segmento", "Area"."Descricao" AS "descricao_area", "PlanoDistribuicaoProduto"."Area" AS "id_area_inicial", "PlanoDistribuicaoProduto"."Segmento" AS "id_segmento_inicial", CASE WHEN SegmentoInicial.tp_enquadramento = 1 THEN 'Artigo 26' WHEN SegmentoInicial.tp_enquadramento = 2 THEN 'Artigo 18' END AS "enquadramento_inicial", "SegmentoInicial"."Descricao" AS "descricao_segmento_inicial", "AreaInicial"."Descricao" AS "descricao_area_inicial", CASE WHEN tbRecursoProposta.tpRecurso = 1 THEN '1 - Pedido de Reconsideração' WHEN tbRecursoProposta.tpRecurso = 2 THEN '2 - Recurso' ELSE '-' END AS "tipo_recurso", "tbRecursoProposta"."stRascunho" AS "prazo_recursal" FROM "sac"."dbo"."vwPainelAvaliarPropostas" LEFT JOIN "sac"."dbo"."distribuicao_avaliacao_proposta" ON distribuicao_avaliacao_proposta.id_preprojeto = vwPainelAvaliarPropostas.idProjeto and distribuicao_avaliacao_proposta.id_orgao_superior = 251 LEFT JOIN "sac"."dbo"."sugestao_enquadramento" ON sugestao_enquadramento.id_preprojeto = vwPainelAvaliarPropostas.idProjeto and sugestao_enquadramento.ultima_sugestao = 1 LEFT JOIN "sac"."dbo"."Segmento" ON Segmento.Codigo = sugestao_enquadramento.id_segmento LEFT JOIN "sac"."dbo"."Area" ON Area.Codigo = sugestao_enquadramento.id_area INNER JOIN "sac"."dbo"."PlanoDistribuicaoProduto" ON PlanoDistribuicaoProduto.idProjeto = vwPainelAvaliarPropostas.idProjeto and PlanoDistribuicaoProduto.stPrincipal = 1 INNER JOIN "sac"."dbo"."Segmento" AS "SegmentoInicial" ON SegmentoInicial.Codigo = PlanoDistribuicaoProduto.Segmento INNER JOIN "sac"."dbo"."Area" AS "AreaInicial" ON AreaInicial.Codigo = PlanoDistribuicaoProduto.Area LEFT JOIN "sac"."dbo"."tbRecursoProposta" ON tbRecursoProposta.idPreProjeto = vwPainelAvaliarPropostas.idProjeto and tbRecursoProposta.stAtivo = 0 WHERE (idSecretaria = 251) AND (( distribuicao_avaliacao_proposta.avaliacao_atual is null AND distribuicao_avaliacao_proposta.id_distribuicao_avaliacao_proposta is null OR distribuicao_avaliacao_proposta.avaliacao_atual = 1 AND distribuicao_avaliacao_proposta.id_distribuicao_avaliacao_proposta > 0 AND distribuicao_avaliacao_proposta.id_perfil IN (131,92,147) )) ORDER BY "" desc
Rastreamento do erro
#0 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Statement.php(303): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#2 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT TOP 10 "...', Array)
#3 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Db/Adapter/Abstract.php(737): Zend_Db_Adapter_Pdo_Abstract->query(Object(MinC_Db_Table_Select), Array)
#4 /var/www/salic/application/modules/admissibilidade/models/DbTable/VwPainelAvaliarPropostas.php(241): Zend_Db_Adapter_Abstract->fetchAll(Object(MinC_Db_Table_Select))
#5 /var/www/salic/application/modules/admissibilidade/controllers/AdmissibilidadeController.php(2956): Admissibilidade_Model_DbTable_VwPainelAvaliarPropostas->obterPropostasParaAvaliacao(Array, Array, '0', '10', Array, Object(Admissibilidade_Model_DistribuicaoAvaliacaoProposta))
#6 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Controller/Action.php(516): Admissibilidade_AdmissibilidadeController->listarPropostasAjaxAction()
#7 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('listarPropostas...')
#8 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#9 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Application/Bootstrap/Bootstrap.php(105): Zend_Controller_Front->dispatch()
#10 /var/www/salic/vendor/zendframework/zendframework1/library/Zend/Application.php(384): Zend_Application_Bootstrap_Bootstrap->run()
#11 /var/www/salic/index.php(37): Zend_Application->run()
#12 {main}
Parâmetros requisitados
array (
  'module' => 'admissibilidade',
  'controller' => 'admissibilidade',
  'action' => 'listar-propostas-ajax',
  'draw' => '5',
  'columns' => 
  array (
    0 => 
    array (
      'data' => '',
      'name' => 'idProjeto',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    1 => 
    array (
      'data' => 'NomeProposta',
      'name' => 'NomeProposta',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    2 => 
    array (
      'data' => 'DtMovimentacao',
      'name' => 'DtMovimentacao',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    3 => 
    array (
      'data' => 'diasCorridos',
      'name' => '',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    4 => 
    array (
      'data' => '',
      'name' => '',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    5 => 
    array (
      'data' => 'Tecnico',
      'name' => 'Tecnico',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    6 => 
    array (
      'data' => '',
      'name' => '',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    7 => 
    array (
      'data' => '',
      'name' => '',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    8 => 
    array (
      'data' => '',
      'name' => 'tipo_recurso',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
    9 => 
    array (
      'data' => '',
      'name' => '',
      'searchable' => 'true',
      'orderable' => 'true',
      'search' => 
      array (
        'value' => '',
        'regex' => 'false',
      ),
    ),
  ),
  'order' => 
  array (
    0 => 
    array (
      'column' => '3',
      'dir' => 'desc',
    ),
  ),
  'start' => '0',
  'length' => '10',
  'search' => 
  array (
    'value' => '',
    'regex' => 'false',
  ),
  'filtro' => 'undefined',
)

**Comment by boletocosta** [comment]
homologado
