### ISSUE TITLE
[Solicitações] Permitir encaminhar para outras unidades

### ISSUE THREAD

**Issue by FernandaLA** [culturagovbr/salic-minc#1343]
Permitir encaminhar solicitações para qualquer unidade do MinC e ser distribuídas para os técnicos dessas unidades;
 - pegar exemplo de consulta de unidades e técnicos na url: http://local.salic/readequacao/readequacoes/avaliar-readequacao?id=501eac548e7d4fa987034573abc6e179MTQ0OTc=ZUA3NWVmUiEzNDUwb3RT&filtro=aguardando_distribuicao; Perfil: Coordenador de Acompanhamento SEFIC/SACAV

 - Qualquer perfil da unidade que o projeto está pode encaminhar.

**Comment by FernandaLA** [comment]
Aguardando homologação.

**Comment by boletocosta** [comment]
Homologado
