### ISSUE TITLE
[READEQUAÇÃO] - READEQUAÇÃO DE ATÉ 50%

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1347]
**Ajustes**

1 . Não permitir que o proponente altere no remanejamento de 50%  os valores da etapa de **Custos Vinculados** e da etapa de **Captação de Recursos**, nessas etapas a aplicação não deverá liberar o link no item orçamentário.

2 . Para projetos mais antigos em que a planilha orçamentária contém a etapa Custos Administrativos e a etapa Divulgação:
a . permitir que o proponente possa alterar as rubricas dentro da mesma etapa;
b. permitir que o proponente retire valores ate 50% dessas etapas para enviar para somente para as etapas de Pré-Produção / Preparação, Produção / Execução e Pós-Produção.

**Comment by fernao** [comment]
Custos Vinculados -> idPlanilhaEtapa = 8
Captação de recursos -> idPlanilhaEtapa = 10

**Comment by fernao** [comment]
"1 . Não permitir que o proponente altere no remanejamento de 50% os valores da etapa de Custos Vinculados e da etapa de Captação de Recursos, nessas etapas a aplicação não deverá liberar o link no item orçamentário."

Feito, em hmg

**Comment by fernao** [comment]
Disponível para homologação.
