### ISSUE TITLE
[READEAQUAÇÃO] - ALTERAÇÃO DE PLANILHA ORÇAMENTÁRIA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1349]
**Melhoria**

Permitir ao proponente na funcionalidade de planilha orçamentária nos casos de remanejamento acima de 50%, complementação e redução: 

1 . Alterar a fonte de recurso do projeto e;
2 . Para os projetos que contém a etapa de custos vinculados, recalcular os valores dos custos vinculados e Captação de recursos com base nos índices registrados tabela tbCustosVinculados e;
3. Incluir a validação utilizando a modal de preços.

**Comment by fernao** [comment]
2 . Para os projetos que contém a etapa de custos vinculados, recalcular os valores dos custos vinculados e Captação de recursos com base nos índices registrados tabela tbCustosVinculados e;
1. Incluir a validação utilizando a modal de preços.

Não entendi, seria possível detalhar melhor o ajuste?

**Comment by romulomb** [comment]
**2 . Para os projetos que contém a etapa de custos vinculados, recalcular os valores dos custos vinculados e Captação de recursos com base nos índices registrados tabela tbCustosVinculados e;**

Os projetos que contém as etapas **Custos Vinculados** e **Captação de Recursos** deverão ter os seus itens orçamentários recalculados pelos os índices da tabela tbCustoVinculados.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/fc3c9f0a-c2af-429b-9846-718105a42bef)

![CustosVinculados.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a03ca29a-44e7-4dab-ae6c-3376bf46ec65)

@clebersantos  poderia ajudar por gentileza o @fernao a entender esses cálculos já que você implementou na fase de propostas com também a utilização da modal de preços?

**Comment by fernao** [comment]
Implementado, movido para homologação

**Comment by fernao** [comment]
Roteiro para teste:

- alterar fonte de recurso: utilizar qualquer projeto com readequação de planilha orçamentária disponível e verificar se consegue alterar a fonte do recurso (ao editar item)

- cálculo de custos vinculados: utilizar um projeto que tenha itens de custos vinculados (a partir de junho/2017); realizar redução ou complementação e verificar se cálculo dos custos vinculados está correto
