### ISSUE TITLE
[Solicitações] Incluir nova coluna na listagem

### ISSUE THREAD

**Issue by FernandaLA** [culturagovbr/salic-minc#1350]
Identifiquei que será necessário apresentar a data de encaminhamento da solicitação na lista de solicitações para os usuários internos.

Identifiquei também que a data de encaminhamento inicial será a data de envio da solicitação para o MinC.

**Comment by FernandaLA** [comment]
Aguardando homologação

**Comment by boletocosta** [comment]
Oi pessoal. 

De acordo com o que foi solicitado está homologado.

Contudo, na minha opinião apenas acrescentar uma coluna com a data do último encaminhamento não é suficiente. Além disso teria que ser criado um novo botão ao lado do botão encaminhar denominado "Histórico de encaminhamentos".  Ao clicar nesse botão seria apresentado uma listagem de todos os encaminhamentos realizados para aquela solicitação, contendo as seguintes informações: nome de quem enviou, nome de quem recebeu e data do encaminhamento. 

Poderia ser adicionada essa tarefa nessa issue ou é necessário criar uma nova?

**Comment by clebersantos** [comment]
@boletocosta, conversamos com o @romulomb durante o desenvolvimento sobre essa funcionalidade de manter o histórico e o mesmo informou que não seria necessário registrar os encaminhamentos, desse modo, essas informações não são gravadas pelo sistema.
