### ISSUE TITLE
[Admissibilidade] [HOTFIX] Erro ao enviar proposta 

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1351]
Vários proponentes relatam o erro abaixo ao tentar enviar uma proposta ... 

Poderiam verificar, por gentileza?

![Capturar.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/7bb969db-c731-472e-9dc5-bb2c47584721)

**Comment by clebersantos** [comment]
Não foi possível reproduzir o erro até o momento. O método para enviar a proposta ao MinC faz  atualização do CNAE do proponente e o serviço da receita teve algumas instabilidades na semana passada(17 a 21/09), no momento o serviço está estabilizado e não apresenta erros.

Subi para homologação um tratamento de erro quando o serviço da receita está indisponível.
