### ISSUE TITLE
[Admissibilidade] [FIX] Erro ao analisar propostas específicas 

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1353]
Ambiente: produção
Perfil: coordenador de admissibilidade
Link: http://salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas

Ao clicar no botão analisar (olhinho) para o sistema retorna o seguinte erro:

![Capturar.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/67751842-e576-4c3d-9a66-c32f51c00ec9)

Não são todas as propostas que apresentam o erro. Exemplos das que apresentam o erro:  285073, 281069 e 285862.

**Comment by clebersantos** [comment]
Ao comparar o tipo de enquadramento, o sistema buscava o segmento do proponente e da sugestão de enquadramento, o erro acontecia pq alguns segmentos estavam inativos no banco de dados e a query que buscava trazia apenas segmentos ativos. Alterei a query que faz a busca do segmento, ignorando se é ativo ou não.

Disponível para homologação.

**Comment by boletocosta** [comment]
homologado
