### ISSUE TITLE
[Solicitações] Colocar Visualização da proposta no novo modelo em Avaliação

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1360]
Migrar os componentes de Visualização da proposta para o novo padrão na parte de Avaliação ( Coordenador de Admissibilidade -> Admissibilidade -> Avaliação ).
![image.png](https://images.zenhubusercontent.com/5a576a214b5806bc2bc25a64/f36445d1-fd95-4b96-81b4-b260abc3453b)

**Comment by guiamado** [comment]
Disponível no ambiente de homologação, favor testar.

**Comment by boletocosta** [comment]
Não entendi a relevância dessa modificação. Qual é o propósito? Foi o @romulomb que solicitou?

**Comment by clebersantos** [comment]
@boletocosta, a proposta completa é renderizada em várias telas e em cada tela era um código específico e muitas vezes duplicado. Toda vez que alterava alguma informação tinha que alterar em vários lugares. Isso dificutava a manutenção do código.

Estamos migrando aos poucos todas as telas de proposta para o modelo atual, com isso estamos reutilizando bastante código. Por exemplo, essa visualização de proposta é a mesma que é renderizada ao consultar dados do projeto, em análise de readequação e ao verificar o versionamento da proposta. 

Talvez não tenha relevância visualmente, mas para o sistema é um ganho enorme.

**Comment by RuanHerculano** [comment]
Detalhe foi solucionado, poderia verificar?

**Comment by boletocosta** [comment]
homologado pode subir
