### ISSUE TITLE
[Solicitações] Propostas arquivadas ou projetos arquivados definitivamente

### ISSUE THREAD

**Issue by FernandaLA** [culturagovbr/salic-minc#1380]
- Não permitir o envio de solicitações de proposta arquivada ou projeto arquivado definitivamente

(Verificar regra que define se a proposta é arquivada definitivamente, na tela proposta/manterpropostaincentivofiscal/listar-propostas-arquivadas)

**Comment by FernandaLA** [comment]
@romulomb na tabela de situação no banco tem 11 situações de arquivamento, qual dessas é utilizada para definir o projeto como arquivado definitivamente?

**Comment by boletocosta** [comment]
Na minha opinião as situações que correspondem aos projetos arquivados de forma definitiva são as seguintes:

A13, A42, E16, E36, E63, E64, E65, G16, G17, K00 e K01.

**Comment by FernandaLA** [comment]
Aguardando homologação.

**Comment by boletocosta** [comment]
homologado
