### ISSUE TITLE
[FIX] Erro ao consultar regularidade do proponente

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1381]
Eu como usuário interno do sistema Salic, perfil Protocolo SEFIC/DEMEF/CGFNC, ao consultar a regularidade do proponente o sistema apresenta um erro, conforme imagem abaixo. 

![photo_2018-09-17_18-23-20.jpg](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/7b14a544-800b-4c9d-b4f0-4d9626dbbe51)

Reportado via telegram pelo  Francisco(Tido).

**Comment by RuanHerculano** [comment]
Erro corrigido, disponível em homologação.
