### ISSUE TITLE
[Admissibilidade] [Perfil proponente] Alterar visualização da proposta em 03 situações

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1400]
@clebersantos , conforme conversamos segue a issue sobre alteração da visualização da proposta:

Após enviar a proposta ao MinC, consultar uma proposta arquivada ou em análise final, o proponente visualiza a proposta da mesma forma como se esta estivesse com ele disponível para edição.  Segue a visualização atual:

![Capturar.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/ac348e00-2cb9-421f-b727-d022e2204e90)

Dessa forma, quando a proposta estiver em uma das 03 situações a seguir, a solicitação é para alterar a visualização da proposta no perfil proponente para o modelo utilizado na avaliação de uma proposta (ver print) 

Situações para alterar a visualização no perfil proponente: 
a) Proposta enviada (situação no sistema "Enviada ao MinC para avaliação")
b) Proposta com análise finalizada (situação no sistema "Proposta em análise final")
c) Proposta arquivada (situação no sistema "Proposta arquivada")

Print da visualização que seria mais adequada:
![Capturar2.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/1884ee47-5a9d-42af-bcdd-10b1809961c2)

Detalhe importante:  a única função que teria que ser adicionada a esta  visualização é o campo "Minhas Solicitações", que precisa redirecionar para a ferramenta modificada de acordo com as novas regras implementadas no card #1380 (já homologado, mas ainda não subiu para produção).

**Comment by clebersantos** [comment]
Identifiquei dois problemas ao bloquear o formulário da proposta nas situações informadas. Conforme segue abaixo:
 - [ ] Recurso enquadramento: quando o projeto é enquadrado o sistema permite inserir recurso, ver possibilidade de integrar tela ao novo modelo.
- [ ] Adequação à realidade: verificar possível impacto ao adequar o projeto à realidade, pois o sistema reutiliza as mesmas telas na adequação.

**Comment by clebersantos** [comment]
Primeira versão disponível em homologação, ainda faltam alguns ajustes.

**Comment by clebersantos** [comment]
Novas funcionalidades solicitadas pelo @boletocosta:
 - [ ] adicionar fluxo alternativo no diagrama para o proponente
 - [ ] sinalizar no menu lateral quando tiver diligencia para o proponente
 - [ ] adicionar feature discovery no botão flutuante de visualizar proposta proponente

**Comment by boletocosta** [comment]
Não sei se seria uma issue só para isso, mas tinha mais uma.. lembra? hehe

 - [ ] Ocultar/Retirar menu lateral da ferramenta "Minhas Solicitações"

**Comment by clebersantos** [comment]
Verdade, não lembrava. Disponibilizei mais uma versão agora.

**Comment by clebersantos** [comment]
Finalizado. Disponível para homologação.

**Comment by boletocosta** [comment]
Oi @clebersantos!

1. Botão flutuante com o texto para acessar as minhas solicitações não apareceu aqui. Seria melhor alterar a regra para aparecer sempre, conforme havia solicitado. Pode confiar que os proponentes vão gostar. rsrs

2. Botão de solicitar o desarquivamento não está aparacendo na listagem da proposta arquivada.

De resto tudo certo!

**Comment by boletocosta** [comment]
1. Aumenta para 5 então. Nos 5 primeiros acessos a mensagem vai aparecer. Ok?

2. Tudo bem.  Vou homologar, mas não podemos subir para produção essa issue sem resolver a questão do botão de solicitar desarquivamento. Blz? 

Valeu!

**Comment by clebersantos** [comment]
Alterações realizadas.

**Comment by boletocosta** [comment]
homologado
