### ISSUE TITLE
[HOMOLOGAR PROJETOS] Duplicação de projetos

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#1412]
No perfil de Coordenador de Análise quando acesso o menu de Análise - Homologar Projetos, os projetos estão aparecendo duplicados como se tivessem participado de 2 reuniões da CNIC diferentes (281 e 282).

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/731f997f-0e55-44bc-b3e9-be5b8ee55456)

**Comment by clebersantos** [comment]
Os projetos estão em duas pautas de reunião, ficando duplicado na listagem. Aguardando resposta do Rômulo para verificar se remove de uma pauta ou ajusta a query que traz os projetos para homologação.

**Comment by romulomb** [comment]
Me manda a query para verificar o que está ocorrendo.

**Comment by clebersantos** [comment]
```
SELECT TOP 10 a.AnoProjeto+a.Sequencial as Pronac, "a"."IdPRONAC", "a"."ResumoProjeto", "a"."NomeProjeto", "a"."DtInicioExecucao", "a"."DtFimExecucao", "a"."Orgao" AS "idUnidade", sac.dbo.fnTotalAprovadoProjeto(a.AnoProjeto,a.Sequencial) as vlHomologado, CASE WHEN b.Enquadramento = '1' THEN 'Artigo 26' WHEN b.Enquadramento = '2' THEN 'Artigo 18' ELSE 'Não enquadrado' END AS Enquadramento , "b"."DtEnquadramento", "d"."NrReuniao", "e"."idSecretaria" AS "idOrgaoSuperior", f.Descricao as Area, g.Descricao as Segmento, "h"."stAnaliseProjeto", "i"."usu_nome" AS "Tecnico", DATEDIFF(day, h.dtrecebido, GETDATE()) AS tempoAnalise FROM "sac"."dbo"."Projetos" AS "a" INNER JOIN "sac"."dbo"."enquadramento" AS "b" ON a.IdPRONAC = b.IdPRONAC LEFT JOIN "BDCORPORATIVO"."scSAC"."tbPauta" AS "c" ON a.IdPRONAC = c.IdPRONAC LEFT JOIN "sac"."dbo"."tbReuniao" AS "d" ON c.idNrReuniao = d.idNrReuniao INNER JOIN "sac"."dbo"."Orgaos" AS "e" ON a.OrgaoOrigem = e.Codigo INNER JOIN "sac"."dbo"."Area" AS "f" ON f.Codigo = a.Area INNER JOIN "sac"."dbo"."Segmento" AS "g" ON g.Codigo = a.Segmento INNER JOIN "sac"."dbo"."tbVerificaProjeto" AS "h" ON h.IdPRONAC = a.IdPRONAC INNER JOIN "TABELAS"."dbo"."Usuarios" AS "i" ON h.idUsuario = i.usu_codigo INNER JOIN "sac"."dbo"."tbProjetoFase" AS "j" ON a.IdPRONAC = J.idPronac WHERE (j.idNormativo > 6) AND (j.stEstado = 1) AND (sac.dbo.fnDtPortariaAprovacao(a.AnoProjeto,a.Sequencial) IS NOT NULL) AND (a.Situacao = 'D50') AND (NOT EXISTS(SELECT TOP 1 * FROM SAC.dbo.tbDiligencia WHERE idPronac = a.IdPRONAC AND idTipoDiligencia = 181 AND DtSolicitacao IS NOT NULL AND DtResposta IS NULL AND stEstado = 0 AND stEnviado = 'S')) AND (a.Orgao = '262') ORDER BY "IdPRONAC" asc
```

**Comment by romulomb** [comment]
Segue a nova query
SQL
'SELECT a.AnoProjeto+a.Sequencial as Pronac, a.IdPRONAC, a.ResumoProjeto, a.NomeProjeto, a.DtInicioExecucao, a.DtFimExecucao, a.Orgao AS idUnidade, 
              sac.dbo.fnTotalAprovadoProjeto(a.AnoProjeto,a.Sequencial) as vlHomologado, 
			  CASE WHEN b.Enquadramento = '1' THEN 'Artigo 26' WHEN b.Enquadramento = '2' THEN 'Artigo 18' ELSE 'Não enquadrado' END AS Enquadramento , b.DtEnquadramento,
			  d.NrReuniao, e.idSecretaria AS idOrgaoSuperior, f.Descricao as Area, g.Descricao as Segmento, h.stAnaliseProjeto, i.usu_nome AS Tecnico, 
			  DATEDIFF(day, h.dtrecebido, GETDATE()) AS tempoAnalise 
FROM sac.dbo.Projetos                 AS a 
INNER JOIN sac.dbo.enquadramento      AS b ON a.IdPRONAC      = b.IdPRONAC 
INNER JOIN sac.dbo.Parecer            AS k ON a.IdPRONAC      = k.IdPRONAC AND K.TipoParecer = 1 AND K.stAtivo = 1 AND K.idTipoAgente = 6  
INNER JOIN sac.dbo.Orgaos             AS e ON a.OrgaoOrigem   = e.Codigo 
INNER JOIN sac.dbo.Area               AS f ON f.Codigo        = a.Area 
INNER JOIN sac.dbo.Segmento           AS g ON g.Codigo        = a.Segmento 
INNER JOIN sac.dbo.tbVerificaProjeto  AS h ON h.IdPRONAC      = a.IdPRONAC 
INNER JOIN TABELAS.dbo.Usuarios       AS i ON h.idUsuario     = i.usu_codigo 
INNER JOIN sac.dbo.tbProjetoFase      AS j ON a.IdPRONAC      = J.idPronac
INNER JOIN sac.dbo.tbReuniao          AS d ON K.NumeroReuniao = d.NrReuniao 
WHERE j.idNormativo > 6 AND j.stEstado = 1 AND sac.dbo.fnDtPortariaAprovacao(a.AnoProjeto,a.Sequencial) IS NOT NULL AND a.Situacao = 'D50' 
      AND NOT EXISTS(SELECT TOP 1 * FROM SAC.dbo.tbDiligencia 
	                               WHERE idPronac = a.IdPRONAC AND idTipoDiligencia = 181 AND DtSolicitacao IS NOT NULL AND DtResposta IS NULL AND stEstado = 0 AND stEnviado = 'S')
	 AND a.Orgao = '262'  AND K.TipoParecer = 1 AND K.stAtivo = 1 AND K.idTipoAgente = 6  
	 ORDER BY a.NomeProjeto asc  '
