### ISSUE TITLE
Data de emissão do comprovante é indicada como inválida mesmo estando dentro do período correto,

### ISSUE THREAD

**Issue by RuanHerculano** [culturagovbr/salic-minc#1443]

**Comment by RuanHerculano** [comment]
Após a correção do bug, falei com o Charles pelo Telegram para homologar as correções feitas, que foram relatadas por ele mesmo. Até então não obtive retorno dele. Mediante isso, estou movendo esta demanda para impedimentos.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Subir para produção com urgência por gentileza**

**Obrigado**
