### ISSUE TITLE
Validar para que comprovante não seja cadastrado sem o fornecedor

### ISSUE THREAD

**Issue by RuanHerculano** [culturagovbr/salic-minc#1444]

**Comment by RuanHerculano** [comment]
Após a correção do bug, falei com o Charles pelo Telegram para homologar as correções feitas, que foram relatadas por ele mesmo. Até então não obtive retorno dele. Mediante isso, estou movendo esta demanda para impedimentos.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Subir para produção com urgência por gentileza**

**Obrigado**
