### ISSUE TITLE
[ADEQUAÇÃO A REALIDADE] Projeto não altera para B11 quando tem mais que 10% captado.

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1447]
Eu, como Coordenador de Análise, ao avaliar a adequação à realidade de um projeto com mais de 10% captado o sistema não altera a situação para B11, informa apenas que o projeto aguardará o percentual mínimo captado. Conforme imagem abaixo:

 ![image.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/b8d01109-c766-4c39-9499-4b77e3f7952d)

No entanto, ele possui mais de 10% de captação do valor autorizado a captar, não faz sentido

![image.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/4ed31202-83df-40b7-8720-8e498972e241)

**Comment by clebersantos** [comment]
O sistema estava buscando o valor total do projeto, ignorando a fonte do recurso, para calcular o percentual captado, foi ajustado para usar os mesmos parâmetros dos valores apresentados em consultar dados do projeto.

**Comment by clebersantos** [comment]
O sistema estava buscando o valor total do projeto, ignorando a fonte do recurso, para calcular o percentual captado. Foi ajustado para usar os mesmos parâmetros dos valores apresentados em consultar dados do projeto.

Disponível em homologação.

**Comment by AdmissibilidadeSAV** [comment]
Homologado.
