### ISSUE TITLE
[Clonar Projeto] Botão de clonar não aparece corretamente

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#145]
Atualmente para mostrar o botão de clonar projeto na página de Listar Projetos, o sistema utiliza o metódo verificarPermissaoProposta(), há um erro na verificação quando a proposta já foi transformada em projeto. Verificar a query que busca a proposta do projeto e refatorar.

**Comment by romulomb** [comment]
Só para confirmar:

O botão é liberado para proponente pessoa física e para dirigente no caso do pessoa jurídica. - CORRETO.

No caso do procurador da pessoa juridíca o botão está aparecendo mas o mesmo não tem acesso a proposta. VAMOS AVALIAR.

De qualquer forma vamos subir no pacote de amanhã.
