### ISSUE TITLE
[HOTFIX] [Admissibilidade] Botão sem ação e visualização de documentos

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#1452]
No perfil de Coordenador de Admissibilidade não estou conseguindo encaminhar a proposta para o componente da CNIC sugerir o enquadramento e quando abro os documentos anexados não aparecem.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/8ab17d16-bd0e-42b0-a78c-06d29b255ab9)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/1dbd40da-26ce-4e35-b9c4-9e31bac06ed5)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV Pode testar em homologação?

**Comment by boletocosta** [comment]
Por mim homologado. Acabei de testar e funcionou tudo.
