### ISSUE TITLE
[DADOS PROJETO] Migrar Outras Informações para Modelo Novo

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1456]
Migrar a tela de Dados Projeto, os submenus contidos na Parte Outras Informações para o novo modelo de Vue.

Certidões Negativas:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Local de Realização e Deslocamento:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Documentos Anexados:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Documentos Assinados:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Dados Complementares:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Plano de Distribuição:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Providência Tomada:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Historico Encaminhamento:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Diligências do Projeto:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Diligências do Projeto:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

**Comment by Paulophmp** [comment]
Verificar na parte de Diligência do Projeto se realmente há necessidade de utilizar: (que estão estáticos na view)
- TIPO DE DILIGÊNCIA
- PRORROGADO

**Comment by clebersantos** [comment]
Após a migração, criar anotação para marcar as actions antigas como deprecated.

Exemplo:
``` 
/**
  * @deprecated migrado para controller rest em 16/10/2018
  */
```

**Comment by guiamado** [comment]
Modelo Novo de Outras informações em Dados do projeto já está disponível em Homologação.
@romulomb

**Comment by romulomb** [comment]
**FICOU EXCELENTE**

**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO POR GENTILEZA**
