### ISSUE TITLE
Criar a opção "Modo Noturno"

### ISSUE THREAD

**Issue by nitaibezerra** [culturagovbr/salic-minc#1489]
O Modo Noturno é uma funcionalidade que está na moda por proporcionar maior conforto para os usuários ao reduzir a luminosidade das telas. Esta funcionalidade será útil principalmente para os técnicos que utilizam o Salic por muito tempo.

**Comment by clebersantos** [comment]
Criamos a funcionalidade para o novo layout que será implementado gradualmente após a aprovação do cliente. Abaixo seguem imagens do modelo construído.

### Modo normal:
![Screenshot from 2018-10-23 19-44-23.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/f886c395-ba5e-4551-a6f1-1a09144629d5)

### Modo noturno:
![Screenshot from 2018-10-23 19-43-59.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/3505c238-da22-403e-85d7-bdcad77fd2f2)
