### ISSUE TITLE
[Adequação à realidade de execução] Aumentar o n° de caracteres

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#1578]
No perfil de Coordenador de Análise no menu Análise - Avaliar adequação de projeto - Avaliar, quando clico no + , opção avaliar projeto não estou conseguindo encaminhar uma diligência (devolver ao proponente), visto que o limite de caracteres foi excedido, sendo assim, necessito que seja ampliado de 1000 para 8000.

http://salic.cultura.gov.br/analise/analise/visualizarprojeto?idpronac=217588#/

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/23976069-d127-40da-b170-5d850ba46eb0)

**Comment by clebersantos** [comment]
disponível em produção.
