### ISSUE TITLE
[CUMPRIMENTO DO OBJETO] Correções de bugs

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1618]
Perfil: SEFIC/ARQ - Técnico de Avaliação 
Menu: Acompanhamento -> Analisar Comprovação do Objeto
Erros reportados:
 - [x] Ao acessar a lista de projetos para análise e clicar na opção 'Avaliar', na tela de análise ao clicar em qualquer opção do menu lateral o sistema carrega a tela com os dados vazios.
 - [x] Quando finaliza a análise o sistema não registra as informações corretamente, o projeto sai da listagem mas não altera para a situação correta.
 - [x] Se clicar na aba "Etapas de trabalho" e depois na aba "Parecer técnico": a tela cai e aparece a mensagem de erro "Relatório não encontrado" - volta para a tela "Lista de Relatórios - Técnico"
 - [x] Ao tentar salvar as informações já escritas do Parecer técnico, aparece um alerta informando que para salvar é necessário escrever a conclusão. O botão "salvar" deve ser diferente do botão "finalizar".
 - [x] Não há o perfil de Coordenador - Geral para avaliar o resultado da análise técnica
 - [x] Não há previsto o "caminho" para os trâmites após a análise técnica ter como resultado o descumprimento do objeto. Nesse caso  o projeto não deve ir para análise financeira e sim para o Coordenadora-Geral para finalização e emissão do Laudo Final de reprovação do projeto. Ver com  o @wouerner se o Laudo já está com a situação E92.
 - [x] Após a finalização da análise técnica e emissão do Parecer técnico, este fica disponível no Salic para visualização do proponente. Retirar pois ainda não há decisão final e a visualização dá causas para recursos intempestivos e retrabalhos. Mostrar somente após a emissão do Laudo Final que é a situação E93
  - [x] Só pode finalizar se não tiver em diligência E62
  - [x] Corrigir charset providência tomada na situacao E92 e nas outras páginas
  - [x] Mover o menu para avaliação de resultados
  - [x] Ver a possibilidade de incluir tabela no editor rico
  - [x] Adicionar opção de visualizar o parecer no filtro "em analise"

**Comment by marianafontenele** [comment]
Olá @clebersantos analisemos as novas ações e temos algumas melhorias/ erros:

1. correção do problema de navegação do menu lateral: funcionando corretamente.

2. Correções ao salvar o parecer: foi diferenciado o botão "SALVAR" do "FINALIZAR E ASSINAR", contudo após salvar perde-se a formatação do documento. Print em anexo.

3. template no documento da assinatura: esse foi feito só para a parte do técnico (primeiro avaliador) né?

Nesta parte acontece diferentes problemas em projetos aleatórios:

 - Para alguns projetos na tela do Parecer (com o QR code) consta sem os dados de assinatura e para outros esta mesma tela aparece com a assinatura do técnico e do coordenador, sendo que neste momento o coordenador ainda não teve ciência do parecer produzido. (prints em anexo)

- Registro ainda que na tela em que aparece as assinaturas errôneas do técnico e Coordenador, o nome do Carlos aparece assinando duas vezes, sendo que a pessoa indicada para assinatura como coordenador foi a Mariana L. 

- Não sei se esse é o momento para fazer esta observação, contudo faz-se necessário ajustar o texto do campo de assinaturas do parecer - retirar a informação "conforme horário de brasília", além de ajustar data e hora da assinatura. 

- Não sei se esse é o momento para fazer esta observação, mas na parte das assinaturas do parecer, para o técnico é mostrado cargo no campo da função do colaborador, contudo, há dois tipos de técnico (Agente Administrativo ou Técnico em Nível Superior) e caso essa informação seja de fato necessária (não sei se já definido para este parecer e se há possibilidade de alteração de formato) precisaria diferencia o tipo de cargo para cada técnico (alguns possuem cargo de "agente administrativo" e outros tem cargo de "Técnico de Nível Superior")  .

Além disso, observei que foi alterado o layout e a barra de rolagem, ficou muito bom o novo design. Não sei se também seria agora ou só depois em fase de melhoria, mas acreditamos ser imprescindível ter uma caixa de texto (tipo um capo de justificativa), quando houver necessidade de retorno do projeto para a instância anterior.

Qualquer dúvida estamos à disposição. 

[https://app.zenhub.com/files/104502087/868444ee-0d23-4570-b236-82ec39f4485d/download](https://app.zenhub.com/files/104502087/868444ee-0d23-4570-b236-82ec39f4485d/download)

**Comment by clebersantos** [comment]
Olá @marianafontenele, sobre os problemas apontados. 
Pontuei os subitens para melhor entendimento.
 - Item 1 - Ok
 - Item 2 - Problema da formatação foi corrigido.
 - Item 3 - É um template de documento único para todas as avaliações. 
   * Subitem 3.1 - No documento o nome só aparece após a assinatura, esse projeto que você visualizou eu assinei utilizando o perfil do Carlos como Técnico de Prestação de Contas e como Coordenador de Prestação de Contas. 
   * Subitem 3.2 - A assinatura não é direcionada para uma pessoa específica e sim para um perfil. Qualquer usuário que tiver o perfil exigido pode assinar o documento. Removi da tela do parecer técnico a opção de selecionar os Avaliadores, tendo em vista que não faz sentido na assinatura.
   * Subitem 3.3 - Vou verificar o texto e a hora pois fazem parte do módulo global da assinatura
   * Subitem 3.4 - @romulomb na tabela tbAtoAdministrativo foi cadastrado o assinante como "Agente Administrativo", sugiro utilizar um termo mais genérico, que atenda "Agente Administrativo e Técnico em Nível Superior".
 - Item 4 - A justificativa seria ao devolver o projeto para o técnico?


Subi hoje mais uma atualização. Agora a opção de assinar aparece na listagem para o Coordenador de Prestação de Contas/Coordenador de Avaliação.

**Comment by marianafontenele** [comment]
Oi @clebersantos ,


Item 3 - É um template de documento único para todas as avaliações - OK

Subitem 3.1 - No documento o nome só aparece após a assinatura, esse projeto que você visualizou eu assinei utilizando o perfil do Carlos como Técnico de Prestação de Contas e como Coordenador de Prestação de Contas: acredito que não... porque esse fui eu e o Carlos que fizemos como teste e mesmo ele colocando meu nome como coordenadora apareceu o nome dele. 

Subitem 3.2 - A assinatura não é direcionada para uma pessoa específica e sim para um perfil. Qualquer usuário que tiver o perfil exigido pode assinar o documento. Removi da tela do parecer técnico a opção de selecionar os Avaliadores, tendo em vista que não faz sentido na assinatura: com certeza é bem melhor assim! Não tem sentido realmente ter esta relação de avaliadores.

Subitem 3.3 - Vou verificar o texto e a hora pois fazem parte do módulo global da assinatura : OK

Item 4 - A justificativa seria ao devolver o projeto para o técnico? Isso. Mas gostaríamos de abrir um campo de justificativa para devolução em qualquer instância. é porque é importante explicar o motivo da devolução. 

Vou verificar a nova atualização ainda hoje.

**Comment by marianafontenele** [comment]
[Uploading... Ajustes salic 08.11.18.pdf ]Oi Cleber,

Quanto a nova atualização: opção de assinar aparece na listagem para o Coordenador de Prestação de Contas/Coordenador de Avaliação.

Teste: pronac 133816 - caixa de técnico de avaliação - Perfil da Mariana Lacerda

1. Quando analiso um projeto ao assinar como técnica aparece três assinaturas: de técnico, coordenador e Coordenador-Geral, sendo que eu ainda não encaminhei para a próxima instância. Além disso, não aparece meu nome como assinante, aparece o do Carlos e o do Rômulo (print em anexo).  

2. mesmo eu apertando o botão "FINALIZAR E ASSINAR" para o projeto ele não sai da caixa de análise do técnico. O certo seria ele ir para a caixa do Coordenador para assinatura. 

Teste: pronac 147436 - caixa de técnico de avaliação - Perfil da Mariana Lacerda

Para este projeto quando eu aperto o botão "FINALIZAR E ASSINAR" aparece a tela do parecer assinado, contudo já não aparece nenhum nome assinando. (print em anexo)


Por conta destes erros não consegui avaliar a assinatura no nível de Coordenador. 

[Uploading... Ajustes salic 08.11.18.pdf ]

**Comment by marianafontenele** [comment]
[https://app.zenhub.com/files/104502087/4e775b86-79da-4a6d-ba93-4c4ea8ddf62d/download](https://app.zenhub.com/files/104502087/4e775b86-79da-4a6d-ba93-4c4ea8ddf62d/download)

**Comment by clebersantos** [comment]
Olá @marianafontenele, podemos passar o fluxo da avaliação de cumprimento do objeto amanhã? 

Hoje corrigi algumas inconsistências e finalizei as alterações da assinatura. Já é possível executar todo o processo de assinar. Falta apenas a opção de devolver para o técnico com o campo de justificativa. 

Escolhe um horário bom pra vocês e me avisa. Pode ser? Obrigado.

**Comment by marianafontenele** [comment]
@clebersantos Ótimo! Pode ser às 10hs?

**Comment by clebersantos** [comment]
@marianafontenele Vamos marcar 10h30 entao. Prefere presencial ou pode ser via hangout?

**Comment by marianafontenele** [comment]
@clebersantos Pode ser 10:30. Pra nós tanto faz se for presencial ou não.
