### ISSUE TITLE
[CUMPRIMENTO DO OBJETO] Assinatura

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1619]
- [x] @romulomb definir onde inicia o fluxo de assinatura
- [x] @romulomb definir quais os perfis envolvidos
- [x] @romulomb definir o ato administrativo
- [x] migrar o código do módulo default para o modelo específico, o módulo será `comprovacao-objeto`
- [x] Criar a opção de devolver no bloco de assinatura ou criar uma listagem para o Coordenador-geral devolver

**Comment by clebersantos** [comment]
O idAtoAdministrativo dessa assinatura será 621 - Parecer de Avaliação do Objeto

**Comment by clebersantos** [comment]
O fluxo da assinatura será inicializado quando o técnico de análise(futuro técnico de prestação de contas) finalizar o parecer de cumprimento de objeto.

Após a última assinatura, o sistema deverá alterar a situação do projeto de acordo com as seguintes regras:

 - [ ] `E68` para cumprimento do objeto aprovado e aprovado com ressalva (providência tomada:  Projeto encaminhado para avaliação financeira.)
 - [ ] `E92` para cumprimento do objeto reprovado na análise técnica (providência tomada: Projeto encaminhado para revisão da avaliação de  resultados.)

Olá @marianafontenele pode confirmar essas informações?

**Comment by clebersantos** [comment]
Prezado(a)s @marianafontenele  e @carlosassen disponibilizei no ambiente de homologação o primeiro nível da assinatura(técnico) e diversas correções do módulo de comprovação do objeto.  
Vocês já podem homologar os seguintes itens:
 - correção do problema de navegação do menu lateral
 - correções ao salvar o parecer
 - template do documento da assinatura

Amanhã continuo trabalhando nos outros itens das issues. Boa noite!

**Comment by marianafontenele** [comment]
@clebersantos Ok! Vamos olhar hj.

**Comment by clebersantos** [comment]
Olá @marianafontenele. Foi disponibilizado no ambiente de homologação mais um pacote de atualização do módulo de cumprimento do objeto. Agora é possível devolver um documento na assinatura.

**Comment by carlosassen** [comment]
Boa tarde, @clebersantos ! Nos testes iniciais realizados, não foram encontradas falhas na devolução de projetos, parece que está tudo OK! (se verificarmos algo num momento posterior, nós te comunicamos)
Em relação à inserção de tabelas no parecer de avaliação do objeto, quando no preenchimento do campo “recomendações”, depois que se insere alguma tabela no referido campo, todo o texto inserido após a tabela acaba desaparecendo da tela. Outro ponto percebido foi que, no momento de imprimir o parecer de avaliação, as linhas de tabelas inseridas também acabam desaparecendo, contudo, a formatação da tabela permanece a mesma (só as linhas da tabela que somem na hora da impressão do documento).  

Obrigado!

**Comment by clebersantos** [comment]
@carlosassen Olá Carlos! Obrigado por fazer os testes necessários. Vou verificar o problema das tabelas.
