### ISSUE TITLE
COMPROVAÇÃO FINANCEIRA [HOTFIX]

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1621]
Proponente relatam que lançam a comprovação financeira, a aplicação emite a mensagem de salvo com sucesso e não sobe a informação para a base de dados.  

Recebemos até agora 13 solicitação relatando essa inconsistência.

Ainda houve um caso em que a aplicação subiu uma comprovação com valor negativo.

[https://app.zenhub.com/files/104502087/abb7ee73-6914-431a-845f-76296e65ab41/download](https://app.zenhub.com/files/104502087/abb7ee73-6914-431a-845f-76296e65ab41/download)

**Comment by wouerner** [comment]
Em Analise.

**Comment by wouerner** [comment]
Teria como informar qual navegador foi usado para fazer os testes?

**Comment by romulomb** [comment]
**Essa issue é um hotfix. Está a 15 dias  no backlog e ainda não foi resolvida.**

Tenho 12 solicitação do proponente com o mesmo caso.

Utilizando os navegadores Chrome e Firefox.

**Comment by wouerner** [comment]
O mesmo está em homologação a 16 dias, só não fiz a referencia aqui, mas tem a comunicação no telegram.
