### ISSUE TITLE
Erros na Homologação

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#1674]
@wouerner , além dessa parte de não mostrar a planilha, verifiquei em testes anteriores que:

 - [x] Só é possível salvar a avaliação do comprovante como "Aprovado se tiver algum caractere no campo "Parecer da Avaliação";

 - [x] Ao salvar a a avaliação do comprovante está aparecendo a mensagem "Houve algum problema ao salvar", mesmo não tendo nenhum erro;

- [x]  Quando o projeto está em E-30 (Análise de Resposta de Diligência) e é redistribuído pelo coordenador, ele tem a situação alterada para E-27.

- [x]  A justificativa da devolução do projeto inserida pelo coordenador não pode ser visualizada pelo técnico. 

- [x]  Modelo do parecer não está aparecendo conforme o modelo enviado pela Janete;

- [x] Os campos "Valores Comprovados" constantes na tela do parecer técnico não estão formatados como moeda.

**Comment by volthier** [comment]
Issue já implementada.
