### ISSUE TITLE
[Admissibilidade] Custos Vinculados

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#1676]
No perfil de proponente quando ele tenta salvar 0% nos custos vinculados, seja nos Custos de Administração, Custos de Divulgação ou Remuneração para captação de recursos, o sistema acaba salvando automaticamente o percentual padrão.

http://hmg.salic.cultura.gov.br/proposta/manterorcamento/custosvinculados?idPreProjeto=280829

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/9e539470-b9d4-4db7-a1de-9bd6c62ec5ac)

**Comment by clebersantos** [comment]
Correção disponível em produção. Verificar se está ok. Obrigado

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos Está OK. Muito obrigada!
