### ISSUE TITLE
[HOTFIX] Dados Projeto - Corrigir valor autorizado

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1680]
O valor autorizado a captar na consulta de dados do projeto apresenta erro conforme imagem abaixo.

![2018-11-12 10.01.11.jpg](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/aca740fc-4131-4724-8ed0-94307fd0674e)

Erro reportado pelo @romulomb

**Comment by clebersantos** [comment]
@romulomb disponível em produção. Verificar se está ok.

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos Está ok! Muito obrigada!
