### ISSUE TITLE
Readequação - Assinatura em massa

### ISSUE THREAD

**Issue by AssisTydo** [culturagovbr/salic-minc#1682]
@Fernão, no bloco de assinaturas nos perfis do Coordenador, Coordenador-Geral e Diretor,  aparece a opção para assinatura em massa, mas quando marcada essa opção, o sistema registra a seguinte mensagem "usuário sem autorização para assinar o documento".

**Comment by fernao** [comment]
Duplicada com https://github.com/culturagovbr/salic-minc/issues/1681
