### ISSUE TITLE
[CORE] Teste automatizados (PHPUnit)

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#170]
Adicionar e padronizar o teste dentro do sistema.
Existe algumas estudos prévios sobre isso.

**Comment by wouerner** [comment]
Criei e atualizei alguns testes para servirem de exemplo.
Vamos iniciar a fazer cobertura do código com testes com phpunit

**Comment by vinnyfs89** [comment]
Fiquei interessado pelos testes utilizados no Salic-Minc. Estava observando, os arquivos vinculados a essa Issue. O commit vinculado a ela seria [esse](https://github.com/culturagovbr/salic-minc/commit/bfdbd15e6d6d982fcc92c8dcaff3ad14443200b5) ?

Caso positivo, também gostaria de aplicar testes no SalicBR. Você poderia detalhar qual o passo-a-passo utilizado para executar os testes e quais quesitos básicos você sugere para os testes atendam?

**Comment by vinnyfs89** [comment]
Criei uma issue para que possamos discutir melhor a respeito dos testes. Se puder deixar seu comentário ensinando como você fez, vai ajudar bastante. :+1: 

https://github.com/culturagovbr/salic-minc/issues/198
