### ISSUE TITLE
Readequação de planilha orçamentária: ajustes

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1701]
* soma incorreta no valor total quando inicia readequação (verificar se possui outras planilhas)

**Comment by fernao** [comment]
No caso em questão, foi feito outra readequação.

**Comment by fernao** [comment]
Realizados ajustes relacionados, na finalização da readequação - readequações dos tipos "planilha orçamentária, saldo de aplicação e plano de distribuição" não geravam registros de Aprovação corretos, não sendo trocados os dados após publicação de portaria. Essa correção foi publicada na release https://github.com/culturagovbr/salic-minc/releases/tag/v6.2.2.

Continuo investigando o erro.

**Comment by fernao** [comment]
O problema estava na formação do total, nos casos em que numa readequação de planilha anterior um item havia sido excluído. Corrigido e jogado para hmg

**Comment by romulomb** [comment]
@fernao Fernão,

A complementação ou redução é a diferença entre planilha.

A aplicação estão colocando o valor total da nova planilha.

**Comment by fernao** [comment]
![photo_2018-11-23_10-33-46](https://user-images.githubusercontent.com/4325697/48943759-61d7a000-ef0b-11e8-9bd1-56242ec50abf.jpg)

**Comment by fernao** [comment]
Subi correção, disponível em homologação

**Comment by fernao** [comment]
![Uploading photo_2018-11-23_10-33-46.jpg…]()
