### ISSUE TITLE
Readequação / assinaturas: ajustes variados no fluxo das vinculadas

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1703]
* coord parecer vinculada: remover siEncaminhamento ao clicar no finalizar, para que este possa assinar corretamente - OK
* diretor SEFIC: não encaminha mais para o Secretário - remover da regra do readequacao/service/assinatura/Assinar.php OK
* coord acompanhamento - analisados: adicionar link para visualizar documento quando possuir documento disponível - OK
* coord acomp. - adicionar descritor do cargo conforme siEncaminhamento para parecerista, técnico e coordenador - OK
* ao visualizar documento assinatura, não retorna para local correto - OK

**Comment by fernao** [comment]
Implementado, disponível em hmg

**Comment by fernao** [comment]
branch: feature/readequacao-assinaturas-ajustes

**Comment by fernao** [comment]
Adicionado: "ao visualizar documento assinatura, não retorna para local correto " - OK

Disponível em hmg

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Comment by romulomb** [comment]
**SUBIR PARA PRODUÇÃO POR GENTILEZA**
