### ISSUE TITLE
Readequação: parecerista não consegue assinar após idas e vindas com coordenador de parecer

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1704]
Mapear condições de reprodução do bug.

**Comment by fernao** [comment]
Favor dar mais detalhes.

Não seria similar ao #1719, em que faltam os atos administrativos para as vinculadas ?

**Comment by fernao** [comment]
Movido para coluna "impedimentos"

**Comment by fernao** [comment]
Relacionado com #1719, em tratamento por meio da criação de novos atos para as vinculadas.
Movido para homologação

**Comment by fernao** [comment]
Parecerista não consegue assinar readequações caso exista uma outra pendende de assinatura com outra pessoa.

Ex: tenho duas readequações, tipo 2 e tipo 10. A tipo 2 está para assinatura do diretor; enquanto isso, a tipo 10 tem documento gerado mas botão "assinar" não é exibido, somente sendo liberado após finalização do fluxo da readequação do tipo 2.

**Comment by fernao** [comment]
Ocorre somente no banco HMG.
Botão não liberava porque não existem todas as trilhas nesse ambiente. Ok no ambiente de produção

**Comment by fernao** [comment]
Não consegui realizar atualização por script, será necessário atualizar o ambiente HMG a partir de PROD por outras vias.

Tabela a ser atualizada:
sac.dbo.tbAtoAdministrativo

**Comment by romulomb** [comment]
**Estamos refatorando o módulo de parecerista e efetuaremos a correção na nova codificação**
