### ISSUE TITLE
[Readequação] Problema com solicitação devolvida

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1717]
O proponente fez uma spilicitação, foi devolvido para o proponente, o proponente alterou a readequação e reenviou para o MinC. Nesse caso, é preciso alterar a tabela tbreadequação os atributos dos campos statendimento para "N", estava "E" e stestado para "0", estava "1".

 Qdo devolvido para o proponente, se a readequação for enviada novamente para o MinC, o sistema precisa alterar na tabela tbreadequação os atributos statendiemento e stestado.

**Comment by fernao** [comment]
Disponível para homologação

**Comment by romulomb** [comment]
@fernao 

Quando o **técnico devolver** o pedido de readequação para o proponente os atributos da tabela tbReadequacao deverão ser:

stAtendimento = E
siEncaminhamento = 12
stEstado = 0

Quando o **proponente enviar novamente** o pedido de readequação para o proponente os atributos da tabela tbReadequacao deverão ser:

stAtendimento = N
siEncaminhamento = 1
stEstado = 0

**Comment by fernao** [comment]
Quando ele envia novamente, trata-se de outra readequação, correto?

**Comment by fernao** [comment]
branch: hotfix/readequacao-devolvida

**Comment by fernao** [comment]
Disponível para homologação

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Parabéns**

**Subir para produção imediatamente, por gentileza**
