### ISSUE TITLE
[Aprovação] Erro ao publicar portaria de projeto homologado 

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1718]
**O pedido de uma nova funcionalidade está relacionado a um problema? Se sim descreva-o**
Ao atualizar a publicação de uma portaria de projeto homologado, que teve redução ou complementação, o sistema informa uma mensagem de sucesso, no entanto, os dados não são alterados e o projeto não muda de situação.

**Qual a proposta de solução?**
O projeto que teve redução ou complementação deve ter a situação alterada para `E12` se tiver captação e `E10` caso não tenha.

**Especificação da funcionalidade**
Perfil: Técnico de portaria
Menu: Análise->Atualização de portaria
Inserir número da portaria (exemplo: 0702/18) e filtrar pela situação `Redução`.

**Comment by clebersantos** [comment]
Ao analisar o erro reportado, verifiquei que a funcionalidade era específica para projetos readequados, foi alterado as tratativas de atualização da portaria para aceitar os projetos homologados com alteração no valor da planilha orçamentária.

Disponível em homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Obrigado**

**Subir para produção por gentileza**.
