### ISSUE TITLE
[DADOS PROJETO] Migrar Execução para modelo Novo

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1727]
Mudar a parte de Execução para o modelo novo, seguindo padrão de Rest e Service e colocando vuetify.
![image.png](https://images.zenhubusercontent.com/5a576a214b5806bc2bc25a64/b5ce7706-847b-45c7-829d-28a37c82ac99)

**Comment by guiamado** [comment]
Parte de Execução foi migrada para o Modelo novo, e está disponível no ambiente de homologação.
@romulomb

**Comment by guiamado** [comment]
Somente o Submenu de dados bancários que por enquanto nao foi modificado.

**Comment by romulomb** [comment]
@guiamado 

Não está trazendo as marcas anexadas.

![Marcas.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2dfe0676-1c48-434e-ac01-47da2694cab7)

**Comment by Paulophmp** [comment]
@romulomb, boa tarde ja está em HMG poderia fazer o teste novamente.
