### ISSUE TITLE
[HOTFIX] Verificar rotina automática da situação B11

### ISSUE THREAD

**Issue by wisleyalbuquerque** [culturagovbr/salic-minc#175]
Estou tendo um problema com dois projetos no SALIC. Geralmente quando o projeto que tem Plano de Execução Imediata de Projeto aprovado em editais ou Plano Anual após a autorização para captação de recursos e consequentemente a abertura das contas no dia seguinte a situação é alterada automaticamente para B11 – Encaminhado para análise técnica, no entanto, estou com dois projetos urgentes que precisam de análise técnica para ser avaliado na CNIC amanhã, que esse trâmite não ocorreu. Os números dos PRONACs: 177560 e 177757.

**Comment by clebersantos** [comment]
Após conversa com o @romulomb, a procedure  `spEncaminharProjetoParaAnaliseTecnica`  que automaticamente alterava a situação dos projetos para análise foi desativada. Atualmente todos os projetos deveram passar pela adequação à realidade, funcionalidade desenvolvida que permite ao proponente atualizar dados do projeto antes de ir para análise do parecerista.
