### ISSUE TITLE
Avaliação Resultados

### ISSUE THREAD

**Issue by volthier** [culturagovbr/salic-minc#1752]
- [x] - Correção do botão devolver no painel de laudo final
- [x] - Documento parecer Técnico remoção do "Ã".(Template PHP)
- [x] - Editor texto rico parecer Laudo Final.
- [x] - Link direto da listagem de parecer Técnico para o documento de Assinatura(igual o do Laudo Final )
- [x] - Acesso dos menus ao Coordenador-Geral de Prestação de Contas (Menu Antigo)
- [x] - Verificar acesso aos menus novos e antigos (Parecer Técnico, Laudo Final).

###
- Editar menu de Avaliação Resultados:
- [x] Analise Prestação de Contas(novo) >> Parecer Técnico
- [x] Analise Parecer >> Remover ( Menu Antigo)
- [x] Analisar Laudo Final >> Remover ( Menu Antigo)
- [x] Analisar Laudo Final(novo) >> Laudo Final
- [x] Verificar nos Perfis que acessam as funcionalidades de Parecer e Laudo.

**Comment by luizfpinheiro** [comment]
Para a tarefa "Editor texto rico parecer Laudo Final" sugiro o reuso do componente EditorTexto, encontrado em **modules/avaliacaoResultados/components/ParecerTecnico/components/**
