### ISSUE TITLE
[CORE] Migrar para PHP 7.x 

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#176]
Podemos verificar e refatorar o sistema para aderir ao PHP 7.x que traz diversas melhorias na linguagem de programação.

Tarefa a ser implementadas antes:
* Criar container com PHP 7  #185

**Comment by decko** [comment]
Existe algum guia de migração, como alguns problemas comuns e suas soluções?
O Zend1 funciona sem maiores problemas com o PHP7?
Se possível, já partir para o PHP 7.2.

**Comment by vinnyfs89** [comment]
@decko  fiz uma análise no meu primeiro dia de trabalho na UFABC e disponibilizei em um repositório no meu github, assim que der da uma olhada : https://github.com/vinnyfs89/dockerPHP5.3a7

Se você acessar esse [item](https://github.com/vinnyfs89/dockerPHP5.3a7#frameworks--compatibilidade) vai observar que o ZendFramework desde a versão 1.12.12 já tem compatibilidade com o PHP 7.x.

No caso nossa principal atividade seria de mapear o código-fonte da aplicação todas as incompatibilidades com a migração da versão atual que foi migrada da 5.3 para 5.6 para que migremos para a versão 7.x.

Ferramentas como o PHPCompability, que é um recurso que pode ser aplicado no PHPCS (PHP Code Sniffer) nos fornece todos os requisitos para que possamos extrair um relatório de todos os trechos de código de toda a aplicação que contenham incompatibilidade entre versões que precisam ser ajustados para que essa migração seja possível.

Caso queiram conhecer um pouco mais sobre o PHPCompability : https://github.com/wimg/PHPCompatibility

Algumas IDEs já possuem essa integração como o PHPStorm, por exemplo. A última migração de versão do PHP 5.3 para 5.6 que precisava ser feita no Salic para que fosse possível trabalhar com a versão 5.6 do PHP foi feita utilizando o PHPCompability com e recursos do PHPStorm.

Acredito que mapeando a lista com todas as incompatibilidades podemos dividir em atividades e mobilizar uma força-tarefa para realizar essa atividade.

**Comment by wouerner** [comment]
Fiz as preparações para migrar, e agora vamos testar em homologação o sistema.

**Comment by vinnyfs89** [comment]
Pessoal, acabei de atualizar o projeto e fazer uma varredura mapeando todas as inconsistências usando como referência a versão 7.1 e o resultado foi o abaixo:

![php7 1_inspection_2017-12-27_19-19-57](https://user-images.githubusercontent.com/3949238/34393833-8442cc10-eb3c-11e7-943f-f80eaab72842.png)

**Comment by wouerner** [comment]
Como posso fazer a mesma verificação?

**Comment by vinnyfs89** [comment]
O Code Inspect foi realizado através de uma verificação que foi configurada em conjunto com o CodeSniffer dentro da IDE PHPStorm. A configuração foi feita dentro da ferramenta para que valide de acordo com a versão desejada do PHP. Neste caso escolhi a versão 7.1. 
Alguns desses macro não são impactantes nesse momento, como "Code Smell", "Code Style" e "Unused".

Sugiro que criemos um plano de ação para dividir todos os itens listados com os membros do time para atacarmos com mais eficácia.

Eu particularmente, gostaria de participar dessa atividade.

:+1:

**Comment by decko** [comment]
Então, queria entender nesse relatório, o que foi apontado de incompatibilidades entre o PHP 5.6 e o 7.x

A principio, acho q seria interessante já focar essa migração para o PHP 7.2, que apresenta fortes avanços em desempenho segundo alguns benchmarks:
https://www.phoronix.com/scan.php?page=news_item&px=PHP-7.2-Final-Benchmark

**Comment by clebersantos** [comment]
@vinnyfs89 parece que essa issue foi concluída né? O sistema já está compatível com a versão 7.

**Comment by wouerner** [comment]
Concordo e Fechada.

**Comment by vinnyfs89** [comment]
@clebersantos Yes
