### ISSUE TITLE
[ADMISSIBILIDADE] Reanalisar enquadramento - botão quebrado 

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#1773]
Perfil: Coordenador de Admissibilidade

Link: http://salic.cultura.gov.br/admissibilidade/enquadramento/gerenciar-enquadramento

Ao clicar no botão "Visualizar devolução" (lupa amarela) nada acontece.

![erro.PNG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/af18c2e5-3dea-4944-9b6f-9636a67d5aa4)

**Comment by clebersantos** [comment]
disponível em produção.
