### ISSUE TITLE
[Assinatura] Gerenciar assinaturas: paginação e busca com problemas

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1780]
* busca não funciona quando pronac está na segunda página
* paginação não funciona corretamente
* avaliar se vale trazer toda a lista e filtrar pelo datatables

**Comment by clebersantos** [comment]
Em avaliação verifiquei que a query utilizada atualmente já traz todos os projetos e o datatables que filtra as informações. A montagem da página e busca eram processadas via ajax, o que não é necessário, ja que todos os projetos estavam na busca. Como propostas estou desativando a requsição ajax.

**Comment by clebersantos** [comment]
Ajuste em gerenciar assinatura está disponível em homologação.

@Wanderson_ASPAR, essa correção resolve também o problema do filtro para a assinatura do módulo de fiscalização.
