### ISSUE TITLE
Visualização - Relatório de Cumprimento do Objeto

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1795]
Inserir nas telas iniciais dos perfis SEFIC/ARQ - Técnico de Prestação de Contas, SEFIC/ARQ - Coordenador de Prestação de Contas e SEFIC/ARQ - Coordenador-Geral de Prestação de Contas botão que permita visualizar o parecer técnico do cumprimento do objeto. 

Exemplo:

![image](https://user-images.githubusercontent.com/37881003/49652633-befa4800-fa19-11e8-9865-cc18e33ff24f.png)

Informações a serem mostradas ao clicar no botão
![image](https://user-images.githubusercontent.com/37881003/49652678-e2bd8e00-fa19-11e8-9be0-2e7b21648b83.png)

![image](https://user-images.githubusercontent.com/37881003/49653429-113c6880-fa1c-11e8-907b-d570da495093.png)

A imagem acima foi retirada do perfil SEFIC/DIC - Diretor do Departamento ao se clicar no botão indicado abaixo:

![image](https://user-images.githubusercontent.com/37881003/49653543-6e381e80-fa1c-11e8-990c-b73df61c0b26.png)

**Comment by volthier** [comment]
Implementado em Homologação para validação!

**Comment by DouglasMinC** [comment]
Verificado! @volthier, é possível também colocar na aba "Assinar" dos perfis SEFIC/ARQ - Coordenador de Prestação de Contas e SEFIC/ARQ - Coordenador-Geral de Prestação de Contas?
