### ISSUE TITLE
Visualização - Diligência

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1796]
Alterar o modelo de visualização de diligência atual no perfil SEFIC/ARQ - Técnico de Prestação de Contas que não permite acessar os arquivos anexados na resposta:

![image](https://user-images.githubusercontent.com/37881003/49659999-a5163080-fa2c-11e8-9c6b-e19227329be6.png)

![image](https://user-images.githubusercontent.com/37881003/49659931-75672880-fa2c-11e8-8392-eb9496b3b39c.png)

Para o modelo de visualização de diligência da "Diligências do projeto" que permite o acesso aos arquvos anexados na resposta:

![image](https://user-images.githubusercontent.com/37881003/49660289-574df800-fa2d-11e8-91ad-f902614f71c1.png)

![image](https://user-images.githubusercontent.com/37881003/49660317-6af95e80-fa2d-11e8-9037-04a8336785c5.png)

**Comment by volthier** [comment]
Foi demonstrada solução para o Douglas e o mesmo ficou de rever essa issue com vocês.

**Comment by volthier** [comment]
Como requisitado o layout novo foi implementado em homologação para validação!

**Comment by DouglasMinC** [comment]
Implementação do novo layout verificada!

**Comment by DouglasMinC** [comment]
@volthier
É normal que esteja aparecendo "Invalid Date"? Quando for para a Produção não aparecerá?

![image](https://user-images.githubusercontent.com/37881003/50236067-9884c700-03a0-11e9-82e3-1f391acc98b3.png)
