### ISSUE TITLE
Incluir Editor de Texto Rico - Diligência

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1797]
Perfil SEFIC/ARQ - Técnico de Prestação de Contas

Incluir Editor de Texto Rico para a digitação das diligências da prestação de contas.

Obs.: No modelo atual, está havendo erro na codificação dos caracteres:
         O @romulomb solicitou que a localização dos botões "Salvar" e "Cancelar" fosse alterada para o fim da página, padrão utilizado em outras partes do sistemas, segundo ele. Também solicitou que a tonalidade da cor verde fosse a mesma utilizada no resto do sistema.

![image](https://user-images.githubusercontent.com/37881003/49660745-8022bd00-fa2e-11e8-99f6-14ffc228609a.png)

**Comment by ramonsales** [comment]
Implementado no ambiente de homologação para validação.

**Comment by DouglasMinC** [comment]
Editor de texto rico implementado, entretanto o texto permanece sendo salvo com erro de codificação de caracteres. 

![image](https://user-images.githubusercontent.com/37881003/49952691-9bd10c00-fee3-11e8-99c3-6f52e29ac284.png)

**Comment by DouglasMinC** [comment]
Erro de codificação de caractere corrigido ao salvar o texto.

**Comment by DouglasMinC** [comment]
@volthier ,
Erro na Produção. O campo para incluir o texto não está aparecendo. 

![image](https://user-images.githubusercontent.com/37881003/50354142-bc2b4700-0531-11e9-8330-a7549f122d8e.png)
