### ISSUE TITLE
Erro - Salvar Parecer Técnico

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1800]
A opção de salvar não está funcionando corretamente:
a) Em alguns momentos, não salva as modificações;
b) Há casos em que salvamentos anteriores ao último salvamento retornam;

![image](https://user-images.githubusercontent.com/37881003/49661620-a8abb680-fa30-11e8-8850-d8229c63b91e.png)

![image](https://user-images.githubusercontent.com/37881003/49661645-be20e080-fa30-11e8-93e8-33ab0dd65be8.png)

![image](https://user-images.githubusercontent.com/37881003/49661669-d690fb00-fa30-11e8-94b8-3a9d8ae4cca9.png)

Observação quanto à última imagem:

O @romulomb solicitou que a localização dos botões "Salvar" e "Finalizar" fosse alterada para o fim da página, padrão utilizado em outras partes do sistemas, segundo ele. Também solicitou que a tonalidade da cor verde fosse a mesma utilizada no resto do sistema.

**Comment by FernandaLA** [comment]
Disponível em Homologação!

**Comment by DouglasMinC** [comment]
A opção "Salvar" está funcionando corretamente. O layout foi alterado conforme solicitado pelo @romulomb .

**Comment by DouglasMinC** [comment]
A opção "Salvar" está funcionando corretamente. O layout foi alterado, conforme solicitado pelo @romulomb .

**Comment by FernandaLA** [comment]
Acrescentada novas mudanças de layout também ao laudo final. Por gentileza, homologar.

**Comment by DouglasMinC** [comment]
Novo layout verificado na tela do laudo final também.
