### ISSUE TITLE
[Readequação] Custos vinculados: não permitir aumentar remuneração acima do que foi aprovado

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1801]
Adicionar regra para impedir que o custo vinculado suba para além do valor originalmente aprovado (como trata-se de uma regra de entrada, o proponente não pode alterar o valor ao longo do projeto).

**Comment by fernao** [comment]
Implementado, disponível para homologação

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO POR GENTILEZA**

**OBRIGADO**
