### ISSUE TITLE
Incluir Parecer da Avaliação  - Opção Visualizar Comprovante

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1802]
A opção "Visualizar Comprovante" presente nos perfis SEFIC/ARQ - Coordenador de Prestação de Contas e SEFIC/ARQ - Coordenador-Geral de Prestação de Contas possibilita a visualização dos status do comprovante (Não Avaliado, Aprovado e Reprovado) e o arquivo do comprovante, mas não permite visualizar o Parecer da Avaliação.

![image](https://user-images.githubusercontent.com/37881003/49663161-edd1e780-fa34-11e8-85b6-8eb078e65259.png)

![image](https://user-images.githubusercontent.com/37881003/49663192-03471180-fa35-11e8-81e0-be521b72722a.png)

![image](https://user-images.githubusercontent.com/37881003/49663233-2671c100-fa35-11e8-8028-019d7d6f251d.png)

O campo Parecer da Avaliação é preenchido pelo técnico de prestação de contas durante a avaliação dos comprovantes:

Perfil: SEFIC/ARQ - Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/49663363-88cac180-fa35-11e8-9784-2b41dbbb6f03.png)

**Comment by volthier** [comment]
Texto do parecer implementado em Homologação como requisitado na issue!

@romulomb @DouglasMinC  @Janete

**Comment by DouglasMinC** [comment]
Visualização do texto do parecer da avaliação não disponível. No caso de comprovantes que possuem o campo "Justificativa do proponente" preenchido, é o texto desse campo que aparece:

![image](https://user-images.githubusercontent.com/37881003/49954451-a42b4600-fee7-11e8-9729-4f0be1d71cd7.png)

**Comment by FernandaLA** [comment]
Correção do campo feita, favor homologar.

@DouglasMinC

**Comment by DouglasMinC** [comment]
Correção feita. É possível visualizar o campo parecer da avaliação nos perfis  SEFIC/ARQ - Coordenador de Prestação de Contas e SEFIC/ARQ - Coordenador-Geral de Prestação de Contas, conforme solicitado.

**Comment by FernandaLA** [comment]
@DouglasMinC  foi colocado os dois campos. Agora pode visualizar o Parecer da Avaliação e a Justificativa do Proponente no comprovante, quando houver. 

Está disponível no ambiente de homologação.

**Comment by FernandaLA** [comment]
Tem como sim, vou inverter.

**Comment by FernandaLA** [comment]
Feito

**Comment by DouglasMinC** [comment]
Issue totalmente atendida!
