### ISSUE TITLE
Opção de Assinar na Tela Inicial - Perfis Diretor e Secretário

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1803]
Incluir a opção de assinar o laudo na tela inicial dos perfis SEFIC/DIC - Diretor e SEFIC - Secretario (a).

Modelo Atual SEFIC/DIC - Diretor e SEFIC - Secretario (a)

![image](https://user-images.githubusercontent.com/37881003/49663676-874dc900-fa36-11e8-8d6a-896f4f007a1a.png)

Modelo esperado SEFIC/DIC - Diretor e SEFIC - Secretario (a)

![image](https://user-images.githubusercontent.com/37881003/49663846-135ff080-fa37-11e8-99b5-8c6089422be7.png)

**Comment by volthier** [comment]
Campo de Assinatura para os PERFIS de Secretário e Diretor foram finalizados.

Disponibilizado em Homologação para testes.

**Comment by DouglasMinC** [comment]
@volthier ,

O Laudo Final não está sendo direcionado para a aba "Assinar" nos perfis de Coordenador-geral, Diretor e Secretário. A assinatura do Laudo Final só está sendo possível pelo menu "Assinaturas". Assim, não foi possível verificar a entrega da solicitação feita na issue.

**Comment by volthier** [comment]
Correção implementada em HMG.

Validar assinatura no modulo.

**Comment by DouglasMinC** [comment]
@volthier ,

No perfil de Diretor, a aba "Assinar" adicionada está refletindo o que já está na aba "Em assinatura" (exceto pelos botões de ação diferentes). Além disso, a aba "Em assinatura" no perfil de secretário está sendo uma cópia da mesma aba do perfil de diretor.

**Comment by volthier** [comment]
Foi implementada correção da aba de visualização do estado "Em Assinatura" no modulo de Laudo Final.

Disponibilizado em Homologação para validação da correção.

**Comment by DouglasMinC** [comment]
Após a inclusão da opção "Assinar", a opção "Devolver" não está funcionando nos perfis SEFIC/ARQ - Coordenador-Geral de Prestação de Contas, SEFIC/DIC- Diretor de Departamento e SEFIC - Secretário (a)

**Comment by volthier** [comment]
A correção esta implementada em Homologação.

De acordo com conversado com o Wouerner, o fluxo de Laudo Final e Parecer técnico quando devolvidos ficou assim:

Quando Laudo final esta em assinatura devolve-se para laudo em analise.
Quando Laudo final esta em analise e devolve-se o Documento Parecer Técnico e invalidado e volta para analise do técnico.

Quando o documento Parecer Técnico esta em assinatura o mesmo volta para analise do técnico quando devolvido.

Esse fluxo foi discutido e firmado juntamente com o @romulomb em reunião.

**Comment by DouglasMinC** [comment]
1. Botão sem ação:

Perfil: SEFIC/ARQ - Coordenador-Geral de Prestação de Contas

Tela:  Avaliação de Resultados: Parecer Técnico

![image](https://user-images.githubusercontent.com/37881003/51492613-9d6ed900-1d99-11e9-8227-a91b5d79f85f.png)

2. Ausência dos botões para a assinatura:

Perfis: SEFIC/DIC - Diretor do Departamento e SEFIC - Secretário (a)

![image](https://user-images.githubusercontent.com/37881003/51493071-32be9d00-1d9b-11e9-8f94-f0ee89a7fa83.png)

![image](https://user-images.githubusercontent.com/37881003/51493154-87621800-1d9b-11e9-8bf2-a72e9f286f93.png)

![image](https://user-images.githubusercontent.com/37881003/51493196-b082a880-1d9b-11e9-86e6-5d7c0084fcd4.png)

**Comment by volthier** [comment]
Disponibilizado para homologação FIX. @DouglasMinC  @romulomb

**Comment by DouglasMinC** [comment]
Homologado.
