### ISSUE TITLE
CONCILIAÇÃO BANCÁRIA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1815]
Alteração da consulta de conciliação bancária

1. alinhar os labels e os campos alfanuméricos à esquerda;
2. centralizar os labels e os campos data;
3. alinhar os labels e os campos numéricos à direita;
4. retirar as colunas vlComprovado e Dt.Lançamento;
5. alterar o nome do label da coluna Valor para Vl.Comprovado 
6 Não permitir quebra de linha no campo CNPJ /CPF e
7. Retirar  R$ do campos moeda.

![Conciliacao.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/144215cc-d485-4ba5-a554-e9c8592ecb74)

**Comment by guiamado** [comment]
@romulomb Disponível no ambiente de homologação.

**Comment by romulomb** [comment]
Alinnhar à esquerda o label Fornecedor;

Alinhar à direita o label Número;

Alinhar à direita o label e o campo Vl. Diferença.

**Comment by guiamado** [comment]
disponível em homologação @romulomb

**Comment by romulomb** [comment]
![Tela.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/89d0984a-c2cc-4cb2-9ed9-d1914500d4bf)

**Comment by clebersantos** [comment]
Demanda atendida na issue #1868.
