### ISSUE TITLE
[Homologação] - Quando o recurso é finalizado não aparece no filtro "após recurso"

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1821]
Após o componente finalizar o parecer o sistema não mostra o projeto na lista de homologação após recurso.

Reportado pelo @romulo e @AdmissibilidadeSAV .

**Comment by clebersantos** [comment]
@thais_mendess, disponível em homologação.

**Comment by AdmissibilidadeSAV** [comment]
Homologado.
