### ISSUE TITLE
Lista de encaminhamento de projetos - perfil SAV/CGAV/CEP - Coordenador de Avaliação

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1848]
@volthier
O @romulomb solicitou a abertura desta issue.

A lista de encaminhamento de projetos para o perfil SAV/CGAV/CEP - Coordenador de Avaliação está sendo a mesma do perfil SEFIC-ARQ - Coordenador de Avaliação.
Como são perfis de setores diferentes (SEFIC/DEIPC/CGARE e SAV/CGAC/CEP), as listas de encaminhamento são diferentes.

![image](https://user-images.githubusercontent.com/37881003/50224388-f99ea180-0384-11e9-8423-7db999d50194.png)

A lista de encaminhamento para o perfil SAV/CGAV/CEP - Coordenador de Avaliação deve ser composta pelos seguintes usuários:

SAV/CGAC/CEP

Thiago Rodrigues    CPF: 030.871.991-33
Aline Lourenço        CPF: 077.291.366-86

**Comment by volthier** [comment]
Solicitação implementada em Homologação para analise.

**Comment by volthier** [comment]
Alteração efetuada.

**Comment by AdmissibilidadeSAV** [comment]
@volthier Homologado, por gentileza subir para produção.
