### ISSUE TITLE
[CORE] Docker salic com PHP 7

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#185]
Criar docker com php para podermos testar o sistema na nova versão do PHP 7.
Adicionar o container "Composer" para instalar a dependências do sistema.
referencias: 
https://github.com/gjuniioor/docker-php-sqlsrv 

Para trabalhar com pdo e sql server temos que usar o  **php7.0-sybase** como dependeria do projeto.

**Comment by wouerner** [comment]
Já temos imagens funcionais com php7 e já colocamos o ambiente de homologação com esse container. vamos caçar bugs agora.

**Comment by vinnyfs89** [comment]
Somente para fins de rastreabilidade, essa Issue foi desenvolvida no repositório [culturagovbr/docker-salic](https://github.com/culturagovbr/docker-salic/tree/feature-php7) e foi utilizada a branch "feature-php7".
