### ISSUE TITLE
Salvar - Avaliação de Comprovantes

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1855]
Perfil SEFIC/ARQ - Técnico de Prestação de Contas

Tela:

![image](https://user-images.githubusercontent.com/37881003/50343786-62198a00-050f-11e9-9e9c-a2dfe33a4f49.png)

Comportamento normal: 

Salvar a escolha "Aprovado" com ou sem preenchimento do campo "Parecer da Avaliação";
Salvar a escolha  "Reprovado" somente se tiver preenchimento do campo "Parecer da Avaliação". Caso a opção tenha sido escolhida e não tenha preenchimento do campo, mostrar mensagem solicitando o preenchimento.

Erros atuais:

1. Para comprovantes que estão inicialmente em "Não avaliado":

     Gravação da opção (Aprovado, Reprovado), após salvar, acontece somente se tiver algum caractere no campo "Parecer da Avaliação".

2. Comprovantes já avaliados.

    Possibilidade de salvar "Reprovado" sem preenchimento do campo "Parecer de Avaliação".

**Comment by clebersantos** [comment]
@DouglasMinC Douglas  pode adicionar à issue o problema de carregamento quando tem vários comprovantes?

**Comment by DouglasMinC** [comment]
Posso sim, @clebersantos . Estou montando todas agora.

**Comment by volthier** [comment]
Esta em implementada Homologação.

**Comment by DouglasMinC** [comment]
Homologado.
