### ISSUE TITLE
Lentidão/Travamento 

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1858]
Ocorrência de lentidão/travamento na opção "Comprovar Item" de itens de custos que possuem número alto de comprovantes de despesas.

Exemplo:  Projeto: 138997 - PROGRAMA DE MÚSICA & ORQUESTRA INSTITUTO GPA
               Item de Custo: Músico de Base

![image](https://user-images.githubusercontent.com/37881003/50345007-98a5d380-0514-11e9-8af7-e29948f5c607.png)

**Comment by DouglasMinC** [comment]
Verificada a diminuição da lentidão e a remoção dos travamentos em "Comprovar Item".

**Comment by clebersantos** [comment]
@DouglasMinC subi mais algumas correções e acredito que ficou mais rápido. Assim que você homologar podemos subir para produção.

**Comment by DouglasMinC** [comment]
@clebersantos, verificada melhora significativa em "Comprovar Item". Homologado! 

Entretanto, verifica-se lentidão/travamento na opção "Visualizar Projeto" nos perfis SEFIC/ARQ - Coordenador de Prestação de Contas e SEFIC/ARQ - Coordenador-Geral de Prestação de Contas.

![image](https://user-images.githubusercontent.com/37881003/50486733-68fa3e00-09e2-11e9-9336-20bdb5dd177b.png)

**Comment by clebersantos** [comment]
@DouglasMinC refatorei a parte de visualização do coordenador. Peço que faça o teste também na avaliação de itens, pois tive que ajustar para utilizar o mesmo componente nas duas planilhas.

Disponível em homologação.

**Comment by DouglasMinC** [comment]
Avaliar comprovantes (SEFIC/ARQ-Técnico de Prestação de Contas) e Visualizar Comprovantes (SEFIC/ARQ - Coordenador de Prestação de Contas e SEFIC/ARQ-Coordenador-Geral de Prestação de Contas) funcionando satisfatoriamente.   
Homologado!
