### ISSUE TITLE
Erro - Tipo de Diligência Invertido

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1869]
Perfis: SEFIC/ARQ - Técnico de Prestação de Contas  e  Proponente

**1.** As diligências que estão sendo realizadas do tipo "Somente itens recusados" estão sendo listadas como sendo do tipo "Todos os itens orçamentários":
![image](https://user-images.githubusercontent.com/37881003/50451080-f07b7a80-0918-11e9-8e46-863db13f1d29.png)

![image](https://user-images.githubusercontent.com/37881003/50450738-eeb0b780-0916-11e9-8c7c-5173453c6a6b.png)

Não está sendo possível verificar qual o tipo de diligência que está chegando ao proponente. Em teste feito no perfil de proponente em HMG, ao se tentar fazer a comprovação financeira e verificar o tipo de diligência que está chegando para o proponente, está aparecendo a seguinte tela de erro:

![image](https://user-images.githubusercontent.com/37881003/50450853-a04fe880-0917-11e9-97eb-13dcb61ba4f8.png)

![image](https://user-images.githubusercontent.com/37881003/50450869-b8c00300-0917-11e9-9899-9d2fabdeec6e.png)

**2.**  As diligências que estão sendo realizadas  do tipo "Todos os itens orçamentários"  estão sendo listadas como sendo do tipo "Somente itens recusados"  (descrito somente por Diligência na prestação de contas):

![image](https://user-images.githubusercontent.com/37881003/50450979-59162780-0918-11e9-8708-1f42c2a1b129.png)

Em teste feito no perfil do proponente em HMG, verificou-se que está chegando ao proponente o tipo de diligência correto ("Todos os itens orçamentários).

**Comment by FernandaLA** [comment]
@DouglasMinC  Correções disponíveis em homologação, favor verificar.

**Comment by DouglasMinC** [comment]
@FernandaLA , os erros persistiram nos testes  que eu fiz.

**Comment by DouglasMinC** [comment]
@FernandaLA , erros corrigidos!

**Comment by DouglasMinC** [comment]
@FernandaLA , verifiquei alguns problemas:

**Tipo de diligência: Somente itens recusados** 

**1. Dualidade de telas**

Inicialmente na opção "Comprovação Financeira" está aparecendo uma tela (Tela 2) que não salva as alterações e permite incluir novos comprovantes (o tipo de diligência "Somente itens recusados" é só para editar comprovantes recusados): 

Tela 1
![image](https://user-images.githubusercontent.com/37881003/50490756-03b04800-09f6-11e9-9f2b-85b55a7fa74c.png)

Tela 2
![image](https://user-images.githubusercontent.com/37881003/50490777-188cdb80-09f6-11e9-8457-9b8764e61e33.png)

Posteriormente, ao escolher um item de custo, editar um comprovante de despesa e salvar, aparece outro tipo de tela para a comprovação financeira (Tela 6) que permite salvar as edições feitas e não permite incluir novos comprovantes (tela correta): 


Tela 3
![image](https://user-images.githubusercontent.com/37881003/50490901-af599800-09f6-11e9-8db8-bf6ef644a6ea.png)

Tela 4
![image](https://user-images.githubusercontent.com/37881003/50490928-cac4a300-09f6-11e9-84ed-549c1cd7792d.png)

Tela 5

![image](https://user-images.githubusercontent.com/37881003/50491185-38bd9a00-09f8-11e9-9995-69aec6bf600a.png)
Obs.: As modificações não são salvas.

Tela 6

![image](https://user-images.githubusercontent.com/37881003/50491281-a7025c80-09f8-11e9-9b98-1266fd894b6e.png)

![image](https://user-images.githubusercontent.com/37881003/50491298-b84b6900-09f8-11e9-88b7-bfe6e8bfb260.png)

As alterações feitas a partir desta tela são salvas.

**Comment by FernandaLA** [comment]
@DouglasMinC Acabei de subir a correção pra homologação, favor verificar

**Comment by DouglasMinC** [comment]
@FernandaLA 
**1. Na "Comprovação Financeira" do tipo de diligência "Somente Itens recusados", o botão "Enviar" está apresentando erro:**

![image](https://user-images.githubusercontent.com/37881003/50691603-5d2cfe00-1018-11e9-955f-235389005bc5.png)

Erro:

![image](https://user-images.githubusercontent.com/37881003/50691626-6e760a80-1018-11e9-82b9-f20a6092ec61.png)

**2. O tipo de diligência "Todos os itens orçamentários" está aparecendo como o tipo "Somente Itens Recusados" na "Comprovação Financeira" para o proponente:**

Perfil: SEFIC/ARQ - Técnico de Prestação de Contas:
![image](https://user-images.githubusercontent.com/37881003/50691907-53f06100-1019-11e9-9e57-c428229d539c.png)

Perfil Proponente:

Em "Diligências" o tipo está correto:

![image](https://user-images.githubusercontent.com/37881003/50692036-b8132500-1019-11e9-89d3-5f1ca75dae01.png)

Porém, em "Comprovação Financeira" aparece o modelo correspondente ao tipo "Somente Itens Recusados":

![image](https://user-images.githubusercontent.com/37881003/50692108-ef81d180-1019-11e9-9807-e5ea40313897.png)

![image](https://user-images.githubusercontent.com/37881003/50692127-fc9ec080-1019-11e9-9cc7-04749e1b0bec.png)

**Comment by FernandaLA** [comment]
@DouglasMinC Correções disponíveis em Homologação

**Comment by DouglasMinC** [comment]
Verificado. Homologado!
