### ISSUE TITLE
[Prestação de contas] Comprovação financeira: duplicidade de comprovantes de outros municípios 

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1873]
Ao realizar comprovação financeira o sistema exibe comprovantes duplicados e de outras etapas na comprovação.

reportado pelo @romulomb.

**Comment by clebersantos** [comment]
Disponível no ambiente de homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
