### ISSUE TITLE
Formatação - Planilha de análise 

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1876]
@romulomb , solicitou que:

Os campos com valores em "R$", na planilha de análise do projeto, fossem colocados no formato de moeda e alinhados à direita. 

![image](https://user-images.githubusercontent.com/37881003/50700442-b8b7b580-1031-11e9-9ae0-8c0f7d3dcaa4.png)

**Comment by volthier** [comment]
correção implementada em Homologação!

**Comment by DouglasMinC** [comment]
Verificado. Homologado!
