### ISSUE TITLE
[ANALISE TECNICA] Migração do módulo para novo Layout e aplicação de melhorias na análise

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1878]
# Refatoração e novas funcionalidades
- [x] Migração do módulo da análise técnica para nova interface
- [x] Ao analisar planilha, permitir comparar a planilha editada pelo parecerista com a planilha original da proposta, não mostrar as duas por padrão, adicionar um botão para visualizar a original.
- [x] Calcular os totais dinamicamente
- [x] Os custos vinculados não podem ser alterados, o sistema deve fazer o cálculo.
- [x] Quando um item ultrapassar o valor mediano o sistema deve tornar a justificativa do parecerista obrigatória
- [x] Possibilitar o parecerista de visualizar o valor mediano do item baseado na Etapa, Produto e Estado.
- [x] Ao editar um item, o sistema deve validar a mediana.
- [x] Opção para restaurar um item editado pelo parecerista
- [x] Opção para restaurar toda a planilha editada pelo parecerista
- [x] Opção para zerar item 
- [x] Adicionar busca na listagem pelo PRONAC
- [x] Criar opção de selecionar itens na planilha e analisar separado na planilha, destacando na comparação também
- [x] Na finalização validar toda análise técnica
- [x] O sistema deve exibir a proposta para análise com as seguintes opções
 - Dados do projeto
 - Histórico de avaliações
 - Histórico de sugestões de enquadramento
 - Proponente
 - Documentos anexados
 - Plano de distribuição
 - Local de realização
 - Custos vinculados
 - Planilha orçamentária original

## Diligência
 - [x] Migrar funcionalidade do módulo para nova interface

## Declarar impedimento
 - [x] Migrar funcionalidade para nova interface

## Visualizar histórico
- [x] Aplicar nova interface

## Assinatura
- [x] Remover produtos do projeto
- [x] Remover diligencias
- [x] Remover acoes relevantes
- [x] No texto do parecer: Posicionamento Técnico => Parecer Técnico -> destacar
- [x] Parecer favorável: subir para a parte de cima do texto e destacar
- [x] Ajustar o Texto do documento para "Assinado eletrônicamente ver a issue #1903"
- [x] Justificar texto do documento

## Correções gerais 
-  [x] O valor do item não pode ultrapassar o solicitado (a regra está implementada, mas alguns pareceristas conseguem ultrapassar o valor).
- [x] Validar regras no front e back-end.
 - [x] Se o parecer favorável for "não" o sistema zera a planilha, possibilitar a opção do parecerista reintegrar o produto zerado.
 - [x] O parecerista não sabe a situação de análise do produto secundário, consegue visualizar o produto mas não sabe se já foi analisado)
 - [x] O sistema deve carregar por padrão o parecer favorável como "sim"
 - [x] ERRO: Para salvar a análise de conteúdo o sistema obriga a preencher "Ações relevantes"
 - [x] Remover o campo "ações relevantes" do parecer
-  [x] O parecerista tem dificuldade em saber quantos produtos existem no projeto
-  [x] O parecerista tem dificuldade em consultar o projeto
-  [x] Se o parecerista estiver com todos os produtos do projeto deve iniciar pelos secundários
-  [x] Melhoria: a consolidação só aparece quando os produtos secundários são finalizados, deixar desativado e colocar mensagem de orientação para o parecerista.
- [x] Melhoria: a contagem dos dias deverá descontar os dias em diligência
- [x] Na grid que lista os produtos adicionar novo layout do vuetify
- [x] Erro: Declarar impedimento não está funcionando (sem action)
- [x]  Memória de cálculo(valor solicitado, valor aprovado), valores aprovados por fonte, produto e etapa
- [x] Melhorar a cor do `hover` do item inativo
- [x] Bug nos produtos secundários as informações não estão carregando

Exemplos de modelos ​para o parecer
- PROJETO 184673 ver impressão
- PROJETO 182406 ver impressão

### Correções

- [x] O sistema não pode permitir na análise de custos que os pareceristas editem os itens de recursos de outras fontes, eles podem apenas visualizar.
- [x] Ao finalizar apareceu a opção de ir para o documento para assinar, porém ao clicar no ícone voltar e a partir daí não consigo mais assinar.
- [x] Ajuste no documento de assinatura

**Comment by clebersantos** [comment]
@Romulo_Menho, @thais_mendess e Marc, disponibilizei no ambiente do homologação a primeira parte da refatoração da análise do parecerista. Considero que já temos 50% dos trabalhos prontos. 

Podem avaliar a estrutura geral, fluxo, análise de conteúdo e em parte a análise de custos. 

Obrigado.

**Comment by clebersantos** [comment]
Ajustar o controle da análise do parecer para utilizar duas novas colunas na tabela sac.dbo.tbDistribuirParecer, conforme segue abaixo:

`siEncaminhamento`: 
 - 4 = Solicitação encaminhada ao parecerista /  técnico;
 - 5 = Solicitação devolvida ao coordenador da unidade de análise pelo parecerista
 Chave estrangeira da tabela: sac.dbo.tbTipoEncaminhamento

`siAnalise`: 
    - 0 = Aguardando análise
    - 1 = Em análise
    - 2 = Analisado
    - 3 = Finalizado

Regras para finalização:
1 - O sistema só deve permitir a finalização do produto principal após todos os produtos secundários estarem finalizados.
1 - Se o parecerista estiver apenas com um produto do projeto, o sistema encaminhará o produto para análise do Coordenador de Parecer.
2 - Se o parecerista estiver com mais de um produto, ao finalizar, se não for o último produto, o sistema deverá finalizar a análise, mas não encaminhará para o Coordenador.
3 -  Se o parecerista estiver com mais de um produto, ao finalizar o último produto, o sistema deverá  finalizar a análise do produto atual e encaminhar para o Coordenador de Parecer todos os produtos do mesmo projeto que estão disponíveis para análise dele.

**Comment by clebersantos** [comment]
No módulo de análise da adequação à realidade, acrescentar  ao registro na tabela tbDistribuirParecer as seguintes informações:
- [ ] siAnalise = 0
- [ ] siEncaminhamento = 3 - Encaminhado para o Coordenador de Parecer

**Comment by clebersantos** [comment]
Quando o parecerista declara impedimento os seguintes os seguintes atributos são gravados na tabela `tbDistribuirParecer`:
  - FecharAnalise: 0
  - stEstado: 0
  - siEncaminhamento: 3
  - siAnalise: 0

**Comment by clebersantos** [comment]
teste comentário.

**Comment by clebersantos** [comment]
Quando o parecerista declara impedimento os seguintes atributos são gravados na tabela `tbDistribuirParecer`:

- FecharAnalise: 0
- stEstado: 0
- siEncaminhamento: 3
- siAnalise: 0

**Comment by clebersantos** [comment]
OPÇÕES PARA O siAnalise
0. Aguardando Distribuição para o parecerista (Coordenador de Parecer)
1. Em análise pelo parecerista (Parecerista)
2. Analisado pelo parecerista  (Parecerista)
3. Finalizado análise técnica  (Parecerista)
4. Em validação pelo coordenador (Coordenador de Parecer)
5. Validados pelo coordenador (Coordenador de Parecer)

**Comment by clebersantos** [comment]
@romulomb informo que a issue está disponível para homologação.

**Comment by AdmissibilidadeSAV** [comment]
Alguns ajustes:

- Quando é produto secundário o sistema não finaliza a análise, o produto secundário aparece para assinatura (somente produtos principais devem disponibilizar a opção de assinatura);
- Os produtos principais com produtos secundários não ficam disponíveis para finalização;
- Padronizar os ícones da listagem do parecerista, trocar ícone de assinatura para o lápis e o de análise para o gavel, alternando as cores;
- Mostrar todas diligências para que o parecerista que estiver analisando o produto (no caso de análise desmembrada) independentemente se o produto ora em análise tenha ou não sido diligenciado, pois se tiver com pareceristas diferentes não acabem diligenciando a mesma coisa, ou tenham ciência na hora de concluir de que se trata de pendência de uma resposta à diligência de outro produto do projeto;
- Informar o parecerista no detalhamento da diligência;
- Não conseguir finalizar nenhuma análise, mesmo com o produto secundário analisado a checagem do produto principal informa que há produto secundário sem concluir, não permitindo finalizar a análise do projeto, muito menos assinar o documento (vide Pronac: 185367 na minha caixa CPF: 01444542117).
- A declaração de impedimento deverá aparecer para o proponente até antes de gerar o documento para assinatura. O parecerista ao declarar o impedimento tudo que ele já salvou deverá ser apagado para que o próximo parecerista pegue a análise do zero.

**Comment by Paulophmp** [comment]
Ajustes feitos, e está no ambiente de HOMOLOGAÇÂO.

**Comment by AdmissibilidadeSAV** [comment]
O sistema não pode permitir na análise de custos que os pareceristas editem os itens de recursos de outras fontes, eles podem apenas visualizar.

https://hmg.salic.cultura.gov.br/index/index/#/parecer/analise-inicial/analisar/115/221841/0/custos

![image](https://user-images.githubusercontent.com/35490669/62056978-1477a500-b1f5-11e9-9dcf-fc67ed20e273.png)

**Comment by romulomb** [comment]
**VERIFICAR APRESENTAÇÃO DO CÁLCULO DO MEDIANA NA PLANILHA**
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/867d05af-fa27-46ad-adf7-c0c64d00383f)

**PRONAC 190035**
Produto secundário.

-------------------------------------------------------------------------------------------------------------

**FINALIZEI E NÃO ASSINEI**
**PRONAC 183932**
Quando finalizer apareceu a opção de ir para o documento para assinar, Porém resolvir clicar no ícone voltar e a partir daí não consigo mais assinar.

------------------------------------------------------------------------------------------------------------

**AJUSTE NO DOCUMENTO GERADO PARA ASSINATURA**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/37b245e7-b59c-42c1-9269-cceb84cca1f1)

**Comment by clebersantos** [comment]
@romulomb, informo que os ajustes foram realizados e estão disponíveis no ambiente de homologação.

Itens ajustados:
 - [X]  Parecerista não pode editar itens de outras fontes
 - [X]  Valor da mediana - A validação do cálculo da mediana é realizada no cadastro da proposta, até a análise da planilha pelo parecerista o valor da mediana pode sofrer alteração. Para resolver esta situação quando o parecerista salva um item, o sistema faz uma nova validação do custo praticado e remove a marcação que informa se o item ultrapassou o valor da mediana.
- [X] Finalizei e não assinei
- [X] Correções no documento de parecer técnico. Obs: Não foi possível adicionar ao template o nome da unidade por extenso, tendo em vista que no banco de dados não temos esta informação.

**Comment by romulomb** [comment]
#### AJUSTES

1. Tela de finalizar está em loop
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/dd210005-116c-4ee6-aa22-1ebb62e0aa21)

**Comment by clebersantos** [comment]
@romulomb, pode refazer o teste? 

Tentei simular o erro aqui e o problema reportado não aconteceu(conforme imagem abaixo). Pode ter ocorrido algum problema de conexão.

![image](https://user-images.githubusercontent.com/2494751/66338910-6edd6200-e918-11e9-8ee4-0e06d747896a.png)

**Comment by romulomb** [comment]
** HOMOLOGADA**

**NÃO SUBIR  para produção porque a nova funcionalidade está provocando algumas inconsistência na readequação.**

**Somente após os ajustes na readequação e que poderá ser executada a promoção para a produção**
