### ISSUE TITLE
Erro: Visualizar Comprovantes - Aba "Histórico"

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1879]
Ambiente: Produção 

Perfil: SEFIC/ARQ - Técnico de Prestação de Contas

Erro: Opção "Visualizar Comprovantes" não carrega as informações dos comprovantes na aba "Histórico".

![image](https://user-images.githubusercontent.com/37881003/50847808-a7381b80-1359-11e9-9214-10e146a8aecc.png)

![image](https://user-images.githubusercontent.com/37881003/50847826-b9b25500-1359-11e9-992f-f7366c76278c.png)

![image](https://user-images.githubusercontent.com/37881003/50847838-c171f980-1359-11e9-947b-be4237ba9721.png)

Obs.: A opção está funcionando corretamente na HMG.

**Comment by volthier** [comment]
Correção impĺementada com a resolução ada issue #1858
