### ISSUE TITLE
[CORE] Plugar o salic-minc ao Sentry

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#188]
Ao plugar o salic-minc ao Sentry, passamos a ter controle pontual sobre todas as exceções lançadas pelo PHP/Zend, com alguns extras como abrir automaticamente issues, notificar os desenvolvedores, metadados e outros elementos que podem acelerar a resolução dos problemas.

Consegui encontrar um helper para Zend2 em https://github.com/cloud-solutions/zend-sentry
e a biblioteca padrão para o PHP https://docs.sentry.io/clients/php que requer alguma "intervenção" manual no código. Se todas as exceções da aplicação herdarem de uma unica classe, provavelmente facilite no trabalho de injetar o Sentry para que ele trate as exceções.

**Branch:** https://github.com/culturagovbr/salic-minc/tree/feature-sentry

**Comment by wouerner** [comment]
Precisamos fazer a analise dos erros que Sentry está captando, e se precisamos de mais informações.
