### ISSUE TITLE
[ASSINATURA] - Atualização do template para novo Ministério

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#1903]
**ALTERAÇÃO NO NOME DA INSTTITUIÇÃO**

![Doc_1.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/1ff4e81e-0b63-4f13-b342-66bc829e6aea)

![Doc_3.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2f95100a-e28f-42d1-91bd-a7431584b1e4)

**ALTERAÇÃO O TEXTO SOBRE ASSINATURA**

![Doc_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a07fd2f7-c8a3-482c-8957-def1638f1a37)

**Comment by AdmissibilidadeSAV** [comment]
Conforme solicitado pelo @romulomb, informo que faltou alterar a tela abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/5caf1a48-1497-4e94-ba94-fdebbdd829f3)

No documento abaixo do nome "Ministério da Cidadania" deverá aparecer o nome completo da Secretaria/Vinculada (e não a Sigla) como por exemplo:

* Secretaria de Fomento e Incentivo à Cultura
* Secretaria do Audiovisual
* Instituto do Patrimônio Histórico e Artístico Nacional
* Instituto Brasileiro de Museus
* Fundação Biblioteca Nacional
* Fundação Nacional de Artes

![Parecer Técnico do Projeto.JPG](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/812f2a27-0a4b-47b8-832e-5bce780103da)

**Comment by clebersantos** [comment]
Alterar o texto "Documento assinado eletronicamente com fundamento no artigo 73 da instrução normativa nº 02/2019 do Ministério da Cidadania publicado no Diário Oficial da União na data de 24/04/2019 por:" para "Documento assinado eletronicamente.".

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV o texto "Documento assinado eletronicamente com fundamento no artigo 73 da instrução normativa nº 02/2019 do Ministério da Cidadania publicado no Diário Oficial da União na data de 24/04/2019 por:"  para "Documento assinado eletronicamente por:", alteração disponível no ambiente de homologação.

Sobre os templates da assinatura com a sigla "SAV" não encontrei no código o problema reportado, acredito que as alterações já foram realizadas pelo @fernao.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
