### ISSUE TITLE
[DADOS PROJETO] Refatorando o vuex

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1919]
Colocando o vuex de dados Projeto na nova estrutura, criar um arquivo de api e modulo com a store para cada menu encontrado na página, será feito nos seguintes menus:

- Outras Informações
- Execução
- Dados Bancários

**Comment by guiamado** [comment]
@clebersantos Refatoração disponível no ambiente de homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**
