### ISSUE TITLE
Atualização de página após "Devolver"

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#1923]
Perfis: SEFIC/ARQ - Coordenador-Geral de Prestação de Contas
          SEFIC/DIC - Diretor do Departamento
          SEFIC - Secretário (a)

A ação de "Devolver" não é seguida de atualização automática da página, dando a impressão para o usuário que a operação de devolução do projeto não aconteceu.

**Comment by volthier** [comment]
Implementado em Homologação solução.

Verificar!

**Comment by DouglasMinC** [comment]
**1.** 
Perfil: SEFIC/ARQ - Coordenador-Geral de Prestação de Contas

A seguinte página não está sendo atualizada automaticamente após a devolução:

![image](https://user-images.githubusercontent.com/37881003/52138113-6a4b0600-2633-11e9-8286-80bfeaea98a5.png)

**2.** 
Nos testes realizados, em algumas devoluções, o parecer técnico retornou para o técnico sem o texto e sem o status de quando foi emitido.

**Comment by volthier** [comment]
Correção implementada em Homologação!

**Comment by DouglasMinC** [comment]
Em novos testes realizados, os erros listados não foram verificados. 

Homologado.
