### ISSUE TITLE
[DADOS PROJETO] Migração Prestação de Contas para layout novo

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1924]
Migrar Todo menu de Prestação de contas usando vuetify, Services e Rest Controllers.
Menus a serem migrados:
- [x] Relação de pagamentos
- [x] Execução de Receita e Despesa
- [x] Relatório Físico
- [x] Pagamentos Por UF / Municipio
- [x] Pagamentos Consolidados
- [x] Relatórios Trimestrais
- [x] Relatório de Cumprimento do Objeto

![image.png](https://images.zenhubusercontent.com/5a576a214b5806bc2bc25a64/ed7ce99a-ae
c9-46ba-a52f-e2b4c744dfd5)

**Comment by Paulophmp** [comment]
@romulomb, boa tarde já esta disponível para teste no ambiente de Homologação.

**Comment by romulomb** [comment]
**RELAÇÃO DE PAGAMENTOS**
![Relacao_Pagamento_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a162dd13-670c-48a3-ad24-63076f67b99c)

![Relacao_Pagamento_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/75314d44-4e39-4e32-813a-204da5d384eb)

**Comment by romulomb** [comment]
**EXECUÇÃO DA RECEITA E DESPESA**

![Execucao_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b397649b-ade1-4c42-bd47-dc68793b596a)

![Execucao_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/ce9e7db0-c28b-4c01-8e92-8b54c5cdd3f2)

**Comment by romulomb** [comment]
**PAGAMENTO UF / MUNICÍPIO**

![Relacao_Pagamento_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/36ba35ba-3d44-43f9-a93f-8b429314fd70)

**Comment by romulomb** [comment]
**RELATÓRIO TRIMESTRAL**

Retirar o menu lateral e remover o código do sistema.

**Comment by romulomb** [comment]
**RELATÓRIO DE CUMPRIMENTO DO OBJETO**]

![Cumprimento_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6d803b27-8b47-4064-a5c3-135f5c8bfe0c)

![Cumprimento_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/438cdfb8-e831-4ce0-afbd-c55285449647)

![Cumprimento_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3da7bf96-61ff-4b4b-910d-2f80876e40ee)

**Comment by Paulophmp** [comment]
@romulomb, não entendi bem o que é para fazer na tela: RELATÓRIO TRIMESTRAL.

**Comment by romulomb** [comment]
**RELATÓRIO TRIMESTRAL**

Retirar o menu lateral e remover o código do sistema.

**É PARA RETIRAR ESSE RELATÓRIO DO SISTEMA**.

**Comment by Paulophmp** [comment]
@romulomb, alterações solicitadas ja estão disponíveis para testes em HMG.

**Comment by romulomb** [comment]
**RELAÇÃO DE PAGAMENTOS**
![Relatorios_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3aa0b1d0-2eae-4449-b7f8-9f0e1774949e)

**Comment by Paulophmp** [comment]
@romulomb, alterações realizadas.

**Comment by romulomb** [comment]
**Relação de pagamento - ok**

**Comment by romulomb** [comment]
**EXECUÇÃO DA RECEITA E DESPESA**

O valor não está alinhado à direita.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA A PRODUÇÃO**

**EXCELENTE TRABALHO, PARABÉNS**

**OBRIGADO**
