### ISSUE TITLE
[DADOS PROJETO][Análise e Aprovação] Migrar todos os sub-menus para Modelo de novo Layout

### ISSUE THREAD

**Issue by Paulophmp** [culturagovbr/salic-minc#1925]
Migração do menu Análise e Aprovação, e os submenus contidos para o novo modelo utilizando Vuetify, Services e Rest Controllers.

Análise do Projeto:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Aprovação:
- [x] Criar Rest Controller
- [x] Criar Service
- [x] Criar Componente

Recursos:
- [ ] Criar Rest Controller
- [ ] Criar Service
- [ ] Criar Componente

**Comment by Paulophmp** [comment]
@romulomb, boa tarde já esta disponível para teste no ambiente de Homologação.

**Comment by Paulophmp** [comment]
@romulomb, aguardando o retorno.

**Comment by romulomb** [comment]
Paulo tem apenas um observação.

Passei para o Cleber pelo hangout.

**Comment by Paulophmp** [comment]
@romulomb, alterações solicitadas ja estam no ambiente de Homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**


**Subir para a produção**


**Parabéns, ficou excelente**


**Obrigado**
