### ISSUE TITLE
[HOTFIX] Dados Complementares não aparecem

### ISSUE THREAD

**Issue by guiamado** [culturagovbr/salic-minc#1954]
Erro Reportado em produção, onde Dados Complementares em Dados Projeto não aparecem.

![image.png](https://images.zenhubusercontent.com/5a576a214b5806bc2bc25a64/371fdc0b-9db5-4549-b90f-4e7c0e3926ac)

**Comment by guiamado** [comment]
Correção Disponível no ambiente de homologação @romulomb

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Subir para produção por gentileza**

**Obrigado**
