### ISSUE TITLE
[Readequações] Definição de rotas da API

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#1961]
Mapeamento das rotas da readequação no Drakov:

https://github.com/culturagovbr/salic-minc/blob/dev/api.apib

**Comment by luizfpinheiro** [comment]
A definição das rotas foram definidas em [readequacao.md](https://github.com/culturagovbr/salic-minc/blob/01efb63f10a5452e3d2b9f9c7a623fc0dfec6c28/front/src/helpers/mock/readequacao.md).
