### ISSUE TITLE
[Readequações] Proposta de reformulação do front para novo layout - Proponente 

### ISSUE THREAD

**Issue by luizfpinheiro** [culturagovbr/salic-minc#1967]
### Listagem de readequações salvas
- [x] Tabela com readequações salvas
- [x] Botões de ação por item (editar/finalizar/excluir)
- [x] Botão único para criação de nova readequação 
- [x] Finalizar readequação
- [x] Tela de visualização de readequação
- [x] Alterar link para painel de readequações novo
- [x] Ajuste de recarregamentos (dispatch)
- [x] Buscar dados do agente na página visualizarReadequação (não possui dados no back)
- [x] Padronização de cores dos botões
- [x] Bug na exclusão
- [x] Formatação de data na tabela
- [x] Implementar busca no painel
- [x] Verificar outros tipos de readequação / redirect
- [x] Adicionar confirmação na finalização de readequação
- [x] Colocar edição no v-form e validação - textarea
- [x] Colocar edição no v-form e validação - input
- [x] Permissionamento no front
- [x] Liberar botão de finalizar somente se válido (Painel)
- [x] Visualização da solicitação lado a lado - avaliar diff
- [x] Arquivo (ajustes)
- [x] Alterar plugin de texto rico para o genérico *
- [x] Forçar atualização da lista de tipos de readequações disponíveis quando exclui uma readequação
- [x] Ajustes na visualização
- [x] Data aparece errada nas readequações de data
- [x] API: textos grandes (250+) vem cortados
- [x] Revisão geral de lint
- [x] TemplateData: integrar validação
- [x] Bug: ao editar item e salvar (exceto primeiro da lista), ordem da lista se altera e EditarReadequacao muda o elemento editado
- [x] Adicionar permissões / perfil à finalização
- [x] Adicionar link para visualizar arquivo - visualizarReadequacao e Tabela
- [x] Visualizar readequação: não exibir comparação para readequações complexas (planilhas, plano distribuição etc)
- [x] Bug com botão finalizar no preenchimento de TemplateDate
- [x] Menu alto: corrigir carregamento infinito no proponente #2030
- [x] Verificação de permissão para visualizar painel com proponentes / projetos
- [x] Adicionar verificação de permissão no back (buscar, criar, atualizar, finalizar, excluir)
- [x] **Redirecionar visualização para links antigos**

### Ajustes
- [x] Acrescentar botão para sair da funcionalidade
- [x] Bug: Arquivo anexado no pedido anterior, aparecer como anexado em um novo pedido.
- [x] Padronizar a forma de mostrar o arquivo anexado.
- [x] Não está mostrando a solicitação na visualização - verificar
- [x] Finalizar Readequação - formatar a exibição data.
- [x] Painel: acrescentar o status da análise (siEncaminhamento)
- [x] Ajustes na visualização: nome do avaliador
- [x] Ajustes na visualização: truncando avaliação
- [x] Adicionar botão de copiar informação do campo original na edição
- [x] Carregamento de  readequação de data inconsistente
- [x] Verificar erro no campo Diff
- [x] Destacar título na Visualização
- [x] Carregamento de painéis das abas acusa que não tem itens quando está apenas carregando

### Modal de criação/edição de uma readequação 
- [x] Combo para selecionar tipo de Readequação, caso seja uma nova Readequação
- [x] Botões de ação (salvar/finalizar/excluir)
- [x] Campo para edição do tipo especifico de readequação (date, textarea, char etc)
- [x] Edição de readequação (genérico - justificativa e upload arquivo) - conversão vuetify
- [x] Upload de documentos

**Comment by luizfpinheiro** [comment]
Para a visualização da Readequação a comparação de informações deve ser **"campoAtual" vs "readequacaoEditada"**. Somente é possível realizar essa comparação nas abas Edição e Análise, pois não há um histórico de versões dos campos da readequação (a readequação somente grava o valor novo; o dado anterior não é armazenado.

**Comment by romulomb** [comment]
# AJUSTES

## PAINEL DE EDIÇÃO

**1. Acrescentar botão para sair da funcionalidade.**

![Diversa_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/934e5577-88f7-42d1-957a-c432323a626a)

**2. Arquivo anexado no pedido anterior, aparecer como anexado em um novo pedido.**

![Diversa_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/0769efa1-d597-4095-b93c-7655fce1b6ba)

**3. Padronizar a forma de mostrar o arquivo anexaso.**

![Diversa_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/47d05541-6796-43f0-9440-f46aa82b53cf)

**ou**

![Diversa_4.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/5d944da0-5384-42ad-8b82-27291e53f729)

**4. Não está mostrando a solicitação**

![Diversa_5.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6537f0c-d483-4bb5-a376-db15b3ca4fb6)

** 5. Finalizar Readequação - formatar a exibição data.**

![Diversa_6.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d36a27ed-155b-4e17-88f4-7f6a9ec2b0e4)

## PAINEL DE EDIÇÃO

**6. Acrescentar o status da análise**

![Diversa_7.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/773b759f-c297-4da3-8387-a680d2d81e44)

## PAINEL DE FINALIZADAS

**7.Ajuste na visualização**

![Diversa_8.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/948868e5-966c-404f-ae5f-f2b391d0d1af)


![Diversa_9.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/31becbad-00a1-4450-a05f-1b51247a652a)

**Comment by romulomb** [comment]
## Formatação
 ![Tela.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2ae5ae6d-2f6a-41ec-834e-f955c62e19cd)

**Observação**

Acusa alteração aonde não houve.

**Comment by fernao** [comment]
Ajustes finalizados, disponível para homologação.

**Comment by fernao** [comment]
Disponível para homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**PARABÉNS, FICOU ÓTIMO**
