### ISSUE TITLE
[Homologação] Tipo de homologação de projeto

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#1983]
Como Coordenador de Análise(DIAPPI), quando tento analisar um projeto homologado com o tipo "ad referendum" (tpHomologacao = 2) o sistema não disponibiliza o parecer para análise. Gostaria de analisar o projeto independente do tipo da homologação.

Critérios de aceite:
 - Ao acessar o menu "Análise ->Homologar Projeto", na lista "Aguardando análise Inicial" ao clicar em "Homologar projeto", o parecer deve estar disponível para análise e alteração na coluna "Parecer de Homologação".
 - O coordenador poderá encaminhar e gerar o documento para assinatura.

Reportado pelo @romulomb

**Comment by clebersantos** [comment]
Disponível para homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**PARABÉNS FICOU EXCELENTE**

**OBRIGADO**
