### ISSUE TITLE
[Avaliação de Resultados] Inconsistências Análise Laudo Final

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2004]
Como Secretário da Sefic, ao acessar o menu principal "Avaliação de Resultados" -> "Analisar Laudo Final" o sistema apresenta os seguintes problemas:
- [x] Ao acessar a página o menu superior muda e não corresponde ao perfil utilizado
- [x] Ao tentar assinar um documento, na tela de assinatura, ao clicar no botão voltar o sistema redireciona para o módulo de assinatura e não para a tela anterior.

Reportado pelo @romulomb

**Comment by volthier** [comment]
Item 2 da lista implementado em Homologação para analise e validação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA A PRODUÇÃO**

**OBRIGADO**

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA A PRODUÇÃO**

**OBRIGADO**
