### ISSUE TITLE
[Avaliação de Resultados] Cumprimento do Objeto Reprovado

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2005]
Como Coordenador-Geral de Prestação de contas, SEFIC/ARQ, no menu principal "Avaliação de resultados" -> "Analisar laudo final". Gostaria que os projetos que tiveram o cumprimento do objeto reprovado fossem listados na aba "Análise" para emissão do laudo final do projeto.

Informo ainda que o fluxo deve ignorar a avaliação da comprovação financeira e o sistema deverá exibir apenas as informações do cumprimento do objeto na avaliação.

**Informação técnica**:
A ação que finaliza a análise do cumprimento do objeto está disponível no diretório [modules/comprovacao-objeto/service/assinatura/acao/Finalizar.php](https://github.com/culturagovbr/salic-minc/blob/f0ecb6610ad03ef69b30536a16a7470e7733ca5c/application/modules/comprovacao-objeto/service/assinatura/acao/Finalizar.php#L7)

reportado pelo @romulomb.

**Comment by volthier** [comment]
Solicitação implementada em ambiente de Homologação para analise e validação!

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
