### ISSUE TITLE
[Avaliação de resultados] Finalização do Laudo Final

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2006]
Como Secretário da SEFIC, ao finalizar o Laudo Final do projeto, o sistema deve alterar o orgão destino do projeto, conforme regra abaixo. 

Se o orgão superior do projeto for SEFIC(251) alterar o orgão destino para ORGAO_SEFIC_ARQ_CGEPC(303).
Se o orgão superior do projeto for SAV(160) alterar o orgão destino para ORGAO_SAV_CEP(167).

**Informação técnica**
Ação que finaliza o laudo final e altera o orgão destino está no arquivo: [/modules/avaliacao-resultados/service/assinatura/laudo/acao/Finalizar.php](https://github.com/culturagovbr/salic-minc/blob/master/application/modules/avaliacao-resultados/service/assinatura/laudo/acao/Finalizar.php)

reportado pelo @romulomb.

**Comment by volthier** [comment]
Implementado novo destino em ambiente de homologação para indicativo de validação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**Parabéns, ficou excelente.**

**SUBIR PARA PRODUÇÃO**
