### ISSUE TITLE
[Dados do Projeto] Laudo Final

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2007]
Como usuário do sistema, ao consultar os dados do projeto, menu prestação de contas, gostaria ter uma opção para visualizar o "Laudo final" do projeto.

O relatório deve fornecer as informações geradas no relatório do laudo final da avaliação de resultados.

Solicitado pelo @romulomb.

**Comment by Paulophmp** [comment]
@romulomb, já esta Disponível em HMG, já aproveitei e fiz aqueles ajuste em DADOS DO PROJETO, dos links: Captação de recursos e Comprovação que quando clicados redirecionava para tela antiga.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
