### ISSUE TITLE
[Readequação] Erro no cálculo de remuneração para captação de recursos

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#2012]
Readequação planilha - cálculo de remuneração para captação com erros nos casos listados abaixo:

1) Pronac: 182657 -> OK
Se for maior que o q ele pediu inicialmente, não está deixando subir. Mas se houve complementação, poderia subir até os limites estabelecidos. Mas manteve abaixo.

2) Pronac 179490 -> OK
Complementação, 4% de remuneração. Manteve valor abaixo do percentual

3) Pronac 163248 -> verificar
Projeto 2016, não tem recálculo e está recalculando

4) Pronac 162591 -> erro não relacionado ao sistema
Zerou custos de remuneração de captação

5) Pronac 178318 -> OK
Complementou mas não recalculou.

6) Pronac 183994 -> OK
Complementou, mas não recalculou, manteve o valor original

7) Pronac: 172208 -> Aguardando detalhes
Erro no cálculo

**Comment by fernao** [comment]
@romulomb como fica em relação à regra descrita e implementada na https://github.com/culturagovbr/salic-minc/issues/1801 ?

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
