### ISSUE TITLE
Força Tarefa Comprovação Financeira

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#2018]
Verificar comprovantes sendo salvos sem fornecedores.

**Comment by romulomb** [comment]
**INCONSISTÊNCIA 1**

Na comprovação, se o usuário digitar o CNPJ/CPF  e não clicar na lupa para carregar as informações.
E  clicar no botão Salvar, o sistema gravar sem a informações do fornecvedor.

**INCONSISTÊNCIA 2**
Proponente não conseguem salvar a comprovação financeira.
O sistema dar a mensagem que salvou com sucesso e não grava a informação.

**INCONSISTÊNCIA 3**
Quando tem mais de 10 comprovações no mesmo item, o sistema não mostra a partir do 11 comprovação, apesar de gravar a informação.

**Comment by wouerner** [comment]
Os ajustes acima já estão em produção, vou deixar mais uma semana aberto para casos relacionados, poderem ter um tratamento como hotfix.
