### ISSUE TITLE
[Proposta] Alteração do formulário de proposta cultural - Informações Iniciais

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#205]
[7.1.1] 
**História:** eu como proponente, gostaria de preencher o formulário conforme definição da nova IN

**Checklist:**
- [x] "Data do ato" deve vir em branco.
- [x] Ocultar impacto ambiental.(não está mais sendo usado)
- [x] "Descrição da atividade:" Incluir novo campo no formulário (e na tabela pré-projeto), 8000 varchar, texto rico, com texto de ajuda, na aba de detalhes técnicos

**Comment by chris-redfield** [comment]
Incluir novo campo no formulário (e na tabela pré-projeto), chamado:

Descrição da atividade:
8000 varchar, texto rico, com texto de ajuda, na aba de detalhes tecnicos

**Comment by clebersantos** [comment]
## Proposta 
 - Atualizar os textos de ajuda dos campos de texto rico, os técnicos de admissibilidade da  SAV e SEFIC ficaram responsáveis por enviá-los.
 - No menu, opção de `Responsablidade Social` remover apenas do formulário o campo `Impacto Ambiental`.
- No menu, opção de `Detalhes Técnicos`, adicionar o campo de texto rico `Descrição de atividade` com 8.000(oito mil) caracteres
- Na análise de admissibilidade os campos `Outras informações` e `Detalhes Técnicos` estão invertidos.
- No formulário inicial, no campo `Data do ato` retirar a data padrão que aparece com o ano de 1900.
- No menu, `local de realização` após enviar a proposta para o MinC, o proponente consegue excluir a localização, excluindo os itens orçamentários vinculados.
