### ISSUE TITLE
[Proposta] Alteração no Plano de Distribuição

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#206]
[7.1.1.2] 

**História**: eu como proponente, gostaria de preencher o plano de distribuição conforme necessidade da nova IN

**Relacionadas:** 
#236 #219 #217 #206

**Checklist**
- [x] No resumo do detalhamento do produto, o valor médio do proponente terá o limite de até R$ 225,00.
- [x] No detalhamento do Produto, em Preço Popular, o valor limite do Preço Unitário passará de R$ 50,00 para R$ 75,00.

**REGRA**

Regra para calcular o valor médio proponente:

```
(vlReceitaProponenteIntegral + vlReceitaProponenteParcial) / (qtProponenteIntegral + qtProponenteParcial))   
```
Proponente poderá cadastrar valores que ultrapassem o **valor médio proponente** quando houver transmissão em TV aberta.

**Comment by clebersantos** [comment]
## Plano de Distribuição
No resumo do detalhamento do produto, o `valor médio` do `proponente` terá o limite de até R$ 225,00

No detalhamento do Produto, em `Preço Popular`, o valor limite do Preço Unitário passará de R$ 50,00 para R$ 75,00.

**Comment by ShinNin-chan** [comment]
Revisão dos commits, pronto para enviar para homologação.

**Comment by chris-redfield** [comment]
ARTIGO 20 - LINHA E

Transmissão tv aberta pode estourar o limite de 225,00

Envia de proposta ** nova regra
Informação visual para proponente que projeto estorou a media.
