### ISSUE TITLE
[Proposta] Adequações para IN 2019

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2066]
### PLANO DE DISTRIBUIÇÃO
- Mínimo de **20%**  (vinte por cento) exclusivamente para distribuição gratuita com caráter social, educativo ou formação artística.
- Até 10% (dez por cento) para distribuição gratuita por patrocinadores.
- Até 10% (dez por cento) para distribuição gratuita promocional pelo proponente em ações de divulgação do projeto.
mínimo de 10% (dez por cento) para comercialização em valores que não ultrapassem o valor do Vale-Cultura, nos termos do art. 8º da Lei nº 12.761, de 2012.
- A comercialização a critério do proponente será limitada a 50% (cinquenta por cento) do quantitativo de produtos culturais, sendo o preço médio do ingresso ou produto de **R$ 225,00** (duzentos e vinte e cinco reais), 

### REMUNERAÇÃO PARA CAPTAÇÃO DE RECURSOS
- Limite 10%
- Teto de ** R$ 100.000,00**.

### FORMULÁRIO DE CADASTRO DA PROPOSTA CULTURAL
Incluir o bloco de tipicidade da proposta cultural após o bloco de **Identificação da Proposta Cultural**
![Tela.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/62ea8b02-a5f9-4914-9abb-0d4847261b99)

### Bloco da tipicidade das propostas e seus limites orçamentários
[https://app.zenhub.com/files/104502087/c2271cd1-5579-4da8-bb98-2b3097af3b56/download](https://app.zenhub.com/files/104502087/c2271cd1-5579-4da8-bb98-2b3097af3b56/download)

- Somente um opção poderá ser selecionada;
- Se for selecionada a opção **Singulares** a aplicação deverá gravar no atributo **tpProposta** o valor  **713** - Projetos singulares;
- Se for selecionada a opção **Específicos** a aplicação deverá gravar no atributo **tpProposta** o valor  **714** - Projetos específicos;
- Se for selecionada a opção **Especiais** a aplicação deverá gravar no atributo **tpProposta** o valor  **715** - Projetos especiais.
Query que retorna os valores : 
**SELECT * FROM sac.dbo.Verificacao WHERE idTipo = 28 AND stEstado = 1**.
- Quando for selecionado a opção **Específicos**, aplicação deverá disponibilizar um combo para o proponente escolher a tipologia da proposta.
Query que retorna as informações para carrega o combo:  
**SELECT * FROM sac.dbo.Verificacao WHERE idTipo = 30 AND stEstado = 1  ORDER BY Descricao**

- Quando for selecionado a opção **Especiais**, aplicação deverá disponibilizar um combo para o proponente escolher a tipologia da proposta.
Query que retorna as informações para carrega o combo:  
**SELECT * FROM sac.dbo.Verificacao WHERE idTipo = 29 AND stEstado = 1  ORDER BY Descricao**

- Quando for selecionado a opção **Singulares**, aplicação deverá disponibilizar um combo para o proponente escolher a tipologia da proposta.
Query que retorna as informações para carrega o combo:  
**SELECT * FROM sac.dbo.Verificacao WHERE idTipo = 31 AND stEstado = 1  ORDER BY Descricao**

- Título do Bloco
**Tipicidade  e seus limites orçamentários**

- Labels da opções:
**Singulares, até R$ 1.000.000,00 (Art. 4º, alínea d)
Específicos, até R$ 6.000.000,00 (Art. 4º, § 3º)
Especiais, sem limite (Art. 4º, § 2º)**

**Gravação na tabela PreProjeto**
- A informação da tipicidade da proposta deverá ser armazenada no atributo **tpTipicidade** da tabela PreProjeto;
- A informação da Tipologia da proposta deverá ser armazenada no atributo **tpTipologia** da tabela PreProjeto.

### Cadastro da proposta:
- [x] Desativar regra dos 90 dias do período de execução
- [x] Corrigir label do campo agência, proponentes não sabem que é uma agência do Banco do Brasil.
- [x] Limitar o campo da agência para 5 dígitos

### No Plano de Distribuição:
- [x] Distribuição gratuita: Mínimo de 40% (quarenta por cento).
- [x] Preço Popular: Mínimo de 10% (dez por cento) para comercialização em valores que não ultrapassem 50%(cinquenta por cento) do valor do Vale Cultura, ou seja, não pode ultrapassar R$ 25, 00 (vinte e cinto) reais
- [x] Proponente: Máximo de 40%
- [x] Quando edita o detalhamento, o item fica duplicado na listagem
- [x] PREÇO POPULAR -> adicionar texto: valor de referência do Vale Cultura: R$ 50,00 (cinquenta reais)
- [X] O sistema deve manter os cálculos antigo para projetos com o normativo da instrução normativa anterior.

### Bloco da tipicidade das propostas e seus limites orçamentários
- [x] Ajustar formulário da proposta para cadastramento da Tipicidade e Tipologia da Proposta Cultural
- [x] Adicionar bloco também na adequação à realidade, só deve estar disponível para projetos da IN 2019(idNormativo = 10)
### Atualizar telas de consulta da proposta
- [x] Gerar PDF
- [x] Admissibilidade
- [x] Análise da Adequação à realidade
- [x] Consultar dados do projeto em dados complementares
 
### Custos vinculados:
 - [x] A remuneração para captação fica limitada a 10%(dez por cento) do valor do custo do projeto e ao teto de 100.000,00(cem mil reais) para todos os estados. Aplicar regra apenas para proposta ou projeto IN 2019.

### Assinatura
- [x] Adicionar ao template da assinatura o texto: 
"Documento assinado eletronicamente com fundamento no artigo 73 da instrução normativa nº 02/2019 do Ministério da Cidadania publicado  no Diário Oficial da União na data de 24/04/2019 por:"

### Geral
- [x] No sistema, substituir Rouanet por Lei de Incentivo à Cultura
- [x] No sistema, substituir Ministério da Cultura por Ministério da Cidadania
- [x] Atualizar texto do termo de responsabilidade na criação da proposta

**Comment by clebersantos** [comment]
@romulomb, as seguintes melhorias e alterações já estão disponíveis no ambiente de homologação:
 - Desativação da regra de 90 dias do período de execução
 - Ajustes dos percentuais do detalhamento do plano de distribuição
 - Novo campo para seleção da tipicidade da proposta
 - Novo campo para seleção da tipologia da proposta

**Comment by clebersantos** [comment]
@romulomb todas as tarefas da issue já estão disponíveis no ambiente de homologação.

**Comment by clebersantos** [comment]
@romulomb disponibilizei no ambiente de homologação a atualização das regras para o plano de distribuição, diferenciando a instrução normativa.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**PARABÉNS, FICOU ÓTIMO**
