### ISSUE TITLE
 [Readequações] Proposta de reformulação do front para novo layout - Análise / técnico

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#2067]
Apenas readequações diversas

* [x] Backend: ajustar permissões para permitir edição / visualização pelo técnico e coord de acompanhamento
* [x] Front: ação de avaliar readequação com permissão somente para o técnico
* [x] Front: criar estrutura da página de avaliação
* [x] Front: exibir antes e depois
* [x] Backend: obter avaliação
* [x] Somente técnico que avalia
* [x] Front: criar botão/componente de edição do parecer do técnico (no modelo do parecer inicial)
* [x] Front: validação para finalizar
* [x] Backend: salvar avaliar readequação
* [x] Backend: finalizar / criar assinatura
* [x] Front: redirecionar para assinatura
* [x] Front: criar suporte a listagem de readequações de diferentes Pronac
* [x] Backend: criar suporte a listagem de readequações de diferentes pronacs - migrar backend do painel para técnico de acompanhamento
* [x] Front: Restringir botão de criar readequação
* [x] Front: mapear ações do técnico para implementar no painel
* [x] Front: visualizar análise finalizada / não assinada
* [x] Front: mapear adaptações para coordenador de acompanhamento
* [x] Front: listar abas do coordenador: (aguardando distribuição, em análise, analisados, aguardando publicação)
* [x] Backend: habilitar buscar de painéis do coordenador
* [x] Front: componente "distribuir"
* [x] Backend: componente "distribuir"
* [x] Front: componente "encaminhar"
* [x] Backend: componente "encaminhar"
* [x] Front: listagem em análise deve exibir nome do técnico
* [x] Front: adicionar botão de assinar projeto na lista de analisados
* [x] Front: adicionar botão de visualizar assinatura na lista de analisados
* [x] Front: adicionar mensagem de carregamento de parecerista ao selecionar SAV/SEFIC (distribuir e encaminhar)
* [x] Front: adicionar tratamento visual de acesso negado
* [x] Front: ajustar botão 'visualizar'
* [x] Front: traduzir 'items por página' - 'all'
* [x] Front: remover opção 'rejeitar' na distribuição
* [x] Front: remover coluna 'arquivo'
* [x] Front: aguardando distribuição: adicionar coluna 'qtd dias aguardando distribuição'
* [x] Front: em análise: adicionar coluna 'qtd dias em análise'
* [x] Front: em análise: adicionar coluna 'data de distribuição'
* [x] Front: em análise: adicionar órgão / vinculada - FUNARTE  / Fulano de Tal
* [x] Front: renomear componente 'encaminhar' para  'redistribuir'
* [x] Backend: devolver: preparar 'redistribuir' para invalidar o documento
* [x] Front: analisados - devolver: mesma tela do redistribuir com a pergunta se é para o mesmo técnico primeiro (mantém orientação/observação, mas confdiciona combo de órgão a se for encaminhar para um novo técnico)
* [x] Front: analisados - adicionar - DtEnvio, DtDistribuição, DtDevolução, Total dias para avaliar
* [x] Front: aguardando publicação: manter apenas coluna "visualizar"
* [x] Front: aguardando publicação: remover ação de distribuir
* [x] Backend: obter lista de idDocumentoAssinatura na tela de analisados
* [x] Front: analisados: liberar botão de assinatura
* [x] Front/back: adequar visualização e assinatura por coordenador geral / diretor / secretário
* [x] Front: analisados: verificar se é possível assinar o documento atual
* [x] Front: componente de finalizar ciclo de readequação
* [x] Backend: componente de finalizar
* [x] Front: componente visualizar: ajustar exibição de campos de avaliação - adicionar campos nas buscas de coord análise e coord acompanhamento
* [x] Front: visualizar - ajustar comparação de campos / diff
* [x] Front: aumentar tamanho da comparação planilha
* [x] Front: revisar comportamento do "avaliar" ao gravar e finalizar no técbico / parecerista
* [x] Front/back: impedimento somente para parecerista - siEncaminhamento = 1, dsObservacao = 'texto'
* [x] Front: alterar "vinculada" para "unidade" na tabelaCoordenador
* [x] Front: adicionar menu "avaliar readequações" em análise - diretor e secretário
* [x] Front: painel - conferir diretor e secretário
* [x] Front: adicionar redistribuir para o coord análise
* [x] Front: devolver: técnico / parecerista
* [x] Front: coord - verificar "dias aguardando distribuição" e "dias em análise" vindo null - averiguar cálculo nos painéis
* [x] Front: alterar link para painel do coordenador
* [x] Front: cria visualização de planilha no componente 'visualizar'
* [x] Front: criar redirecionamento de 'readequacao/readequacoes/painel' para '#/readequacao/painel'

Planilha
* [x] Front: se ultrapassar mediana, tarjar e exibir modal da mediana (baseado na análise)
* [x] Front: adicionar técnico / pareceristas na planilha ao gravar (?)
* [x] Front: não pode editar custos vinculados
* [x] Front: justificativa - remover da listagem e quebrar a linha na visualização do item

SAV:
* [x] Front: Pode distribuir sem destinatário
* [x] Front: Cai no painel do coord parecer e pode distribuir para parecerista

Técnico
* [x] Front: técnico: alterar para 'data de recebimento'
* [x] Front: quando volta, painel fica carregando
* [x] Front: ajustar tooltips do painel
* [x] Front: documento anexado
* [x] Front: enviar 'origem' no assinar
* [x] Front/backend: adicionar permissão para parcerista
* [x] Front: criar a visualização de planilha orçamentária
* [x] Front: remover coluna arquivo 
* [x] Front: criar componente para 'declarar impedimento'
* [x] Back: criar compnente para 'declarar impedimento', que irá voltar para perfil do coordenador em aguardando distribuição - siEncaminhamento e tbDistribuirReadequacao - dsOrientacao
* [x] Front: mapear caracteres que geram problemas no diff
* [x] Front: ajustes visuais na assinatura
* [x] Front: alterar link para painel do técnico/parecerista

Coordenador de parecer - vinculada
* [x] Front: Aguardando distribuição - igual ao coord
* [x] Front: Aguardando distribuição - ajustes no componente distribuir
* [x] Front: em análise - igual ao coord
* [x] Front: analisados: liberar botão de assinatura
* [x] Front: analisados: não terá aguardado publicação
* [x] Front: analisados: não vẽ com quem está (se está fora da unidade)
* [x] Backend: verificar query da 'em análise' (atual)
* [x] Front: analisados: ou assina ou manda fazer de novo

Correções / ajustes: erros e ajustes encontrados / reportados durante a homologação (desde 16/09/2019)
* [x] Backend: painel do proponente trazendo projetos errados na aba 'em análise'
* [x] Front: painel do proponente não exibe nome do projeto
* [x] Front: avaliar readequação - quando está carregando, exibe como se não tivesse  visualização disponível
* [x] Backend: gravando parecer técnico com caracteres estranhos na assinatura
* [x] Backend: quando técnico edita planilha, deve setar stCustoPraticado = 0 (pois alteração foi aceita)
* [x] Backend: se o técnico já analisou, gerou documento para assinatura e não assinou, ao gravar uma nova alteração na planilha, o documento anteriormente gerado é invalidado
* [x] Front: devolver ao técnico não vai para órgão correto no caso da SEFIC
* [x] Front: corrige erro de carregamento no visualizar readequação
* [x] Backend: siEncaminhamento não é passado em todas as consultas do painel (aguardando distribuição e aguardando publicação)
* [x] Front: ajustes na visualização / abas
* [x] Front: visualização: corrige erro no redirecionamento
* [x] Front: planilha - corrige erro no carregamento
* [x] Front: corrige erro ao devolver parecer ao parecerista
* [x] Front: erro ao visualizar mediana
* [x] Front: redistribuir - corrige carregamento de destinatários
* [x] Front: adiciona bloco informações sobre a localização da solicitação no redistribuir
* [x] Front: restringe botão de visualizar readequação para proponente
* [x] Front: adiciona legenda no campo diff
* [x] Front: remove botão salvar das telas de movimentação da solicitação
* [x] Front: painel: corrige exibição de data
* [x] Front: painel: adiciona link do projeto
* [x] Backend: lista de pareceristas vindo vazia na SAV
* [x] Front: planilha orçamentária - não exibir dados relacionados com a mediana para os itens de custos vinculados
* [x] Front: visualizar readequação - verificar exibição de dados de avaliação
* [x] Backend: redistribuição - não grava na tabela tbDistribuirReadequacao
* [x] Front: redistribuição mandando para órgão 166 quando deveria ser 160 (SAV coordenador)
* [x] Backend: ajustar documento assinatura
* [x] Front: padronizar botão de finalizar de acordo com parecer
* [x] Backend: readequação si 26 não pode aparecer no painel do presidente
* [x] Front: distribuir readequação na SAV - adicionar SAV e SAV/CAP
* [x] Front: proponente - exibição do finalizar somente depois que entra na edição da readequação
* [x] Backend: remover painel antigo
* [x] Backend: alterar links do antigo
* [x] Front: painel do proponente - finalizar pegando dados de modal aberta antes
* [x] Backend: readequação planilha - não permitir que proponente adicione item de custos vinculados e remuneração para captação
* [x] Front: distribuição não envia em alguns casos - algu erro no refresh
* [x] Front: avaliação - parecer deve vir já anotado como favorável na análise por padrão
* [x] Backend: não está distribuindo corretamente projetos da vinculada/coord parecer
* [x] Front: redistribuir readequação - se for o órgão atual, abre caixa de destinatários
* [x] Backend: assinatura gerando inválida quando finaliza direto (avaliação não salva)
* [x] Backend: menu liberando readequações no E24 (bug)
* [x] Front: adiciona visualização para saldo de aplicação
* [x] Backend: corrige painel para exibir corretamente no painel do coord geral as análises feitas por pareceristas

**Comment by romulomb** [comment]
**HOMOLOGADO**

**PARABÉNS FICOU ESPETACULAR**

**SUBIR PARA PRODUÇÃO POR GENTILEZA**
