### ISSUE TITLE
[Proposta] Alteração no orçamento do projeto - Custos Vinculados

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#207]
[7.1.1.3]
História: eu como proponente, gostaria de definir os percentuais dos Custos Vinculados e Remuneração para Captação de acordo com a Nova IN.

**Checklist**
- [x] Atualizar o nome da página para “Custos Vinculados/Remuneração”
- [x] Vão ser retirados Direitos autorais e Controle e Auditoria (Controle e Auditoria estava cadastrado no banco de desenvolvimento)

**Atualização dos cálculos dos Custos Vinculados**

- [x] Custos de administração,  Até 15% sobre o valor do projeto (pré-produção, produção e pós-produção)

**Custos de divulgação**
 - [x]  Valor do projeto de até 300mil pode ter até 30%
 - [x]  Valor do projeto de mais de 300mil até 20%
 

**Remuneração para captação**
~~- [ ] Remover da visualização: O item "Remuneração para captação" dos custos vinculados atual, será migrado para uma nova ETAPA que ainda será definida.~~

**Regras para o item “Remuneração para captação”:**

 - [x]   Valor de até 10% e limite máximo de 150mil sobre o valor total do custo do projeto(pré-produção, produção, pós-produção e custos vinculados. Art 8, parágrafo 1);
  **Exceções**
  - [x]    O valor máximo do item para as regiões Norte, Nordeste e Centro-oeste será ampliado para até 150 mil + 15% do valor total do custo do projeto
  - [x]  O valor máximo do item para a região Sul e para os estados do Espirito Santo e Minas Gerais será ampliado para até 150 mil + 12.5% do valor total do custo do projeto

 - [x] Deverão ser feito ajustes no banco para a nova ETAPA, atualmente o item está na etapa Custos Vinculados

**Demais Tarefas**
- [x] Alterar texto "Custos Vinculados" para "Custos Vinculados e Remuneração" no Cadastro de Produtos no menu Orçamento do Projeto.
- [x]  Verificar se existem itens dos Custos Vinculados antigos e excluir ao salvar o novo.
- [x] No Formulário Custo Vinculados / Remuneração aparece o botão salvar quando não existe Local de Realização cadastro.
- [x] Atualizar "Valor do Projeto" no Resumo da Planilha que fica no Cadastro de Produtos no menu Orçamento do Projeto.
- [x] Criar teste inicial
- [x] Alterar o nome Valor Custo do Projeto para Custo Total (Custo do Projeto + Valores de outras leis + Valores de outras fontes)
- [x] Destacar Valor do Projeto e Custo Total no Cadastro de Custos por Produto.
~~- [] Adicionar Outras Fontes no Resumo da Planilha em Cadastrar Custos por Produto.~~ Outra issue.
- [x] Alterar Valor do Projeto para Custo Total (Custo do Projeto + Valores de outras leis + Valores de outras fontes) na Planilha Orçamentária Geral da Proposta.
- [ ] Ajustar a regra do UF e Munícipio para Projetos integralmente executados

**Comment by chris-redfield** [comment]
Controle e Auditoria e remuneração para captação não estão mais nos custos vinculados

**Comment by clebersantos** [comment]
## Custos Vinculados
Atualizar o nome da página para “Custos Vinculados/Remuneração”
Atualização dos cálculos dos Custos Vinculados

-Atualmente teremos apenas dois itens, que são:
* Custos de administração 
  + Até 15% sobre o valor do projeto (pré-produção, produção e pós-produção)

* Custos de divulgação 
  + Valor do projeto de até 300mil pode ter até 30% 
  + Valor do projeto de mais de 300mil até 20%
  + Exceções	
    - Não há

O item "Remuneração para captação" dos custos vinculados atual, será migrado para uma nova ETAPA que ainda será definida.
Regras para o item “Remuneração para captação”:
- Valor de até 10%(proponente pode definir o percentual) e limite máximo de 150mil sobre o valor total do custo do projeto(pré-produção, produção, pós-produção e custos vinculados. Art 8, parágrafo 1);
- Exceções
 * O valor máximo do item para as regiões Norte, Nordeste e Centro-oeste será ampliado para até 150 mil + 15% do valor total do custo do projeto
 * O valor máximo do item para a região Sul e para os estados do Espirito Santo e Minas Gerais será ampliado para até 150 mil + 12.5% do valor total do custo do projeto

Deverão ser feito ajustes no banco para a nova ETAPA, atualmente o item está na etapa Custos Vinculados

**Comment by clebersantos** [comment]
@romulomb, o valor do projeto(pré-produção, produção e pós-produção) é apenas para a Fonte de Recurso de Incentivo Fiscal?

**Comment by clebersantos** [comment]
> Seção II
 Do Regramento dos Projetos Culturais
Art. 6º Os percentuais das etapas de Custos Vinculados (Anexo I) serão calculados sobre o Valor do Projeto (Anexo I), e detalhadamente comprovados quando de suas execuções, equivalendo ao somatório das seguintes etapas:
I - pré-produção;
II - produção;
III - pós-produção;
IV - recolhimentos; e
V - assessoria contábil e jurídica.
§ 1º São considerados custos vinculados para fins deste artigo:
a) custos de administração; e
b) custos de divulgação.
§ 2º É obrigatória a contratação de contador com o registro no conselho de classe para a execução de todos os projetos, podendo o proponente utilizar o profissional de sua empresa.
§ 3º É obrigatória a previsão de serviços advocatícios para todos os projetos, ainda que posteriormente o item não venha a ser executado.
Art. 7º O projeto que simultaneamente contenha ações contempladas pelos artigos 18 e 26 da Lei nº 8.313, de 1991, será enquadrado em apenas um dos dispositivos, de acordo com o produto principal do projeto, nos termos do Anexo IV.
Art. 8º Os valores admitidos para remuneração para todo aquele que realize a captação de recursos ficam limitados a 10% (dez por cento) do valor do Custo do Projeto (Anexo I) e ao teto de R$ 150.000,00 (cento e cinquenta mil reais).
§ 1º Para projetos a serem integralmente executados nas Regiões Norte, Nordeste ou Centro-Oeste, o percentual previsto no caput será ampliado a 15% (quinze por cento) do valor do Custo do Projeto (Anexo I) e 12,5% (doze e meio por cento) para a Região Sul e para os estados de Espírito Santo e Minas Gerais.
§ 2º Os valores destinados à remuneração para captação de recursos somente poderão ser pagos proporcionalmente às parcelas já captadas.
Art. 9º Os custos de divulgação não poderão ultrapassar 30% (trinta por cento) do Valor do Projeto de até R$ 300.000,00 (trezentos mil reais) e não poderão ultrapassar 20% (vinte por cento) para os demais projetos.
Art. 10. Os custos administrativos não poderão ultrapassar o limite de 15% (quinze por cento) do Valor do Projeto (Anexo I), sendo admitidas como despesas de administração para os fins do Decreto nº 5.761, de 2006:

**Comment by clebersantos** [comment]
É necessário alterar o campo `pcCalculo` da tabela `tbCustosVinculados` para float, para que os 12.5% da região SUL e estados MG e ES sejam aceitos. by @guiamado

**Comment by clebersantos** [comment]
## Criando nova etapa para Remuneração para captação de Recursos. 
Insert para criar nova Etapa
```
INSERT INTO sac.dbo.tbPlanilhaEtapa (Descricao,tpCusto,stEstado,tpGrupo,nrOrdenacao)
VALUES ('Remuneração de Captação de Recursos','A',1,'D',7) go
```
Atualiza o item "Remuneração para captação de recursos" para a Etapa criada anteriormente (id=10)
```
UPDATE sac.dbo.tbItensPlanilhaProduto
SET idPlanilhaEtapa=10
WHERE idProduto=0 AND idPlanilhaEtapa=8 AND idPlanilhaItens=5249 go
```
 @romulomb, existe algum impacto nesta atualização do item de remuneração? O nome da Etapa já foi definido?

Outra opção é criar mais um item, mas aparecerá duplicado nos Custos Vinculados e Remuneração
```
INSERT INTO sac.dbo.tbItensPlanilhaProduto (idProduto,idPlanilhaEtapa,idPlanilhaItens)
VALUES (0,10,5249) go
```
Pair Programming com @wouerner.

**Comment by chris-redfield** [comment]
Custos Vinculados - Divulgação - Se ultrapassar o valor (300.000,00) deve registrar na tbCustosVinculados.

**Comment by chris-redfield** [comment]
Para cálculo dos cultos vinculados deverá pegar o UF e Município com o menor percentual dentro do Local de Realização.

**Comment by chris-redfield** [comment]
Alterar o nome Valor Custo do Projeto para Custo Total (Custo do Projeto + Valores de outras leis + Valores de outras fontes)
Destacar Valor do Projeto e Custo Total no Cadastro de Custos por Produto.
Adicionar Outras Fontes no Resumo da Planilha em Cadastrar Custos por Produto.

**Comment by clebersantos** [comment]
A Coordenação de Admissiblidade ficou responsável por definir o termo `Projetos integralmente executados' do § 1, art. 8.

**Comment by boletocosta** [comment]
Exemplos:

projeto integralmente realizado na região sul =  qualquer produto realizado em alguma cidade fora dessa região não pode ter despesas na etapa de produção.    

projeto integralmente realizado na região sul =  qualquer produto que tenha despesa na etapa de produção deve ser realizado em uma cidade da região sul.
 São duas definições que dizem a mesma coisa, mas de maneira inversa... deu para entender?
 Acho que pela segunda definição da para entender melhor..

**Comment by clebersantos** [comment]
Conforme conversa com André(@boletocosta), a definição sobre projeto integralmente executado ainda está em definição. Gerando um impedimento para concluir essa atividade.

**Comment by boletocosta** [comment]
Segue a definição (é aquela primeira definição que tínhamos passado.. ou seja, não envolve mais a planilha orçamentária..):  Projetos “integralmente executados” significa que a disponibilização do(s) produto(s) cultural(is) deve se dar estritamente nas Regiões beneficiadas.

MUITO IMPORTANTE:  a verificação se dará por intermédio do Detalhamento do Plano de Distribuição: 
        -as localidades que estiverem SEM DADOS não contam para a métrica;
        -contam portanto as localidades que apresentarem detalhamento de produtos culturais a serem ofertados/comercializados, e
        -havendo pluralidade de regiões prevalece a de menor percentual.

EXEMPLO PARA ENTENDER MELHOR:
No local de realização o proponente cadastrou 4 cidades: salvador, floripa, são paulo e rio. Esse cadastro ainda não interfere na métrica. Agora vamos as hipóteses de preenchimento no plano de distribuição (que definirão o percentual):

Hipótese 1) Detalhou rio ou são paulo (inseriu produtos em qualquer uma dessas cidades) prevalece o menor percentual (10%) para todo projeto (independente se ele detalhou salvador ou floripa)

Hipótese 2) Detalhou apenas salvador (inseriu produto apenas nessa cidade) prevalece o percentual maior (15%) para todo projeto

Hipótese 3) Detalhou apenas floripa (inseriu produto apenas nessa cidade)  prevalece o percentual de 12,5 % para todo projeto.

Hipótese 4) Detalhou salvador e floripa apenas (inseriu produtos apenas nessas duas cidades) prevalece o menor percentual (12,5%) para todo projeto.

**Comment by clebersantos** [comment]
@boletocosta Entendido. Estou desenvolvendo o controle das alterações na Diligência, provavelmente essa alteração pode gerar atraso na entrega de amanhã. Qual a prioridade para amanhã à tarde? Custos Vinculados ou Contronle das Alterações na Diligência?

**Comment by boletocosta** [comment]
Custos Vinculados

**Comment by guiamado** [comment]
@boletocosta A funcionalidade está disponível para Teste

**Comment by boletocosta** [comment]
Perfeito. Pode mover o card para Feito.

**Comment by clebersantos** [comment]
Quando não tiver detalhamento, deve manter o padrão 10%.

**Comment by AdmissibilidadeSAV** [comment]
Na SAV achamos melhor deixar do jeito que está por enquanto para avaliarmos com calma caso a caso que surgirá para pensarmos numa maneira mais eficaz de como deverá ser esse regramento para projetos de produção audiovisual. 

Sendo assim, sugiro que mova o cartão para feito.

**Comment by clebersantos** [comment]
Custos Vinculados atualizado! Por padrão o sistema selecionado o percentual mais baixo caso o usuário não detalhe o Plano de Distribuição.
