### ISSUE TITLE
[Avaliação de Resultados] Projetos da SAV no painel da SEFIC no Laudo Final

### ISSUE THREAD

**Issue by volthier** [culturagovbr/salic-minc#2078]
Ao entrar na fase de Avaliação para gerar Laudo Final ambas as área SEFIC/SAV estão aparecendo sem distinção.

Imagem do erro:

![photo_2019-05-14_08-11-31.jpg](https://images.zenhubusercontent.com/5a68701f4b5806bc2bc417c4/52e841de-d411-4ffd-ac97-73652ee0a17f)

**Comment by volthier** [comment]
Correção implementada em ambiente de Homologação para validação.

@romulomb

**Comment by romulomb** [comment]
**HOMOLOGADO**
