### ISSUE TITLE
[Diligência] Destacar os campos que foram modificados pelo proponente

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#208]
Eu como **avaliador de propostas** gostaria de :  
- Que os (textos/campos) que forem modificados em uma diligência pelo proponente voltem com o seguinte comportamento: 
  - Para textos (adicionados/alterados) eles vem com plano de fundo verde
  - Para textos removidos eles vem com plano de fundo vermelho 
  - A referência padrão de identificação de uma alteração é o número da linha
 
* Versionar apenas a última versão da proposta. 

url de modificação: http://hmg.salic.cultura.gov.br/analise/analise/visualizarprojeto?idpronac=204078

obs 1 : Usar o github como modelo de cores
obs 2: Nesse sprint o escopo esta delimitado a apenas a mostrar os macros itens que tiverem alterações.

**Comment by chris-redfield** [comment]
levantamos agora que de fato essa funcionalidade será só no projeto, pois na proposta nao haverá mais essa diligencia, na proposta será avaliado so enquadramento e natureza cultural

**Comment by chris-redfield** [comment]
no retorno ao analista, evidenciar o que foi modificado pelo proponente

**Comment by chris-redfield** [comment]
conplexidade altissima pois foi solicitado guardar o historico das alterações

**Comment by fernao** [comment]
Fluxo para implementação
1) Técnico cria diligência
2) Proponente altera campos      <----  campos "versionados"
3) Técnico quer saber o que foi mudado   <---- visualização das diferenças entre as duas versões
4) Técnico pode realizar novas diligências. Ao criar uma nova, aceita nova versão do proponente como atual. Volta para o 2)

**Comment by clebersantos** [comment]
Teste de comentário

**Comment by boletocosta** [comment]
* Na tela Análise de alterações da Proposta o botão voltar não funciona! 

*  Eu sei que a questão mais profunda da mudança das cores na alteração de todos os textos ficou para outra sprint,  mas seria muito pedir nessa sprint que apenas os "macro campos" (Proponente, Ficha técnica, Resumo, Objetivos ...... até Planilha orçamentária) que sofreram alguma alteração viessem sinalizados de alguma forma? Assim o técnico expandiria somente aquele "macro campo" para fazer a análise.       Deu para entender?

De resto tudo certo.

**Comment by boletocosta** [comment]
Tudo certo. Apenas com esse erro:  Na tela de Análise de alterações da Proposta (aquela que compara o que foi alterado pelo proponente) não aparece o campo democratização de acesso (era para aparecer) e o campo impacto ambiental está aparecendo (não era para aparecer)
