### ISSUE TITLE
Regra para permitir comprovação acima do aprovado.

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#2080]
![photo_2019-05-14_10-06-06](https://user-images.githubusercontent.com/287287/57700259-f657cb00-762f-11e9-9e51-78b258dffc6a.jpg)

reportado por @romulomb

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
