### ISSUE TITLE
[Homologação] Alterar unidade do projeto ao finalizar assinatura de projeto indeferido

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2084]

**Comment by romulomb** [comment]
### PROJETO INDEFERIDO NA HOMOLOGAÇÃO

**Quando tiver captação enviar para**:
272 no caso de projeto da SEFIC e 166 no caso de projeto da SAV..

**Sem captação**
262 no caso de projeto da SEFIC e 171no caso de projeto da SAV
