### ISSUE TITLE
[Dados do Projeto] Corrigir máscara da conta corrente

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2088]
Como proponente, ao visualizar os dados de um projeto com uma conta corrente que possui 8 dígitos, o sistema apresenta apenas os 6 primeiros caracteres. Conforme imagem abaixo.

![2019-05-20 10 16 15](https://user-images.githubusercontent.com/2494751/58024353-5ba43400-7ae8-11e9-8d1a-70ac9eb4dd29.jpg)

Reportado pelo @romulomb.

**Comment by clebersantos** [comment]
@clebersantos Disponível no ambiente de homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
