### ISSUE TITLE
[Relatórios] Consultar projeto cultural

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2089]
Como perfil interno do sistema(Técnicos ou Coordenadores), ao acessar o menu principal Relatórios -> Projetos, depois de escolher a UF o sistema não disponibiliza os municípios para seleção. Conforme imagem abaixo.

![2019-05-20 10 18 00](https://user-images.githubusercontent.com/2494751/58024662-19c7bd80-7ae9-11e9-91c3-4e96894cb495.jpg)

Reportado pelo @romulomb

**Comment by clebersantos** [comment]
@clebersantos Disponível no ambiente de homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
