### ISSUE TITLE
[Proposta] Dar visibilidade ao proponente do resultado da avaliação da proposta

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#209]
**Historia:**
Eu como **proponente** ao ter minha proposta avaliada pelo **coordenador de admissibilidade** gostaria de: 
- Receber um email informando que minha proposta foi avaliada com o status da avaliação
- Caso minha proposta seja **arquivada ou indeferida**, gostaria de visualizar pelo sistema 
- independente do status da minha proposta gostaria de poder abri-la 

Eu como **coordenador de admissibilidade** gostaria de arquivar as propostas culturais segundo os criterios da nova IN.

**Regras:**
para ter essa funcionalidades precisa fazer: 
- Reajustar msg de email (área de negócio)
- armazenar o motivo de arquivamento
- criação de um filtro para mostrar as propostas arquivadas / indeferidas

**Observação:**
 Comentado o trecho abaixo - jogado para issue #289

**Checklist**
- [x] Arquivar propostas, colocando data(dtArquivamento) e estado da proposta (stestado)
- [x]  listagem para proponente visualizar propostas arquivadas.
- [x]  Enviar E-mail para proponente ao arquivar.
- [ ]  Mensagem do E-mail.

**Branch:** [feature-visualizacao-proponente](https://github.com/culturagovbr/salic-minc/tree/feature-visualizacao-proponente) 

~~Eu como **coordenador de admissibilidade** gostaria de ter a funcionalidade de avaliação de proposta com as seguintes características:~~
 
~~- Visualizar a proposta com o parecer do tecnico de admissibilidade. ~~
~~ - Emitir o parecer, com as seguintes possibilidades [Aceito, Arquivar , Desarquivar]~~

~~A Mesma proposta pode ser avaliada 3x~~

**Comment by fernao** [comment]
0) Definir tabela para motivo de arquivamento de proposta
1) Coordenador de admissibilidade arquiva proposta
2) Disparo de email para proponente com motivo (trocar texto)
3) Proponente pode visualizar propostas arquivadas

**Comment by fernao** [comment]
Definição preliminar da tabela que armazenará o motivo do arquivamento da proposta.

CREATE TABLE sac.dbo.PreProjetoArquivado (
	idPropostaArquivada int NOT NULL IDENTITY(1,1),
	idPreProjeto int NOT NULL,
	MotivoArquivamento varchar(MAX),
	SolicitacaoDesarquivamento varchar(MAX),
	Avaliacao varchar(MAX),
	idAvaliador int NOT NULL,
	dtArquivamento datetime,
	dtSolicitacaoDesarquivamento datetime,
	dtAvaliacao datetime,
	stEstado int,
	stDecisao int
) go

**Comment by marcusvinicus** [comment]
Falta padrão de e-mail
mostrar o proponente o motivo de arquivamento.

**Comment by boletocosta** [comment]
Detalhes sobre o e-mail padrão:

Assunto: Proposta arquivada

Texto:

Sr(a) Proponente,

Informa-se que a proposta nº X foi arquivada no exame preliminar de admissibilidade pelo seguinte motivo: 

****Texto gravado na Justificativa no momento do arquivamento****

O proponente pode pedir o desarquivamento da proposta via sistema acessando a listagem das propostas arquivadas e clicando no botão "solicitar desarquivamento". O pedido deve ser motivado, ou seja, conter as justificativas necessárias para o desarquivamento.

Se o pedido for aceito a proposta será desarquivada e o proponente receberá uma nova diligência. 

Se o pedido for negado o proponente poderá solicitar o desarquivamento via sistema pela segunda vez, desde que apresente novos elementos na motivação. Se o pedido de desarquivamento for negado pela segunda vez o proponente não poderá mais desarquivar a proposta.

Dúvidas: proposta.incentivo@cultura.gov.br ou http://rouanet.cultura.gov.br/.

Atenciosamente,
Coordenação de Admissibilidade de Propostas.

**Comment by boletocosta** [comment]
Quando o proponente acessar a proposta na listagem das arquivadas a ideia é que esse texto que foi envaido por e-mail apareça em destaque (pensei em aparecer primeiro .. acima dos outros campos).

**Comment by AdmissibilidadeSAV** [comment]
Em relação ao texto padrão como tem propostas analisadas pela SEFIC e SAV, na minha opinião fica melhor o coordenador inserir na justificativa do arquivamento como fosse um comunicado direto ao proponente e o sistema envia o conteúdo desse comunicado.

Exemplo:

Assunto: Arquivamento de proposta cultural

Proposta: Número - Título da proposta
Proponente: XYXY

**** Texto gravado na Justificativa no momento do arquivamento ****

**Comment by boletocosta** [comment]
Por mim pode ser.

**Comment by boletocosta** [comment]
Tendo em vista que o texto que será enviado pelo e-mail será o mesmo gravado na justificativa do arquivamento, segue a atualização do texto que será gravado na justificativa para o arquivamento:

Sr(a) Proponente,

Informa-se que a proposta nº X foi arquivada no exame preliminar de admissibilidade pelo seguinte motivo: 

*Motivo do arquivamento*

O proponente pode pedir o desarquivamento da proposta uma única vez acessando a listagem das propostas arquivadas e clicando no botão "solicitar desarquivamento". O pedido deve ser motivado, ou seja, conter as justificativas necessárias para o desarquivamento.

**Comment by wouerner** [comment]
Mensagem adicionada.
