### ISSUE TITLE
[Avaliação de Resultados] Projetos da SAV no painel da SEFIC no Comprovação Financeira

### ISSUE THREAD

**Issue by volthier** [culturagovbr/salic-minc#2091]
Correção na Comprovação Financeira

![photo_2019-05-20_14-13-33.jpg](https://images.zenhubusercontent.com/5a68701f4b5806bc2bc417c4/ee2cfc8c-aff3-441d-90d6-e28ad6fe75e0)

**Comment by volthier** [comment]
Conforme requisitado, a correção esta implementada para avaliação em ambiente de homologação.

@romulomb

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
