### ISSUE TITLE
[Dados Projeto] Erro ao consultar projetos sem contas movimentação e bloqueada

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2101]
Como técnico do sistema ao consultar um projeto sem conta movimentação e bloqueada, o sistema não exibe os dados. Conforme imagem abaixo.

![photo_2019-05-22_09-23-14](https://user-images.githubusercontent.com/2494751/58180406-701b3480-7c80-11e9-8f7b-d8324032e67d.jpg)

Reportado pelo @romulomb

**Comment by clebersantos** [comment]
Disponível no ambiente de homologação.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**

**Comment by thevirtualkleber** [comment]
Estou com este mesmo problema atualmente.
