### ISSUE TITLE
[ANALISE TECNICA] Refatoração dos painéis do Coordenador de Parecer

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2109]
## Migração dos painéis
- [x] Aguardando distribuição
- [x] Em análise
- [x] Em validação
- [x] Validados
- [x] Devolvidos
- [x] Com impedimento do parecerista

## Ações
 - [x] Mostrar lista com o histórico de avaliações
 - [x] Visualização dos detalhes da avaliação
 - [x] Criar distribuição da análise para um parecerista
 - [x] Criar encaminhamento da análise para um parecerista 
 - [x] Criar redistribuição da análise para um parecerista 
 - [x] Criar validação da avaliação
 - [x] Criar finalização da análise e assinatura do parecer técnico 

## Filtro
 - [x] Filtrar produtos por situação
 - [x] Permitir o filtro por PRONAC, nome do projeto e segmento

## Assinatura
 - Ao devolver
    - [x] inabilitar o documento
    - [x] fechar analise para o coordenador

Views montadas para os paineis:
### PAINEL - AGUARDANDO DISTRIBUIÇÃO PARA ANÁLISE
```
SELECT 
IdPronac, 
NrProjeto, 
NomeProjeto, 
idProduto, 
Produto,
 stPrincipal, 
idArea,
 Area,
 idSegmento, 
Segmento, 
idDistribuirParecer,
idOrgao,
idOrgaoOrigem,
FecharAnalise,
DtEnvioMincVinculada,
qtDiasDistribuir,
QtdeSecundarios,
Valor,
siAnalise,
siEncaminhamento
FROM sac.dbo.vwPainelAguardandoDistribuicaoAnaliseTecnica
```
### PAINEL - EM VALIDAÇÃO PELO COORDENADOR
```
SELECT 
IdPRONAC,
NrProjeto,
NomeProjeto,
idProduto,
Produto,
idArea,
Area,
idSegmento,
Segmento,
idDistribuirParecer,
Parecerista,
idOrgao,
idOrgaoOrigem,
siAnalise,
siEncaminhamento, DtEnvioMincVinculada,
DtDistribuicao,
DtDevolucao,
TempoTotalAnalise,
TempoParecerista,
TempoDiligencia,
qtDiligenciaProduto,
Valor,
Obs,
TecnicoValidador,
dtValidacao,
stPrincipal,
FecharAnalise
FROM sac.dbo.vwPainelEmValidacao
```
### PAINEL - VALIDADOS PELO COORDENADOR
```
SELECT 
IdPRONAC,
NrProjeto,
NomeProjeto,
idProduto,
Produto,
idArea,
Area,
idSegmento,
Segmento,
idDistribuirParecer,
Parecerista,
idOrgao,
idOrgaoOrigem,
siAnalise,
siEncaminhamento,
DtEnvioMincVinculada,
DtDistribuicao,
DtDevolucao,
TempoTotalAnalise,
TempoParecerista,
TempoDiligencia,
qtDiligenciaProduto,
Valor,
Obs,
stPrincipal,
FecharAnalise,
TecnicoValidador,
dtValidacao 
FROM sac.dbo.vwPainelValidados
```
### VALIDADOS PELO COORDENADOR COM DEVOLUÇÃO PARA A VINCULADA RESPONSÁVEL

```
SELECT
IdPRONAC,
NrProjeto,
NomeProjeto,
idProduto,
Produto,
idArea,
Area,
idSegmento,
Segmento,
idDistribuirParecer,
Parecerista,
idOrgao,
idOrgaoOrigem,
siAnalise,
siEncaminhamento,
DtEnvioMincVinculada,
DtDistribuicao,
DtDevolucao,
TempoTotalAnalise,
TempoParecerista,
TempoDiligencia,
qtDiligenciaProduto,
Valor,
Obs,
stPrincipal,
FecharAnalise,
TecnicoValidador,
dtValidacao
FROM sac.dbo.vwPainelValidadosComDevolucao
WHERE idOrgao = 92
```

**Comment by clebersantos** [comment]
Regras na visualização dos paines
```
### siAnalise
0. Aguardando Distribuição para o parecerista (Coordenador de Parecer)
1. Em análise pelo parecerista (Parecerista)
2. Analisado pelo parecerista  (Parecerista)
3. Finalizado análise técnica  (Parecerista)
4. Em validação pelo coordenador (Coordenador de Parecer)
5. Validados pelo coordenador (Coordenador de Parecer)

### siEncaminhamento
3  Solicitação encaminhada a  unidade de análise pelo MinC
4  Solicitação encaminhada ao parecerista /  técnico
5  Solicitação devolvida ao coordenador da unidade de análise pelo parecerista
```

**Comment by AdmissibilidadeSAV** [comment]
No menu Análise => Gerenciar pareceres, no painel **Em Validação**
Ao visualizar a análise não está aparecendo a Consolidação do Parecer, somente a análise de conteúdo e de custo, só sendo possível verificar o texto da Consolidação depois da validação do parecer no documento para assinatura.

É necessário que essa informação esteja disponível na tela de visualização da análise de conteúdo e de custos.

http://hmg.salic.cultura.gov.br/#/parecer/gerenciar/produto/19/221865/1

![image](https://user-images.githubusercontent.com/35490669/61959567-1134ad00-af9a-11e9-8539-6c02f195dc3d.png)
****
Ainda no painel **Em validação** na coluna Ações preciso que diferencie os ícones dos produtos secundários do principal. No produto principal poderá permanecer na descrição "Visualizar produto e assinar documento", porém no produto secundário a descrição da ação deverá ser alterada para  "Visualizar produto e validar análise".

**Comment by romulomb** [comment]
**EM VALIDAÇÃO**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3249393e-e93c-417c-9326-6ad3df32f8e5)

-------------------------------------------------------------------------------------------------------------

**VALIDADOS**
Nesse painel também necessita da ações de devolver para o parecerista refazer a análise.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a83ca8e1-2315-4d68-942f-86aa65122773)

-------------------------------------------------------------------------------------------------------------

**DEVOLVIDOS**
Quando a SECULT devolve o projeto para a unidade vinculada o projeto não aparece em nenhum painel.  O correto seria aparecer no painel de Devolvidos.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/9e4a8d13-b925-43e2-8bc7-c5d31bef8a1f)

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/0cd4b593-3ccf-4ee6-9704-f2987a81fcfa)

-----------------------------------------------------------------------------------------------------------
**FUNCIONALIDADE DE ENCAMINHAR  PARA OUTRA VINCULADA COM VOLTA**
Implementar a possibilidade de enviar o projeto para outra unidade de análise e após a validação da análise pelo coordenador essa análise deverá retornar automaticamente a vinculada original.
O documento deverá ser gerado e assinado na vinculada encaminhadora.

**Comment by clebersantos** [comment]
@romulomb, disponibilizei no ambiente de homologação os seguintes itens:
 - Consolidação de parecer: o texto foi adicionado na tela de visualização da análise de conteúdo e de custos.
 - Painel em validação: diferenciar os ícones dos produtos secundários do principal. 
 - Painel em validação e painel validados: nova funcionalidade para o coordenador de parecer solicitar a reanálise do produto. Ao devolver, quando é produto principal, o sistema inabilita o documento assinado pelo parecerista.

Estou com impedimento para as atividades abaixo, pois é necessário melhor detalhamento dos fluxos.
- Devolvidos: quando a secult devolve o projeto para a unidade vinculada
- Funcionalidade de encaminhar para outra vinculada com volta
- Alterar o modelo de assinatura de documento

**Comment by clebersantos** [comment]
**Detalhamento**
No painel de "Devolvidos (SECULT)" ao clicar no botão concluir o sistema deverá abrir opção para o Coordenador de Parecer digitar o motivo da não aceitação de reanálise(gravar no histórico e fecharAnalise = 2, tipoAnalise  = 3) ou poderá distribuir para análise do parecerista(distribuir, encaminhar e devolver para o mesmo parecerista).

**Comment by clebersantos** [comment]
@romulomb, disponibilizei no ambiente de homologação o novo painel com os projetos devolvidos pela Secult, com as opções:
  - Distribuir/Encaminhar Produto
  - Devolver para Secult
  - Devolver para reanálise do parecerista
  - Visualizar histórico 


Faltam apenas os painéis que tratarão a funcionalidade de "encaminhar para outra vinculada com volta", tendo em vista que será necessário melhor detalhamento das regras de negócio.

**Comment by romulomb** [comment]
### AJUSTES

#### PERFIL COORDENADOR DE PARECER

**1. Não permite visualizar a análise do produtos (Em todos paineis )**

PASSO - 1
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/db972723-20a4-4255-9875-911d222ab777)

PASSO - 2
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/048e6627-20df-457a-aa0c-4c3b1b4412ac)

**2. A data de envio está incorreta e o painel também não mostra a quantidade de dias que o produto está com o parecerista.**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2e15423b-0338-4215-b663-044e82a18372)

**Comment by clebersantos** [comment]
@romulomb ajustes disponíveis no ambiente de homologação.

**Comment by romulomb** [comment]
### AJUSTES

#### PERFIL DO COORDENADOR DE PARECER

##### PAINEL ASSINAR

O coordenador não consegue devolver o projeto para  técnico reavaliar o parecer emitido.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f3711eda-4830-4b2e-a125-1c3b136d7499)

**Comment by romulomb** [comment]
**HOMOLOGADA**

**NÃO SUBIR para produção porque a nova funcionalidade está provocando algumas inconsistência na readequação.**

**Somente após os ajustes na readequação e que poderá ser executada a promoção para a produção.**
