### ISSUE TITLE
Readequações - Erro ao gravar data - período de execução

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#2114]
* [ ] correção na visualização do diff: não está formatando
* [x] alteração de proponente: Permitir somente números, sem traço, ponto ou barra.
* [x] alteração de período de execução: Gravação da data com formato incorreto, formato correto é dd/mm/aaaa.
* [ ] Quando compara a versão original com a versão alterada, caracteres estranhos (?) substituem
    por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

**Comment by fernao** [comment]
Disponível para homologação

**Comment by romulomb** [comment]
**Readequação - Alteração de Razão Social**

1. Não anexou o documento;
2. Não gravou a versão readequada;
3. Não exibe a mensagem após clicar no botão salvar.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6312288-4d83-46a7-b80e-d7a01500cf31)

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/cc0286e7-ae70-4e2a-bf71-0de0eabdc084)

**Readequação - Agência Bancária**

1. Não anexou o documento;

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2b920111-1920-4557-9a89-57d80d7bb609)

**Readequação - Sinópse da Obra**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6b9b838a-dc77-4219-8491-3cb710424fb7)


**Readequação - Impacto Ambiental**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3b389c07-ebd5-4f8c-a92f-980ca5f971cb)


**Readequação - Especificação Técnica**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/7f6c40d2-2eac-4e1b-a0d7-fc7c17bc926c)

**Readequação - Estratégia de Execução**

1. Não anexou o documento;


**Readequação - Alteração de Proponente**

1. Não anexou o documento;
2. Permitir **somente números**, sem traço, ponto ou barra.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/214e0252-a3ee-4638-a47b-84e1528af305)

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/10a93893-4272-48d6-81c6-2a49417d9991)

**Readequação - Nome do Projeto**

1. Não anexou o documento;

**Readequação - Período de Execução**

1. Não anexou o documento;
2. Gravação da data com formato incorreto, formato correto é dd/mm/aaaa.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a7da9b86-a5cd-42f8-aa4b-8680ec11d497)


**Readequação - Resumo do Projeto**

1. Não anexou o documento;

**Readequação - Objetivos**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/7ce82d2a-c37d-4ccb-8145-ff5cffa0af0b)

**Readequação - Justificativa**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

**Readequação - Acessibilidade**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

**Readequação - Democratização de Acesso**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

**Readequação - Etapas de Trabalho**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/5399311d-3aaa-4626-9f60-7d3b80570bd7)

**Readequação - Ficha Técnica**

1. Não anexou o documento;
2. Quando compara a versão original com a versão alterada, os dois campos na **VISUALIZAÇÃO** pedem a formatação, mas no banco de dados grava **corretamente** formatado.
3. Quando compara a versão original com a versão alterada,  caracteres estranhos (?) substituem 
 por exemplos os hifens (-) digitados nos textos, o mesmo acontece na gravação no banco de dados.

**Comment by romulomb** [comment]
**EXCLUIR OU ALTERAR DOCUMENTO**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2eb63014-9527-471a-b314-ed257b80d9cd)

![Tela.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/0231d50d-379b-4fa1-9d25-0961c258ec1c)
