### ISSUE TITLE
Ajustes de estabilização - readequação/análise

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#2145]
Issue para sistematizar e documentar correções e ajustes da issue #2067, que implementou os painéis de readequação na análise e telas de análise

* [x] Visualização de saldo não aparece (ao clicar no visualizar na tabela)
* [x] Ajustes no título do painel de readequações
* [x] Planilha orçamentária - diferenciar itens aumentados, reduzidos, excluídos e adicionados
* [x] Painel 'analisados' - adicionar vinculada aos siEncaminhamento 4, 5, 24
* [x] Redistribuir: ajustes na abertura dos destinatários
* [x] Diligência
* [x] Excluir readequação de planilha
* [x] Legenda para alterações na planilha orçamentária
* [ ] Planilha: cards para valores (ativa, remanejada, diferença +/-)

**Comment by romulomb** [comment]
No perfil do técnico de acompanhamento inserir a ação de distribuir.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/cf7c31f5-6829-4bd6-8e46-7ec76002f2bd)

**Comment by romulomb** [comment]
**PERFIL COORDENADOR DE PARECER**

**Em análise**

**1. Redistribuir Readequação**

Nas vinculadas não aparece o combo com os nomes dos parecerista na redistribuição, exceto SAV.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/696c053c-c982-46e0-b009-6e8b27fe5498)

**2. Redistribuir Readequação**
Quando encaminhar o projeto para outra vinculada, inibir o combos dos Pareceristas.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3398ae9d-ed62-4d61-9f38-8d349845e9a5)

**Comment by romulomb** [comment]
**PERFIL DO PROPONENTE**

**Readequação de 50%**

Incluir no grupo A  **Pós-Produção**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/625f98e9-ed24-4668-ab87-41ce8e1b399f)

**Comment by romulomb** [comment]
**HOMOLOGAO**

**FICOU EXCELENTE**

**PARABÉNS**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
