### ISSUE TITLE
[Readequação - Projeto] Solicitação de utilização do saldo de aplicação financeira

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#215]
[7.1.2.3.3]

**História:** Eu como proponente, desejo solicitar o saldo de aplicação financeira pelo sistema, com intuito de utilizá-lo na execução do projeto

Entendemos que será necessário uma nova interface para essa funcionalidade, precisamos de orientações de como encaixar ela no fluxo atual.

Referência na IN,  Art. 32:
> § 2º Os recursos depositados na Conta Vinculada, enquanto não empregados em sua finalidade, serão automaticamente aplicados em fundo de aplicação financeira de curto prazo, ou operação de
mercado aberto lastreada em título da dívida pública federal.

> § 3º Os rendimentos da aplicação financeira só poderão ser utilizados no próprio projeto cultural, dentro dos parâmetros já aprovados pelo MinC, estando sujeitos às condições de prestação de contas dos recursos captados, observado o disposto no art. 37. Caso os recursos provenientes de aplicações financeiras não sejam utilizados no projeto cultural, serão recolhidos ao FNC.

> § 4º Ao término da execução do projeto cultural, os saldos remanescentes da Conta Vinculada serão recolhidos ao FNC, nos moldes do art. 5º, V, da Lei nº 8.313, de 1991, dispensada a anuência do proponente.

**Comment by romulomb** [comment]
Será colocado em outra issue
