### ISSUE TITLE
[Parecer] Gerenciar Parecer - Análise Complementar

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#2150]
# HU001  - Coordenador de Parecer(Brasília)  - Solicitar análise complementar

### Descrição

**Sendo** um Coordenador de Parecer
**Desejo** solicitar análise
**Para** complementar o parecer técnico

### Cenários

Cenário 1: Acessar a tela de solicitar análise complementar
**Dado** que o usuário deseja solicitar análise complementar
**Quando**  seleciona a opção "Em validação" na lista de "Produtos por situação"
**E** clica na opção "Solicitar análise complementar"
**Então** o sistema exibe o formulário para solicitação 

Cenário 2: Visualizar formulário de análise complementar
**Dado**  que o usuário deseja solicitar análise complementar
**E** clica na opção "solicitar análise complementar"
**Então** o sistema disponibiliza o formulário de análise
**E** carrega a lista de "Órgãos destino"
**E** exibe o campo "Observação para unidade vinculada"

Cenário 3: Incluir solicitação de análise complementar
**Dado**  que o usuário deseja solicitar análise complementar
**E** o usuário preencheu a "Observação para unidade vinculada" com mais que 10 caracteres
**Então** o sistema verifica que todos os campos obrigatórios foram preenchidos;
**E** habilita o botão "Enviar"
**Quando** clica na opção "Enviar"
**Então** o sistema apresenta a mensagem "Confirma o envio para a unidade vinculada?"
**Quando** clica em "Confirmar"
**Então** o sistema exibe a mensagem "Produto encaminhado com sucesso"
**E** encaminha o produto para o "Coordenador de Parecer" do órgão selecionado 
 
# HU0002 - Coordenador de Parecer - Painel enviadas para análise compartilhada

**Sendo** um Coordenador de Parecer
**Desejo** visualizar produtos distribuídos para análise complementar 
**Para** gerenciar envios

Cenário 1: Listar produtos do órgão que estão em análise complementar
**Dado** que o usuário deseja listar os produtos em análise complementar
**Quando**  seleciona a opção "Enviadas para análise compartilhada (outra unidade)" na lista de "Produtos por situação"
**Então** o sistema exibe os itens que estão em análise complementar

Cenário 2: Visualizar produto em análise complementar
**Dado** que o usuário deseja visualizar o produto em análise complementar
**Quando**  clicar no nome do produto
**Então** o sistema detalha o produto em análise

Cenário 3: Visualizar histórico
**Dado** que o usuário deseja visualizar o histórico de análise do produto
**Quando**  clicar no ícone "Visualizar histórico"
**Então** o sistema exibe o histórico de avaliação do produto

Cenário 4: Distribuir produto
**Dado** que o usuário deseja distribuir o produto para um novo parecerista
**Quando**  clicar no ícone "Distribuir produto"
**Então** o sistema exibe o formulário para distribuição do produto

Cenário 5: Visualizar detalhes da avaliação
**Dado** que o usuário deseja visualizar detalhes da avaliação
**Quando**  clicar no ícone de "Exibir mais"
**Então** o sistema exibe os detalhes da avaliação com o Pronac, Nome do Projeto, Produto, Área, Segmento, Valor do Produto e o Parecerista.

#### Cenário 1
![image](https://user-images.githubusercontent.com/2494751/65461524-771ea300-de2a-11e9-8d9a-fb19bce6a49e.png)

#### Cenários 2, 3 e 4
![image](https://user-images.githubusercontent.com/2494751/65510272-ef2cad80-deaa-11e9-8513-63e167c0dc90.png)

#### Cenário 5
![image](https://user-images.githubusercontent.com/2494751/65510230-dc19dd80-deaa-11e9-9901-b347962c52ae.png)

# HU0003 - Coordenador de Parecer - Devolvidas da análise compartilhada

**Sendo** um Coordenador de Parecer
**Desejo** visualizar produtos devolvidos após análise complementar 
**Para** gerenciar produtos validados

Cenário 1: Listar produto devolvido após análise complementar
**Dado**  que o usuário desejar visualizar produtos devolvidos após análise complementar
**Quando** seleciona a opção "Devolvidas análise compartilhada(outra unidade)" na lista de "Produtos por situação"
**Então** o sistema exibe o item na lista

Cenário 2: Validar análise
**Dado**  que o usuário deseja validar análise complementar
**Quando**  clica na opção "Validar análise"
**Então** o sistema apresenta a mensagem "Confirma a validação da análise do produto?"
**Quando** o usuário clica em "Confirmar"
**Então** o sistema exibe a mensagem "Validação realizada com sucesso"
**E** encaminha o produto para o painel "Validados"

Cenário 3: Redistribuir produto
**Dado**  que o usuário deseja redistribuir produto
**Quando**  clica na opção "Redistribuir produto"
**Então** o sistema exibe o formulário para gerenciar o produto

Cenário 4: Devolver para reanálise do parecerista
**Dado**  que o usuário deseja solicitar nova análise do parecerista
**Quando**  clica na opção "Devolver para reanálise do parecerista"
**Então** o sistema exibe o formulário solicitar nova análise do parecerista

Cenário 5: Solicitar análise complementar 
**Dado**  que o usuário deseja solicitar análise complementar
**Quando**  clica na opção "Solicitar análise complementar"
**Então** o sistema exibe o formulário para solicitar nova análise complementar

Cenário 6: Visualizar histórico
**Dado**  que o usuário deseja visualizar o histórico do produto
**Quando**  clica na opção "Visualizar histórico"
**Então** o sistema exibe uma lista com o histórico de análise

#### Cenários 1, 2, 3, 4, 5 e 6

![image](https://user-images.githubusercontent.com/2494751/65518092-2191d700-deba-11e9-9309-8b44edefeb72.png)

# HU0004 - Coordenador de Parecer(Vinculada) - Distribuir análise complementar

### Descrição

**Sendo** um Coordenador de Parecer(Unidade Vinculada) 
**Desejo** distribuir produto para análise
**Para** um técnico da unidade

Cenário 1: Listar produto distribuição
**Dado**  que o usuário desejar visualizar produto com análise complementar disponível
**Quando** seleciona a opção "Aguardando distribuição" na lista de "Produtos por situação"
**E** existe produto com órgão de origem diferente do atual
**E** o tipo de análise for igual a "Análise de custo"
**Então** o sistema exibe o item na lista com uma cor destacada

Cenário 2: Visualizar produto 
**Dado**  que o usuário desejar detalhar o produto
**Quando** clica no nome do produto
**Então** o sistema exibe o detalhamento da análise de conteúdo
**E** da análise de custos
**E** da consolidação do parecer quando for produto principal

Cenário 3: Visualizar formulário distribuir produto
**Dado**  que o usuário deseja distribuir produto
**Quando** clica na opção "Distribuir ou encaminhar produto" no painel
**Então** o sistema exibe o formulário de Gerenciar Produto
**E** carrega a lista de "Pareceristas" do órgão
**E** exibe o campo "Observação para o parecerista"

Cenário 4: Distribuir produto para análise
**Dado**  que o usuário deseja distribuir produto para um parecerista
**E** o usuário selecionou um parecerista
**E** o usuário preencheu a "Observação para o parecerista" com mais que 10 caracteres
**Então** o sistema verifica que todos os campos obrigatórios foram preenchidos
**E** habilita o botão de "Enviar"
**Quando** clica na opção "Enviar"
**Então** o sistema apresenta a mensagem "Confirma a distribuição para o parecerista?"
**Quando** clica em "Confirmar"
**Então** o sistema exibe a mensagem "Distribuição realizada com sucesso"
**E** encaminha o produto para o parecerista selecionado. 

#### Cenário 1
![image](https://user-images.githubusercontent.com/2494751/65461267-f95a9780-de29-11e9-8e88-026ba7b1b135.png)

#### Cenário 2:
![image](https://user-images.githubusercontent.com/2494751/65461413-33c43480-de2a-11e9-9f50-87d005a3678f.png)

#### Cenário 3
![image](https://user-images.githubusercontent.com/2494751/65461348-11cab200-de2a-11e9-8850-72d4f74c3b8b.png)

# HU0005 - Parecerista - Análise complementar

**Sendo** um Parecerista
**Desejo** visualizar produtos 
**Para** realizar análise complementar

Cenário 1: Acessar a lista de produtos para análise inicial
**Dado** que o usuário deseja visualizar produtos disponíveis para análise complementar
**Quando** acessa a tela de "Análise inicial"
**Então** o sistema exibe a lista de produtos disponíveis para análise
**E** exibe o produto com análise complementar destacado dos demais itens 

Cenário 2: Realizar análise de custos
**Dado** que o usuário deseja realizar análise complementar
**Quando** clica na opção "Analisar produto"
**Então** o sistema disponibiliza o produto apenas para análise de custos 

Cenário 3: Realizar diligência
**Dado** que o usuário deseja diligenciar o produto
**Quando** clica na opção "Diligências"
**Então** o sistema disponibiliza a lista com diligências e a opção para "Nova diligência"

Cenário 4: Validar finalização de análise
**Dado** que o usuário deseja validar a análise
**Quando** clica na opção "Finalizar análise"
**Então** o sistema valida se a análise de custo foi realizada
**E** se existe diligência em aberto 
**Então** habilita o botão "Finalizar parecer" 

Cenário 5: Finalizar análise
**Dado** que o usuário deseja finalizar a análise
**Quando** clica na opção "Finalizar parecer"
**Então** o sistema valida se a análise de custo no backend
**E** se existe diligência em aberto no backend 
**Então** o sistema encaminha o produto para o Coordenador de Parecer da unidade atual
**E** exibe a mensagem "Avaliação realizada com sucesso"
 
#### Cenário 1
![image](https://user-images.githubusercontent.com/2494751/65510598-b93bf900-deab-11e9-9ce6-24e787fa58ae.png)

#### Cenário 2
![image](https://user-images.githubusercontent.com/2494751/65514388-99a8ce80-deb3-11e9-940a-5da821314d77.png)

#### Cenário 3
![image](https://user-images.githubusercontent.com/2494751/65514458-b5ac7000-deb3-11e9-87a2-a02c2cc9888b.png)

#### Cenários 4 e 5
![image](https://user-images.githubusercontent.com/2494751/65514504-cc52c700-deb3-11e9-9d4c-1e83fdbc3ebf.png)

# HU0006 - Coordenador de Parecer(Vinculada) - Validar análise complementar

**Sendo** um Coordenador de Parecer(Unidade Vinculada) 
**Desejo** visualizar produto
**Para** realizar validação da análise complementar

Cenário 1: Listar produto analisado
**Dado**  que o usuário desejar visualizar produto com análise complementar realizada
**Quando** seleciona a opção "Em validação" na lista de "Produtos por situação"
**E** existe produto com órgão de origem diferente do atual
**E** o tipo de análise for igual a "Análise de custo"
**Então** o sistema exibe o item na lista com uma cor destacada

Cenário 2: Validar análise com alteração de valor na análise de custo
**Dado**  que o usuário deseja validar análise complementar
**Quando**  clica na opção "Validar análise"
**Então** o sistema apresenta a mensagem "Confirma a validação da análise do produto?"
**Quando** o usuário clica em "Confirmar"
**Então** o sistema exibe a mensagem "Validação realizada com sucesso"
**E** devolve o produto para o parecerista original
**E** desabilita o documento do parecer disponível para assinatura

Cenário 3: Validar análise sem alteração de valor na análise de custo
**Dado**  que o usuário deseja validar análise complementar
**Quando**  clica na opção "Validar análise"
**Então** o sistema apresenta a mensagem "Confirma a validação da análise do produto?"
**Quando** o usuário clica em "Confirmar"
**Então** o sistema exibe a mensagem "Validação realizada com sucesso"
**E** devolve o produto para o Coordenador de Parecer da unidade de origem

#### Cenários 1 e 2
![image](https://user-images.githubusercontent.com/2494751/65516501-7f70ef80-deb7-11e9-8d90-23deecce8036.png)

#### Cenário 3
![image](https://user-images.githubusercontent.com/2494751/65516584-a0d1db80-deb7-11e9-9272-4c8a1fbb6921.png)

**Comment by clebersantos** [comment]
@romulomb, disponibilizei ontem no ambiente de homologação os painéis para análise complementar. No entanto, ainda é necessário configurar as trilhas que serão utilizadas no ambiente de produção para realizarmos o teste geral do fluxo.

**Comment by clebersantos** [comment]
@romulomb disponível para homologação.

Informo que foi necessário realizar refatoração da análise inicial do parecerista(issue #1878) e em todos os painéis do coordenador de parecer(#2109) para atender a análise complementar. 

Na análise complementar, um parecerista de outra unidade faz análise financeira na planilha de um produto já analisado.

**Comment by romulomb** [comment]
### AJUSTE

Não é possível completar o fluxo da análise complementar.

Quando o parecerista alterar a planilha, depois da validação o projeto deverá retornar ao parecerista original para emissão de novo parecer.

Não conseguimos executar esse passo.

**Comment by clebersantos** [comment]
@romulomb, pode detalhar o fluxo realizado? Quais unidades e projetos foram utilizados para o teste de análise complementar?

**Comment by romulomb** [comment]
#### AJUSTES.

##PERFIL DE COORDENADOR DE PARECER

1. Painel em validação

a. Passo 1
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/376cf076-d8ad-4694-a4f4-1291ddb3b3eb)

b. Passo 2 - Não carrega as unidades destino
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/44faa30b-f527-4ae4-a9d1-3f6b09cce39d)

2. Após a validação pela outra unidade não consigo finalizar o parecer.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/641f8750-42cb-4f18-b7d7-8e0c8297ad35)

**Comment by romulomb** [comment]
#### AJUSTE

**PERFIL COORDENADOR DE PARECER**

**Painel validados**

Ao clicar no link do produto, a aplicação deverá mostrar o parecer emitido e não o a tela de assinatura do documento.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b510bf93-24ee-448f-97c9-35d767e99f58)

Está mostrando ...
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b60e6b3e-99ae-4bc8-b592-e1059418dbf4)

**Comment by romulomb** [comment]
Quando projeto volta para o parecerista original e este aciona o botão finalizar o projetos desaparece do grid e não gera o documento para ser assinado.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bb840819-c4bd-44c6-9c8a-f9e0c3398ffa)

Informação do banco
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b767df97-3996-4a0f-b5d1-398cf9b5677d)

**Comment by romulomb** [comment]
#### Ajuste

Não alterou o atributo FechaAnalise para 1 e não gravou a data do atributo DtRetorno na tabela tbDistribuirParecer.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/ba4011dc-8192-43eb-ab43-0848e80ebfd4)

**Comment by clebersantos** [comment]
@romulomb foi aplicada uma melhoria ao finalizar assinatura. Disponível no ambiente de homologação

**Comment by romulomb** [comment]
**HOMOLOGADA**

**NÃO SUBIR para produção estamos na semana da CNIC**

**PARABÉNS PELO TRABALHO**
