### ISSUE TITLE
[ADMISSIBILIDADE] Problemas para transformar proposta em projeto

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#2156]
### PROBLEMA

Desativação do SEI da Cultura. 

Existe um web-service no Salic para gerar o nº de processo no sei.

### CORREÇÃO

Permitir ao web-service do Salic gerar o nº de processo no sei da Cidadania.
.
### COMO CHEGAR AO PROBLEMA

No perfil de **Coordenador-geral de Admissibilidade e Aprovação** no menu **Admissibilidade/ Avaliação** ao clicar numa proposta no botão analisar, quando clicamos em **Transformar** após confirmação da ação aparece a mensagem **"Tipo de procedimento [100000520] não encontrado"** e não estamos conseguindo transformar as propostas em projetos.

**PASSO 1**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/22ea91db-8bfe-46a8-a1bb-089bd9d342c2)

**PASSO 2**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/4ec7fb58-f861-4ea3-bb72-7770109887c4)

**PASSO 3**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/3c9a0620-f029-4d66-8c62-029de5e2f394)

**PASSO 4**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/487e0680-c9fc-42f7-94cd-a7a17c7d7aeb)

**PASSO 5**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/4bdcc018-2374-4809-b533-1549a48a7693)

**PASSO 6**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/ba502495-a44d-48be-add8-c5ad382e72f4)

**Comment by romulomb** [comment]
Prezados @felipevelter, @ThaysMatta

Solicito atendimento urgente.

Desde já agradeço o pronto atendimento.
