### ISSUE TITLE
[READEQUAÇÃO] Diligência não está funcionando

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#2157]
### PROBLEMA

No ambiente de produção o sistema não está  enviando a diligência emitida nos perfis de Técnico de Acompanhamento e Parecerista na **funcionalidade de readequação**.

**Vale ressaltar que no ambiente de homologação funciona perfeitamente.**

### COMO CHEGAR AO PROBLEMA

No perfil de **Técnico de Acompanhamento** no menu **Acompanhamento/ Avaliar Readequações** na coluna Ações quando clico em **Diligências** e depois em **Nova diligência**, digito o texto e clico em Enviar, aparece a mensagem Salvo com sucesso, porém a diligência não fica registrada no painel e quando consulto os dados do projeto para checar se a diligência foi enviada, constatei que não está sendo enviada.

**PASSO 1**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/68f3c2da-bb7c-4005-9734-729ab45d1f72)

**PASSO 2**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/1c312dfe-d74e-466a-8794-c092ff9d6b2c)

**PASSO 3**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/1cd050cd-85ac-431d-99d9-81dc83e3aff2)

**PASSO 4**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/00d30421-d508-41bf-98d5-c0b883fead37)

**PASSO 5**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/8e8fd58e-dccc-4141-aede-b1569925cae6)

**PASSO 6**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/f8b3c47c-39bc-434d-893f-4f6a3e99cebf)

**PASSO 7**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/25130901-ed92-40cb-8639-2f6f8d8c6a7d)

**OBS: Esse problema não ocorre no ambiente de homologação.**

**Comment by romulomb** [comment]
Prezados @felipevelter, @ThaysMatta

Solicito atendimento urgente.

Desde já agradeço o pronto atendimento.
