### ISSUE TITLE
[SGFT] - AVALIACAO FINANCEIRA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#2159]
#### PERFIL - COORDENADOR DE PRESTAÇÃO DE CONTAS 

**1. DASHBOARD**

Somas incorretas.
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/eaf71999-752d-452a-bc49-016cb7f5fe68)

**2. Painel Distribuir**

A aplicação não permite enviar  projetos para os técnicos da SGFT

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6dcaf2ec-f512-4334-8e15-2ce59931b3e3)

O sistema deverá considerar os técnico da unidade **SGFT/DEFNC/CGPC** , codigo **733**.

**Unidades de avaliação de resultado:**

303 - SEFIC
167 - SAV
**733 - SGFT (nova unidade)**

**Órgãos Superiores**
251 - SEFIC
160 - SAV
**731 - SGFT**

---------------------------------------------------------------------------------------------------

**2. Painel Distribuir**

a. Separar os projetos por unidade.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a4b8ab63-84a5-4b00-ab64-bd31b3143997)

b. Permitir distribuição de projetos para essa unidade

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6dcaf2ec-f512-4334-8e15-2ce59931b3e3)

---------------------------------------------------------------------------------------------------

**3. Painel Assinar**

a. Separar os projetos por unidade.

b.  Para itens orçamentários não comprovados retirar o ícone de visualização para evitar o descrito na tela abaixo.
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/7e106f4d-6b56-4cfd-911f-d917adce4d71)
---------------------------------------------------------------------------------------------------

**4. Painel Histórico**

a. Separar os projetos por unidade.

===========================================================

#### PERFIL - TÉCNICO DE PRESTAÇÃO DE CONTAS 

1. Quando existe muito  comprovantes para o mesmo item orçamentário a tela demora muito para renderizar.

![Avaliacao_Tecnico_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3377431e-d713-42bf-bd89-aa48251f14e0)

2. Alterar  os nome das unidades ao gerar o documento para assinatura.

a. Mudar de  **SECRETARIA ESPECIAL DA CULTURA** para **SECRETARIA EXECUTIVA**;
b. E quando órgão superior for 731 o nome da secretaria deverá ser **Secretaria de Gestão de Fundos e Transferências - SGFT**.

![Avaliacao_Tecnico_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6154cefd-7718-4828-95be-e133ef0ba513)

3. Comprovante de pagamento internacional não aparecem no grid de avaliação do técnico.

Aparecem na relação de pagamentos
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/06b18db7-33dd-4e4c-b414-d0b87461ff35)

Não aparecem no grid do téncico
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d072e73e-6638-4d09-9bbe-6f7774d9a6b1)

4.  Melhorar os ícones expressados na figura abaixo por estão desformatados.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/49311837-d2c9-4a42-9b8d-b01d197ebf15)

5. Retirar o ícone de devolução para o técnico do perfil do técnico

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bd1610ef-ed52-4551-8c2f-48e8e7dc4827)

6. Histórico de encaminhamentos não está mostrando nenhuma informação.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/7e2d37fe-3ba4-485f-8a1b-1ce2ab7cdded)

7. Alterar a descrição da legenda abaixo

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/334070dd-4967-4cff-904d-b3925a97aa39)

8. Na tela do documento ao clicar em Gerenciar Projetos a aplicação desarma.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/17ca2e3e-ec72-42a0-b94e-ddeb2c306736)
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b811f3be-1801-4486-8b62-65c4fd7f1741)

9. Ajustar documento a ser assinado.
a. Alinhar os labels, números e valores à direita;
b. Formatar número
c. Fomatar valores

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/9a57ca9a-c904-4fd2-bf6a-36ff252398a0)

10. Ao Finalizar o parecer gerar o documento para assinatura.
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/cacbe52b-6bd5-440c-bbe3-3b9fefd9ef57)

11. Após a emissão do parecer a aplicação deverá retornar para o painel.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/13dc6a7c-b709-42d1-96f0-2e90c5690ae5)

12. Melhorar a templante de análise financeira.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/86081d07-da2a-4f4d-bf2d-0785bc1671da)

===========================================================

#### PERFIL - COORDENADOR GERAL DE PRESTAÇÃO DE CONTAS 

O dashboard não está contando corretamente
 
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c3631d10-98bf-4756-a7ab-8cf6e8bb55b4)

===========================================================

#### PERFIL - SECRETÁRIO
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/4f3b8eb9-dda7-41f2-82fe-323ceb5230d1)

**Comment by clebersantos** [comment]
Informo que foi disponibilizado no ambiente de homologação(hmg.salic.cultura.gov.br) do salic, a atualização do modulo de avaliação de resultados nas etapas de análise da comprovação financeira e emissão do laudo final para utilização da nova Secretaria de Gestão de Fundos e Transferências - SGFT.

Esclareço que foram realizados vários ajustes e melhorias no módulo para atender a nova unidade. Entre as melhorias, as mais relevantes são:
 - Melhor visualização do andamento da análise durante o parecer técnico 
 - Quantidade de comprovantes disponíveis para análise
 - Atualização automática da quantidade de comprovantes aprovados, reprovados e pendentes de avaliação
- Atualização automática dos valores aprovados e reprovados
- Melhoria de 50% na performance de carregamento dos painéis, planilha e comprovantes
- Disponibilização de informações relevantes durante a análise
- Visualização dos pagamentos do projeto
- Visualização da conciliação bancária do projeto
- Visualização da execução das receitas e despesas do projeto
- Melhoria na visualização dos projetos diligenciados 
- Visualização da planilha no modo listagem
- Opção para ocultar itens não comprovados

**Comment by romulomb** [comment]
### AJUSTES

#### PERFIL DO COORDENADOR DE PARECER

##### PAINEL ASSINAR

O coordenador não consegue devolver o projeto para  técnico reavaliar o parecer emitido.

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f3711eda-4830-4b2e-a125-1c3b136d7499)

**Comment by clebersantos** [comment]
@romulomb, correções disponíveis no ambiente de homologação.

**Comment by romulomb** [comment]
### AJUSTES

**Avaliação financeira**

Avaliação de Resultados - Visualizar Parecer

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f622a1b7-c760-4ffa-993a-3729478fcb4f)

Avaliação de Resultados - Visualizar Parecer - **Perfil do Técnico**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/182631a0-6c2a-4332-ade2-178bf12454d6)


**Após o ajuste estará homologado pela SEFIC**

**Sugerimos antes da subida para a produção o aval da SGFT.**

**Comment by clebersantos** [comment]
@romulomb, ajustes disponíveis no ambiente de homologação.
