### ISSUE TITLE
[Readequação - Projeto] Solicitação de modificação do plano de distribuição de produto cultural

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#217]
[7.1.2.3.5]
**História:** Como proponente desejo inserir os dados no plano de distribuição de acordo com a Nova IN.

Referência na IN, Art. 20.

> Da Ampliação do Acesso

> Art. 20. A proposta cultural deverá conter um Plano de Distribuição detalhado, visando assegurar a ampliação do acesso aos produtos, bens e serviços culturais produzidos, contendo:

> I - estimativa da quantidade total de ingressos ou produtos culturais previstos, observados os seguintes limites:

> a) mínimo de 10% (dez por cento) exclusivamente para distribuição gratuita com caráter social, educativo ou formação artística;

> b) até 10 % (dez por cento) para distribuição gratuita por patrocinadores;

> c) até 10 % (dez por cento) para distribuição gratuita promocional pelo proponente em ações de divulgação do projeto;

> d) mínimo de 20% (vinte por cento) para comercialização em valores que não ultrapassem R$ 75,00 (setenta e cinco reais);

> e) a comercialização em valores a critério do proponente será limitada a 50% (cinquenta por cento) do quantitativo de produtos culturais, sendo o preço médio do ingresso ou produto de R$ 225,00 (duzentos e vinte e cinco reais), excetuando-se projetos com transmissão ao vivo em TV aberta; e

**Relacionadas:** 
#236 #219 #217 #206

**Comment by clebersantos** [comment]
@romulomb, essa é a issue da readequação do plano de distribução e detalhamentos.

**Comment by clebersantos** [comment]
Issue duplicada com a #536
