### ISSUE TITLE
[Readequação - Projeto] Solicitação de modificação do local de realização do projeto

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#219]
[7.1.2.3.7] 
**História:** Como proponente desejo poder solicitar a modificação do local de realização do projeto, atualizando a planilha orçamentária, plano de distribuição e cronograma de execução quando necessário.

> Art. 36. O projeto cultural poderá ser alterado na fase de execução, mediante solicitação do proponente, registrada e justificada por meio do Salic, no mínimo, 30 (trinta) dias antes do início da execução da meta ou ação a ser alterada; somente serão objeto de análise após a liberação para movimentação dos recursos, salvo o disposto no art. 41.

> § 2º No caso de alteração do espaço físico ou novo local de realização do projeto, o proponente não poderá infringir o disposto no art. 5º, devendo apresentar, se for o caso:
I - planilha orçamentária adequada à nova realidade;
II - ajuste do Plano de Distribuição, de ampliação de acesso e acessibilidade; e
III - cronograma de execução atualizado.

**Relacionadas:** 
#236 #219 #217 #206

**Comment by Pedro-Philipe** [comment]
@romulomb Corrigido bug ao tentar apagar um novo local de realização cadastrado na readequação. Favor testar em homologar. (refs: [819f67](https://github.com/culturagovbr/salic-minc/commit/819f67117537e838dca59afcc2865a8b1116f28b))

**Comment by romulomb** [comment]
Homologado.
