### ISSUE TITLE
[Readequação - Projeto]  Impretar recursos contra a decisão da solicitação de readequação

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#220]
[7.1.2.3.8] 
**História:** Como proponente gostaria de impetrar recurso contra decisão do Técnico sobre a solicitação de readequação.

Dúvidas: Onde é solicitada a readequação? Quais situações do projeto o proponente pode entrar com recurso? Qual o fluxo da funcionalidade?

Precisa de detalhamento de como esse recurso da decisão funcionará

**Comment by romulomb** [comment]
Mudança de escopo
