### ISSUE TITLE
[Admissibilidade] Visão completa dos recursos e  redistribuir os recursos entre os técnicos

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#229]
[7.2.1.8] Detalhar melhor como deverá ser esse fluxo

Depende da #210 e #228
**Historia:** Como coordenador de admissibilidade quero  redistribuir  os recursos entre os técnicos de admissibilidade.

 Disponibilizar funcionalidade para que o coordenador de admissibilidade tenha a visão completa dos recursos e que permita redistribuir os recursos entre os técnicos de admissibilidade

 O que seria "tenha a visão completa" ?

**Comment by nitaibezerra** [comment]
Sugestão de descrição no formato de Estória de Usuário:

Eu como Coordenador de Análise, quero visualizar completamente as informações dos Recursos e também quero distribuí-los entre os Técnicos de Admissibilidade dessa forma [o processo de distribuição será realizado de maneira mais equilibrada e...]

Esta parte entre colchetes pode ser confirmada/detalhada
