### ISSUE TITLE
7.5.2 Analisar a solicitação de utilização do saldo de aplicação financeira

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#234]
7.5.2 Implementar funcionalidade para analisar a solicitação de utilização do saldo de
aplicação financeira

**Historia:** Como técnico gostaria de analisar a solicitação de utilização do saldo de
aplicação financeira.

**Comment by clebersantos** [comment]
Fechando este card, funcionalidade desenvolvida na issue #807
