### ISSUE TITLE
[Assinatura] 7.5.8 Assinatura digital

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#240]
7.5.8 Implementar a funcionalidade de assinatura digital

** História : ** Como (detalhar perfis) desejo assinar digitalmente o resultado da avaliação da readequação e espero (detalhar fluxo).

Dúvidas :
    - Assinatura digital é referente ao recurso de readequação ou apenas do resultado da readequação ?
    - Qual o fluxo de assinatura ?
    - Quais os perfis que estarão presentes no fluxo (bloco) de assinatura ?

**Comment by clebersantos** [comment]
Funcionalide já desenvolvida na issue #873.
