### ISSUE TITLE
Alteração do texto da declaração da Proposta

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#263]
Atualizar o texto da declaração (anexo 2 IN)

**Comment by boletocosta** [comment]
Segue o texto:

DECLARAÇÃO DE RESPONSABILIDADE
DECLARO para todos os fins de direito, estar ciente da obrigatoriedade de:
TER CONHECIMENTO:
- sobre a legislação referente ao benefício fiscal pretendido e das normas relativas à
utilização de recursos públicos e respectivos regulamentos em especial às vedações, a ser acessado
no Portal da Rouanet;
- que a gestão de recursos captados é decisão única e exclusiva do proponente, a partir da
qual a responsabilização pela utilização desses recursos públicos torna-se indissociável e para a qual
deve levar em conta a real possibilidade de captação futura com vistas ao cumprimento total do objeto
pactuado;
- que a incorreta utilização dos recursos do incentivo sujeita o incentivador ou proponente ou
ambos, às sanções penais e administrativas, previstas na Lei nº 8.313, de 1991, e na Legislação do
Imposto de Renda e respectivos regulamentos; e
- sobre o conteúdo do Portal da Lei Rouanet, disponível no endereço rouanet.cultura.gov.br.
MANTER:
- comprovantes documentais das informações constantes no cadastro das propostas
culturais, assim como das fases subsequentes de aprovação, execução e avaliação de resultados; e
- os dados cadastrais atualizados junto ao banco de dados do Sistema MinC.
PERMANECER em situação de regularidade fiscal, tributária e previdenciária (seguridade
social) durante toda a tramitação da proposta e do projeto cultural;
ACATAR os valores definidos pelo Ministério da Cultura na divulgação oficial do resultado da
homologação ou, em caso de discordância, formalizar recurso conforme a Lei do Processo
Administrativo nº 9.784, de 1999;
PROMOVER a execução do objeto do projeto na forma e prazos estabelecidos e aplicar os
recursos captados exclusivamente na consecução do objeto, comprovando seu bom e regular emprego,
bem como os resultados alcançados;
PERMITIR E FACILITAR o acesso a toda documentação, dependências e locais do projeto,
à fiscalização por meio de auditorias, vistorias in loco, visitas técnicas e demais diligências, que serão
realizadas diretamente pelo MinC, por suas entidades vinculadas, ou mediante parceria com outros
órgãos federais, estaduais, distrital e municipais;
DAR PUBLICIDADE, na promoção e divulgação do projeto, ao apoio do Ministério da
Cultura, com observância dos modelos constantes do Manual de Uso das Marcas do Pronac, disponível
no Portal da Rouanet, tendo em vista que a divulgação da Lei Rouanet é fundamental para o controle
social, para o conhecimento do público em geral, para a motivação e o engajamento de novos
patrocinadores e doadores, bem como para a evolução e a expansão do mecanismo;
PRESTAR CONTAS dos valores captados, depositados e aplicados, bem como dos
resultados do projeto, nas condições e prazos fixados ou sempre que for solicitado;
DEVOLVER em valor atualizado, o saldo dos recursos captados e não utilizados na
execução do projeto, quando não transferidos para outro projeto, mediante recolhimento ao Fundo
Nacional da Cultura (FNC), conforme instruções dispostas no Portal da Rouanet.
Assim, COMPROMETO-ME a:
ACOMPANHAR e SANAR tempestivamente qualquer solicitação das áreas técnicas do
Ministério da Cultura;
APLICAR E PROMOVER A DIVULGAÇÃO da classificação indicativa para exibição de
obras, espetáculos, eventos, shows e conteúdo audiovisual, conforme Portaria nº 368, de 11 de
fevereiro de 2014, do Ministério da Justiça;
OBTER E APRESENTAR AO MINC antes do início de execução do projeto, alvará(s) ou
autorização(ões) equivalente(s) emitida(s) pelo(s) órgão(s) público(s) competente(s), caso alguma(s)
da(s) atividade(s) decorrentes do projeto sejam executadas em espaços públicos;
OBTER E APRESENTAR AO MINC, antes do início de execução do projeto, declaração de
autorização dos titulares dos direitos autorais, conexos e de imagem em relação aos acervos, às obras
e imagens de terceiros como condição para utilizá-los no projeto; e
Por fim, ATESTO serem fidedignas as informações prestadas no preenchimento dos
formulários, assim como de outras documentações juntadas ao longo da tramitação do projeto, e que
responderei por eventuais infrações que vierem a ser cometidas.
