### ISSUE TITLE
Alterar textos de ajuda

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#264]
Alterar textos de ajuda

Referencia #205

**Comment by fernao** [comment]
Resumo:

No campo Resumo deve-se descrever o objetivo do projeto em no máximo 5 linhas. O texto deve ser conciso e apresentar de forma clara os produtos que compõem a proposta.

Pergunta-chave: O QUÊ?

 

Objetivos:

O campo Objetivos deve conter os objetivos gerais e específicos de forma separada, especificando cada categoria (geral e específico).

 

No Objetivo Geral deve-se descrever, resumidamente, qual o principal resultado que o projeto pretende alcançar, qual a sua finalidade.

Pergunta-chave: PARA QUÊ?

 

Nos Objetivos específicos deve-se citar todas as ações que serão realizadas no projeto, ou seja, quais os produtos específicos que serão oferecidos à população. Os objetivos específicos devem ser mensuráveis e devidamente comprovados na prestação de contas.

Perguntas-chaves: QUAIS? QUANTOS?

 

Justificativa:

Destaque a necessidade do uso do Mecanismo Incentivo a Projetos Culturais para financiamento deste, apresentando em quais incisos do Art. 1º da Lei 8313/91 o projeto se enquadra, bem como quais objetivos do Art. 3° da referida norma serão alcançados.

Pergunta-chave: POR QUE A LEI ROUANET?

 

Acessibilidade:

O campo Acessibilidade deve conter informações quanto à Acessibilidade Física e Acessibilidade de Conteúdo.

 

A Acessibilidade FÍSICA deve oferecer facilitadores para a locomoção no espaço físico (banheiros, rampas, guias táteis).

A Acessibilidade de CONTEÚDO deve prever medidas para compreensão do projeto (Libras, Braille, audiodescrição, legenda descritiva, visita sensorial).

 

Democratização de Acesso:

Descreva no campo Democratização de Acesso a forma de distribuição e comercialização dos produtos da proposta.

Apresente também outras medidas de ampliação de acesso, tais como: ensaio aberto, oficinas paralelas ou transmissão pela internet.

 

Etapas de trabalho:

Divida as etapas do projeto em ‘Pré-produção’, ‘Execução’ e ‘Pós-produção’, estimando – em dias/semanas/meses – a duração de cada etapa.

 

Ficha Técnica:

Descreva com detalhes qual atividade (mesmo que voluntária) o dirigente ou a instituição proponente realizará no projeto. Apresente também currículo resumido dos principais participantes.

 

Sinopse:

Insira o conteúdo de todos os produtos do projeto que necessitam de um breve resumo em relação ao seu assunto, por exemplo: seminários, palestras, livros, espetáculo de circo, peça teatral, espetáculo de dança, performance, classificação indicativa etária.

 

Especificações Técnicas:

Insira detalhamento técnico de todos os produtos: paginação, duração, material, projeto pedagógico.

 

Outras informações:

Apresente neste campo informações complementares que não tenham sido abordadas nos campos anteriores, mas que são significativas para a avaliação da proposta.

**Comment by boletocosta** [comment]
Texto que estava faltando:

Apresente nesse campo detalhes de sua atividade cultural que não foram mencionados nos campos anteriores, como a programação do evento por exemplo.
