### ISSUE TITLE
[REVIEW] Sprint 

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#273]
Criação dos relatórios da Sprint 06.
Resolução das atividades executadas.
Melhorias propostas.

**Proposta:**
- Criar projeto especifico com os scripts SQL, como conversado com @fernao.

**Comment by ShinNin-chan** [comment]
Adicionar padrão para que todas as vezes que um formulário for enviado, o botão seja desabilitado. [Sugestão]
