### ISSUE TITLE
[Proposta] Validação transmissão canal aberto

### ISSUE THREAD

**Issue by ShinNin-chan** [culturagovbr/salic-minc#282]
Eu como **Sistema** devo implementar as seguintes regras: 
Dentro do cadastramento do produto deverá aparecer a opção para escolher se esse produto será transmitido em canal aberto. Caso essa opção tiver sido escolhida: o  médio para este produto não precisa ser realizada. 

- O avaliador da proposta deverá visualizar de forma destacada se essa opção foi escolhida pelço proponente. 

*Checklist**
- [x] Adicionar coluna PlanoDistribuiçãoProdudo
- [x] CRUD do campo.
- [x] Mudar validação no detalhamento do produto.
- [x] Validação no envio da proposta ao MinC.
- [ ] Mostrar ao tecnico que item e de canal aberto dentro da avaliação.

**Comment by AdmissibilidadeSAV** [comment]
Quando o proponente insere no Plano de distribuição a quantidade de exemplares do produto referente a distribuição gratuita para população o sistema permite que ele aumente a quantidade sem que retire de outro campo, que acaba aumentando o número de exemplares e não está sendo recalculado na quantidade total do produto. [Uploading... image.png ]

**Comment by AdmissibilidadeSAV** [comment]
Quando o proponente insere no Plano de distribuição de uma quantidade de exemplares do produto referente a distribuição gratuita para a população do sistema, deixe-o aumente a quantidade sem rejeitar o outro campo, que acaba aumentando o número de exemplares e não está sendo recalculado na quantidade total do produto. ![Inconsistência PD.JPG](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/cfef2836-bd0c-4e50-a958-7eb995eaace7)

**Comment by boletocosta** [comment]
Testei e deu certo. =)

**Comment by AdmissibilidadeSAV** [comment]
Gente quando o proponente insere que o produto será transmitido em canal aberto não aparece essa informação em campo nenhum quando a proposta é encaminhada para avaliação do MinC.

**Comment by fernao** [comment]
Adicionar campo "canal aberto" na tela 

http://hmg.salic.cultura.gov.br/admissibilidade/admissibilidade/exibirpropostacultural?idPreProjeto=206771&realizar_analise=sim
