### ISSUE TITLE
[SugestãoEnquadramento]Criar funcionalidade para sugestão de enquadramento de propostas culturais.

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#287]
Eu como *Técnico Admis / Coordenador Admis. / C. Geral Admis. / CNIC / Coordenador Pronac* gostaria que o enquadramento de propostas culturais se comportassem da seguinte maneira:

- Primeiro gostaria de saber a lista de proposta que  necessito realizar o enquadramento. 

Cada enquadramento deverá registrar as seguintes informações: 
  - id da proposta
  - Texto motivo do enquadramento
  - Perfil 
  - unidade 
  - Usuário 
  - Data da avaliação  
  
* armazenar histórico de avaliações. 

Cada nível de avaliação de sugestão de enquadramento, deverá observar o histórico anterior a sua avaliação, antes de realizar sua sugestão de avaliação. 
 
Criar tela para realização do enquadramento - 
- um campo texto com motivação do enquadramento
- combo box  de area segmento

Após enquadramento encaminhar para o próximo nível. 

para o caso de técnico de admissibilidade pode apenas enviar para coordenador / . C. Geral de admissibilidade.  

para caso coordenador / C. Geral de admissibilidade - haverá duas alternativas. - 
- [Se dúvidas] pode enviar para as  vinculadas 
- [senão] enviar direto para CNIC 

Obs: Está contido nessa sprint até dia 26 de janeiro

**Comment by fernao** [comment]
Ao carregar o campo para sugestão de enquadramento, verificar se possui alguma entrada no histórico. Caso exista, exibe.

**Comment by fernao** [comment]
Sugestão de implementação (vinny)

1) Modelagem da tabela
2) Partial do formulário
3) Partial do histórico - caso haja encaminhamento vinculado à proposta, exibir
4) Tratamento da controller que for utilizar
5) Se NÃO estiver em conformidade visual, não mostrar dados de enquadramento

**Comment by fernao** [comment]
select * from sac.dbo.tbMovimentacao where idProjeto = 240105 and stEstado = 0   ---- busca localização atual do projeto   (stEstado=0 atual)

**Comment by vinnyfs89** [comment]
Adicionaremos uma coluna na lista de propostas para avaliação com o título "Enquadramento", que receberá um check caso não tenha sido enquadrado ainda.

Conforme foi informado pelo colaborador Rômulo, a sugestão de enquadramento será opcional.

**Comment by vinnyfs89** [comment]
Segue abaixo script da tabela que comportará essa funcionalidade:

CREATE TABLE sugestao_enquadramento
(
    id_sugestao_enquadramento INT PRIMARY KEY NOT NULL IDENTITY,
    id_orgao INT NOT NULL,
    id_perfil_usuario INT NOT NULL,
    id_usuario_avaliador INT NOT NULL,
    id_area VARCHAR(4),
    id_segmento VARCHAR(4),
    id_preprojeto INT NOT NULL,
    descricao_motivacao VARCHAR(8000),
    data_avaliacao DATETIME,
    CONSTRAINT sugestao_enquadramento_Area_Codigo_fk FOREIGN KEY (id_area) REFERENCES Area (Codigo),
    CONSTRAINT sugestao_enquadramento_Segmento_Codigo_fk FOREIGN KEY (id_segmento) REFERENCES Segmento (Codigo),
    CONSTRAINT sugestao_enquadramento_id_proposta_cultural_fk FOREIGN KEY (id_preprojeto) REFERENCES PreProjeto (idPreProjeto)
);
