### ISSUE TITLE
[Admissibilidade] Avaliar admissibilidade da proposta

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#289]
Eu como coordenador de admissibilidade gostaria de ter a funcionalidade de avaliação de proposta com as seguintes características:

- Visualizar a proposta com o parecer do tecnico de admissibilidade.
- Emitir o parecer, com as seguintes possibilidades [Aceito, Arquivar , Desarquivar]

A Mesma proposta pode ser avaliada 3x

* [x] Listar impactos
* [x] Alterar tabela tbAvaliacaoProposta (adicionar idPerfil)
* [x] Técnico: Alterar inserção de avaliação pelo técnico de admissibilidade
* [x] SQL: alteração da trigger trAvaliacaoProposta_Insert
* [x] Coordenador: Visualizar a proposta com o parecer do tecnico de admissibilidade
* [x] Coordenador: Adicionar parecer com dados do seu perfil (sem invalidar o parecer do técnico)
~[ ] Coordenador: Emitir parecer com as seguintes possibilidades [Aceito, Arquivar , Desarquivar]~ (aceito e arquivar já existem)

Desarquivamento da proposta movido para #292

**Comment by fernao** [comment]
Hoje existe somente uma análise do técnico. 

1) Criar uma nova análise por coordenador e salvar como o coordenador
2) Gravar análise e sugestão de enquadramento, selecionando apenas área e segmento
3) Verificar necessidade de manter avaliação da proposta para IN antiga e criar para nova

**Comment by fernao** [comment]
Atualmente, há somente uma avaliação da admissibilidade, feita pelo técnico. Uma nova análise é adicionada à tabela desativando a análise anterior. Pelo novo fluxo da IN 2018, o coordenador fará uma avaliação para além da já realizada pelo técnico.

Atualmente há apenas uma coluna de identificação do idTecnico, e não do idPerfil ou idUnidade. Uma possibilidade de resolução seria adicionar estes dois campos (idPerfil e idUnidade) ao registro da tbAvaliacaoProposta.

No entanto, numa análise preliminar verificou-se que há alguns relatórios gerenciais e diversas queries pelo sistema que utilizam essa tabela, causando um impacto de refatoração para adequação das queries. Gostaria de ouvir mais opiniões sobre as formas pensadas para resolução de tal questão.

**Comment by boletocosta** [comment]
Não entendi nada poderia traduzir? rs

**Comment by fernao** [comment]
o que define um projeto aprovado? 

* tbAvaliacaoProposta - conformidadeOk == 1
* PreProjeto - dtArquivamento is null

o que define um projeto arquivado? 

* PreProjeto - dtArquivamento is not null  (preencher dtArquivamento)

o que define um projeto desarquivado? 

*

**Comment by fernao** [comment]
Análise de impacto - continuação:

1) Admissibilidade: 
-> técnico de admissibilidade: adicionar campos idUnidade e idPerfil à gravação / inserção de nova avaliação
AdmissibilidadeController->salvaravaliacaoAction: adicionar campos
  - idUnidade(codOrgaoSuperior) 
  - idPerfil (codGrupo)

-> inserirdocumentoAction -> insere um registro na tbAvaliacaoProposta quando sobe um documento
-> exibirpropostacultural -> "histórico de avaliações" -> *DÚVIDA*: adicionar perfil avaliador ?

2) Enquadramento - avaliar:
-> obterProjetosParaEnquadramento - pega stEstado = 0 e idTecnico.
-> obterProjetosEnquadradosParaAssinatura - pega stEstado = 0 e idTecnico.
-> obterProjetosParaEnquadramentoVinculados - pega stEstado = 0 e idTecnico. 

3) AnalisarPropostaDAO:
-> possibilidade de impacto na visualização do projeto - não está filtrando tbAvaliacaoProposta (LEFT JOIN na função buscarGeral($idPreProjeto)
-> não está filtrando tbAvaliacaoProposta buscarHistorico($idPreProjeto)
-> inserirAvaliacao()

4) PreProjeto

ok
-> adicionar perfil nas listagens de tbAvaliacaoProposta

**Comment by fernao** [comment]
ALTER TABLE sac.dbo.tbAvaliacaoProposta ADD idPerfil int DEFAULT NULL

(dúvida: DEFAULT NULL ou NOT NULL ? Dúvida surgiu porque trata-se de uma tabela que já possui centenas de milhares de registros; por conta disso, preferiu-se deixar como DEFAULT NULL, muito embora o padrão das chaves externas seja NOT NULL)

**Comment by fernao** [comment]
Há uma trigger de insert na tbAvaliacaoProposta que deve ser alterada de modo a adicionar também o idPerfil.

**Comment by boletocosta** [comment]
Fernão, se uma solução para o impedimento envolve a possibilidade de o coordenador de admissibilidade também fazer avaliação para além do técnico pode mandar bala. O coordenador pode optar por fazer a avaliação sim. Aliás essa funcionalidade tem mesmo que existir, pois caso ele queira fazer novas diligências por conta própria ou mesmo "puxar" uma proposta para ele por conta da complexidade ou pressão política ele pode.

**Comment by fernao** [comment]
Olá André!

Atualmente é possível fazer tal análise, porém, sem rastreabilidade quanto ao perfil, visto que na tabela há apenas informações quanto ao usuário. Foi feita uma alteração para armazenar também os dados do perfil.

Entretanto, há uma instrução de banco (trigger) que é acionada toda vem que tento realizar uma inserção na tabela. Esta trigger se sobrepõe à minha tentativa de inserção, devendo ser ajustada na trigger de nome trAvaliacaoProposta_Insert. Para tal, necessito do auxílio da área técnica (Rômulo)

**Comment by fernao** [comment]
Editei a trigger adicionando o campo idPerfil, alterando o seguinte trecho da instrução:

    `INSERT INTO tbAvaliacaoProposta 
(idProjeto,idTecnico,DtEnvio ,DtAvaliacao,Avaliacao,ConformidadeOK,stEstado, idPerfil) `
`SELECT idProjeto,idTecnico,@DtEnvio,getdate()  ,Avaliacao,ConformidadeOK,0, idPerfil        FROM     Inserted`

**Comment by fernao** [comment]
Vou remover da coluna impedimento, mas a tarefa precisa de revisão

**Comment by boletocosta** [comment]
testado e tudo certo. Mas não entendi a relevância dessa tarefa, pois a mesma informação que o menu retrátil apresenta eu encontro clicando no "histórico de avaliações". Não é isso?

**Comment by fernao** [comment]
Não havia forma de saber se a avaliação era de um coordenador ou de um técnico pois na parte do banco de dados somente havia identificação a respeito do usuário. Caso um usuário acumule as funções de técnico e coordenador, já não é mais possível distinguir.

**Comment by boletocosta** [comment]
Blz..

**Comment by boletocosta** [comment]
Só um detalhe: na coluna Perfil nada aparece..está em branco... é assim mesmo?

**Comment by fernao** [comment]
Precisamos tratar como aparecerao os registros anteriores. Aparece em branco pois antes dessa modificiaçao esse registro nao era gravado. Qual seria o comportamento desejado?

**Comment by boletocosta** [comment]
O ideal seria mostrar nome (ou CPF) e perfil (técnico, coordenador, coordenador geral, funarte, cnic) do usuário que gravou a avaliação.
