### ISSUE TITLE
[Admissibilidade] Desarquivar Proposta perfil minc

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#292]
Eu como **tecnico de admissibilidade / coordenador de admissibilidade**  mediante solicitação do proponente posso desarquivar a proposta da seguinte forma: 

- Adicionar item de menu [desarquivamentos]  dentro do menu admissibilidade que ao clicar deverá aparecer uma lista com as propostas desarquivadas, ordenadas inicialmente pela data de solicitação de arquivamento. 
- a lista deverá aparecer com os seguintes campos :  
| número da proposta | nome da proposta | data de solicitação de desarquivamento |
- ao clicar em qualquer item da linha deverá abrir a proposta. 
- Ao abrir a proposta a primeira coisa que gostaria de visualizar em destaque seria a justificativa de arquivamento por parte do técnico e loga abaixo a justificativa de desarquivamento da parte do proponente. 
- Deverá alem disso ter abaixo das justificativas dois botões: [Aceitar] [Recusar] com os seguintes comportamentos: 
[aceitar]   - A proposta volta para caixa do perfil que fez o desarquivamento. - Envia email para o proponente informando.  
[recusar]  - A proposta continua na lista de arquivadas podendo ser visualizadas.  - Envia email para o proponente informando. 

   
* [x] Adicionar item de menu [desarquivamentos] 
* [x] Criar lista com as propostas com pedido de desarquivamento ordenadas inicialmente pela data de solicitação de arquivamento. Com:  | número da proposta | nome da proposta | data de solicitação de desarquivamento |
* [x] Ao clicar em qualquer item da linha deverá abrir a proposta; visualizar em destaque a justificativa de arquivamento por parte do técnico e logo abaixo a justificativa de desarquivamento da parte do proponente; botões [Aceitar] [Recusar]
* [x] Ação de aceitar: proposta volta para caixa do perfil que fez o desarquivamento. - Envia email para o proponente informando.
* [x] Ação de recusar: proposta continua na lista de arquivadas podendo ser visualizadas.  - Envia email para o proponente informando.

**Comment by boletocosta** [comment]
Galera, 

E-mail envaido ao proponente ao "aceitar o pedido de desarquivamento*: 

Senhor(a) Proponente,

O pedido de desarquivamento referente à proposta nº X foi aceito.  A proposta será desarquivada e seguirá em análise. Dessa forma, acompanhe diariamente a proposta no sistema em virtude de novas diligências e comunicados. 

**Importante** Com relação ao indeferimento do pedido de desarquivamento na verdade teria que abrir uma caixa texto para registrar o motivo da recusa. Aí o e-mail enviado para o proponente seria o texto gravado na recusa. O texto que será gravado na recusa já poderia vir preenchido. Semelhante ao que ocorre na gravação da justificativa para o arquivamento. Deu para entender?

Texto pré preenchido que será gravado ao *recusar o pedido de desarquivamento* e enviado por e-mail:

Senhor(a) Proponente,

O pedido de desarquivamento referente à proposta nº X  não foi aceito pelo seguinte motivo:

*Motivo da recusa*.

Salientamos que o proponente poderá inscrever e enviar novamente a mesma proposta ao MinC, desde que observada a restrição contida na alínea "c", inciso I do artigo 23 da Instrução Normativa nº 05/2017 do Ministério da Cultura.

**Comment by boletocosta** [comment]
Pessoal esse card está na sprint 08, mas até agora nem começo a ser feito... =(  

Provavelmente não vão entregar na sexta a tempo....

**Comment by boletocosta** [comment]
Ao aceitar o pedido de arquivamento tudo certo. Só não deu para verificar se o e-mail está sendo disparado para o proponente.

Contudo ao reprovar um pedido nada acontece. O pedido continua para análise.

***Além disso, Conforme escrevi no comentário do dia 19/01***:

Com relação ao indeferimento do pedido de desarquivamento na verdade teria que abrir uma caixa texto para ***registrar o motivo da recusa***. Aí o e-mail enviado para o proponente seria o texto gravado na recusa. O texto que será gravado na recusa já poderia vir preenchido. Semelhante ao que ocorre na gravação da justificativa para o arquivamento. Deu para entender?

Texto pré preenchido que será gravado ao recusar o pedido de desarquivamento e enviado por e-mail:

Assunto: Desarquivamento da proposta nº X

Senhor(a) Proponente,

O pedido de desarquivamento referente à proposta supracitada não foi aceito pelo seguinte motivo:

*Motivo da recusa*

Salientamos que o proponente poderá inscrever e enviar novamente a mesma proposta ao MinC desde que observada a restrição contida na alínea "c", inciso I do artigo 23 da Instrução Normativa nº 05/2017 do Ministério da Cultura.

**Comment by boletocosta** [comment]
Bom dia pessoal!. Alguma previsão da conclusão desse card?

Continuamos sem conseguir negar um pedido de desarquivamento, pois não temos a opção para escrever os motivos do indeferimento.  

Sugiro ler meus comentários do dia 19/01 e 23/02 para solucionar a questão.

Valeu...

**Comment by wouerner** [comment]
@boletocosta André o @Romulo_Menho  náo priorizou essa tarefa, por favor alinhar com ele, quando isso ira entrar em execução.

**Comment by wouerner** [comment]
@Pedro-Philipe vai atender essa demanda agora: @boletocosta

**Comment by Pedro-Philipe** [comment]
@boletocosta Estou precisando do template do email que será enviado após a avaliação do desarquivamento da proposta, Obrigado !

**Comment by boletocosta** [comment]
E-mail envaido ao proponente ao ***aceitar o pedido de desarquivamento***:

"Assunto: Desarquivamento da proposta nº X

Senhor(a) Proponente,

O pedido de desarquivamento referente à proposta supracitada foi aceito.  A proposta será desarquivada e seguirá em análise. Dessa forma, acompanhe diariamente a proposta no sistema em virtude de novas diligências e comunicados".

-------------

E-mail envaido ao proponente ao ***negar o pedido de desarquivamento***:

"Assunto: Desarquivamento da proposta nº X

Senhor(a) Proponente,

O pedido de desarquivamento referente à proposta supracitada não foi aceito pelo seguinte motivo:

*texto gravado no motivo da recusa*. 

Salientamos que o proponente poderá inscrever e enviar novamente a mesma proposta ao MinC desde que observada a restrição contida na alínea "c", inciso I do artigo 23 da Instrução Normativa nº 05/2017 do Ministério da Cultura."

---------

Importante: com relação ao indeferimento do pedido de desarquivamento tem que abrir uma caixa texto para registrar o motivo da recusa. Aí o e-mail enviado para o proponente seria o modelo acima + o texto gravado no motivo da recusa.

**Comment by Pedro-Philipe** [comment]
@boletocosta Poderia testar por favor? Só está com detalhe na contagem dos dados da paginação. Mas como a funcionalidade em si ja foi terminada, subi para teste.

**Comment by Pedro-Philipe** [comment]
@Pedro-Philipe Não consegui fazer uma operação no banco, o que vai causar um erro no fluxo. Segunda de manhã já estará tudo ok. Obrigado e boa noite

**Comment by AdmissibilidadeSAV** [comment]
Quando você consulta no sistema qualquer proposta que foi arquivada e que foi solicitado o desarquivamento, as informações não ficam registradas na proposta (deveriam constar no histórico). Essa informação só aparece para o proponente quando clica em listar propostas arquivadas.

No perfil do Coordenador de Admissibilidade menu Admissibilidade - Desarquivamento quando as propostas estão com status Aprovado e Reprovado não é possível visualizar o pedido de desarquivamento do proponente. Nessa mesma tela deveria também ter a opção de ao clicar em cima do n° da proposta abri-la para consulta. 

Já em relação a aprimoramento seria ideal se tivesse um menu retrátil com as opções "Em análise" e"Analisadas" visando filtrar as solicitações para facilitar a visualização e a análise do coordenador. Outra coisa que também seria muito bom é ao clicar na coluna "Data da Solicitação" as mesmas listassem por ordem crescente ou decrescente.

**Comment by Pedro-Philipe** [comment]
```sql
ALTER TABLE SAC.dbo.PreProjetoArquivado ADD AnaliseDesarquivamento varchar(max)
ALTER TABLE SAC.dbo.PreProjetoArquivado ADD dtAnaliseDesarquivamento varchar(max)
ALTER TABLE SAC.dbo.PreProjetoArquivado ADD idAvaliadorAnaliseDesarquivamento varchar(max)
ALTER TABLE SAC.dbo.PreProjetoArquivado ADD ultimaSolicitacao int
```

**Comment by Pedro-Philipe** [comment]
Impedimento: Necessidade da cópia da base de produção para prossegir com o desenvolvimento.

**Comment by boletocosta** [comment]
Boa tarde Pedro... alguma novidade? Lembrando que além do comentário da Thais do dia 10/04 ainda tem o detalhe na contagem dos dados da paginação. Valeuu!!

**Comment by Pedro-Philipe** [comment]
@boletocosta Recomecei a fazer a demanda, pois tive de parar ela sexta dia 13/04 devido aos impedimentos de banco

**Comment by boletocosta** [comment]
Homologado!

**Comment by romulomb** [comment]
Pode subir para produção.

**Comment by boletocosta** [comment]
na verdade ficou faltando só um detalhe:  quando você consulta no sistema qualquer proposta que foi arquivada e que foi solicitado o desarquivamento, as informações não ficam registradas na proposta.

deveria ser criado um campo de histórico de desarquivamento (igual existe para histórico de avaliações e enquadramento)

**Comment by AdmissibilidadeSAV** [comment]
Ficou ótimo, mas uma coisa importante que ficou faltando é aparecer as propostas separadas por órgão, no meu perfil aparece tanto as da SAV como da SEFIC, quando deveria aparecer só as que foram classificadas como Audiovisual.
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/fea72eda-5745-44e8-ae32-65a4cf53b327)

**Comment by romulomb** [comment]
Para separar as propostas SAV e da SEFIC, utilize o atributo AreaAbrangencia da tabela PreProjeto.

AreaAbrangencia = 0 -- proposta da SAV

AreaAbrangencia = 1 -- proposta da SEFIC

Acrescentar campo de pesquisa pelo nº da proposta.

**Comment by decko** [comment]
@romulomb e @boletocosta, entendi que o que foi trabalhado até o dia 18/04, foi homologado por vocês e está em produção. As novas sugestões a partir desse ponto, poderiam ser colocadas em uma nova issue com estimativa e rastreabilidade corretas.

Podemos fechar esta issue e planejar a execução dessas novas sugestões?

**Comment by romulomb** [comment]
Tem como levar o que foi depois do dia 18/04 para uma nova issue?

Se puder levar eu fecharei a issue, isso para não perder o que foi adicionado pelo pessoal.
