### ISSUE TITLE
[SugestãoEnquadramento] Encaminhamento de Proposta

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#296]
Eu como Técnico Admis / Coordenador Admis. / C. Geral Admis. / CNIC / Coordenador Pronac gostaria que o enquadramento de propostas culturais se comportassem da seguinte maneira:

Após avaliação o sistema deve permitir encaminhar para o próximo ator nos seguinte cenários:

- Para o caso de técnico de admissibilidade pode apenas enviar para coordenador / . C. Geral de admissibilidade.

~~As informações abaixo fazem parte de uma nova issue.~~
~~- Para caso coordenador / C. Geral de admissibilidade - haverão duas alternativas:~~
~~* [Se dúvidas] pode enviar para as  vinculadas~~
~~* [senão] enviar direto para CNIC~~

**Comment by vinnyfs89** [comment]
Conforme acordado na última reunião o foco dessa atividade será no encaminhamento do Técnico para Coordenador de Admissibilidade.

**Comment by marcusvinicus** [comment]
Conforme concordamos em reunião com a área, devemos manter o fluxo atual como funciona atualmente para os perfis Técnico de Admissibilidade e Coordenador de Admissibilidade. 

Ao encaminhar deve ser exido, de acordo com a unidade, qual o perfil que deve ser encaminhado.

Para perfis diferentes de Coordenador de Admissibilidade e Técnico de admissibilidade, devem ser exibidas as propostas para avaliação que estão atribuídas para o perfil dentro da área (Órgão Superior).

Dados técnicos:

- Modificar a tabela sac.dbo.tbMovimentacao, adicionando as colunas:
    * id_orgao
    * id_perfil

**Comment by boletocosta** [comment]
Só lembrando que no perfil de técnico o botão de transformar ou arquivar proposta deve estar desabilitado. Quem poderá fazer isso é o coordenador/coordenador geral.

**Comment by vinnyfs89** [comment]
Detalhes técnicos da modificação do banco de dados para comportar o novo fluxo:

```
    ALTER TABLE sac.dbo.tbMovimentacao ADD id_orgao INT NULL;
    ALTER TABLE sac.dbo.tbMovimentacao ADD id_perfil INT NULL;
```

**Comment by vinnyfs89** [comment]
* Checklist
- [ ] Tabela no banco de dados e Mapeamentos na aplicação para distribuição de avaliação da proposta
- [ ] Tratamento para exibição do botão e coluna de encaminhamento
- [ ] Tratamento para exibição de propostas para avaliação de acordo com o perfil do usuário logado
- [ ] Diálogo com modal para seleção de qual perfil o usuário deseja encaminhar a avaliação

**Comment by vinnyfs89** [comment]
Detalhes técnicos da modificação do banco de dados para comportar o novo fluxo:

CREATE TABLE distribuicao_avaliacao_proposta
(
    id_distribuicao_avaliacao_proposta INT PRIMARY KEY NOT NULL IDENTITY,
    id_preprojeto INT NOT NULL,
    id_orgao_superior INT NOT NULL,
    id_perfil INT NOT NULL,
    data_distribuicao INT NOT NULL,
    avaliacao_atual BIT DEFAULT 0 NOT NULL,
    CONSTRAINT distribuicao_avaliacao_proposta_PreProjeto_idPreProjeto_fk FOREIGN KEY (id_preprojeto) REFERENCES PreProjeto (idPreProjeto)
);

/*
  avaliacao_atual
  0 - Inativa
  1 - Ativa
*/

**Comment by boletocosta** [comment]
Bom dia galera. Segue o fluxo de enquadramento de propostas que pensei (excluindo vinculada, pois é opcional e conseguimos trabalhar sem por enquanto):

*No perfil de Coordenador de Admissibilidade*:

Após visualizar o enquadramento realizado pelo técnico o Coordenador vai salvar sua sugestão de enquadramento. Depois de gravado o enquadramento do Coordenador ele precisa enviar a proposta para os componentes da CNIC (novo botão).  

*No perfil da CNIC*:

O componente da CNIC precisa ter acesso a um novo menu chamado "propostas enquadradas" onde vai visualizar a lista de propostas que foram enviadas pelo Coordenar de Admissibilidade para sugestão de enquadramento. Nessa listagem também deve ter a quantidade de dias que a proposta entrou na  "caixa", pois ele tem apenas 05 dias para fazer uma sugestão de enquadramento.  Após ele acessar a proposta também deve ter um botão para  enquadrar proposta (mesma funcionalidade do técnico e do coordenador). A CNIC não realizará diligências nessa fase, ou seja, não tem avaliação. É só a sugestão de enquadramento mesmo. *Importante*: quando o componente da CNIC salvar o enquadramento da proposta ou se esse enquadramento não for realizado dentro de 05 dias, a proposta "some" da caixa da CNIC e deve "aparecer" para o perfil de Coordenador Geral no novo menu que será criado (ver abaixo).  

*No perfil da Coordenar Geral*:

Precisa ter acesso a um novo menu chamado "propostas enquadradas" onde vai visualizar a lista de propostas para realizar o enquadramento (ou seja, já foram enquadradas pelo técnico, coordenador e CNIC).  Mas o coordenar geral deve ter acesso a avaliação da proposta (mesma funcionalidade de técnico e coordenador), pois ele poderá realizar diligências antes de enquadrar a proposta .  *Importante*: quando o coordenador geral salvar o enquadramento da proposta ela "some" da caixa da caixa e deve "aparecer" para o perfil de Coordenador de Admissibilidade no novo menu que será criado (ver abaixo).  


*No perfil de Coordenador de Admissibilidade*:

Precisa ter acesso a um novo menu chamado "propostas enquadradas" onde vai visualizar a lista de propostas para realizar o enquadramento (ou seja, já foram enquadradas pelo técnico, pelo próprio coordenador de admissibilidade, CNIC e Coordenador Geral).  O coordenar deve ter acesso a avaliação da proposta, pois ele poderá realizar diligências, arquivar ou finalmente transformar a proposta em projeto.

Deu para entender mais ou menos?

**Comment by vinnyfs89** [comment]
Foi necessário adiocionar uma regra para que seja possível encaminhar uma avaliação de proposta mantendo seu histórico:

* Sempre ao encaminhar a avaliação da proposta a situação das avaliações anteriores (histórico) é definida como inativada e o novo registro será mantido como o ativo para que o fluxo consiga ser concluído.

**Comment by vinnyfs89** [comment]
Imagens da execução do fluxo de encaminhamento de avaliações de propostas mantendo a forma antiga, mas acrescentando o fluxo de avaliação de acordo com o perfil do usuário logado.

###  Técnico de Admissibilidade 
![Screenshot from 2018-01-30 20-36-24.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/97e3fdb6-b865-43d0-92d1-aea321a2ea28)

![Screenshot from 2018-01-30 20-36-32.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/6f02dbbc-70f0-424d-954f-09876bb56771)

![Screenshot from 2018-01-30 20-36-35.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/2edac72a-4d34-4177-b8b2-c86b2b29c4a6)

![Screenshot from 2018-01-30 20-36-41.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/1f6ec5db-2797-4421-97b1-18f9044f6264)

###  Coordenador de Admissibilidade 

![Screenshot from 2018-01-30 20-37-25.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/bb2dc34f-272d-426b-ab65-012997c7956d)

**Comment by boletocosta** [comment]
Blz!!!. Libera para teste aí...=)

Agora falta acrescentar o fluxo coordenador -> cnic -> coordenador geral -> coordendor   ....   da forma que expliquei nos comentários acima....

**Comment by vinnyfs89** [comment]
@boletocosta Beleza! Mas esse trecho da CNIC e vinculadas ainda não entra nessa sprint 😁

**Comment by boletocosta** [comment]
Melhoria: o técnico tem que conseguir encaminhar para o Coordenador mesmo sem enquadrar, apenas com a avaliação realizada. Motivo: na avaliação o técnico vai sugerir o arquivamento e encaminhar para o coordenador sem enquadrar a proposta. Blz?

**Comment by boletocosta** [comment]
Outra melhoria: após o técnico encaminhar a proposta ela precisa "sumir" do perfil de técnico.

**Comment by vinnyfs89** [comment]
@boletocosta Beleza, desde nossa ante-penúltima reunião na qual o Rômulo participou, ele mesmo informou que o enquadramento não deve ser obrigatório na avaliação, independente do perfil.

**Comment by vinnyfs89** [comment]
@boletocosta Bacana. Podemos incluir essa atividade na próxima sprint, caso seja interesse de vocês. 👍🏼
A demanda de encaminhamento atual está de acordo com o que conversamos?

**Comment by boletocosta** [comment]
Só falta sumir da caixa do técnico após ele enviar ao coordenador. Creio não dar muito trabalho e seria essencial ficar pronto até sexta (na verdade até amanhã seria demais... rs)

**Comment by vinnyfs89** [comment]
@boletocosta , Entemos que o último item solicitado é uma melhoria. Visto que pretendemos subir o que foi testado até o momento para ambiente de produção hoje, consideramos que não há tempo hábil para desenvolver e testar a melhoria.
Existe alguma outra questão combinada na segunda feira que não está de acordo?

**Comment by boletocosta** [comment]
Poxa.. pelo menos até sexta então na entrega do card... 

De resto tudo certo.

**Comment by vinnyfs89** [comment]
@boletocosta Então vamos subir como está hoje para prod e vou me esforçar para tentar concluir até sexta essa melhoria. Combinado?

**Comment by boletocosta** [comment]
blz

**Comment by vinnyfs89** [comment]
@boletocosta Acabei de finalizar a melhoria aplicando as regras solicitadas.
O item já está disponível no ambiente de testes para validação.

**Comment by boletocosta** [comment]
Conforme conversamos na reunião, sugiro que no histórico de enquadramento fosse incluído duas colunas mostrando a área e o segmento que cada pessoa gravou na avaliação de enquadramento.

**Comment by vinnyfs89** [comment]
Senhores a melhoria foi realizada, foi adicionada as duas colunas Área e Segmento, conforme solicitado.

Fizemos um deployment para o ambiente http://hmg.salic.cultura.gov.br .

Por gentileza verificar.
