### ISSUE TITLE
[Admissibilidade] Exibir/remover campos na avaliação da proposta

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#301]
Eu como técnico de admissibilidade ou coordenador de admissibilidade quero ver os campos conforme dados enviados pela nova IN.
-Na tela de avaliação: 
* [x] Exibir descrição da atividade

-Na tela de gerar PDF:
* [x] Exibir descrição da atividade

**Comment by isaiassm** [comment]
Durante o desenvolvimento, viu-se necessária a mudança também na parte de Gerar PDF aonde existia ainda o campo Impacto Ambiental, e não tinha o campo Descrição da Atividade.

**Comment by wouerner** [comment]
Executado!
