### ISSUE TITLE
Deploy Produção

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#324]
Nós como equipe de desenvolvimento, precisamos fazer deployment para produção utilizando a versão estável da branch develop e assim como executar os scripts de banco de dados, conforme necessidade da área.

**Comment by vinnyfs89** [comment]
@vinnyfs89 Prezados, estamos iniciando o processo de deployment do código-fonte e banco de dados.

**Comment by vinnyfs89** [comment]
Heron, segue o arquivo com todos os scripts sql concatenados para serem executados no ambiente de produção:

https://github.com/culturagovbr/salic-minc/blob/develop/sql/SQLServer/dbchangelog/2018.sql

**Comment by heronbonfim** [comment]
Script executado com sucesso. Um backup da trigger alterada foi realizado caso seja necessário restauração.
