### ISSUE TITLE
Sugestão Enquadramento - Coordenador de Admissibilidade

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#349]
Eu como **Coordenador de Admissibilidade** gostaria de poder encaminhar a proposta para CNIC para ter os seguintes beneficios: 
- Permitir o fluxo da proposta de acordo com a nova IN.  

Esta funcionalidade de ter o seguinte comportamento: 
- Ter um botão enviar proposta para CNIC 
- pré-condição para envio: selecionar a área e o segmento ( como sugestão de enquadramento ). 
- A proposta deve cair na caixa da CNIC da área selecionada.

**Comment by vinnyfs89** [comment]
Após analisar o banco de dados identificamos que todos os perfis abaixo tem relação com CNIC. Precisamos saber para qual dos perfis o coordenador de admissibilidade deve enviar a proposta para análise da CNIC.

Os perfis cadastrados no banco de dados são:

- CNIC
- Membros Natos da CNIC
- Componente da Comissão
- Presidente da CNIC
- Coordenador CNIC

**Comment by vinnyfs89** [comment]
utilizaremos o perfil "Componente da Comissão" caso seja um perfil diferente, por gentileza nos informar

**Comment by vinnyfs89** [comment]
Checklist

- [ ] Ter um botão enviar proposta para CNIC
- [ ] Pré-condição para envio: selecionar a área e o segmento ( como sugestão de enquadramento ).
- [ ] A proposta deve cair na caixa da CNIC da área selecionada.

**Comment by boletocosta** [comment]
É esse perfil mesmo!

**Comment by vinnyfs89** [comment]
Dados Tecnicos:
Foi identificada a necessidade de criar uma coluna chamada id_orgao_superior na tabela 'sac.dbo.sugestao_enquadramento'

**Comment by vinnyfs89** [comment]
Para o perfil "Coordenador de admissibilidade" adicionei na tela de Sugestão de Enquadramento a seguinte mensagem para carater informativo.

``` 

OBS: A seleção dos campos Área e Segmento é essencial para encaminhar a avaliação da Proposta Cultural

``` 

![Screenshot from 2018-02-07 15-47-29.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/1d95daa8-fc8a-47fe-8f2b-008a6772bf3f)

**Comment by vinnyfs89** [comment]
Adicionei também um tratamento para quando a área e segmento não são informados preencher o histórico das sugestões com um ' - '

**Comment by boletocosta** [comment]
Testei aqui e deu certo

**Comment by boletocosta** [comment]
Testado e aprovado
