### ISSUE TITLE
[PROPOSTA] Bug ao anexar documento

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#350]
Eu como proponente ao tentar anexar documento em minha proposta, não consigo selecionar o tipo de documento e o mesmo é obrigatório.

**Comment by boletocosta** [comment]
Existe mesmo esse bug? Aqui no meu perfil de proponente funciona normal...

**Comment by clebersantos** [comment]
@boletocosta Sim, o campo para selecionar o tipo de documento não aparece.

**Comment by wouerner** [comment]
Resolvido.
