### ISSUE TITLE
[CNIC] Bug ao finalizar a análise após assinatura

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#351]
Eu como comissário da CNIC, não consigo finalizar a análise após assinatura.![bug-assinatura.jpg](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/22fd7a1e-40b8-4585-bf91-fd81228cd0ee)

**Comment by clebersantos** [comment]
Verificar também erro na análise inicial -> http://hmg.salic.cultura.gov.br/gerenciarpautareuniao/gerenciarpautareuniao/readequacao/false/plenaria/false

**Comment by clebersantos** [comment]
Coordenador da CNIC - Menu: Análise -> Reunião CNIC -> http://hmg.salic.cultura.gov.br/gerenciarpautareuniao/gerenciaradministrativo

**Comment by fernao** [comment]
A ferramenta de assinatura da CNIC vigente na IN de 2017 tinha uma parte que buscava informações de enquadramento utilizando a view vwEnquadramentoDoProjeto.

Nessa consulta, havia uma cláusula que restringia a listagem de enquadramentos às situações seguintes:

B02 se a data fosse maior que 10 dias a contar da data da situação
ou
B03 ou B11.

O bug reportado semana passada surgiu quando projetos com a situação C10 começaram a chegar à caixa da CNIC.

Vocês sabem de alguma alteração nesse sentido?
