### ISSUE TITLE
Sugestão de enquadramento CNIC

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#352]
Eu como **componente da comissão - CNIC** gostaria de fazer sugestão de enquadramento para que tenha os seguintes benefícios: 
- Dar continuidade ao fluxo da nova IN  

com o seguinte comportamento:  

- Acessar a funcionalidade de sugerir enquadramento pelo Menu:  Admissibilidade -> Avaliação 
- Ao entrar nesse menu gostaria de enxergar todas as propostas para fazer avaliação, 
- As propostas devem ser apresentadas com tempo restante para sair da caixa da CNIC; que inicia sempre com a chegada ca proposta a caixa da CNIC e tem o prazo de 5 dias. 
- quando clicar no botão para avaliar gostaria de ter ter habilitado para mim apenas a funcionalidade de sugestão de enquadramento. 
- gostaria que caso entenda não ter capacidade de realizar a sugestão de enquadramento, possa encaminhar para outra área dentro da cnic que entenda ter essa capacidade. 
- Ao finalizar o enquadramento gostaria de ter um botão para encaminhar para a próxima área no fluxo [Coordenador Geral, CNIC ( não fui capaz de enquadrar) ]
~~- Caso a proposta tenha recebido a sugestão de enquadramento e tenha se passado o prazo de 5 dias sem ser enviada, ela deve ser encaminhada automaticamente para o **Coordenador geral** com a sugestão de enquadramento realizada.~~
~~- Caso a proposta não tenha recebida nenhum sugestão de enquadramento no prazo final dos 5 dias, ela deve ser automaticamente encaminhada para o *Coordenador Geral* concordando tacitamente com o enquadramento do Coordenador de Admissibilidade.~~
~~- A mensagem que ficará gravada na sugestão de enquadramento.   {a área vai enviar a msg de aprovação tácita}, a A área e segmento deve continuar a mesma do coordenador de admissibilidade.~~ 
As tarefas tachadas foram movidas para a issue #359

**Comment by fernao** [comment]
Como cadastrar novo componente da comissão:

1) Associar perfil de componente da cnic a um perfil
- entrar como 'Gestor Salic'
- menu 'administrativo -> manter agentes'
- adicionar perfil de 'componente da comissão' ao login desejado

2) Associa área e segmento a componente
- entrar como 'Coordenador CNIC'
- menu 'administrativo -> manter agentes'
- pesquisar por cpf
- menu 'área cultural': vincular área e segmento

**Comment by vinnyfs89** [comment]
Checklist:

- [ ] Acessar a funcionalidade de sugerir enquadramento pelo Menu:  Admissibilidade -> Avaliação 
- [ ] Ao entrar nesse menu gostaria de enxergar todas as propostas para fazer avaliação, 
- [ ] As propostas devem ser apresentadas com tempo restante para sair da caixa da CNIC; que inicia sempre com a chegada ca proposta a caixa da CNIC e tem o prazo de 5 dias. 
- [ ] quando clicar no botão para avaliar gostaria de ter ter habilitado para mim apenas a funcionalidade de sugestão de enquadramento. 
- [ ] gostaria que caso entenda não ter capacidade de realizar a sugestão de enquadramento, possa encaminhar para outra área dentro da cnic que entenda ter essa capacidade. 
- [ ] Ao finalizar o enquadramento gostaria de ter um botão para encaminhar para a próxima área no fluxo [Coordenador Geral, CNIC ( não fui capaz de enquadrar) ]

**Comment by vinnyfs89** [comment]
Alteração de banco realizada. 

Segue os scripts executados no banco de dados:
```
-- Adição da coluna 'ultimo_enquadramento' na tabela 'sac.dbo.sugestao_enquadramento'
ALTER TABLE sac.dbo.sugestao_enquadramento ADD ultimo_enquadramento BIT DEFAULT 0 NULL

-- Ajuste de dados antigos da tabela 'sac.dbo.sugestao_enquadramento'

update enquadramento set ultimo_enquadramento = 1
--select count(*)
from sac.dbo.sugestao_enquadramento enquadramento
  inner join (select max(data_avaliacao) as data_avaliacao, id_preprojeto
              from sac.dbo.sugestao_enquadramento
              GROUP BY id_preprojeto
             ) tabela_temporaria
    on enquadramento.id_preprojeto = tabela_temporaria.id_preprojeto
    and enquadramento.data_avaliacao = tabela_temporaria.data_avaliacao
where enquadramento.ultimo_enquadramento is null

update enquadramento set ultimo_enquadramento = 0
from sac.dbo.sugestao_enquadramento enquadramento
where enquadramento.ultimo_enquadramento is null
--COMMIT TRANSACTION ;
--ROLLBACK TRANSACTION ;

-- Definindo coluna id_orgao_superior como obrigatório
ALTER TABLE sac.dbo.sugestao_enquadramento ALTER COLUMN ultimo_enquadramento BIT NOT NULL;
``
Partindo para alteração na aplicação.

**Comment by vinnyfs89** [comment]
Checklist:
- [ ] Criar functionalidade que pode ser acessada através de um link e que também será acessada pela CronJob para que de tempos em tempos tire as propotas para avaliação que estão na carga do Membro da Comissão que estão com prazo superior a 5 dias e movimente automaticamente para o Coordenador Geral

**Comment by vinnyfs89** [comment]
Como medida de segurança foi identificada a necessidade da criação de um tratamento para acesso a funcionalidade encaminha tacitamente a avaliação para Coordenador Geral de Admissibilidade em casos que ultrapassem 5 dias na caixa do Membro da Comissão.

O tratamento é feito através de uma validação de 2 fatores, no qual são verificados:
* No primeiro fator o valor definido para um hash dentro do arquivo de configuração dentro da aplicação
* No segundo fator é informado por url qual o hash para acessar essa funcionalidade. 

Dessa maneira conseguimos evitar ataques por essa url, pois a rotina utilizada pela CronJob só funcionará se possuir o hash correto

**Comment by boletocosta** [comment]
Testado e aprovado
