### ISSUE TITLE
[Admissibilidade] Sugestão de Enquadramento Coordenador Geral

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#353]
Eu como **Coordenador Geral** gostaria de fazer sugestão de enquadramento para que tenha os seguintes benefícios:

- Dar continuidade ao fluxo da nova IN

com o seguinte comportamento:

- Acessar a funcionalidade de sugerir enquadramento pelo Menu:  Admissibilidade -> Avaliação
- Ao entrar nesse menu gostaria de enxergar todas as propostas que foram distribuídas para seu perfil para fazer avaliação,
- A funcinalidades de dilegência deve esta habilitada no mesmo moldes do coordenador de admissibilidade e tecnico de admissibilidade. 
- Ao finalizar o enquadramento gostaria de ter um botão para encaminhar para a próxima área no fluxo [**Coordenador de Admissibilidade**] 
- Ao enviar a proposta deve sair da caixa dele

**Comment by vinnyfs89** [comment]
André  e @thais_mendess  boa tarde, tudo bom?
Estou atacando a atividade de encaminhamento para perfil Coordenador Geral
Ao consultar os perfis no banco de dados identifiquei que existem vários perfis entitulados Coordenador Geral
Gostaria de saber qual deles deve ser utilizado pela avaliação da proposta:

* Coordenador-Geral de Admissibilidade e Aprovação
* Coordenador Geral de Acompanhamento e Prestação de Contas
* Coordenador - Geral de Acompanhamento
* Coordenador - Geral  de Prestação de Contas
* Coordenador - Geral de Análise

**Comment by vinnyfs89** [comment]
Thais comentou que o correto é: Coordenador- geral de admissibilidade e aprovação

**Comment by vinnyfs89** [comment]
André e Thaís, Após analisar o fluxo de avaliação de proposta surgir a seguinte dúvida, à partir desse momento, as propostas só poderão ser transformadas em projeto após terem ao menos uma sugestão de enquadramento vinda da CNIC, ou efetuadas diretamente ou efetuadas tacitamente . Correto?

**Comment by vinnyfs89** [comment]
Conforme conversamos com André(SEFIC) e Thaís(SAV) , à partir de agora as propostas só poderão ser transformadas em projeto após ter ao menos uma avaliação normal ou tacitamente por parte do perfil "Componente da Comissão".

Os perfis que podem efetuar a transformação de proposta em projeto são:
- Coordenador de Admissibilidade;
- Coordenador Geral de Admissibilidade.

**Comment by vinnyfs89** [comment]
Conforme conversado com Thais e André, no fluxo somente o Coordenador Geral transformará a proposta em projeto.

**Comment by boletocosta** [comment]
Vicente sugere que o Coordenador de Admissibilidade também possa transformar se ele quiser.

**Comment by vinnyfs89** [comment]
@boletocosta Conforme conversamos, não vai de acordo com o que foi acordado e planejado para o desenvolvimento anteriomente. O combinado foi permitir a transformação de proposta em projeto somente  para Coordenador Geral de Admissibilidade. 

Caso tenham essa necessidade, do ponto de vista da aplicação e com a modelagem da aplicação e banco de dados criados a partir dos itens levantado com vocês anteriormente, a possibilidade viável é:

- Permitir encaminhar a proposta da visão Coordenador Geral de ADmissibilidade de volta para Coordenador de Admissibilidade

Lembrando que essa sugestão dada acima não foi implementada, atualmente o fluxo encerra com o Coordenador Geral de Admissibilidade.

Para um funcionamento diferente do comentado, será necessário um esforço maior para adaptar a aplicação e todos os itens que já foram entregues e validados por vocês para que estejam de acordo com o que estão precisando.

**Comment by AdmissibilidadeSAV** [comment]
@boletocosta Pelo amor de Deus, minha coordenadora-geral não tem a menor condição de ficar por conta de transformar proposta em projeto, não sei nem pq o técnico não pode transformar. Aqui na SAV a equipe é bem reduzida e as atribuições de cada coordenação são muitas.

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Outra opção seria criar uma rotina parecida com a do coordenador de cnic para que aprove tacitamente e reencaminhe para coordenador de admissibilidade
