### ISSUE TITLE
CNIC - Criar rotina para fechar prazo de 5 dias de análise da CNIC

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#359]
- Buscar as propostas para avaliação da CNIC que já passaram do prazo.
- Caso a proposta tenha recebido a sugestão de enquadramento e tenha se passado o prazo de 5 dias sem ser enviada, ela deve ser encaminhada automaticamente para o Coordenador geral com a sugestão de enquadramento realizada.
- Caso a proposta não tenha recebida nenhum sugestão de enquadramento no prazo final dos 5 dias, ela deve ser automaticamente encaminhada para o Coordenador Geral concordando tacitamente com o enquadramento do Coordenador de Admissibilidade
- A mensagem de aprovação tácita que ficará gravada na sugestão de enquadramento será enviada pela área. 
- A área e segmento deve continuar a mesma do coordenador de admissibilidade.

**Referencia:**
#358

**Comment by vinnyfs89** [comment]
Checlist:
- [ ] Buscar propostas para avaliação que ultrapassaram 5 dias para usuários com perfil Componentes da Comissão
- [ ] Movimentar todas as propostas para perfil Coordenador Geral de Admissibilidade automaticamente, mantendo informações anteriores e com comentário especificado na Issue anterior informando que foi revogado tacitamente.
- [ ] Criar Crontab que tem como responsabilidade executar essa rotina de verificação a cada 5 minutos
- [ ] Aplicar a rotina em um dos nós do ambiente de homologação
- [ ] Aplicar a rotina em um dos nós do ambiente de produção

**Comment by vinnyfs89** [comment]
Definições de crontab aplicadas no ambiente de homologação.

Para editar as crontabs atual.
```
    sudo crontab -e
```
Adicionado o conteúdo abaixo.
```
5  0    * * *   root    wget -o /var/www/cron/salic-minc/propostas-avaliacoes -q http://hmg.salic.cultura.gov.br/admissibilidade/enquadramento-proposta/tratar-avaliacoes-vencidas-componentes-comissao?hash=*********
```

Para listar as crontabs cadastradas:

```
	sudo crontab -l
```

**Comment by wouerner** [comment]
Seria bom documentar isso dentro do projeto já que issues vão ser arquivadas no futuro, acho que uma pasta na raiz do projeto estilo cronjobs.md, deixaria todos ciente que existem cronjobs

**Comment by vinnyfs89** [comment]
@wouerner vc chegou a ver o que fiz nesse arquivo? https://github.com/culturagovbr/salic-minc/tree/feature-encaminhar-avaliacao-proposta-cnic/application/modules/admissibilidade
