### ISSUE TITLE
[PROPOSTA] Bug no histórico de avaliações

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#372]
## O que deveria/poderia acontecer? 
As avaliações salvas após análise e o registo do envio da proposta ao MinC devem aparecer em ordem cronológica  no histórico de avaliações.

## O que atualmente está acontecendo? 
As avaliações salvas após análise e o registo do envio da proposta ao MinC ***não*** aparecem na ordem cronológica correta no histórico de avaliações.

## Qual poderia ser a solução? 
Aparecer na ordem cronológica correta.

**Comment by vinnyfs89** [comment]
Essa regra não foi especificada anteriormente durante o processo de criação da funcionalidade. Apesar de simples de ser resolvido não é um bug.

@boletocosta atualmente a ordenação de sugestões de assinatura está sendo exibida em ordem crescente, você deseja que ela seja exibida em ordem decrescente, correto?

**Comment by vinnyfs89** [comment]
Código alterado.

**Comment by boletocosta** [comment]
É o seguinte: preciso que no histórico de avaliações os registros apareçam em ordem cronológica. Exemplo: dia 07/02 Proposta foi enviada ao MinC. dia 08/02 recebeu a primeira diligência. dia 10/02 Proposta foi enviada ao MinC novamente. dia 11/02 recebeu segunda diligência. dia 15/02 proposta enviada ao minc novamente.. dia 17/02 proposta encaminhada ao coordenador..  etc
 Atualmente está tudo misturado e fora de ordem. Antes era em ordem cronológica, por isso relatei como bug

**Comment by wouerner** [comment]
Vamos tratar isso como melhoria.

**Comment by boletocosta** [comment]
Pq melhoria? Antes do sistema abrir dia 01/02  funcionava normal. Abriu o sistema e veio com esse "bug". Não creio ser melhoria, mas sim um bug devido alguma alteração.  Mas enfim.. o importante é ajustar..

**Comment by vinnyfs89** [comment]
Desculpe, houve um equivoco nosso. Confundimos essa funcionalidade com o histórico de sugestões de enquadramento. Vamos verificar.

**Comment by wouerner** [comment]
Corrigido a classificação. @boletocosta

**Comment by boletocosta** [comment]
Alguém cuidando desse bug? Está atrapalhando bastante...
