### ISSUE TITLE
[Parecerista] Readequação – Não é possível avaliar a planilha orçamentária, emitir e assinar o parecer - quebra de tela

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#392]
Eu como parecerista 

Readequação – Não não consigol avaliar a planilha orçamentária, emitir e assinar o parecer

**Comment by marcusvinicus** [comment]
Estamos aguardando mais informações desse BUG

**Comment by clebersantos** [comment]
Já foi corrigido o carregamento da planilha de 50%, confirmar se era esse o erro.
