### ISSUE TITLE
[PROPONENTE] Cálculo dos Custos vinculados

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#394]
Informado que estava apresentando erro nos cálculos dos custos vinculados; 

![calculo dos custos vinculados.jpg](https://images.zenhubusercontent.com/5a5e41a54b5806bc2bc2fa8a/177c3e0f-0983-4782-8197-93f6ee1451e8)

**Comment by marcusvinicus** [comment]
Estamos aguardando mais informações sobre esse erro.

**Comment by clebersantos** [comment]
@boletocosta, sabe de algum erro referente ao Custos Vinculados?

**Comment by boletocosta** [comment]
Até onde sei não
