### ISSUE TITLE
[BUG][CNIC] Erro assinar finalizar parecer

### ISSUE THREAD

**Issue by marcusvinicus** [culturagovbr/salic-minc#406]
o seguinte erro está aparecendo quando tento assinar/finalizar o parecer: 

![bug-cnic-assinarparecer.jpg](https://images.zenhubusercontent.com/5a5e41a54b5806bc2bc2fa8a/55e067b7-7502-4b56-a016-e0b3c6aa29d6)

**Comment by clebersantos** [comment]
Aqui só aparece o menu na imagem.
