### ISSUE TITLE
Finalizar após assinatura - Secretário

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#456]
No perfil SAV - Secretário (a) não está sendo possível finalizar a análise do projeto após a assinatura da Análise Técnica para Homologação de Projeto. 

Quando é clicado na opção "finalizar" o projeto era para o projeto sair do painel e ir para outra situação e isso não está acontecendo.

![photo_2018-02-14_17-32-35.jpg](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/52a305d3-f211-4dd3-8e70-ab4201ebddf2)

**Comment by wouerner** [comment]
Finalizado, entra na proxima realese.
