### ISSUE TITLE
Gerar documento de Portaria

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#457]
No perfil SAV/CGAV/COAP/DAP - Técnico de Portaria, no menu Análise opção Atualização de Portaria quando clico em imprimir (Gerar Arquivo RTF) no documento gerado não aparece, em alguns projetos, o nome do proponente e nem a cidade. Segue em anexo o arquivo:
[https://app.zenhub.com/files/104502087/102af415-b50a-41bf-a48c-c8fe494f6e9e/download](https://app.zenhub.com/files/104502087/102af415-b50a-41bf-a48c-c8fe494f6e9e/download)

**Comment by clebersantos** [comment]
## PUBLICAÇÃO NO DOU
Atualizar o arquivo gerado com as seguintes regras:
- [ ] Fonte Calibri e tamanho 9
- [ ] Alinhar assinatura à direita
- [ ] No documento o número da portaria deve ter apenas 3 dígitos
- [ ] Em algumas situações o nome do proponente não aparece
- [ ] Em algumas situações a cidade não aparece
- [ ] Trocar a ordem dos projetos nas portarias gerais (ORDER BY 12, 19, 1)
​

**Comment by guiamado** [comment]
Foi encontrado erros por conta de charset em:
- [ ] Cargo (Ex: Secretário)
- [ ] Assinatura

**Comment by guiamado** [comment]
@AdmissibilidadeSAV poderia me informar, se as portarias chegam somente até o número 999 (por ser 3 digitos)? E se caso a portaria estiver na casa das dezenas/unidades pode ser portaria nr. 75, ou portaria nr. 075?

**Comment by AdmissibilidadeSAV** [comment]
@guiamado as portarias podem chegar a mais de 1000, embora não seja comum. Se estiver na casa das dezenas pode ser 75.

**Comment by guiamado** [comment]
@AdmissibilidadeSAV issue disponível no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
Homologado, favor subir para produção.
