### ISSUE TITLE
Movimentar projeto após assinatura

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#459]
No perfil SAV/CGAV/COAP/DAP - Coordenador-Geral de Admissibilidade e Aprovação não está sendo possível movimentar o projeto após a assinatura do Parecer de Aprovação Preliminar.

Quando é clicado na opção "movimentar" era para o projeto sair do painel e ir para assinatura no perfil SAV/DPAV - Diretor do Departamento e não está acontecendo.
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/96dfaf6c-c844-4e53-9fd2-d6f41e45bdea)

**Comment by vinnyfs89** [comment]
Vinculado com o PR #515
