### ISSUE TITLE
Documentação - Guia de utilização Vue.JS

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#466]
Eu como Analista de Sistemas, identifiquei a necessidade da geração de uma documentação que contenha informações sobre o Vue.js assim como guias básicos de utilização do framework dentro do projeto.

Além disso é interessante listar:
- Versão;
- Vantagens / Desvantagens da utilização do framework progressivo (Exemplo: Antes da utilização do Vue.js levavam 2 minutos para carregamento das informações X e Y, agora leva 10 segundos; Exemplo: Permite ou não cache; Etc...); 
- Compatibilidades / Incompatibilidades;
- Estruturas de pastas utilizada atualmente no projeto;
- Exemplificar criação de componentes;
- Exemplificar casos que podem ser reutilizados;

**Comment by clebersantos** [comment]
@vinnyfs89 Pra ir ajudando

Como passo inicial: https://vuejs.org/

Comparações com outros frameworks: https://br.vuejs.org/v2/guide/comparison.html
