### ISSUE TITLE
[BUG] Planilha Orçamentária - Adequação do projeto

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#495]
No perfil SAV/CGAV/COAP/DAP - Coordenador de Análise no menu Análise opção Avaliar adequação do projeto e clico em avaliar e abro a Planilha Orçamentária a Anterior e a Atual as etapas não estão aparecendo na mesma linha, dificultando muito a análise da mesma.

Ex: Na planilha Anterior a primeira etapa que aparece é Assessoria Contábil e Jurídica e na planilha Atual a primeira que aparece é a etapa de Pré-produção, quando deveria ser a mesma etapa lado a lado. 

Outra coisa que não aparece na coluna correspondente a Planilha Anterior são os valores dos custos vinculados.

http://salic.cultura.gov.br/analise/analise/visualizarprojeto?idpronac=217473

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/935e80f5-a773-4895-9ba0-1465e53fe7bb)

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos a visualização mudou bastante, ficou bem melhor, uma coisa que notei na Planilha Orçamentária é que como os Direitos autorais saiu dos custos vinculados ele não apareceu na planilha atual, neste caso terei que diligenciar o proponente toda vez para que insira esse custo em algum produto ou esse custo está perdido em algum lugar? Porque ele nem aparece na tela do proponente quando ele vai readequar.

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV Temos que avaliar essa questão, adicionar este item em outra etapa da planilha

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV, como este trata de adequação à realidade do projeto, vou abrir uma nova issue para esta questão dos direitos autorais, essa nova issue deverá ser avaliada tbm pelo @romulomb, pois trata-se de alteração no cardápio das planilhas.

**Comment by AdmissibilidadeSAV** [comment]
No perfil de proponente na fase de adequação a realidade de execução uma outra coisa que notei é que alterando o local de realização de Rio de Janeiro por exemplo para uma cidade do Centro-oeste (DF) quando entrei para alterar os custos vinculados não trouxe a opção de 15% de Remuneração para captação de recursos só aparece o máximo de 10%. O projeto só ocorrerá no DF e só tem distribuição do produto no DF.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/a98d514f-df02-404f-906f-053c9fe73974)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/ae1e1634-21e9-4f1e-8e26-6b430f1e4b0c)

Senti a necessidade de poder alterar o plano de distribuição, como editar ou excluir o detalhamento, por exemplo uma exposição de artes o proponente conseguiu um espaço maior e quer aumentar a quantidade de público e alterar de distribuição não gratuita para totalmente gratuita, e o sistema não permite, acredito que só deve impossibilitar a exclusão do produto, mas o detalhamento tem que aparecer a opção de edição.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/4cc458c8-e65d-4a82-949f-4f4364916911)

O sistema só permite você fazer um novo detalhamento e excluí-lo, mas o detalhamento originalmente aprovado não aparece para edição.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/47f6aa62-943f-4310-a035-f85a6d417fde)

**Comment by clebersantos** [comment]
> 1) No perfil de proponente na fase de adequação a realidade de execução uma outra coisa que notei é que alterando o local de realização de Rio de Janeiro por exemplo para uma cidade do Centro-oeste (DF) quando entrei para alterar os custos vinculados não trouxe a opção de 15% de Remuneração para captação de recursos só aparece o máximo de 10%. O projeto só ocorrerá no DF e só tem distribuição do produto no DF.
 
Verifiquei aqui e temos o seguinte bug. Ao excluir o local de realização o detalhamento do Plano de Distribuição não é excluído. Os custos vinculados busca o detalhamento para gerar os percentuais.  

> 2) Senti a necessidade de poder alterar o plano de distribuição, como editar ou excluir o detalhamento, por exemplo uma exposição de artes o proponente conseguiu um espaço maior e quer aumentar a quantidade de público e alterar de distribuição não gratuita para totalmente gratuita, e o sistema não permite, acredito que só deve impossibilitar a exclusão do produto, mas o detalhamento tem que aparecer a opção de edição.

Atualmente não é possível editar o detalhamento, somente excluir e cadastrar um novo. Podemos atualizar essa regra nas próximas sprints, tendo em vista que trata-se de melhoria.

> 3) O sistema só permite você fazer um novo detalhamento e excluí-lo, mas o detalhamento originalmente aprovado não aparece para edição.

Ao excluir o local de realização do detalhamento originalmente aprovado, o sistema oculta as informações(o correto é excluir).


As questões 1 e 3 são bugs e resolveremos o mais rápido possível, esses erros também acontecem no cadastramento de proposta. A questão 2 é melhoria e entrará no planejamento do projeto. Tudo bem?

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos pode fechar a issue e disponibilizar as atualizações em produção por gentileza, pois  estou precisando o mais rápido possível para avaliar um projeto e viabilizar a inclusão do mesmo na pauta da CNIC da semana que vem.

Grata!

**Comment by AdmissibilidadeSAV** [comment]
Após a disponibilização das atualizações da adequação a realidade de execução quando entro para avaliar o projeto aparece a mensagem de que não existe versão para a proposta informada, talvez seja porque o sistema retirou da caixa do proponente automaticamente após a finalização do prazo (30 dias), no entanto, é necessário que o sistema mostre a última alteração salva pelo proponente (mesmo que não tenha enviado ao MinC) ou o projeto originalmente aprovado quando o proponente não faz nenhuma alteração.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/accc9d84-c6a4-475a-acd7-a6438af080a2)

OBS: Trata-se do mesmo projeto reportado no card #528, no qual havia observado que pelo menos o período de execução o proponente havia alterado.
