### ISSUE TITLE
Paginação - Propostas para avaliação

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#505]
Eu como Analista de Sistema identifiquei que a paginação da lista de propostas para avaliação está contabilizando valores diferentes da quantidade de registros retornados.

Pré-condições para atendimento:
- [ ] Quantidade todal de registros seja exibida corretamente
- [ ] Seleção de itens da paginação funciona corretamente.

**Comment by boletocosta** [comment]
Bug corrigido
