### ISSUE TITLE
[Admissibilidade] [BUG] Percentuais para Exemplar no Plano de Distribuição

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#509]
Como proponente no detalhamento do plano de distribuição ao selecionar o tipo de venda como exemplar o sistema não altera automaticamente a quantidade do produto quando eu escolho o percentual desejado.

Exemplo: cadastrei 3000 livros e selecionei a percentagem de 30% para distribuição "proponente", mas o sistema trava na quantidade 1500 (que seria a percentagem de 50%).  

![Capturar.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/753e1004-90b5-4f61-8793-5c06e9337aff)

**Comment by clebersantos** [comment]
Disponível para teste.

**Comment by romulomb** [comment]
Homologado
