### ISSUE TITLE
[Admissibilidade] [BUG] - Proponente não consegue excluir proposta

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#517]
Proponente ao clicar no botão "Excluir Proposta" nada acontece. 

![Capturar.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/47a12dab-bc06-4215-81a0-fd8b7b7f357e)

**Comment by romulomb** [comment]
PERFIL DO PROPONENTE.

Link de excluir consulta não está funcionando. Segue a tela abaixo.

![Proposta.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d7639cdb-d5f7-41f6-89ee-387e3a1cbd6d)
