### ISSUE TITLE
[BUG] Falha ao abrir tela de envio de proposta

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#520]
Eu como Proponente identifiquei que ao encaminhar uma proposta para o ministério fui redirecionado para a tela de identicação da Proposta no ambiente de homologação(hmg.cultura.gov.br).

Condições para aceitação:
- [x] Acessar a funcionalidade de Envio de Proposta ao MinC
- [x] Enviar a proposta para o minc

**Comment by vinnyfs89** [comment]
Após analisarmos o erro, identificamos que o usuário utilizado pela aplicação para acessar o banco de dados perdeu permissão para acesso em uma determinada SP.

Identificamos que o erro abaixo está sendo exibido:
```
 [S0005][229] The EXECUTE permission was denied on the object 'spChecklistParaApresentacaoDeProposta', database 'SAC', schema 'dbo'.
```
@heronbonfim, você pode verificar essa questão de permissão para nós, por gentileza?

**Comment by heronbonfim** [comment]
@vinnyfs89, permissão concedida para o usuários "usuarios_internet".
