### ISSUE TITLE
[BUG] Adequação à realidade de execução

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#528]
No perfil de SAV/CGAV/COAP/DAP - Coordenador de Análise no menu Análise opção Avaliar adequação de projeto quando clico em avaliar os campos que estão na cor cinza não aparecem as informações que foram inseridas no campo "Anterior" somente consta a informação "Atual" impossibilitando a avaliação do projeto.

OBS: Trata-se do pronac: 1770333, que o sistema após o encerramento do prazo de 30 dias para adequação devolveu ao MinC, mas a única alteração que o sistema permitiu que visualizasse é a do período de execução de 09/11/2017 a 31/12/2018 para 23/01/2018 a 30/06/2018, mas não foi possível verificar através da tela de avaliação, mas a de consulta do projeto. 

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/8376911d-2952-4b06-9b80-d4dbefc7c0c7)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/b8d65e4a-5443-4e91-9cb2-0a7373532b13)

http://salic.cultura.gov.br/analise/analise/visualizarprojeto?idpronac=215184

Segue abaixo alguns prints das telas:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/281eefd6-5b84-411d-bcdc-a2ab3fc07fb1)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/ce65860f-838b-4080-be77-5d77b475e512)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/be6c66c5-dbff-4f00-8288-8015d3418202)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV Estou verificando. Inicialmente não teve alterações na proposta. Estamos refatorando essa visualização das alterações da adequação à realidade. Disponibilizei uma versão inicial na homologação. Falta mostrar os Custos Vinculados
