### ISSUE TITLE
[Readequação] Planilha Orçamentária - Remanejamento de 50%

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#533]
Eu como Proponente desejo alterar o valor unitário de itens da planilha orçamentária em até 50% do valor aprovado (para mais ou para menos). Esta funcionalidade já existe no sistema, no entanto, após readequar várias planilhas e acessar a redequação de 50%,  quando edito alguns itens o sistema apresenta inconsistências, conforme listado abaixo.

- [x] itens duplicados na mesma etapa, município, produto e fonte. (Pronac: 127376)
- [x] não exibir coluna de reintegrar na edição do item
- [x] adicionar botão e funcionalidade de criar nova planilha
- [x] reconstruir lógica de reintegrar planilha
- [x] reconstruir lógica de reintegrar item
- [x] travar edição caso valor comprovado = valor aprovado
- [x] ao acionar o botão reintegrar item individual o sistema fica carregando eternamente
- [x] verificar cálculo do valor máximo e mínimo considerando itens parcialmente comprovados (Exemplo: Narrador de audiodescrição - Pronac:155384)
- [x] verificar tbReadequacao / regras de puxar projetos (no caso, 'rp')
- [x] ao abrir qualquer item e depois abrir alguns itens o sistema não atualiza as informações, deixando o valor máximo e mínimo do item anterior(Exemplo: após abrir qualquer item e abrir o item 38 Refeição do Pronac: 155384 os valores originais não são carregados)
- [x] Cópia da planilha: não copiar item zerado (quantidade, ocorrência ou valor unitário)

Regras para adequação:
Valor máximo: (Valor aprovado + 50%) - Valor comprovado;
Valor mínimo: (Valor aprovado - 50%) - Valor comprovado;

Informações utilizadas para reprodução dos erros:
Ambiente: hmg.salic.cultura.gov.br
Pronac: 155384
Nome do Projeto: PLANO ANUAL 2017 DA ASSOCIAÇÃO PAULISTA DOS AMIGOS DA ARTE - APAA
Proponente: 06.196.001/0001-30 - Associação Paulista dos Amigos da Arte
Situação: E75 - Expirado o prazo de execução do projeto

**Comment by decko** [comment]
# Especificação Técnica
O proponente pode alterar itens, quantidades e valores da planilha orçamentária, justificando cada alteração. As alterações de valores de cada item estão restritas à margem de 50%, para cima e para baixo. Ainda, o proponente deve fazer uma justificativa geral da alteração e anexar o arquivo que achar necessário. 
Quando o proponente finalizar, a planilha ativa do projejo é automaticamente alterada.


## Interface
A interface é composta dos seguintes componentes:
* Informações básicas sobre o projeto
* Valor do Remanejamento, dividido entre grupos:
** Grupo A - Pré-Produçao / Preparação & Produção / Execução
** Grupo B - Divulgação / Comercialização
** Grupo C - Custos / Administrativos
** Grupo D - Recolhimentos
* Botão de reintegrar valores (restaura valores iniciais ao início da edição)

* Lista Colapsível com Totalização ao Final, contendo:
    * Fonte de Recursos
        * Produto
            * Etapa
                * UF/ Municipio
                    * Planilha de Itens agrupada.
                    * Índice**
                    * Nome do Item (com link para edição)
                    * Qtde de Dias que o item vai ser utilizado no projeto/etapa
                    * Qtde do Item
                    * Ocorrência**
                    * Valor Unitário
                    * Valor Aprovado
                    * Valor Comprovado
                    * Justificativa de Readequação
                    * Ação
                        * Botão Solicitar Exclusão de Item
                        * Botão Restaurar Item (caso ele tenha sido excluído)
                * Total da UF/Município
            * Totalização Etapa
        * Totalização Produto
    * Totalização Fonte de Recurso
* Botão Finalizar

### Informações básicas sobre o projeto
Uma linha contendo as informações PRONAC e Nome do Projeto

### Valor do Remanejamento
Uma linha contendo o saldo entra planilha readequada - a planilha aprovada. Cor azul quando o saldo é positivo e vermelho quando o saldo é negativo.

### Botão Incluir Novo Item
O botão deve abrir uma modal com os seguintes campos:
* Fonte de Recurso
* Uf
* Municipio
* Etapa
* Produto
* Item
* Dados do Item:
    * Unidade
    * Quantidade
    * Ocorrencia
    * Valor Unitário
    * Dias
    * Total = Quantidade x Ocorrência x Valor unitário
* Justificativa 
**OBS: Todos os campos são obrigatórios**
* Botão Salvar
* Botão Cancelar

Ao Salvar o item, a modal é fechada e a planilha é atualizada com o novo item, junto com a totalização na parte superior da tela.

### Nome do Item
O nome do item é um link que leva a uma modal para edição do item com as seguintes informações:
* Nome do Produto
* Nome da Etapa
* Nome do Item
* Valor Comprovado do Item
* Valores solicitados
    * Descrição da unidade
    * Descrição da quantidade
    * Descrição da ocorrencia
    * Descrição da valor unitário
    * Descrição do Dias
    * Descrição do Total
* Dados para readequação com os seguintes campos:
    * Unidade
    * Quantidade
    * Ocorrência
    * Valor Unitário
    * Dias
    * Total = Quantidade x Ocorrência x Valor Unitário
    * Justificativa da Readequação - Sem limite de caracteres.
* Botão Salvar
* Botão Cancelar

Ao clicar no botão Salvar, a modal fecha e a planilha é atualizada com os valores informados.

### Ação
#### Botão Solicitar Exclusão de Item
Ao clicar no botão, pede a confirmação da exclusão através de um modal. Caso seja confirmada, o item fica inabilitado, e na coluna ação é exibido o texto "Item Excluído".

#### Botão Restaura Item (caso ele tenha sido excluído)
Ao clicar no botão, pede a confirmação da restauração através de um modal. Caso seja confirmado, o item é reabilitado, e na coluna ação, é exibido o botão "Solicitar Exclusão de Item".


## Situação atual
### Ao acionar o botão "Solicitar exclusão de item" o sistema não executa o comando.

### Ao clicar no link para editar itens existentes o sistema não tem ação, permite editar apenas novos itens

### O valor total do remanejamento não é calculado corretamente

## Suspeitas
Projetos em situação 'E12', 'E13', 'E15', 'E23', 'E74', 'E75' (mais algum?)

Isolamento de Procedimentos (efeitos colaterais)
Existem rotinas SQL que alteram as tabelas?

### Situações de Reprodução
1-    Fazer somente Planilha  orçamentária
2-    Fazer Remanejamento 50% e depois Planilha  orçamentária
3-    Fazer Remanejamento 50% e não finalizar, e depois criar Planilha  orçamentária
4-    Fazer 2+ Remanejamentos 50% e depois Planilha  orçamentária


## Resolução Técnica
- [ ] Investigar as quatro situações suspeitas listadas acima 
- [ ] Mapear todo o fluxo do remanejamento 50% = 15
- [ ] Mapear todo o fluxo da readequação = 25
- [ ] Configurar a estrutura de testes automatizados minima (setUp e tearDown) = 30
- [ ] Fazer o teste automatizado do backend do remanejamento 50% = 15
- [ ] Fazer o teste automatizado do backend do readequação = 35
- [ ] Testar as quatro suspeitas acima e reproduzir os comportamentos esperados = 40
- [ ] Migrar as SPs referentes ao modulo Planilha Orçamentária para código nativo = 20
- [ ] Refatorações necessárias = ?


## Especificações dúbias
Caso o remanejamento for igual a zero(0), qual o tratamento esperado dentro do fluxo?

**Comment by fernao** [comment]
planilha orçamentária

complementação  +
redução         -
remanejamento = 0


remanejamento 50%


Tornar o sistema capaz de realizar mais de uma readequação de planilha orçamentária


condições de readequação:
- conta liberada
- não pode liberar se um tipo de readequação estiver em andamento
- se for plano anual - tipo de projeto - campo na tabela PreProjeto - stProposta = 614 - valorCaptado = valorAprovado/12
- adicionar plano bienal 1/24 , trienal 1/36, quadrienal 1/48
- plano execução vigente



-> Contrato de patrocínio / Selecionado em edital público: liberação antes da captação de 20%


condições de remanejamento 50%:
- conta liberada
- não pode liberar se um tipo de readequação estiver em andamento
- se for plano anual - tipo de projeto - campo na tabela PreProjeto - stProposta = 614 - valorCaptado = valorAprovado/12


siEncaminhamento -> controla fluxo

dúvida: se ele está realizando uma readequação e alteram as condições 


ADICIONAR CAMPO: tbReadequacao - gravar dataEnvio na finalização da readequação / remanejamento
efeito aparece na planilha da CNIC, o item aparece como unidade "não informada". Descobrir qual das interações na planilha acarreta o erro



tbPlanilhaProposta - quando é aprovada, vira tbPlanilhaAprovacao

tbPlanilhaAprovacao - tpPlanilha = CO

CNIC: aprovações monocráticas ou de plenária. Quando componente tem uma versão e plenária discorda, sistema faz a cópia com tpPlanlha SE e inativa a CO. Volta para caixa do componente como SE.

tpPlanilha SE -> secretário

......
tpPlanilha RP -> 50%. Não é enviada para aprovação do MinC. Ao finalizar, substui a corrente e torna-se ativa - stAtiva = 's'.

tpPlanilha SR -> Solicitação readequada

tpPlanilha SA -> Saldo de aplicação (implementar): permitir aplicação de rendimentos como readequação de complementação. Não vai entrar na conta captação. Complementação. Não requer publicação no Diário Oficial / portaria




- no cadastramento da proposta

- alterar liberarLinks para planilha orçamentária


TESTES:
-> tentar criar nova planilha orçamentária quando outra planilha orçamentária estiver em análise
-> 


impedir readequação de item quando tem comprovação

Coord -> [vinculada -> coordenador] -> parecerista/técnico -> coordenador -> [sai da vinculada] -> coordenador acompanhamento -> [publicar portaria - atualizar] -> troca de planilha

Só publica portaria quando for redução ou complementação. Só troca planilha quando portaria for publicada e atualizada.
Se saldo zero, dispensa portaria. Após finalização do coordenador de acompanhamento, 


caso o item tenha sido RETIRADO pelo conselheiro (planilha original, CO), não pode liberar link para edição do item (nem exclusão) - seja aplicação ou readequação - 

na readequação, não 

Remover botão de incluir item solto. Adicionar botão de "incluir item" diretamente no município/produto




Suspeitas:
- projetos com + de uma planilha orçamentária - 147176 - 127376 
- SOMA ERRADA: Quando há mais de um SR, garantir que vai puxar dados APENAS da planilha ativa, discriminada na tbReadequacao
- Readequação SR: galo da madrugada. Remuneração para captação de recursos - no NE é R$150.000 - atualizar a regra na readequação

**Comment by fernao** [comment]
Versão publicada em ambiente de testes para homologação.
Foi descoberto um erro que faz com que um projeto já remanejado apresente bug na exibição da planilha quando em um novo remanejamento. A solução é atualizar a spPlanilhaOrcamentaria, no caso do tipoPlanilha = 5, no ELSE, adicionando a referência a tbReadequacao:

``INNER JOIN sac.dbo.tbReadequacao             h on (k.idReadequacao  = h .idReadequacao)
``...
``WHERE ....
``AND  h.idTipoReadequacao = 1 
``AND h.siEncaminhamento  = 11
``AND h.stAtendimento     = 'D'
``AND h.stEstado = 0
``

**Comment by fernao** [comment]
Adicionado campo tpAcao para alterar a cor do item alterado

**Comment by romulomb** [comment]
Veja a tela anexada.
![Remanejamento_5.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c9c12ca6-07c1-4b35-b0de-b5c8ac9dbe4e)

**Comment by romulomb** [comment]
Veja a tela anexada.
![Remanejamento_6.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/81167a70-e766-412d-86d7-121b06fef5f2)

**Comment by romulomb** [comment]
homologado.
