### ISSUE TITLE
[Admissibilidade] Visualizar local de realização

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#534]
No perfil Técnico de admissibilidade e Coordenador de admissibilidade na avaliação da proposta (menu admissibilidade opção avaliação) quando clicamos em avaliar não está permitindo visualizar o local de realização/deslocamento, quando clicamos na setinha ela não abre para verificarmos as informações.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/242389ac-4982-46e4-9d86-44f60cd4be10)

**Comment by vinnyfs89** [comment]
Iniciando atendimento desta demanda

**Comment by vinnyfs89** [comment]
Item corrigido. No próximo deployment os ajustes já estarão visíveis.

**Comment by romulomb** [comment]
Não está mostrando a planilha orçamentária.
![Coinsu.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/265661d0-81d7-482b-b5b0-cdd5d2c2cf53)

Não está mostrando Documentos Anexados -- Documentos da Proposta.
![cons.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/972ef755-be39-4ae4-89d3-f65f01f4b67a)

Na informação do Histórico de Sugestões de Enquadramento não está trazendo o enquadramento conforme a tela anexada.
![Enquadramento.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/81af2454-f94b-4d0c-b760-5f3204dfb4a7)

**Comment by vinnyfs89** [comment]
Beleza, @romulomb ! O ideial é que seja aberta uma Issue para esses itens que você mencionou dentro dessa Issue. 
Vou abrir esses dois itens que você mencionou em uma nova Issue para que esses outros itens não fiquem perdidos :+1:

**Comment by vinnyfs89** [comment]
Abri os itens mencionados nas Issues:
- #643
- #642
