### ISSUE TITLE
[Readequação] Proponente - Plano de Distribuição

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#536]
Eu como proponente ao ter o projeto liberado para readequação, desejo readequar o plano de distribuição e detalhamento no formato da IN (Instrução Normativa) mais atual. Atualmente o sistema apresenta o formato antigo não sendo possível editar os itens. 

 - [x] Criar opção na readequação para listar os detalhamentos por produtos
 - [x] Criar funcionalidade para cadastrar novo detalhamento
 - [x] Criar funcionalidade para editar um item já cadastrado 
 - [x] Criar funcionalidade para exclusão lógica de um item cadastrado
 - [x] Após a edição dos itens de detalhamento o proponente deve clicar em salvar para consolidar o plano de distribuição
 - [x] O sistema deve diferenciar o plano de distribuição anteriores à IN 2017.
 - [x] Ao salvar a readequação do plano de distribuição o sistema deve gravar o id da readequação nos detalhamentos alterados
 - [x] Ao excluir a readequação o sistema deve remover os detalhamentos já salvos.
~- [ ] Adicionar visualização da solicitação para o proponente na opção do menu: Execução -> Dados da readequação~
- [x] (novo) mover a readequação do plano de distribuição para uma página própria
- [x] (novo) adicionar no menu de consultar dados do projeto, no nível de readequação a opção do Plano de Distribuição 
- [x] (novo) a nova tela deve permitir anexar arquivo e o campo justificativa, conforme tela atual de solicitações gerais
- [x] remover item da listagem que não é original
- [x] permitir a finalização apenas com a justificativa
- [x] [problema legado] quando o proponente salva uma nova readequacao altera todos os registros do projeto na `tbplanodistribuicao`

**Comment by clebersantos** [comment]
@romulomb, essa é a issue da readequação do plano de distribução e detalhamentos.

**Comment by romulomb** [comment]
Ao finalizar o sistema não está atualizando as tabelas originais.

**Comment by clebersantos** [comment]
@romulomb e @romulo_menho, na parte de proponente, atualizei o método para remover o item que não era original e fiz uma nova validação do campo justificativa ao finalizar o envio da readequação.

Ao editar o detalhamento, não encontrei o erro que você reportou, na própria imagem que anexada o formulário está preenchido. Pode testar novamente?

**Comment by clebersantos** [comment]
@romulomb e @romulo_menho, na parte de proponente, atualizei o método para remover o item que não era original e fiz uma nova validação do campo justificativa ao finalizar o envio da readequação.

Ao editar o detalhamento, não encontrei o erro que você reportou, na própria imagem anexada, o formulário está preenchido. Pode testar novamente?

**Comment by romulomb** [comment]
Novo erro 

Testando com o Pronac 172041 - Plano Anual Vaga Lume 2018. Proponente : Associação Vaga Lume

![Plano_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a36698c5-a9a5-44f2-9e47-2fa0d7c8b800)

**Comment by clebersantos** [comment]
@romulomb e @romulo_menho, não estarei disponível essa semana no MinC, por este motivo, fiz as correções hoje. 

Pode testar novamente?

**Comment by romulomb** [comment]
@clebersantos Assim que chegar a Brasília. Obrigado

**Comment by romulomb** [comment]
HOMOLOGADO,

SUBIR PARA A PRODUÇÃO PRO GENTILEZA.

**Comment by clebersantos** [comment]
Na readequação, ao analisar o fluxo de solicitações gerais, identifiquei dois problemas: as readequações de plano de distribuição já cadastradas aparecem na lista de solicitações gerais e ao finalizar as solicitações gerais o sistema finalizava todas as solicitações  de readequação abertas.

São ajustes de compatibilidade com outros tipos de solicitações, por este motivo, estou elevando 4 pontos nesta tarefa.

**Comment by clebersantos** [comment]
Na readequação, ao analisar o fluxo de solicitações gerais, identifiquei dois problemas: as readequações de plano de distribuição já cadastradas aparecem na lista de solicitações gerais e ao finalizar as solicitações gerais o sistema finalizava todas as solicitações  de readequação abertas.

São ajustes de compatibilidade com outros tipos de solicitações, por este motivo, estou elevando 4 pontos nesta tarefa.

#ReavaliarEstimativa

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV e @romulomb, devido ao problema descrito no comentário anterior, atualizei a finalização da solicitação das readequações pelo Proponente. Vocês podem validar essa parte novamente?

**Comment by AdmissibilidadeSAV** [comment]
No perfil do proponente quando finaliza a readequação do Plano de distribuição sem inserir uma justificativa aparece a tela abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/5bd45ac7-2d1f-4a9f-a41f-41a5733a133e)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV  e @thais_mendess, o erro reportado foi corrigido e está disponível para teste novamente. 
 
Aproveito para agradecer pelo excelente nível de teste reallizado na readequação do plano de distribuição. Aoós os testes a possibilidade de erro em produção é muito menor. 

Obrigado!

**Comment by romulomb** [comment]
HOMOLOGADO.

OBRIGADO THAIS PELA HOMOLOGAÇÃO.

OBRIGADO CLEBER PELO EXCELENTE TRABALHO.
