### ISSUE TITLE
[Admissibilidade] [BUG] Limites desatualizados (proponente não consegue enviar proposta)

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#537]
Quando o proponente tenta enviar a proposta ao MinC recebe mensagem de erro que faz referência aos limites para o valor máximo da proposta. O problema é que esses limites estão sendo calculados de acordo com a Instrução Normativa nº 01 do MinC, mas na verdade eles foram atualizados na IN nº 05.

***Os limites corretos são***:
Art. 4º Para o cumprimento do princípio da não concentração, disposto no § 8º do art. 19 da
Lei nº 8.313, de 1991, serão adotados:
I - limites de quantidades e valores de projetos por proponente:
a) para Empreendedor Individual (EI), com enquadramento Microempreendedor Individual (MEI), e para pessoa física, até 4 (quatro) projetos, totalizando R$ 1.500.000,00 (um milhão e quinhentos mil reais);
b) para os demais enquadramentos de Empreendedor Individual (EI), até 8 (oito) projetos,  totalizando R$ 7.500.000,00 (sete milhões e quinhentos mil reais); e
c) para Empresa Individual de Responsabilidade Limitada (EIRELI), Sociedades Limitadas (Ltda.) e demais pessoas jurídicas, até 16 (dezesseis) projetos, totalizando R$ 60.000.000,00 (sessenta milhões de reais). 

Atenção: também não há mais o limite de 10 milhões por projeto para os proponente que se encaixam na alínea c).

Segue o print da mensagem para ilustração:

![erro limite antigo.png](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/6ba17f7c-a2fa-4b9b-8c87-81a656f02d5d)

Ou seja, precisa atualizar tanto o limite de 10 milhões que não existe mais quanto os novos limites que aumentaram (conforme o artigo 4 da IN nº05)

Vinculada com:
#596 e #537

**Comment by boletocosta** [comment]
Prezados,

Bug muito urgente. Proponentes não conseguem enviar as propostas, pois os limites estão desatualizados. Alguém poderia verificar, por favor?

**Comment by wouerner** [comment]
@romulomb sinalizou que vai olhar os valores contidos na SP. Com retorno dele eu vou poder solucionar o problema.
