### ISSUE TITLE
[Solicitação do Proponente] Criar nova funcionalidade

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#54]
### HISTÓRIA DO USUÁRIO:
[Tela_4.pdf](https://github.com/culturagovbr/salic-minc/files/1408191/Tela_4.pdf)
[Tela_3.pdf](https://github.com/culturagovbr/salic-minc/files/1408192/Tela_3.pdf)
[Tela_2.pdf](https://github.com/culturagovbr/salic-minc/files/1408193/Tela_2.pdf)
[Tela_1.pdf](https://github.com/culturagovbr/salic-minc/files/1408194/Tela_1.pdf)

#### PERFIL DO PROPONENTE

Essa funcionalidade permite ao proponente enviar solicitação ao MinC referente a proposta ou projeto cultural.

O caso de uso poderá iniciar: 
1.pelo menu superior ao clicar no item Solicitação;
2.pelo botão na linha da proposta;
3.pelo botão na linha do projeto.

Quando a opção escolhida for: 1. o sistema deverá solicitar que o proponente selecione entre proposta ou projeto e digitar o número da proposta ou do projeto. Após clicar no botão pesquisar o sistema deverá montar a tela 1 para o preenchimento da solicitação.

2.se o opção for na linha da proposta o sistema deverá montar a tela 2 para a solicitação do proponente.

3.2.se o opção for na linha do projeto o sistema deverá montar a tela 2 para a solicitação do proponente.

O sistema deverá disponibilizar ao proponente os seguintes botão de ação para o proponente:

1.Salvar -- permitirá ao proponente digitar e salvar para posterior envio ao MinC. Nesse caso o sistema deverá gravar na tabela tbSolicitado o valor no atributo siEncaminhamento o valor 12 (Solicitação Cadastrada pelo proponente);

2.Enviar - opção que encaminhará ao MinC a solicitação do proponente. Nesse caso o sistema deverá gravar na tabela tbSolicitado o valor no atributo siEncaminhamento o valor 1(Solicitação encaminhada ao MinC pelo Proponente);

3.Cancelar - opção que cancela o envio da solicitação ao MinC.

O sistema deverá permitir ao proponente anexar documento, opção que não é obrigatória.

O sistema só permitirá ao proponente fazer uma nova solicitação se a anterior estiver respondida, ou seja se o valor do atributo stEstado estiver setado para 0 na tabela tbSolicitacao.

Quando o proponente clicar no botão salvar o sistema deverá gravar as seguintes informações na tabela tbSolicitacao:

Segue a query para inserir o registro na tabela tbSolicitacao
```
INSERT INTO sac.dbo.tbSolicitacao
(idProposta, idOrgao, idSolicitante, dtSolicitacao, dsSolicitacao, idTecnico, dtResposta, dsResposta, idDocumento, siEncaminhamento, stEstado)
SELECT ?,?,?,GETDATE(),'TEXTO DIGITADO,
sac.dbo.fnPegarTecnico(?,?,2),NULL,NULL,NULL,1,1
idProposta = (idPreprojeto para proposta ou idProjeto para projeto);
idOrgao = (prospota - se abragencia for igual a zero codigo 171 senão 262. No caso de projeto é só pegar o Orgao da tabela Projetos;
idSolicitante = idgente;
dtSolicitacao = getdate();
dsSolicitacao = solicitação digitada pelo proponente. Máximo de 8000 caracteres;
idTecnico = null;
dtResposta = null;
dsResposta = null;
idDocumento = id do documento anexado ou null;
siEncaminhamento = 12 (Salvar) ou 1 (Enviar)
stEstado = 1
```

#### PERFIL MINC

O sistema separará as solicitações pelo atributo idOrgao da tabela tbSolicitacao.

O sistema deverá apresentar o ícone com um sino quando existir solicitação para a unidade.

Quando o usuário clicar no ícone o sistema devera apresentar a tela 3 anexada.

Query para montar a tela 3.
```
SELECT idSolicitacao,idProposta,idOrgao,Sigla,idSolicitante,Solicitante,dtSolicitacao, dsSolicitacao, idTecnico,Tecnico,dtResposta,dsResposta, idDocumento,siEncaminhamento,dsEncaminhamento,stEstado
FROM sac.dbo.vwPainelDeSolicitacaoProponente
```
O usuário terá as seguintes opções:

1.VISUALIZAR: o sistema mostrará ao usuário a solicitação e permitirá se quiser respondê-la;

2.RESPONDER: funcionalidade para responder a solicitação;

3.ENCAMINHAR: enviar a solicitação para outra unidade responder a solicitação.

Quando o usuário clicar no botão RESPONDER o sistema deverá apresentar a tela 4. Ato de responder significa ATUALIZAR (UPDATE) as seguintes informações na tabela tbSolicitacao:

idTecnico = [USUÁRIO LOGADO];
dtResposta = GETDATE();
dsResposta = RESPOSTA DIGITADA PELO USUÁRIO LOGADO;
siEncaminhamento = 15(Solicitação finalizada pelo MinC)
stEstado = 0

Quando o usuário clicar no botão ENCAMINHAR o sistema deverá ATUALIZAR (UPDATE) as seguintes informações na tabela tbSolicitacao:

idOrgao = UNIDADE SELECIONADA
idTecnico = NULLL
dtResposta = NULL;
dsResposta = NULL;
siEncaminhamento = 1 (Solicitação encaminhada ao MinC pelo Proponente)
stEstado = 1

#### IMPORTANTE: as tela apresentada são sugestivas, isso significa que o desenvolver tem toda liberdade para propor inovações.

**Comment by clebersantos** [comment]
Após o merge tiveram alguns conflitos. Verificar as seguintes funcionalidades:
[ ] Proponente: Cadastro de agentes
[ ] Parecerista: Análise Técnica Inicial
[ ] Consultar dados do projeto: Versão da IN 2017
[ ] Consultar dados do projeto: Planilha Aprovada nas várias fases

**Comment by clebersantos** [comment]
Migrar SP
```

CREATE PROCEDURE dbo.spSelecionarTecnicoSolicitacao (@p_idPronac INT,@p_Proposta_Projeto  VARCHAR(8))
AS  
  DECLARE @idTecnico          INT
  DECLARE @idAgente           INT
  DECLARE @idTecnicoAnterior  INT
  DECLARE @qtProjetos         INT
  DECLARE @qtProjetosAnterior INT
  DECLARE @idOrgao            INT  
  DECLARE @Flag               INT
  DECLARE @Rows               INT
  DECLARE @idPerfil           INT

  SET @Flag = 0
  -- =========================================================================================
  -- DESCOBRIR SE É PROPOSTA OU PROJETO
  -- =========================================================================================
   IF @p_Proposta_Projeto = 'projeto'
      BEGIN
        SELECT @idOrgao = Orgao, @idAgente = b.idAgente
          FROM sac.dbo.Projetos a
		  INNER JOIN Agentes.dbo.Agentes b on (a.CgcCpf = b.CNPJCPF)
         WHERE idPronac = @p_idPronac 
      END

   SET @idOrgao = ISNULL(@idOrgao,0)

   IF @idOrgao = 0
     BEGIN
	   SELECT @idOrgao = AreaAbrangencia, @idAgente = idAgente
	     FROM sac.dbo.PreProjeto 
        WHERE idPreProjeto = @p_idPronac
	   
	   SELECT @Rows = @@ROWCOUNT 
	   IF @Rows = 0
	      BEGIN
	        SET @Flag = 1
		  END
     END

  IF @Flag = 0
     BEGIN
       SET @idPerfil = 92
       
       IF @idOrgao = 0
	      BEGIN
		    SET @idOrgao = 262
		  END
	   ELSE
       IF @idOrgao = 1
	      BEGIN
		    SET @idOrgao = 171
		  END
       ELSE
          BEGIN
            IF @idOrgao = 262 OR @idOrgao = 171 OR @idOrgao = 179
               SET @idPerfil = 110
            ELSE
            IF @idOrgao = 272 OR @idOrgao = 166
               SET @idPerfil = 121
            ELSE
            IF @idOrgao = 303 OR @idOrgao = 167
               SET @idPerfil = 124
		  END

       SET @qtProjetosAnterior = 9999

       DECLARE TheCursor CURSOR FOR
        SELECT usu_codigo
	      FROM tabelas.dbo.vwUsuariosOrgaosGrupos 
         WHERE     sis_codigo  = 21 
		       AND uog_status  = 1
               AND gru_codigo  = 155 
		       AND uog_orgao   = @idOrgao 

       OPEN TheCursor        
       WHILE @@FETCH_STATUS = @@FETCH_STATUS
         BEGIN
           FETCH NEXT FROM TheCursor into @idTecnico          
           IF @@FETCH_STATUS = -2
              CONTINUE
           IF @@FETCH_STATUS = -1
              BREAK
           --------------------------------------------------------------------------------------  
           -- SELECIONAR O TÉCNICO
	       --------------------------------------------------------------------------------------  
           SELECT @qtProjetos = COUNT(*) 
	         FROM       sac.dbo.tbSolicitacao              a
             INNER JOIN tabelas.dbo.vwUsuariosOrgaosGrupos b ON (a.idTecnico = b.usu_Codigo)
             WHERE     b.sis_codigo           = 21 
                   AND a.stEstado             = 1 
			       AND YEAR(a.dtSolicitacao)  = YEAR(Getdate()) 
			       AND MONTH(a.dtSolicitacao) = MONTH(Getdate())
			       AND DAY(a.dtSolicitacao)   = DAY(Getdate())
                   AND a.idTecnico               = @idTecnico 
		           AND b.gru_codigo              = @idPerfil 
			       AND b.uog_orgao               = @idOrgao 
           --------------------------------------------------------------------------------------  
           -- SELECIONAR TÉCNICO
	       --------------------------------------------------------------------------------------  
           SET @qtProjetos = ISNULL(@qtProjetos,0)
           IF @qtProjetosAnterior > @qtProjetos 
              BEGIN
                SET @qtProjetosAnterior = @qtProjetos
                SET @idTecnicoAnterior = @idTecnico
              END
         END            
       CLOSE TheCursor
       DEALLOCATE TheCursor
     END

   IF @Flag = 0
      SELECT @idOrgao as idOrgao,@idPerfil as idPerfil,@idTecnico as idTecnico,@idAgente as idAgente
   ELSE
      SELECT @idOrgao as idOrgao,ISNULL(@idPerfil,0) as idPerfil,ISNULL(@idTecnico,0) as idTecnico,@idAgente as idAgente

```

**Comment by heronbonfim** [comment]
Prezados,

Código de executado com sucesso e SP e criado em homologação.

Att,

**Comment by Pedro-Philipe** [comment]
### Criação da funcionalidade de Solicitação do Proponente

- Remoção de menu sino de notificações
- Adição de menu solicitações na barra superior
- Melhoria de layout do menu lateral consultar dados projeto
- Inclusão de menu consultar dados projeto durante a solicitação feita por um Projeto

### Atividades Técnicas:
- Refatoração de controladores
- Nomeação de valores com constantes
- Criação de novas constantes

**Comment by romulomb** [comment]
BUG -

PERFIL : Tecnico de Atendimento na SACAV

1. Ao apertar o botão Enviar a aplicação apresenta uma mensagem de erro sql conforme a tela abaixo, mas executa a tarefa corretamente.
![Soiicitacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2795d45e-ba33-4547-8db0-d7892b86a64e)


PERFIL : Proponente

[ ] - Substituir o label  Titulo por Nome da Proposta / Projeto.
[ ] - Substituir o label  Situação por Estado.
[ ] - Substituir o label  Data para Dt.Solicitação.
[ ] - Incluir coluna com a data de resposta - nome do label da coluna - Dt.Resposta.
[ ] - Incluir coluna com a quantidade de para atender a solicitação - nome do label da coluna - Qtde Dias

![Solicitacao_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/cdfee35b-3cb6-4c96-a293-4dace0b02289)

**Comment by romulomb** [comment]
O item 1 que trata da permissão foi resolvido?

**Comment by romulomb** [comment]
Homologado
