### ISSUE TITLE
[Admissibilidade] [BUG] Problema no Cadastro de Proposta

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#546]
Prezados, bom dia.

Estou realizando o cadastro de uma proposta no Salic e, pela terceira vez, não consigo visualizar a proposta quando saio do Sistema. Quando vou em listar propostas e seleciono o proponente, aparece a seguinte mensagem de erro: 

![erro minc.png](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/13070c64-2121-4d96-b32c-9c0aa6b34ada)

O número da proposta é: 276793

**Comment by vinnyfs89** [comment]
@boletocosta Tentamos reproduzir o erro, inclusive utilizando o mesmo CNPJ, porém não conseguimos identificar a falha. 
Ao atualizar a página foi verificado se o usuário foi redirecionado para tela de login? Porque uma possibilidade é que a sessão do usuário tenha acabado.

**Comment by boletocosta** [comment]
Vou replicar sua mensagem para o proponente.
