### ISSUE TITLE
[Admissibilidade] [BUG] Quantidade de meia entrada na categoria preço popular no plano de distribuição

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#547]
Prezados,

Ao lançar o detalhamento do Plano de Distribuição, o sistema considera, para vendas de preço popular, 60% para a quantidade de inteiras e 40% para meias. Este cálculo está incorreto, pois deveria considerar 50% para ambas as quantidades.

Segue print da tela:

![bug.png](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/527b198c-0967-4f66-b563-f1cef801e552)

**Comment by clebersantos** [comment]
Disponível para teste.

**Comment by romulomb** [comment]
Homologado
