### ISSUE TITLE
[prestacao-contas] Data Inconsistente ente áreas.

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#550]
Eu, como técnico de prestação de contas, gostaria de ter acesso à informação Data de emissão do documento preenchida pelo usuário, como também, ter acesso à data ao qual o comprovante foi anexado ao sistema, e ainda, a data em que o comprovante foi atualizado( na fase de resposta à diligência).

**Critérios de aceitação:**
- [x] Exibir os campos: Data de Emissão do Documento, Data de Envio do Documento, e Data de Atualização do Documento

## Resolução técnica
- [x] Verificar a existência das três informações no banco de dados
- [x] Caso da não existência, criar os campos
- [x] Mapear os dados para o sistema
- [x] Implementar e disponibilizar os campos nas telas
- [x] Testar segundo especificação pela área de negócios

## Homologação da Funcionalidade
A área de negócios deve utilizar o perfil "Técnico de Prestação de Contas", e na tela ... os três campos contendo as informações: Data de Emissão do Documento, Data de Envio do Documento, e Data de Atualização do Documento

-> Texto da área de Negócios: _Verificar o campo de preenchimento da “Data do documento”. Para o proponente aparece a data da emissão do documento, para o técnico aparece a data que o comprovante foi anexado ao sistema (na fase de prestação de contas) ou a data que o comprovante foi atualizado (na fase de resposta à diligência);

**Comment by wouerner** [comment]
Foi feito deploy para Homologação, fase de testes.

**Comment by wouerner** [comment]
Resolvido
