### ISSUE TITLE
[prestacao-contas] Alterar Nomenclatura na tela de comprovação financeira

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#551]
Eu, como proponente, gostaria de que o campo Data do Documento, se chamasse Data de emissão do comprovante de despesa, para um melhor entendimento.

**Critérios de Aceitação:**
- [x] O campo Data do Documento, na tela Comprovação Financeira deve ter o texto "Data de Emissão do comprovante de Despesa.

-> Texto enviado pela área de negócios: _Alterar a nomenclatura “Data do documento” para “Data de emissão do comprovante de despesa” na tela de comprovação financeira;_

**Comment by wouerner** [comment]
Foi feito deploy para Homologação, fase de testes.

**Comment by wouerner** [comment]
Resolvido
