### ISSUE TITLE
[prestacao-contas] Acrescentar campo com lógica na tela de Comprovação Financeira.

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#552]
Eu, como proponente, gostaria de preencher a informação Data de Pagamento na tela Comprovação Financeira.

Eu, como técnico de Prestação de Contas, gostaria de ter acesso a Data de Pagamento informada pelo usuário na tela de Comprovação Financeira.

**Critérios de aceitação:**
- [x] Campo "Data de Pagamento" para o Proponente
- [x] Campo "Data de Pagamento" para o Técnico de Prestação de Contas
- [x] Organizar a tela de Comprovação Financeira do Proponente (Quais os critérios de organização?)

## Resolução técnica
- [x] Verificar se a informação Data de Pagamento existe no BD
- [x] Caso não exista, criar o campo Data de Pagamento
- [x] Criar o campo Data de Pagamento na tela de Comprovação Financeira do Proponente
- [x] Criar o campo Data de Pagamento na tela de Comprovação Financeira do Técnico de Prestação de Contas

## Homologação da Funcionalidade
Um proponente deve informar a Data de Pagamento na tela de Comprovação Financeira, e o Técnico de Prestação de Contas deve acessar a mesma informação na sua área de Analise de Comprovação Financeira.

-> Texto da área de Negócios: _Acrescentar o campo de preenchimento “Data do pagamento” na tela de comprovação financeira e reorganizar a tela. Observar que precisa ser desse campo a captura dos dados para o preenchimento do campo “Data do pagamento” na tela de relação de pagamentos. Atualmente, o sistema está se baseando, de forma errônea, na data preenchida no campo “Data do documento”;

**Comment by wouerner** [comment]
Foi feito deploy para Homologação, fase de testes.

**Comment by wouerner** [comment]
Adicionando telas para melhorar o entendimento:

![01](https://user-images.githubusercontent.com/287287/37286143-e363bd48-25df-11e8-8bbd-ab2552012f50.jpg)
![02](https://user-images.githubusercontent.com/287287/37286144-e388403c-25df-11e8-9ec6-6d393405aab7.jpg)
![03](https://user-images.githubusercontent.com/287287/37286145-e3af776a-25df-11e8-8ff2-4d52741d90bf.jpg)

**Comment by wouerner** [comment]
Resolvido.
