### ISSUE TITLE
[prestacao-contas] Diferença de valores entre um mesmo item em Comprovação Validada e Planilha Orçamentária Comprovada

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#562]
Eu, como Técnico de Prestação de Contas, gostaria de visualizar os mesmo valores da Comprovação Validada entre a Planilha Orçamentária Comprovada e a tela de análise do item.

**Critérios de aceitação:**
- [ ] Visualizar o mesmo valor de Comprovação Validada de um Item na Planilha Orçamentária Comprovada e a tela de análise do item.

## Resolução técnica
- [ ] Investigar a fonte do valor correto.
- [ ] Propagar a informação correta para ambas as telas.

## Homologação da Funcionalidade
Os técnico de prestação de contas devem visualizar o mesmo valor de Comprovação valida na Planilha Orçamentaria Comprovada e na tela de análise do item.

-> Texto da área de Negócios: _Para um mesmo item de custo, há diferença entre o valor da “Comprovação Validada” apresentado na “Planilha Orçamentária Comprovada” e o valor apresentado na tela de análise do item._

**Comment by wouerner** [comment]
Feito nova analise vamos mudar apenas os itens impugnados.
