### ISSUE TITLE
[BUG] Adequação à realidade de execução

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#567]
No perfil de Coordenador de Análise no ambiente de produção quando concluir a análise da adequação à realidade de execução e em seguida consultei o projeto para verificar algumas informações notei que o proponente alterou o campo Resumo, porém, o sistema não salvou. Trata-se do Pronac: 175798. Segue abaixo os prints das telas:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/9c45ccdd-fe06-426d-8a06-fcbab3c873e6)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/a816f960-ef9d-4cf6-bb5e-b3d36c26eb58)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV Neste caso ele salvou as alterações, mas não atualizou o projeto após o ok da análise técnica. Vou verificar isso. Esse projeto já foi analisado após a adequação?

**Comment by AdmissibilidadeSAV** [comment]
Eu já conclui a avaliação da adequação no perfil de Coordenador de Análise  e encaminhei para análise técnica do parecerista agorinha (o parecerista ainda não analisou), não pude esperar a correção do Bug apresentado, dada a urgência do projeto ser incluído na pauta da semana que vem.

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV O resumo do projeto não era alterado na IN 2017, na correria das correções para a nova IN, o Marcelo, SEFIC, solicitou que o proponente atualizasse  também o resumo do projeto, mas não atualizamos as rotinas de avaliações. Estou fazendo isso agora.

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV Na análise técnica da adequação, quando o parecer é negativo, o sistema devolve o projeto para o proponente adequar novamente. O sistema grava a seguinte mensagem: "Projeto liberado para o proponente adequar à realidade de execução, não podendo representar aumento de custo e observando as vedações do Art. 42, conforme o Art. 72 da Instrução Normativa."  @Romulo_Menho , @thais_mendess  e André, vcs podem atualizar essa mensagem?
