### ISSUE TITLE
[Readequação] Remover botão de incluir item solto. Adicionar botão de "incluir item" diretamente no município/produto (utilizando estrutura existente)

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#576]
Remover botão de incluir item solto. Adicionar botão de "incluir item" diretamente no município/produto (utilizando estrutura existente)

* complexidade: a planilha é feita a partir de uma listagem de itens, agrupados por cidades, etapas, produtos e fontes. Se uma nova cidade é adicionada ao plano de distribuição, não há itens a exibir e logo não se pode montar o botão incluir a partir desse bloco. Isso faz com que seja necessária a existência de um "incluir" solto. Pesquisar mais... 

* [x] Criar botão de 'incluir item neste município'
* [x] Criar validação para impedir adição de cidade que não for cadastrada nos locais de realização * (melhoria adicional)
~~* [ ] Limitar lista de municípios aos presentes nos locais de realização * (melhoria adicional)~~
* [x] Validação para remover possibilidade de adicionar item já adicionado (select sem item)
* [x] Validação para impedir adicionar item repetido em produto / etapa / município

**Comment by romulomb** [comment]
Homologado
