### ISSUE TITLE
[Admissibilidade] Melhorias e alteração no fluxo de enquadramento/transformação de proposta

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#583]
Prezados,

Anexo as atividades para implementar o fluxo da análise de propostas, já com algumas melhorias.

Qualquer dúvida, só falar. 

[https://app.zenhub.com/files/104502087/83e68525-d0e1-42ab-9340-4a499acf52e8/download](https://app.zenhub.com/files/104502087/83e68525-d0e1-42ab-9340-4a499acf52e8/download)

**Comment by vinnyfs89** [comment]
**Perfil Técnico de Admissibilidade**
- [ ] 1. Tela “Admissibilidade->Avaliação” 
http://salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas
- [ ] 1.1 Acrescentar as seguintes abas ao lado do botão imprimir e abaixo do texto admissibilidade de Propostas: “Inicial” “Reavaliação”, “Vinculada” e “Avaliada”
	
Cada aba apresentará a seguinte listagem de propostas e funções:
- [ ] Aba “Inicial” listará as propostas sem nenhuma análise. Retirar as colunas Enquadrado, Encaminhar e Analisado. Manter as outras colunas.
- [ ] Aba “Reavaliação” listará as propostas que retornaram de diligências, ou seja, receberam a avaliação tipo “Não, devolver para o proponente” (ver item 3.2).  Retirar as colunas Enquadrado, Encaminhar e Analisado. Manter o restante. 
- [ ] Aba “Vinculada” conterá a lista das propostas com dúvida enviada para vinculada (ver item 2.2). Retirar as colunas Enquadrado, Encaminhar e Analisado. Manter as outras colunas e incluir coluna “Visualizar resposta”, que deve ficar habilitada quando a vinculada responder a dúvida enviada pelo MinC. Nessa aba esse botão abriria um pop-up com a resposta da vinculada.
Aba “Avaliada” listará as propostas que receberam a avaliação “Sim, salvar análise visual” (ver item 3.3). Retirar as colunas Enquadrado e Analisado. Manter as outras colunas inclusive a coluna encaminhar, pois essa será a única aba com a funcionalidade do botão encaminhar.  
- [ ] 2. Tela “Analisar proposta” ao clicar no botão analisar
http://salic.cultura.gov.br/admissibilidade/admissibilidade/exibirpropostacultural
- [ ] 2.1. Retirar o botão enquadrar. A sugestão de enquadramento do técnico será realizada TEXTUALMENTE na finalização de sua análise visual. 
- [ ] 2.2 Acrescentar um botão com o seguinte nome: “Vinculada”.  Ao clicar no botão surgirá um campo texto para enviar uma dúvida para a vinculada. Clicando em enviar poderemos selecionar para qual vinculada a dúvida será enviada. Assim que a dúvida é encaminhada a proposta deve ser movida automaticamente para a aba “Vinculada”. 
Visualização da proposta continua a mesma. 
- [ ] 3. Tela “Avaliar” ao clicar no botão avaliar
http://salic.cultura.gov.br/admissibilidade/admissibilidade/incluiravaliacao
- [ ] 3.1. Alterar o texto “a proposta está em CONFORMIDADE VISUAL? ” para “Finalizar análise da conformidade visual? ” 
- [ ] 3.2 Manter o tipo de avaliação “Não, devolver para o proponente” com a mesma funcionalidade ao clicar no botão Salvar. Quando a proposta retornar ao MinC deverá aparecer na aba Reavaliação.
- [ ] 3.3 Alterar a funcionalidade do tipo de avaliação “Sim, salvar análise visual”. Ao clicar no botão Salvar a proposta deverá ser automaticamente movida para a aba “Avaliada”, ou seja, no perfil de técnico não é mais necessário encaminhar proposta para o próximo perfil. Ao salvar a linha da proposta não deve mudar de cor (atualmente muda para verde). Além disso, ao clicar no botão Salvar o proponente não deve receber o texto da avaliação via e-mail (atualmente ele recebe).





** Perfil Coordenador de Admissibilidade e Perfil de Coordenador Geral. **
Os dois perfis serão idênticos, ou seja, DEVEM POSSUIR AS MESMAS FUNCIONALIDADES. Por isso, antes de implementar as mudanças a seguir é necessário incluir funções/visualizações que não estão em um no outro. Exemplo: o Coordenador Geral também poderá visualizar todas as propostas e iniciar todo o fluxo (ultrapassando o Técnico e o Coordenador de Admissibilidade).
- [ ] 4. Tela “Admissibilidade->Avaliação” 
http://salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas
- [ ] 4.1 Além das abas que já aparecem no Perfil de Técnico (Inicial, Reavaliação, Avaliada e Vinculada) acrescentar a aba: “CNIC” 
- [ ] Aba “CNIC” conterá a lista das propostas que foram encaminhadas para CNIC. Retirar as colunas Enquadrado, Encaminhar e Analisado. Manter as outras colunas e ainda incluir coluna “Visualizar resposta”, que deve ficar habilitada quando a CNIC devolver a proposta ao MinC. Esse botão redirecionaria para a tela de enquadramento da proposta (http://salic.cultura.gov.br/admissibilidade/enquadramento-proposta/sugerir-enquadramento) para consultarmos o “Histórico de Enquadramento da Proposta” e visualizar a sugestão da CNIC.
- [ ] 5. Tela “Analisar proposta” ao clicar no botão analisar
http://salic.cultura.gov.br/admissibilidade/admissibilidade/exibirpropostacultural
- [ ] 5.1. Manter os botões atuais e incluir o botão Vinculada.
- [ ] 6. Tela “Avaliar” ao clicar no botão avaliar
http://salic.cultura.gov.br/admissibilidade/admissibilidade/incluiravaliacao
- [ ] 6.1. Mesmo comportamento descrito no Perfil Técnico de Admissibilidade.
- [ ] 7. Tela “Enquadrar” ao clicar no botão enquadrar
http://salic.cultura.gov.br/admissibilidade/enquadramento-proposta/sugerir-enquadramento
- [ ] 7.1 Ao salvar uma sugestão de enquadramento no perfil Coordenador de Admissibilidade ou Coordenador Geral a coluna com o botão encaminhar deve ser habilitada e a linha da proposta na aba “Avaliada” deve mudar para a cor verde.
- [ ] 8. Funcionalidade do botão encaminhar (disponível apenas na aba “Avaliada”).
- [ ] 8.1. O botão será liberado somente após a proposta receber uma sugestão de enquadramento no perfil Coordenador de Admissibilidade ou Coordenador Geral.  O botão deve permitir selecionar como destino apenas “Componente de Comissão”.

**Comment by boletocosta** [comment]
Boa Vinny!

**Comment by vinnyfs89** [comment]
@romulomb estou com as dúvidas abaixo, relacionadas aos itens abaixo:

- 1.1) Quais as regras para exibição da aba Vinculada
- 2.2) O que essa nova funcionalidade de Diálogo com a vinculada deve conter? (detalhar mais)
- 3.2) Como podemos identificar que a proposta retornou ao MinC?
- 3.3) O encaminhamento agora será automático ao clicar em Sim? Porque anteriormente eles solicitaram que o encaminhamento para o próximo perfil fosse diferente.
- 6.1) Na tela de Técnico de Admissibilidade foi solicitado que o botão/ação de enquadrar fosse removida. Deve ser mantida para o perfil coordenador? Qual comportamento que eles desejam que seja igual ao de Técnico de admissibilidade?

**Comment by vinnyfs89** [comment]
Conforme conversamos em reunião com o @romulomb seguem as orientações definitivas para esta issue:

Na lista de avaliações de propostas, inclusive para perfil de Componente da Comissão: (/admissibilidade/admissibilidade/listar-propostas)
- [ ] o link "Alterar Uni. da análise da Proposta" do menu lateral será transformado em um item de menu para "Admissibilidade" > "Alterar Uni. da análise da Proposta" , após o item "Desarquivar Proposta"
- [ ] Remover menu lateral "Análise"
- [ ] Na lista deve aparecer 
- [ ] Manter a coluna "Avaliado"
- [ ] Manter a coluna "Enquadrado" renomeando-a para "Enquadramento". Dentro dela deve ser exibido em qual artigo a proposta foi enquadrada (Artigo 18 ou 26, de acordo com a área e segmento escolhidos da tabela Segmento)
- [ ] Incluir as colunas "Área" e "Segmento" antes do enquadramento.
- [ ] Coluna "Encaminhar" deve ser removida e o seu botão deve ser movido para dentro da análise da proposta.(/admissibilidade/admissibilidade/exibirpropostacultural?idPreProjeto=xxxxxxx&realizar_analise=sim)

Na tela de visualização da proposta (/admissibilidade/admissibilidade/exibirpropostacultural?idPreProjeto=276025&realizar_analise=sim ) 
- [ ] adicionar: Área, Segmento e Artigo de enquadramento dentro do bloco de "Informações Complementares"
- [ ] adicionar após o bloco "Histórico de Avaliações" o bloco "Histórico de Sugestões de Enquadramento"

Na tela de Sugestão de enquadramento da Proposta (http://hmg.salic.cultura.gov.br/admissibilidade/enquadramento-proposta/sugerir-enquadramento?id_preprojeto=276025)
- [ ] Remover o botão de visualizar Enquadramento
- [ ] Caso tenha feito algum enquadramento para o perfil atual, a tela com as informações preenchidas previamente, deve ser preenchida.
- [ ] Alteração de label de "Parecer de Enquadramento *" para "Justificativa de Enquadramento"
- [ ] Verificar se oi campo "Justificativa de Enquadramento" está armazenando exatamente 8000 caracteres
- [ ] O carregamento da tela deve trazer as informações do último enquadramento ativo realizado.

No perfil, Coordenador Geral ou Coordenador de Admissibilidade:
- [ ] Deve permitir a transformação de proposta em projeto caso já tenha passado por avaliação da CNIC
- [ ] Ao transformar proposta em projeto, deve armazenar a última sugestão de enquadramento ativa na tabela Enquadramento.

Qualquer dúvida, entrar em contato com o @romulomb

**Comment by vinnyfs89** [comment]
Itens entregues em ambiente de **homologação** do checklist definitivo:

- Aba “Inicial” listará as propostas sem nenhuma análise. Retirar as colunas Enquadrado, Encaminhar e Analisado. Manter as outras colunas.
- Aba “Reavaliação” listará as propostas que retornaram de diligências, ou seja, receberam a avaliação tipo “Não, devolver para o proponente” (ver item 3.2). Retirar as colunas Enquadrado, Encaminhar e Analisado. Manter o restante.
- Aba “Avaliada” listará as propostas que receberam a avaliação “Sim, salvar análise visual” (ver item 3.3). Retirar as colunas Enquadrado e Analisado. Manter as outras colunas inclusive a coluna encaminhar, pois essa será a única aba com a funcionalidade do botão encaminhar.
- "Analisar Proposta" > 2.1. Retirar o botão enquadrar. A sugestão de enquadramento do técnico será realizada TEXTUALMENTE na finalização de sua análise visual.
- "Visualização da proposta" > 3.2 Manter o tipo de avaliação “Não, devolver para o proponente” com a mesma funcionalidade ao clicar no botão Salvar. Quando a proposta retornar ao MinC deverá aparecer na aba Reavaliação.

Na lista de avaliações de propostas, inclusive para perfil de Componente da Comissão: (/admissibilidade/admissibilidade/listar-propostas):
- o link "Alterar Uni. da análise da Proposta" do menu lateral será transformado em um item de menu para "Admissibilidade" > "Alterar Uni. da análise da Proposta" , após o item "Desarquivar Proposta"
- Remover menu lateral "Análise"
- Manter a coluna "Avaliado"
- Manter a coluna "Enquadrado" renomeando-a para "Enquadramento". Dentro dela deve ser exibido em qual artigo a proposta foi enquadrada (Artigo 18 ou 26, de acordo com a área e segmento escolhidos da tabela Segmento)
- Incluir as colunas "Área" e "Segmento" antes do enquadramento.

**Comment by orionteles** [comment]
Itens entregues em ambiente de homologação do checklist definitivo:

- Adicionar após o bloco "Histórico de Avaliações" o bloco "Histórico de Sugestões de Enquadramento"
- Remover o botão de visualizar Enquadramento
- Caso tenha feito algum enquadramento para o perfil atual, a tela com as informações preenchidas previamente, deve ser preenchida.
- Alteração de label de "Parecer de Enquadramento *" para "Justificativa de Enquadramento"

**Comment by vinnyfs89** [comment]
Itens que serão entregues no ambiente de homologação do checklist definitivo:
- Coluna "Encaminhar" deve ser removida e o seu botão deve ser movido para dentro da análise da proposta.
- Verificar se oi campo "Justificativa de Enquadramento" está armazenando exatamente 8000 caracteres (@orionteles )
- Deve permitir a transformação de proposta em projeto caso já tenha passado por avaliação da CNIC
- Remover regra informada anteriormente "ao armazenar um parecer favorável deve também ser registrado uma sugestão de enquadramento para perfil técnico de admissibilidade"

**Comment by vinnyfs89** [comment]
Itens que serão entregues no ambiente de homologação do checklist definitivo:
- Adicionar: Área, Segmento e Artigo de enquadramento dentro do bloco de "Informações Complementares"

Melhorias visuais - Avaliação de propostas:
- [x] Aplicação do novo padrão de cabeçalho breadcrumbs (migralhas de pão) na tela de avaliação de proposta.
- [x] Adição da Ação de "voltar" para o botão que fica junto ao cabeçalho
- [x] Adição de tratamento para exibição do PRONAC somente quando existir
- [x] Ajuste de layout para dispositívos móveis.

Dados técnicos:
- Refatoração de entidade SugestaoEnquadramento para que não seja utilizado um modelo anêmico.

**Comment by vinnyfs89** [comment]
Funcionalidade de Análise de Proposta Cultural:

- Antes:
![captura de tela de 2018-03-15 15-38-54](https://user-images.githubusercontent.com/3949238/37484366-156498ec-2867-11e8-9c44-86343be57c99.png)

- Depois
![captura de tela de 2018-03-15 15-39-15](https://user-images.githubusercontent.com/3949238/37484424-325da68c-2867-11e8-892b-09589ce340bd.png)

![captura de tela de 2018-03-15 15-39-27](https://user-images.githubusercontent.com/3949238/37484430-35fe59e4-2867-11e8-9d68-81c5821f8c8e.png)

**Comment by vinnyfs89** [comment]
Itens que entregues no ambiente de homologação do checklist definitivo:
- Área e Segmento  Obrigatórios no Enquadramento
- Ao transformar proposta em projeto, deve armazenar a última sugestão de enquadramento ativa na tabela Enquadramento.

Correções:
- Análise da proposta : Correção de exibição dos botões de acordo com o perfil
- Correção de erro ao avaliar positivamente uma proposta

Atividades Técnicas:
- [REFACTOR] Refatoração dos métodos de salvar Sugestão de Enquadramento de Proposta
- [REFACTOR] Migração de métodos do controller para model para as entidades
"Projetos" e "Enquadramento".
