### ISSUE TITLE
[Estabilização] Administrativo

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#591]
Manter Agente
Ao Cadastrar um novo agente, o sistema não carrega o combo "Visão"
Perfil: Gestor Salic

**Comment by orionteles** [comment]
Testei no Linux com o Chrome e com o Firefox e ambos exibiram as opções da Visão do Agente.
Tem algum cenário específico onde ocorra o erro?

**Comment by vinnyfs89** [comment]
Vou mover para a guia "Impedimento" do ZenHub, ok?

**Comment by orionteles** [comment]
Essa demanda foi corrigida, vou mover para a guia Feito para validação do @romulomb

**Comment by romulomb** [comment]
homologado
