### ISSUE TITLE
[Estabilização] Planilha 

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#592]
Duplicada com #535 

- [x] Valor Comprovação não está correto
- [x] Readequação ( Problema quando há mais de uma Planilha )
     - Não Edita
     - Não exclui
- [x] Altera
- [x] Regra Remuneração
- [x] PRONAC 147176

**Comment by romulomb** [comment]
Limites orçamentário ajustados.

Homologado.
