### ISSUE TITLE
[Estabilização] Manutenção

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#593]
Perfil: Maioria dos perfis de Coordenação
Passos para encontrar a funcionalidade : Manutenção > Alterar Projeto
Erro : Cai a tela ao alterar a situação do projeto

**Comment by vinnyfs89** [comment]
Time diz: "Essa tela é perigosa. Pode causar efeitos colaterais indesejados. Não é recomendada sua utilização".

**Comment by orionteles** [comment]
@romulomb, não consegui simular o erro em homologação nem no meu local. Estou enviando as telas com a mensagem de sucesso ao alterar o status, pode verificar se o erro persiste, por favor?
Testei no chrome e no firefox, com o perfil "SEFIC - Coordenador do PRONAC" utilizando o PRONAC 180147, alterando para a situação B11, conforme imagem em anexo.

![pronac.png](https://images.zenhubusercontent.com/5aa66a574b5806bc2bca6fb8/a2aba2c2-86a6-47c5-aa3f-bfcaa62ccc1b)

**Comment by decko** [comment]
@romulomb @romulo_menho, verificar os passos de reprodução deste problema, por favor.

**Comment by romulomb** [comment]
FECHADA
