### ISSUE TITLE
[Estabilização] Cadastrar Fornecedor

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#594]
Perfil: proponente
Projetos -> listar projetos  (projetos em E12, E13 .. (comprovação aberta)
Consultar dados projeto -> realizar comprovação
clicar num item com saldo a comprovar

- [x]  Erro ao cadastrar cnpj novo - erro de retorno ajax
-  [x] Erro Layout
-  [x] Sobreposição Razão Social pelo Nome
- [x] CEP: 66053070 -  campos de endereço ficam inabilitados e proponente não consegue preencher

**Comment by guiamado** [comment]
Modificações foram feitas referentes a essa issue, e está disponivel para teste.

**Comment by clebersantos** [comment]
@romulomb, acho que o problema do cep foi resolvido neste Card. Já está disponível para teste.

**Comment by romulomb** [comment]
O problema continua.

Segue a tela.
![fornecedor](https://user-images.githubusercontent.com/32374573/37807110-7e5369f8-2e22-11e8-97d5-e63357f59dc6.png)

**Comment by romulomb** [comment]
Homologado
