### ISSUE TITLE
[Estabilização] Comprovação Financeira

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#595]
Sistema informa que projeto está fora do periodo de execução.
Data checar periodo execução
Permite Comprovação acima do valor - Proponente aumentou 50% do item, comprovou e depois reduziu 50% do item

**Comment by vinnyfs89** [comment]
@fernao diz: "É necessário estudar o período de execução, porém a Comprovação acima do valor está relcionada a um bug corrigido e em homologação de readequação".

**Comment by romulomb** [comment]
Homologado.

**Comment by romulomb** [comment]
homologado.
