### ISSUE TITLE
[Estabilização] Adequação Realidade / Plano Distribuição

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#596]
- [x] Plano Distribuição nos dados consolidados
   - [x] Sistema não grava a quantidade produzida. Grava Zero (erros reportados André e Thais)
   - [x] Quantidade Produzida / Consolidação - [x] Resumo

Vinculada com:
#596 e #537

**Comment by vinnyfs89** [comment]
@wouerner diz : "Provavelmente essa Issua esteja vinculada com a issue #537 "

**Comment by clebersantos** [comment]
@boletocosta podem detalhar esse erro?

**Comment by AdmissibilidadeSAV** [comment]
No perfil Coordenador de Análise, menu Análise - Avaliar adequação de projeto, quando clicamos em avaliar e abrimos o plano de distribuição, depois clicamos no produto o campo quantidade total aparece zerado em alguns casos, só no detalhamento que aparece a quantidade total corretamente.
O pronac que utilizei como exemplo é o 172186.
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/ca869e81-5b59-42f8-bf09-0ab90705db3e)
