### ISSUE TITLE
[Estabilização] Readequação de Planilha

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#597]
O sistema permite incluir item duplicado.

**Comment by fernao** [comment]
* [ ] Adaptar regra de liberação dos links para funcionar com múltiplos remanejamentos de planilha orçamentária
* [ ] Adicionar coluna DtEnvio nas telas do coordenador de acompanhamento
* [ ] Adicionar verificação de preenchimento da solicitação
* [ ] Impedir duplicação na criação de novos itens quando já há remanejamentos anteriores 
* [ ] ao incluir novo item, quando alterar produto ou etapa, atualizar lista de itens excluindo os já existentes
* [ ] exibir botão de "incluir item em um novo município" ao criar nova readequação
* [ ] corrigir erro ao excluir readequação recém criada

**Comment by fernao** [comment]
Lista de verificação:
* criar nova readequação de planilha
* verificar se após criada está indisponível para criação de remanejamento 50%
* verificar se é possível adicionar itens duplicados em um mesmo fonte/produto/fase/cidade (removi opções da combo quando carrega, testar isso)
* finalizar readequação e seguir fluxo com coordenador e técnico
* publicar portaria
Lista de verificação
* verificar troca de planilhas (a troca está sendo rodada pela spAtivarPlanilhaOrcamentaria utilizando idReadequacao, que pelo que chequei, está correta)
* verificar DtEnvio na uc75 e nos painéis do coordenador / técnico
