### ISSUE TITLE
[Estabilização] Prestação de Contas

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#599]
Comprovação Física
Comprovação do Objeto
Etapas de Trabalho
Erro ao salvar dados

Comprovação Financeira
Proponente não consegue excluir comprovante do item - Botão não funciona
PRONAC 161474 - Associação Arte Despertar

**Comment by wouerner** [comment]
Resolvido. Favor homologar

**Comment by wouerner** [comment]
@romulomb vai reavaliar essa issue.
