### ISSUE TITLE
[Estabilização]  - Recurso / Diap

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#602]
-  Perfil: Coord. Analise
   -  Erro: Não consegue finalizar avaliação do recurso

Dados para reprodução do erro:
   -  PRONAC 159540
   -  Botão Finalizar Sem Ação

**Comment by vinnyfs89** [comment]
Passos:

Perfil: Coordenador de Análise
Menu: Análise > Recurso

![Captura de tela de 2018-03-21 15-39-21.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/ff221ea1-dae0-4941-96bf-ddb22c630dfb)

No lista de recursos analisados o botão finalizar está sem ação, não funcionando corretamente.

**Comment by vinnyfs89** [comment]
@romulomb testamos juntos no ambiente de homologação e não conseguimos reproduzir o erro.
