### ISSUE TITLE
[Estabilização] Análise Técnica / CNIC

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#603]
O sistema mostra o link "Análise e Aprovação" para o proponente antes de concluir o parecer.
As situações atuais que **NÃO** permitem visualizar a opção do menu são:
- B11
- B14
- C10
- C30
- C20
- D50
- D51

Exemplo: http://hmg.salic.cultura.gov.br/consultardadosprojeto?idPronac=501eac548e7d4fa987034573abc6e179MjE2MDYwZUA3NWVmUiEzNDUwb3RT

Projeto está em análise e o proponente consegue visualizar

**Comment by vinnyfs89** [comment]
@wouerner diz: Verificar a "fnLiberarLink"

**Comment by vinnyfs89** [comment]
@Pedro-Philipe diz: "fnLiberarLink" no meu módulo.

**Comment by Pedro-Philipe** [comment]
@romulomb Poderia testar essa funcionalidade por favor?

**Comment by romulomb** [comment]
Homologado
