### ISSUE TITLE
[Estabilização] - Analise Técnica

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#604]
**Historia:**
Eu como **Coordenador de Parecer(qualquer orgão)** gostaria de redistribuir a analise do projeto ou produto.

**Passo:**
1. Acessar como  **Coordenador de Parecer(qualquer órgão)**.
2. Menu: Analise >> Gerenciar parecer
3. Filtro na tela opção: Aguardando distribuição.
4. Na coluna "Distribuir / Encaminhar": Botão Distribuir Projeto(Tela 01 e Tela 02) ou Botão Distribuir Produto (Tela 03).

Tela 01:
![issue_604](https://user-images.githubusercontent.com/287287/37665189-82b6bc72-2c3b-11e8-9be3-64347df15a48.png)

Tela 02:
![issue_604_2](https://user-images.githubusercontent.com/287287/37665191-82e23398-2c3b-11e8-96ca-2c61b8163ca7.png)

Tela 03:
![issue_604_2-produto](https://user-images.githubusercontent.com/287287/37665193-830b0f7a-2c3b-11e8-84e6-0646a323c926.png)

**Problemas:**
Relato do cliente:"   - Quando tenta distribuir a análise do projeto, o combo para selecionar não aparece na página. Somente após clicar no botão distribuir. Causa confusão e validação para parecerista vazio não é realizada"

Revisão técnica: Parecer ser um erro de usabilidade, não apresenta erro aparente.

Sugestão de implementação:
* Aplicar o novas regras de usabilidade.
* Aplicar layout do materilizecss.
* Fazer as 2 telas de distribuir projeto e distribuir produto funcionarem da mesma forma.
* Entrar com marcação default de distribuição.

**Comment by orionteles** [comment]
Foi alterada a tela de Distribuir Projeto para deixar com a usabilidade mais intuitiva no tocante a Distribuir ou Encaminhar para outra unidade vinculada.
Foi tomada por base a tela 2 mencionada acima, ou seja a opção para escolher se deseja distribuir ou encaminhar foi movida para a tabela abaixo da de Dados do Projeto.

@romulomb, poderia validar, por favor?

**Comment by romulomb** [comment]
Homologado.
