### ISSUE TITLE
[Estabilização]  - Adequação de Realidade  / Proponente

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#605]
Ao reenviar a proposta durante a fase de adequação a realidade acontece um erro na validação da proposta.

  - [x] Destravar Data Fixa
  - [x] O proponente não consegue enviar de volta para o MinC, o botão de enviar não aparece. (Verificar se está na situação E90 e com a data da situação do projeto menor que 30 dias. Colocar mensagem para o proponente que o prazo expirou.
 - [x] O projeto foi diligenciado na análise de adequação e o proponente não consegue  visualizar a nova diligencia.
- [x] Atualizar mensagem da situação "Projeto liberado para o proponente adequar à realidade de execução por 30 dias, conforme o Art. 26 da IN 5/2017"
- [x] Visualizar as diligencias da adequacao na tela de diligencias do projeto. (fazer select na tbAvaliarAdequacao).

**Comment by clebersantos** [comment]
@romulomb disponível para homologação.

**Comment by romulomb** [comment]
Alguns pequenos ajustes descritos na figura anexada.

![Diligecias.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/0ca89873-14e0-407b-b19d-982a4a056568)

**Comment by clebersantos** [comment]
@romulomb, na tela de diligências, quais campos devem aparecer na avaliação da adequação?
