### ISSUE TITLE
[Homologar Projeto]  - Liberar Link de RECURSO

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#606]
Projeto/Menu Lateral

O recurso é a oportunidade do proponente recorrer de uma decisão do Ministério havendo discordância.

**REGRAS PARA IMPETRAR RECURSO NA HOMOLOGAÇÃO DE PROJETO**

1. Recursos poderá ser impetrado até 10 dias após a homologação , em situação **D51  - Projeto Homologado**, nos casos de projetos homologados;
 
2. Para projetos não homologados nas situações A14, A16, A17, A20, A23 , A24, A41, A42 , D02,  D14 e até 10 após a finalizada da reunião da CNIC;

3. A quantidade máxima de recurso por ato administrativo são dois: o primeiro é o pedido de reconsideração e o segundo é o recurso;

4. Somente poderá ser enviado em pedido por vez, o segundo será liberado após a finalização do primeiro. E terá também 10 após a finalização da avaliação do primeiro recurso;

5. **O link para impetrar recurso deverá ser liberado quando as condições acima foram preenchidas**.

**Comment by ryubr** [comment]
Duplicada #600

**Comment by AdmissibilidadeSAV** [comment]
ESSA ISSUE QUE DEVERÁ SER UTILIZADA PARA LIBERAR O LINK DO HOMOLOGAR PROJETO.

**Comment by clebersantos** [comment]
Não entendi. Liberar o link?

**Comment by romulomb** [comment]
@clebersantos Essa issue trata da liberação da solicitação de  recurso na funcionalidade de homologar projeto para o proponente,  onde  acreditava que estivesse desenvolvida.
Para não atrapalhar a subida para produção da issue 659 - HOMOLOGAR PROJETO resolvir reabrí-la

**Comment by romulomb** [comment]
DEFINIÇÃO NO CORPO DA ISSUE

**Comment by romulomb** [comment]
Não tem como testar porque a assinatura não está funcionando.

**Comment by AdmissibilidadeSAV** [comment]
Aguardando a finalização da #1103 para poder testar essa issue.

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Issue 1103 concluída

**Comment by AdmissibilidadeSAV** [comment]
Testei com o pronac 176109 e não apareceu o link para apresentar o recurso na tela do proponente.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/3c9f6a11-7f1f-4767-92b7-a763b97c285e)

**Comment by romulomb** [comment]
O ajuste solicitado pela Thais não foi implementado

Quem estava com essa issue?

**Comment by clebersantos** [comment]
@romulomb @volthier pode verificar essa issue?

**Comment by volthier** [comment]
@AdmissibilidadeSAV @romulomb Bom dia, vocês podem testar de novo.

Estarei no aguardo.

**Comment by romulomb** [comment]
**Sugestão da query para a tarja**

sql 
' SELECT a.IdPRONAC, a.NumeroReuniao 
FROM SAC.dbo.Parecer AS a 
INNER JOIN SAC.dbo.tbReuniao AS b ON a.NumeroReuniao = b.NrReuniao 
INNER JOIN SAC.dbo.Projetos AS c ON a.IdPRONAC= c.IdPRONAC 
WHERE     b.stEstado = 0 
      AND a.AnoProjeto+a.Sequencial = [ pronac]
	  AND c.Situacao in ('A14','A16','A17','A20','A23','A24','A41','A42','D02','D14','D50')
"

**Comment by clebersantos** [comment]
Disponível para homologação.

**Comment by AdmissibilidadeSAV** [comment]
Homologada.
