### ISSUE TITLE
[Estabilização]  - Visualizar as Diligencias

### ISSUE THREAD

**Issue by chris-redfield** [culturagovbr/salic-minc#608]
**Historia:**
Eu como **proponente**, gostaria de visualizar na minha lista de diligencias, o histórico de **"E90 - Projeto liberado para ajustes"**.

**Passos:**
1. Acessar como proponente.
2. Menu: Projetos >> Listar
3. Pesquisar os projetos, clicar no link na coluna "PRONAC" que esteja na situação **"E90 - Projeto liberado para ajustes"**. (funcionalidade consultar dados do projeto)
4. Menu Lateral: Outras Informações >> Diligencias do projeto.

Tela 01:
![issue_608](https://user-images.githubusercontent.com/287287/37663548-307eb476-2c38-11e8-8b9e-f429034a2301.png)

Na tela acima deveria aparecer a diligencia "Projeto liberado para ajustes".
   -  Adequação à Realidade - Quando o projeto retorna(diligencia) a primeira vez para ser ajustado;

**Sugestão de Implementação:**
* Fazer join na tabela tbAvaliarAdequacaoProjeto

**Comment by clebersantos** [comment]
Problema resolvido na issue #605. Atualmente disponível para teste.
