### ISSUE TITLE
[Admissibilidade] 1 - Enquadramento com produto principal

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#628]
Na tela de Sugestão de Enquadramento a Área e Segmento sempre deve vir carregado com as informações do Produto Principal que está localizado na tabela **PlanoDistribuicaoProduto**·

Dados técnicos:
- Quando o atributo 'stPrincipal' for igual a 1 quer dizer que é o produto principal da proposta.

Query a ser utilizada:
```
select --*
  Area as id_area, Segmento as id_segmento
 from sac.dbo.PlanoDistribuicaoProduto
where stPrincipal = 1
  and idProjeto = xxxxx
```

![captura de tela de 2018-03-12 14-54-52](https://user-images.githubusercontent.com/3949238/37679965-422e64ae-2c61-11e8-866b-5c70b8bb4c88.png)

**Comment by vinnyfs89** [comment]
@orionteles Exatamente isso.

**Comment by boletocosta** [comment]
Regras

A aplicação deverá trazer para a tela do técnico o enquadramento escolhido pelo proponente.

Esse enquadramento está cadastrado no plano de distribuição no produto principal.

O técnico poderá concordar ou não que enquadramento da proposta sugerida pelo proponente.  

Sempre haverá uma sugestão de enquadramento.

Sempre o enquadramento ativo deverá ser considerado.

**Comment by boletocosta** [comment]
Segue a tela correta.

![enquadramento](https://user-images.githubusercontent.com/35491935/37777583-ad113c5e-2dc6-11e8-949c-14a083aea985.png)

**Comment by boletocosta** [comment]
A implementação está correta.

**Comment by boletocosta** [comment]
Homologado

**Comment by vinnyfs89** [comment]
@orionteles , man agora que foi homologado o próximo passo é enviar um Pull Request da sua branch homologada para a branch "develop"
