### ISSUE TITLE
[Admissibilidade] Não consegue encaminhar Proposta

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#629]
Mesmo após Sugerir Enquadramento da proposta o botão de encaminhar proposta não está aparendo para os perfis Técnico de Admissibilidade e Componente da Comissão .

![captura de tela de 2018-03-20 17-12-49](https://user-images.githubusercontent.com/3949238/37680219-064b9a50-2c62-11e8-8ae9-12bb3bc709dd.png)

**Comment by boletocosta** [comment]
Não precisa do botão Vini.. Deixa sem é melhor.. Encaminhar vai ser só uma funcionalidade desnecessária, pois eu já acesso as propostas que foram avaliadas. Não precisa do botão encaminhar para o perfil de técnico.

**Comment by vinnyfs89** [comment]
Itens corrigidos e estarão disponíveis para homologação no próximo deployment.

**Comment by boletocosta** [comment]
Dúvida: vai ter ou não o botão de encaminhar? 

Se sim o erro continua, pois mesmo após Sugerir Enquadramento da proposta o botão de encaminhar proposta não está aparecendo para os perfis Técnico de Admissibilidade e Componente da Comissão .

**Comment by boletocosta** [comment]
Botão de encaminhar agora não aparece mais em nenhum perfil, incluindo no de Coordenador.

**Comment by AdmissibilidadeSAV** [comment]
Nos perfis Técnico de Admissibilidade, Coordenador de Admissibilidade, Componente da Comissão o botão encaminhar está aparecendo duplicado.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/11f67bb4-de74-48af-bbc2-567c93058efe)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/840af343-bfe9-430b-a31d-d34bf0d4f5bc)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/78cc9149-177e-40b9-892c-5d985a94462b)

No perfil Técnico de Admissibilidade a opção de encaminhar não deverá permitir o envio para o Coordenador-geral de Acompanhamento, somente para o Coordenador de Admissibilidade.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/35965e27-c4d2-4f74-b2d4-6108528ec37d)

**Comment by romulomb** [comment]
Arquivada, vamos trabalhar somente com a issue 727.
