### ISSUE TITLE
O somatório de Custos Por Produtos não inclui o valor de "Assessoria Contábil e Juridica"

### ISSUE THREAD

**Issue by ricardoqueiroz** [culturagovbr/salic-minc#636]
O **valor total do projeto** apresentado em "**Visualizar Planiha**", difere do total apresentado em "Custos por Produtos". O motivo é que o valor do projeto calculado no **"RESUMO DA PLANILHA ORÇAMENTÁRIA"** não  está considerando na soma total o valor do item **"Valor total Assessoria Contábil e Juridica"**, acarretando impacto nos cálculos finais.  

RESUMO DA PLANILHA ORÇAMENTÁRIA
-------------------------------------------------------------
Valor total   Pré-Produção / Preparação | R$698.500,00
Valor total   Produção / Execução | R$7.993.221,56
Valor total   Pós-Produção | R$25.000,00
Valor total   Assessoria Contábil e Juridica | R$51.600,00
Soma real: | R$8.768.321,56
Calculado pelo programa: | R$8.716.721,56
Diferença: | R$51.600,00

**Comment by wouerner** [comment]
Bom dia, obrigado pela colaboração, teria como especificar melhor com alguns prints screens dos erros? Estaremos verificando assim que possível.

**Comment by ricardoqueiroz** [comment]
![print_screen](https://user-images.githubusercontent.com/8947208/37956193-061ed0d2-3181-11e8-9ff1-aa6eb000a134.jpg)

**Comment by clebersantos** [comment]
Prezado @ricardoqueiroz, agradecemos pela contribuição ao projeto do SALIC. Informamos que a correção estará disponível na próxima versão do sistema. Obrigado

**Comment by ricardoqueiroz** [comment]
Caro @clebersantos, disponha. Sou desenvolvedor com mais de 35 anos de experiência. Como você é o proprietário deste repositório, eu gostaria de dar algumas sugestões e fazer comentário importantes, via e-mail, que poderão ajudar neste desenvolvimento e no seu trabalho. Caso esteja interessado em ouvir entre em contato através do email ricardo.queiroz@brmusic.com.br. Abs,

**Comment by romulomb** [comment]
Homologado.
