### ISSUE TITLE
[Admissibilidade] 3 - Melhorias e alteração no fluxo de enquadramento/transformação de proposta - Continuação

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#638]
Continuação da Issue #583

- [x] Ao transformar proposta em projeto, deve ser utilizada a mesma rotina de Enquadramento de Projeto que é executado manualmente ( Mudança de situação do projeto, providências tomadas, Envio de e-mail, etc)

OBS: Usar como referência classe "Admissibilidade_EnquadramentoController" método "salvarEnquadramentoProjeto"

**Comment by romulomb** [comment]
Vamos trabalhar agora somente com a issue 727
