### ISSUE TITLE
[Admissibilidade]  2 - Publicizar Enquadramento

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#639]
Ao sugerir enquadramento de proposta como Coordenador Geral de Admissibilidade, a sugestão ser visível ao proponente.

Na tela de Avaliação de proposta no perfil Coordenador Geral de Admissibilidade / Coordenador de Admissibilidade, ao sugerir um enquadramento e já estiver na última etapa (após sugestão da CNIC):
- [x] O sistema deve enviar um e-mail para o proponente.
- [x] Após enviar o e-mail, habilitar a opção de visualização de enquadramento para o proponente.

![captura de tela de 2018-03-21 15-07-54](https://user-images.githubusercontent.com/3949238/37728666-a8355df8-2d19-11e8-84e5-b111e985653c.png)

Na tela de edição ou visualição da proposta( http://hmg.salic.cultura.gov.br/proposta/manterpropostaincentivofiscal/identificacaodaproposta/idPreProjeto/276032) :

![captura de tela de 2018-03-21 14-55-22](https://user-images.githubusercontent.com/3949238/37728561-5ffc849e-2d19-11e8-8fd4-7fee79ee4a5b.png)

- [x] Adicionar um item de menu chamado "Enquadramento" com algum ícone
- [x] Ao clicar nessa item, deve exibir a última sugestão de enquadramento ativa com os itens: 
    - Número da Proposta
    - Nome da Proposta
    - Área
    - Segmento
    - Enquadramento (Artigo 18 ou 26) -> Em negrito
- [x] Exibir dois radio buttons "Desistir do Prazo Recursal" e "Recurso"
- [x] Campo de Justificativa do tipo textual que permite até 8000 caracteres
- [x] Anexar somente 1 documento
OBS: Dos itens aciman, somente o Anexar Documento NÃO é obrigatório.
- [x] Botão "Salvar" -> Salvar, mas não envia;
- [x] Botão "Enviar" -> Salvar, e envia;

**OBS: A botão de "Transformar Proposta Em Projeto" só deve estar habilitado quando o prazo de 10 dias para recurso vencer ou o proponente desistir do Prazo Recursal. Para obter essa informação. consultar a tabela "TbRecursoProposta" **

@romulomb enviará o Texto para envio do e-mail para o proponente ou identificador do template que será usado para envio de e-mail  ao proponente no banco de dados e criará a tabela TbRecursoProposta.

![photo_2018-03-21_15-32-47](https://user-images.githubusercontent.com/3949238/37730027-578a720e-2d1d-11e8-87ce-abdf00a36c7d.jpg)

**Comment by vinnyfs89** [comment]
Select p/ envio de e-mail: 
```
SELECT Internet.Descricao
FROM Agentes.dbo.Agentes Agentes
  INNER JOIN Agentes.dbo.Internet Internet ON Internet.idAgente = Agentes.idAgente
WHERE TipoInternet IN (28, 29)
      AND Agentes.idAgente = 9343
```

**Comment by vinnyfs89** [comment]
@Romulo_Menho  @romulomb Pode me dizer por favor, qual Registro devo utilizar na tabela tbTextoEmail par envio de e-mail ao proponente?

**Comment by vinnyfs89** [comment]
Por enquanto enviarei o conteúdo abaixo, manualmente sem consultar à partir dessa tabela, ok?

```

**Comment by vinnyfs89** [comment]
Por enquanto para ganhar tempo enviarei o conteúdo abaixo manualmente sem consultar à partir dessa tabela, caso queira diferente me avise, ok?

```
#Assunto
Proposta {xxxx} - Recurso
```
```
# Corpo do e-mail
Proposta xxx - {Nome da Proposta} : Foi aberto o prazo para entrada com Recurso ou Desistência do Prazo Recursal.
Ao acessar a Proposta {xxx} agora a opção de menu lateral "Enquadramento" estará disponível.
```

**Comment by vinnyfs89** [comment]
Por enquanto para ganhar tempo enviarei o conteúdo abaixo manualmente sem consultar à partir dessa tabela, caso queira diferente me avise, ok?

```
#Assunto
Proposta {xxxx} - Recurso
```
```
# Corpo do e-mail
Proposta xxx - {Nome da Proposta} : Foi aberto o prazo para entrada com Recurso ou Desistência do Prazo Recursal.
Ao acessar a Proposta {xxx} agora a opção  "Enquadramento" no menu lateral estará disponível.
```

**Comment by vinnyfs89** [comment]
Em conjunto com o @clebersantos, aplicamos um conjunto de regras já existentes no SALIC para fase de proposta que verificam se o agente atual tem permissão para editar a proposta ou não.

**Comment by vinnyfs89** [comment]
![screencapture-localhost-recurso-recurso-proposta-visao-proponente-idPreProjeto-237485-2018-04-03-15_06_11.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/ac09084d-77cc-4a21-9fa4-a28390893b96)

![screencapture-localhost-recurso-recurso-proposta-visao-proponente-idPreProjeto-237485-2018-04-03-15_06_56.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/7b72043b-3695-4169-802c-124d158cb63c)

**Comment by AdmissibilidadeSAV** [comment]
Não está aparecendo no perfil do proponente o menu de enquadramento.

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Vocês podem adicionar prints, por gentileza? O menu enquadramento é exibido, após a sugestão de enquadramento da proposta para avaliação que foi distribuĩda para o coordenador geral de admissibilidade

**Comment by AdmissibilidadeSAV** [comment]
Tela do perfil Coordenador-Geral de Admissibilidade e Aprovação demonstrando que a proposta foi enquadrada.
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/7ac8e992-dbe8-4452-bba0-6a3f4e4e3d4b)

Tela do perfil de proponente

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/2c33f9b1-54a1-4afa-89b7-6451d51f7d4a)

**Comment by AdmissibilidadeSAV** [comment]
Em teste realizado hoje o proponente continua sem visualizar o menu lateral de enquadramento.

Tela do Coordenador-Geral de Admissibilidade e Aprovação
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/67a86a7c-6180-4812-a444-c5665e454f02)

Tela do Proponente na qual não aparece o menu enquadramento
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/ffa56f61-d490-4743-8145-12a07749b0a6)

**Comment by romulomb** [comment]
Vamos trabalhar agora somente com a issue 727
