### ISSUE TITLE
[Admissibilidade]  Visualizar Planilha Orçamentária

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#642]
No perfil Técnico de admissibilidade e Coordenador de admissibilidade na avaliação da proposta (menu admissibilidade opção avaliação) quando clicamos em avaliar não está permitindo visualizar a planilha Orçamentária, quando clicamos na setinha ela não está mostrando o documento da proposta.

![image](https://user-images.githubusercontent.com/3949238/37785442-e93532d2-2dd8-11e8-90da-2f495540beed.png)

**Comment by fernao** [comment]
Corrigido em:
a62e0f545aef9e8aa041fa2bdcd427282a7026e9
