### ISSUE TITLE
[Admissibilidade] Visualizar Histórico de Sugestões de Enquadramento

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#643]
No perfil Técnico de admissibilidade e Coordenador de admissibilidade na avaliação da proposta (menu admissibilidade opção avaliação) quando clicamos em avaliar não está trazendo o enquadramento no qual o projeto foi enquadrado, conforme a tela abaixo.

![image](https://user-images.githubusercontent.com/3949238/37785649-77e26a0e-2dd9-11e8-8e8e-d9d38f1bcd0d.png)

**Comment by orionteles** [comment]
@romulomb o problema foi corrigido. Favor validar.

**Comment by boletocosta** [comment]
Erro continua. 

Além disso a opção para conferir o histórico de sugestões de enquadramento não está mais disponível em nenhum perfil.

**Comment by vinnyfs89** [comment]
@boletocosta De acordo com o que foi solicitado pelo Rômulo, o histórico de sugestões de enquadramento agora fico em um bloco dentro da tela de avaliar proposta
