### ISSUE TITLE
[Admissibilidade] 4 - Avaliação de Recurso de Sugestão de Enquadramento da Proposta

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#647]
Criar funcionalidade de Avaliação de Recurso de Sugestão de Enquadramento da Proposta observando os passos e arquivos anexos a seguir: 

- [x] Criação da tabela tbRecursoProposta para comportar o fluxo de Recurso de Proposta entre proponente e Avaliador Técnico
- [x] Quando o proponente criar um recurso para a sugestão de enquadramento deve existir um novo botão para o técnico avaliador da proposta para que consiga dar seu parecer sobre o Recurso.
- [x] Criar tela de Avaliação de Recurso de Enquadramento da Proposta de acordo com a imagem anexo observando a "Parte 1" e "Parte 2". Lembrando que o Recurso só pode ser enviado no máximo duas vezes para avaliação.
- [x] Em caso de deferimento, A aplicação deverá recuperar a sugestão de enquadramento do Proponente. Essa Sugestão está armazenada na tabela PlanoDistribuicaoProjeto no Produto Principal - Código da área e código do Segmento - onde o Produto Principal é identificado pelo atributo stPrincipal igual a 1. A motivação de enquadramento deverá ser utilizada no armazenamento da justificativa da sugestão de enquadramento e também na tabela tbRecursoProposta
- [x] Em caso de Indeferimento, o proponente será oportunizado a entrar com um novo recurso.
- [x] Somente após o segundo indeferimento que será liberado o botão para transformar proposta em projeto. 
**OBS: Lembrando que agora a transformação de proposta em projeto não pdoe ser mais validade somente caso já tenha passado por avaliação da CNIC**
- [x] O Prazo para Impetrar Recurso é de 10 dias, tomando como base o atributo dtRecursoProponente da tabela tbRecursoProposta com o stEstado = 0
- [x] Caso o pedido de reconsideração foi indeferido a aplicação deverá inserir um novo registro na tabela tbRecursoPRoposta e alterar o atributo stEstado para 1 no registro anterior. Essa inserção só poderá ser feita pelo Coordenador Geral de Admissibilidade ou Coordenador de Admissibilidade.

**OBS: a Liberaçao do botão para transformar proposta em projeto ocorrerá somente se o proponente desistir do prazo recursal, caso ultrapasse 10 dias, ou após avaliação do recurso.**

Condições para liberação do botão, observando a tabela tbRecursoProposta:

- [x] (Desistência do Prazo Recursal) tpSolicitacao = 'dr' and stEstado = 0 and stAtendimento = 'N' and tpRecurso = 1
- [x] (Pedido Reconsiderado) tpSolicitacao = 'en' and stEstado = 0 and stAtendimento = 'D' and tpRecurso = 1
- [x] (Recurso Indeferido) tpSolicitacao = 'en' and stEstado = 0 and tpRecurso = 2 and stAtendimento in ('D','I')

![1.jpg](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/a2eb0d98-c557-4690-88e8-57f0299975e8)

![2.jpg](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/81a012a3-7e5c-471e-8682-901b9a0131fe)

![3.jpg](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/26e80e67-5e3a-44aa-a57b-73f2a47aac99)

![4.jpg](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/fc0747e1-e9b2-4476-bb6c-3636adcbfdd8)

![5.jpg](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/f5a57db1-6066-4c26-84f3-cb3a7e09e0d4)

**Comment by romulomb** [comment]
Vamos trabalhar agora somente com a issue 727.
