### ISSUE TITLE
[Estabilização] - CADASTRAR PROPONENTE

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#654]
Perfil do Proponente.

A aplicação de cadastrar proponente em alguns casos esta gravado o valor 0 na uf do endereço do proponente.
Isso acontece na inserção de registro na tabela do banco agentes tbEnderecoNacional

Outro bugs é a aplicação em alguns  casos não gravar do código do usuário logado na tabela agentes do banco agentes.

selects para ajudar a buscar a informção

Buscar agente
select * from Agentes..Agentes where CNPJCPF = '[cpf/cnpf]'
Buscar Endereço do agente
select * from Agentes..EnderecoNacional where idAgente = 337901
Buscar os tipo de domínios
select * from Agentes..tipo
Buscar informações da tabela de dominío
select * from Agentes..Verificacao where IdTipo = 2

**Comment by clebersantos** [comment]
@romulomb, verifiquei  os formulários e não consegui reproduzir o erro. Vou mover para o backlog e quando tiver mais informações tentamos atacar novamente essa issue.
