### ISSUE TITLE
[Movimentação Bancária] Relatório de inconsistências de conta captação

### ISSUE THREAD

**Issue by orionteles** [culturagovbr/salic-minc#660]
Alterar consulta do Relatório de inconsistências de conta captação.

Perfil: SEFIC/GEAR/SACAV - COORDENADOR(A) DE ACOMPANHAMENTO
url /movimentacaodeconta/listar-inconsistencias
Menu: Acompanhamento -> Movimentação Bancária ->  (menu lateral) Relatórios -> Inconsistências de conta captação.

- [x] Conforme solicitação do Rômulo, alterar a consulta da referida tela retirando o filtro por órgão e adicionando filtro por Órgão Superior
- [x] Retirar do Menu lateral o item Inconsistências de conta movimento

**Comment by orionteles** [comment]
Issue concluída. @romulomb, pode validar, por favor?

**Comment by boletocosta** [comment]
Avaliado e homologado.

Obrigado, Orion.

**Comment by boletocosta** [comment]
Orion,

Segue a query ajustada.

SELECT CONVERT(INT,(tmpCaptacao.nrAnoProjeto + tmpCaptacao.nrSequencial)) AS pronac,tmpCaptacao.nrCpfCnpjProponente, projetos.IdPRONAC, 
       projetos.NomeProjeto, contaBancaria.Agencia, contaBancaria.ContaBloqueada
FROM SAC.dbo.tbtmpcaptacao AS tmpCaptacao
LEFT JOIN Projetos AS projetos ON tmpCaptacao.nrAnoProjeto = projetos.AnoProjeto AND tmpCaptacao.nrSequencial = projetos.Sequencial
LEFT JOIN ContaBancaria AS contaBancaria ON tmpCaptacao.nrAnoProjeto = contaBancaria.AnoProjeto AND tmpCaptacao.nrSequencial = contaBancaria.Sequencial
INNER JOIN Orgaos As orgao ON projetos.Orgao = orgao.Codigo
WHERE      orgao.idSecretaria = 251 
      AND tmpCaptacao.tpValidacao in(2,3,4,5,6,7,8,9)
	  AND projetos.Situacao NOT IN ('B11','B14','B20','C10','C20','C30','D09','D10','D16','D16','D17','D20','D22','D23','D27','D28','D29','D50','D51','D52','D60','E90')
      AND tmpCaptacao.nrAnoProjeto + tmpCaptacao.nrSequencial IS NOT NULL
GROUP BY tmpCaptacao.nrAnoProjeto + tmpCaptacao.nrSequencial,tmpCaptacao.nrCpfCnpjProponente,projetos.IdPRONAC,
         projetos.NomeProjeto,contaBancaria.Agencia,contaBancaria.ContaBloqueada

**Comment by orionteles** [comment]
Filtro de situação adicionado. @romulomb, pode validar, por favor?

**Comment by boletocosta** [comment]
Homologado
