### ISSUE TITLE
[Estabilização] - ANEXAR DOCUMENTO DE PROPOSTA

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#665]
Perfil do Proponente.

Proposta Cultural

Menu Lateral : Anexar Documentos.

Ao clicar no botão ENVIAR  a tela quebra conforme a figura anexada.

![Documento.png](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/bb7550f7-482b-45ef-bbc4-2ebf484ba82e)

**Comment by clebersantos** [comment]
Esse erro estava ocorrendo apenas no ambiente de homologação. Já corrigi, mas ainda não está disponível para teste.

**Comment by clebersantos** [comment]
Disponível para teste

**Comment by romulomb** [comment]
Homologado
