### ISSUE TITLE
Assinatura dos documentos de Homologar projeto

### ISSUE THREAD

**Issue by ryubr** [culturagovbr/salic-minc#666]

**Comment by ryubr** [comment]
Na consulta para trazer os documentos, não está vindo nenhum resultado, verificando o sql, acredito que precisa cadastrar um AtoAdministrativo com o idTipoDoAto = 643.

Segue SQL montado para a tela:

SELECT Projetos.AnoProjeto + Projetos.Sequencial AS "pronac", 
"Projetos"."nomeProjeto", "Projetos"."IdPRONAC", "Projetos"."CgcCpf", "Projetos"."Area" AS "cdarea", 
"Projetos"."ResumoProjeto", "Projetos"."UfProjeto", "Projetos"."DtInicioExecucao", "Projetos"."DtFimExecucao", 
"Projetos"."Situacao", "Projetos"."DtSituacao", "Projetos"."Orgao", "tbDocumentoAssinatura"."cdSituacao", 
"tbDocumentoAssinatura"."stEstado", "tbDocumentoAssinatura"."idDocumentoAssinatura", 
(select top 1 sac.dbo.TbAssinatura.idAssinatura from sac.dbo.TbAssinatura inner join sac.dbo.TbAtoAdministrativo ON sac.dbo.TbAtoAdministrativo.idAtoAdministrativo = sac.dbo.TbAssinatura.idAtoAdministrativo AND sac.dbo.TbAtoAdministrativo.idOrgaoDoAssinante = 262 AND sac.dbo.TbAtoAdministrativo.idPerfilDoAssinante = 103 AND sac.dbo.TbAtoAdministrativo.idOrgaoSuperiorDoAssinante = 251 WHERE sac.dbo.TbAssinatura.idDocumentoAssinatura = sac.dbo.tbDocumentoAssinatura.idDocumentoAssinatura AND sac.dbo.TbAtoAdministrativo.idTipoDoAto = sac.dbo.tbDocumentoAssinatura.idTipoDoAtoAdministrativo) AS "possuiAssinatura", ( select top 1 sac.dbo.TbAtoAdministrativo.idOrdemDaAssinatura from sac.dbo.TbAtoAdministrativo where sac.dbo.TbAtoAdministrativo.idTipoDoAto = sac.dbo.tbDocumentoAssinatura.idTipoDoAtoAdministrativo and sac.dbo.TbAtoAdministrativo.idOrdemDaAssinatura > ( select top 1 sac.dbo.TbAtoAdministrativo.idOrdemDaAssinatura from sac.dbo.TbAssinatura inner join sac.dbo.TbAtoAdministrativo ON sac.dbo.TbAtoAdministrativo.idAtoAdministrativo = sac.dbo.TbAssinatura.idAtoAdministrativo AND sac.dbo.TbAtoAdministrativo.idOrgaoDoAssinante = 262 AND sac.dbo.TbAtoAdministrativo.idPerfilDoAssinante = 103 AND sac.dbo.TbAtoAdministrativo.idOrgaoSuperiorDoAssinante = 251 WHERE sac.dbo.TbAssinatura.idDocumentoAssinatura = sac.dbo.tbDocumentoAssinatura.idDocumentoAssinatura AND sac.dbo.TbAtoAdministrativo.idTipoDoAto = sac.dbo.tbDocumentoAssinatura.idTipoDoAtoAdministrativo ) order by idOrdemDaAssinatura asc ) AS "possuiProximaAssinatura", "Area"."Descricao" AS "area", "Segmento"."Descricao" AS "segmento", "Segmento"."tp_enquadramento", 
"tbDocumentoAssinatura"."idTipoDoAtoAdministrativo", "Verificacao"."Descricao" AS "tipoDoAtoAdministrativo", "Enquadramento"."IdEnquadramento" 
FROM "sac"."dbo"."Projetos" 
INNER JOIN "sac"."dbo"."Area" 	
ON Area.Codigo = Projetos.Area 
INNER JOIN "sac"."dbo"."Segmento" 
	ON Segmento.Codigo = Projetos.Segmento 
INNER JOIN "sac"."dbo"."tbDocumentoAssinatura" 
	ON tbDocumentoAssinatura.IdPRONAC = Projetos.IdPRONAC 
INNER JOIN "sac"."dbo"."Verificacao" 
	ON Verificacao.idVerificacao = tbDocumentoAssinatura.idTipoDoAtoAdministrativo 
LEFT JOIN "sac"."dbo"."Enquadramento" 
	ON Enquadramento.IdPRONAC = Projetos.IdPRONAC 
	AND Enquadramento.AnoProjeto = Projetos.AnoProjeto 
	AND Enquadramento.Sequencial = Projetos.Sequencial 
INNER JOIN "sac"."dbo"."TbAtoAdministrativo" 
	ON TbAtoAdministrativo.idOrgaoDoAssinante = 262 
	AND TbAtoAdministrativo.idPerfilDoAssinante = 103 
	AND TbAtoAdministrativo.idOrgaoSuperiorDoAssinante = 251 
	AND TbAtoAdministrativo.idTipoDoAto = tbDocumentoAssinatura.idTipoDoAtoAdministrativo 
	WHERE (Projetos.Orgao = '262') 
	AND (tbDocumentoAssinatura.cdSituacao = 1) 
	AND (tbDocumentoAssinatura.stEstado = 1) 
	AND (tbDocumentoAssinatura.idTipoDoAtoAdministrativo = 643) 
ORDER BY "possuiAssinatura" asc;

SELECT'S de apoio:
SELECT * FROM "sac"."dbo"."TbAtoAdministrativo" WHERE idTipoDoAto = 643; -- Nao vem resultado
SELECT * FROM sac.dbo.tbDocumentoAssinatura WHERE idTipoDoAtoAdministrativo = 643 AND cdSituacao = 1 AND stEstado = 1;
SELECT * FROM sac.dbo.tbHomologacao WHERE "IdPRONAC" = 204068;

**Comment by ryubr** [comment]
Lembrando que está na branch: feature/homologar-projeto3

**Comment by romulomb** [comment]
Não está montando o documento corretamente  e não esta liberando o botão de assinatura.

Está trazendo o documento para assinatura de readequação

**Comment by vinnyfs89** [comment]
@romulomb pode detalhar melhor a inconsistência, por favor? Somente com essas informações não consigo identificar o erro.

**Comment by romulomb** [comment]
@vinnyfs89 A Thais vai detalhar

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV o que foi acordado com conosco foi que a Assinatura que tinha sido criada anteriormente fora do padrão que criamos fosse descartada e fosse utilizada a assinatura no novo padrão. Como não foi estabelecido nessa Issue qual o título do documento, foi utilizado o mesmo título de uma das assinaturas de Readequações.

Sobre a exibição dos botões, a opção de assinar só está disponível caso o usuário logado possua os requisitos para assinar de acordo com o Ato Administrativo. O @romulomb conhece bem essa regra, pode lhe auxiliar, também.
- Perfil
- Cargo
- Orgão superior
- Unidade
- Ordem de assinatura

A opção "Encaminhar para assinatura" não fica disponível nessa tela. A tela onde o usuário já foi redirecionado e visualiza o documento, o Projeto já foi encaminhado para assinatura, o Documento de Assinatura já foi gerado e o fluxo de Assinatura já foi iniciado.

Solicito, por gentileza, que caso o conteúdo da issue tenha sido realizado corretamente, essa issue seja fechada e vocês abram aberta uma nova Issue especificando qual deve ser o corpo e título do Documento.

**Comment by romulomb** [comment]
Titulo do Documento **Parecer de Homologação para Execução do Projeto**

**Comment by vinnyfs89** [comment]
Feito. Disponível no ambiente de homologação.

**Comment by vinnyfs89** [comment]
feature/assinatura-homologacao

**Comment by AdmissibilidadeSAV** [comment]
Acabei de iniciar o fluxo de homologação do Pronac: 176928 e o título do documento permanece como **Parecer Técnico de Readequação do Projeto** conforme pode verificar abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/4b5904a9-d27e-4805-af19-1e8f01377103)

**Comment by romulomb** [comment]
SEGUE ACIMA A OBSERVAÇÃO DA THAIS.

**Comment by vinnyfs89** [comment]
Título substituído por : `Parecer de Homologação para Execução do Projeto`

Ambiente de homologação atualizado, por gentileza verificar.

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89 O título do documento está ok, mas o conteúdo do documento tem ser o mesmo que o da tela de Homologar, o conteúdo que está atualmente é o do parecer técnico do parecerista. 

E depois de clicar em iniciar o fluxo de assinatura o projeto permaneceu no painel do coordenador e não apareceu no perfil do Coordenador-geral para assinatura, conforme descrito na issue 659, "a aplicação deverá gerar o documento que será assinado pelo Coordenador-geral de Admissibilidade e Aprovação, também deverá mudar a situação do projeto bpara D51 e a providência tomada para Projeto aguardando análise para homologação de execução".

**Comment by romulomb** [comment]
@vinnyfs89  Esse  é um dos casos que teremos que usar outra  templete. 

Nesse caso a homologação não é parecer.

**Comment by vinnyfs89** [comment]
A tela mencionada pela Thaís, seria a localizada neste link com perfil Coordenador Geral de Admissibilidade, correto?

- /projeto/homologacao/

**Comment by vinnyfs89** [comment]
Acabei de tentar simular ajuste solicitado porém aparenta estar funcionando corretamente conforme imagens abaixo:

![Captura de tela de 2018-07-30 19-47-13.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/bdcc1895-8e87-4d70-9a8e-064b74a8d019)

![Captura de tela de 2018-07-30 19-47-31.png](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/44d62daf-3274-465f-9fb2-363faf470988)

**Comment by vinnyfs89** [comment]
Sobre os itens mencionados da mudança de situação para **D51** e a providência tomada para **Projeto aguardando análise para homologação de execução** esses itens não foram definidos anteriormente no escopo de criação dessa Issue, por gentileza abrir uma nova Issue.

**Comment by AdmissibilidadeSAV** [comment]
@romulomb favor verificar a solicitação acima do @vinnyfs89.

**Comment by vinnyfs89** [comment]
@romulomb criei uma nova issue ( #1103 ) com sua solicitação e vinculei a essa.
