### ISSUE TITLE
[Estabilização] - PRESTAÇÃO DE CONTAS - Diferença no Valor Aprovado - Planilha Orçamentária Aprovada e Planilha Orçamentária Comprovada

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#673]
@wouerner 
## O que deveria/poderia acontecer?  

O campo "Valor Aprovado" na Planilha Orçamentária Comprovada deveria conter o mesmo valor do campo "Valor Aprovado" da Planilha Orçamentária Aprovada. Pronac: 16-4274.

## O que atualmente está acontecendo? 

O campo "Valor Aprovado" na Planilha Orçamentária Comprovada conter valor diferente do campo "Valor Aprovado" da Planilha Orçamentária Aprovada. Pronac: 16-4274.

## Qual poderia ser a solução? 

O campo "Valor Aprovado" da Planilha Orçamentária Comprovada conter o mesmo valor do campo "Valor Aprovado" da Planilha Orçamentária Aprovada.

## Descreva os passos para o erro/alteração que deseja: 

1. O campo "Valor Aprovado" da Planilha Orçamentária Comprovada conter o mesmo valor do campo "Valor Aprovado" da Planilha Orçamentária Aprovada.

## Onde foram feitos os testes? (Ambiente) 

Ambiente: Salic - Produção
Navegador: Mozilla Firefox
Url: http://salic.cultura.gov.br/realizarprestacaodecontas/planilhaorcamentaria/idPronac/207087 
http://salic.cultura.gov.br/consultardadosprojeto?idPronac=501eac548e7d4fa987034573abc6e179MjA3MDg3ZUA3NWVmUiEzNDUwb3RT

Perfil: SEFIC/ARQ - Técnico de Prestação de Contas
Menu/Localização: 

1) Planilha Orçamentária Comprovada
Prestação de Contas >> Analisar Prestação de Contas >> Analisar Prestação de Contas.
2) Planilha Orçamentária Aprovada
Projeto Atual  >>Vl. Aprovado (D)

## Descrição em detalhes (imagens, arquivos, links, e outros recursos): 

Exemplo: Planilha Orçamentária Aprovada. Pronac: 16-4274.

![image](https://user-images.githubusercontent.com/37881003/38050713-56896dee-32a2-11e8-8713-81eb32dc1ff1.png)

Exemplo: Planilha Orçamentária Comprovada. Pronac: 16-4274.
![image](https://user-images.githubusercontent.com/37881003/38050778-89b28e62-32a2-11e8-94e1-8fb2dffbd10f.png)

**Comment by wouerner** [comment]
Em atendimento.

**Comment by romulomb** [comment]
Necessita de prioridade na correção.

**Comment by wouerner** [comment]
Em atendimento.

**Comment by wouerner** [comment]
@romulomb 

Esse erro é decorrente do uso de diferentes consulta para buscar os mesmos dados:
Tela numero 1 usa a SP:
```sql
exec dbo.spvisualizarplanilhaorcamentaria 132451
```
Tela numero 2:
Usa a View:
```sql
select * from vwComprovacaoFinanceiraProjeto where idpronac=132451 
```

Preciso da sua ajuda para definir quais são os dados corretos.

**Comment by wouerner** [comment]
@wouerner @Romulo_Menho me ajuda nessa issue, por favor
