### ISSUE TITLE
[Estabilização] - PRESTAÇÃO DE CONTAS - Repetição de Comprovantes de Despesas - Itens de custo com o mesmo nome

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#678]
## O que deveria/poderia acontecer?  
Os comprovantes de despesas estarem associados aos itens de custos em conformidade com o envio na prestação de contas. Pronac 16-4274.

## O que atualmente está acontecendo? 
Repetição de comprovantes de despesas nos itens de custos que possuem o mesmo nome. Pronac 16-4274.

## Qual poderia ser a solução? 
Associar os comprovantes de despesas aos itens de custos que possuem o mesmo nome em conformidade com o envio na prestação de contas.

## Descreva os passos para o erro/alteração que deseja: 
1. Identificar os itens de custos que possuem nomes repetidos;
2. Identificar a qual dos itens de custos os comprovantes de despesas realmente pertence;
3. Retirar os comprovantes de despesas incorretos dos itens de custos;
4. Associar os comprovantes de despesas corretos aos itens de custos;

## Onde foram feitos os testes? (Ambiente) 
Ambiente: Produção
Navegador: Mozilla Firefox
Url: http://salic.cultura.gov.br/realizarprestacaodecontas/planilhaorcamentaria/idPronac/207087
Perfil: SEFIC/ARQ - Técnico de Prestação de Contas
Menu/Localização: Prestação de Contas >> Analisar Prestação de Contas >> Analisar Prestação de Contas

## Descrição em detalhes (imagens, arquivos, links, e outros recursos): 
![image](https://user-images.githubusercontent.com/37881003/38057871-2da0d614-32b7-11e8-8345-9c122374de56.png)
![image](https://user-images.githubusercontent.com/37881003/38057904-572e9e9e-32b7-11e8-8e86-accd09fd796a.png)
![image](https://user-images.githubusercontent.com/37881003/38057951-7e54096e-32b7-11e8-8b6b-6efd78318fce.png)
![image](https://user-images.githubusercontent.com/37881003/38058005-b2d62aaa-32b7-11e8-8503-0cf3a9eee24e.png)

**Comment by wouerner** [comment]
Em atendimento.

**Comment by romulomb** [comment]
Correção urgente.
