### ISSUE TITLE
[Estabilização] - COMPROVAÇÃO FINANCEIRA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#681]
Perfil do proponente.

Veja a tela anexada.

![Comprovar.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b4e58a0b-db8a-4d44-a77f-5aa8c7de0ac3)

**Comment by romulomb** [comment]
Além do botão editar não aparecer o botão Excluir não apaga o registro.

**Comment by romulomb** [comment]
O botão editar não carregado o campo Data do Pagamento

O botão excluir não está funcionando e a tela cai conforme anexo
![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3ead9d2f-2a61-4a5a-b29c-76c3ff1a0dec)

Quando clica em consulta dados do projeto a tela cai
![comprovacao_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/e000c3c8-e85f-49cc-982f-707f315a4c9a)

**Comment by wouerner** [comment]
Ajustado em homologação.

**Comment by romulomb** [comment]
Não está funcionando

**Comment by romulomb** [comment]
Já foi corrigido, também é ouvidoria

**Comment by romulomb** [comment]
Ontem uma proponente  me mostrou a tela, e os botões de EDITAR e EXCLUIR desapareceram.

**Comment by wouerner** [comment]
@romulomb @Romulo_Menho , só vou poder resolver isso, quando subir a nova versão, pois mudei muitas coisas.

**Comment by romulomb** [comment]
O problema continua.

HOTFIX

**Comment by romulomb** [comment]
Posição de agora a noite - 15/05/2018

Veja a tela
![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/774cf93c-3919-4c88-ac92-e9c3228ede1e)

HOTFIX URGENTE.  

A ouvidoria já está nos pressionando.

**Comment by wouerner** [comment]
@romulomb  @Romulo_Menho, favor fechar issue, se já foi homologada?
