### ISSUE TITLE
[Admissibilidade] Erro ao tentar transformar proposta nº 276396 em projeto.

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#687]
A pedido do Rômulo segue o print do erro ao tentar transformar a proposta nº 276396 em projeto.

![erro transformar.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/f3097834-25de-4280-a38a-0c1dbfc82009)

**Comment by boletocosta** [comment]
Produção

**Comment by boletocosta** [comment]
Pessoal.. alguém poderia verificar esse erro, por gentileza? Proposta já está muito tempo parada e todo dia o proponente liga reclamando... =(

**Comment by clebersantos** [comment]
@boletocosta Vou verificar

**Comment by clebersantos** [comment]
@boletocosta @Romulo_Menho e André, este erro ocorre pq o proponente foi cadastrado por um usuário que não existe no sistema(idUsuario = 142678). Provavelmente não foi cadastrado pelos formulários padrões do SALIC. Procurei no bando de dados e existem atualmente 15 proponentes cadastrados com este usuário.

Existe um formulário externo que faz o cadastro de agentes do salic?

**Comment by clebersantos** [comment]
@clebersantos @Romulo_Menho, pra resolver o problema, temos que atualizar o usuário do agente 03460488697 em produção. O usuário 03460488697 existe na tabela SGCacesso. Segue script que adiciona o idUsuario do cpf  03460488697 ao agente do cpf 03460488697 (idAgente = 225673). Pode verificar e solicitar a atualização?

UPDATE Agentes.dbo.Agentes
SET Usuario=209993
WHERE idAgente=225673

**Comment by boletocosta** [comment]
@romulomb ... bora executar esse script logo? =)

**Comment by romulomb** [comment]
Resolvido

Proposta transformada em projeto.

Pronac - 181064
