### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#70]
- [x] Corrigir plano de distribuição em consultar dados do projeto
- [x] Montar formulário modelo com campos padrões sem materialize 
- [x] Corrigir planilha http://local.salic/consultardadosprojeto/index?idPronac=189786, clicar no link da Vl. Valor Comprovado 
- [x] Menu quebrado em http://local.salic/admissibilidade/admissibilidade/incluiravaliacao
- [ ] Padronizar fundo do titulo da tabela em http://local.salic/recurso/visualizar-recurso?id=6952 
- [ ] Remover classe white-text no cabeçalho do data table http://local.salic/parecer/gerenciar-parecer 
- [x] Menu sem formatação em http://local.salic/agente/agentes/agentes/id/196420
- [x]  Acertar cor das Dialogs
- [x] Corrigir plano de distribuição em consultar dados do projeto 
- [ ] Corrigir ao abrir projeto em http://local.salic/admissibilidade/admissibilidade/proposta-por-proponente?agente=9343&idPreProjeto=240082&realizar_analise=n#abrirModal
- [ ] Atualizar tela ao criar novo local de realizacao http://local.salic/proposta/localderealizacao/form-inserir/idPreProjeto/239899
- [ ] http://local.salic/admissibilidade/enquadramento/encaminhar-assinatura/idPronac/204053
- [x] Corrigir exibição do combo para seleção de técnico em : http://localhost/admissibilidade/admissibilidade/redistribuiranaliseitem?idProjeto=237331
- [x] no perfil proponente o nome dos campos dento da responsabilidade social, detalhes técnicos e outras informações estão muito pequenos em relação ao texto de ajuda.
- [ ] header antigo, parecerista, http://local.salic/assinatura/index/visualizar-projeto/?idDocumentoAssinatura=227&origin=parecer/analise-inicial
http://local.salic/proponente/index/idpronac/150151 - componente comissão
- [x] Gestor do SALIC - Segurança -> Permissoes do SALICWEB - não consigo escolher o perfil no checkbox -  http://hmg.salic.cultura.gov.br/manterusuario/perfissalicweb

**Comment by vinnyfs89** [comment]
Corrigir exibição do combo para seleção de técnico em : http://localhost/admissibilidade/admissibilidade/redistribuiranaliseitem?idProjeto=237331

**Comment by boletocosta** [comment]
no perfil proponente o nome dos campos dento da responsabilidade social, detalhes técnicos e outras informações estão muito pequenos em relação ao texto de ajuda.

**Comment by fernao** [comment]
Normatizar layout nas telas de admissibilidade:
* avaliar proposta
* enquadrar proposta
* arquivar proposta
