### ISSUE TITLE
[Estabilização] - MOVIMENTAÇÃO BANCÁRIA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#708]
Perfil : Coordenador/ Técnico de Acompanhamento

Menu : Acompanhamento-->Movimentação Bancária

Menu Lateral : Relatórios--> Inconsistências de Conta Captação

Tipo de inconsistência -- Sem incentivador.

OBS: Após a correção da inconsistência a aplicação formata de forma incorreta o campo do CNPJ do incentivador, o que impede a validar o item. Veja a tela anexada.

![MovimentacaoBancaria.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/0a455f69-74a4-47d6-8d68-4bc60d70d834)

**Comment by RuanHerculano** [comment]
@romulomb, fico no agurado da query para adicionar um impedimento, e o número de projetos com impedimentos adicionados.

**Comment by romulomb** [comment]
@RuanHerculano Nesse caso estamos sem registros para teste

**Comment by RuanHerculano** [comment]
@romulomb, vou mover para a coluna de impedimentos essa task devido a dificuldade de achar um registro para teste. Fico a disposição para criar esse registro manualmente, bem como criar uma query para adicionar a inconsistência "sem incentivador" ao projeto.

**Comment by romulomb** [comment]
**PRONACs PARA TESTAR**

178894

171635

1410726

177864

177921

**Comment by romulomb** [comment]
HOMOLOGADO.
