### ISSUE TITLE
[BUG] Campo Descrição de Atividades 

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#711]
Após transformar a proposta em projeto o campo Descrição de Atividades não aparece para consulta do projeto no menu lateral esquerdo Outras informações - Dados complementares do projeto ou qualquer outro lugar. Esse campo só aparece na fase de proposta ou na avaliação da adequação da realidade de execução e depois não aparece mais, sendo de extrema importância para futuras análises, até mesmo do parecerista.

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV esse problema foi resolvido?

**Comment by AdmissibilidadeSAV** [comment]
Ainda não.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/a47efcf8-2825-46e9-a376-55406dc3501e)

**Comment by Paulophmp** [comment]
Olá, teria algum idPronac que era para aparecer para fazer alguns teste?

**Comment by AdmissibilidadeSAV** [comment]
@Paulophmp Pronac 183981

http://salic.cultura.gov.br/projeto/#/221438/proposta

**Comment by Paulophmp** [comment]
@AdmissibilidadeSAV, esta disponível para teste no ambiente de HOMOLOGAÇÃO.

**Comment by AdmissibilidadeSAV** [comment]
Homologado, por favor subir para produção.
