### ISSUE TITLE
[Estabilização] - CONSULTAR PROPOSTA

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#712]
No ambiente de produção no perfil Coordenador de Admissibilidade quando clico no menu Relatórios - Propostas e consulto qualquer proposta (independente se foi enviada ou não ao MinC, esteja diligenciada ou esteja arquivada) está aparecendo as opções: Enquadrar, Transformar em projeto e Arquivar, e por tratar-se de tela apenas para consulta não deveria ter essas opções, elas só devem aparecer no menu Admissibilidade - Avaliação.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/d968137a-aeae-4ed6-b495-01b54fe2eb12)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/771c358a-4daa-4e2c-ae8c-0dc899891be8)

**Comment by romulomb** [comment]
Continua com o mesmo problema relatado acima.
