### ISSUE TITLE
[Estabilização] - CADASTRAR PROCURADOR

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#723]
A aplicação não permite cadastrar o procurador.

A tela está fora do padrão.

![Procurador.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2327beec-45a6-4e3a-b472-8e700720164c)

**Comment by wouerner** [comment]
Em atendimento

**Comment by wouerner** [comment]
Em homologação #728

**Comment by wouerner** [comment]
Solução em produção para a parte de salvar os dados, a solução de layout está em desenvolvimento.
