### ISSUE TITLE
[Estabilização] - PRESTAÇÃO DE CONTAS - INCLUIR NOVOS DOCUMENTOS NA FASE DE DILIGÊNCIA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#729]
3-	Criar uma rotina que possa abrir para o proponente incluir novos documentos na fase de resposta à diligência, uma vez que ele tem sido diligenciado por ausência de documentos. Entregue, porém foram encontrados os seguintes erros:

            3.1- Opção de Readequação aparece para o proponente quando a "Diligência: Todos os comprovantes" é realizada.
            3.2- Perfil: Proponente
            Diligência: Somente itens recusados
            Opção de incluir novos comprovantes de despesas aparece após fazer correções em comprovante de despesa recusado.
            3.3. Perfil: Proponente 
            Diligência - Somente itens recusados 
            Erro: DateTime::_construct(): Failed to parse time string (28/06/2017) at position 0 (2): Unexpected character. 
            Tal erro aparece ao abrir alguns comprovantes de despesa recusados para ajustes, não sendo possível editar os dados.
            3.4. Perfil: Proponente
            Diligência: Todos os comprovantes
            O preenchimento do campo "Data do Pagamento" está sendo apagado quando o comprovante de despesa recusado retorna para o proponente ao ser diligenciado.
            3.5. Botão voltar ao visualizar a resposta de diligência:
            Prestação de Contas >> Diligência >> Visualizar
            3.6. Opções de diligências não aparecem quando é escolhida a opção de análise por amostragem.

**Comment by DouglasMinC** [comment]
![image](https://user-images.githubusercontent.com/37881003/39144984-bc49aa20-4708-11e8-96e6-bf9129a1a56e.png)

**Comment by DouglasMinC** [comment]
3.1- Opção de Readequação aparece para o proponente quando a "Diligência: Todos os comprovantes" é realizada.

Selecionando Diligência – Todos os itens orçamentários
Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39149819-c42917d6-4716-11e8-8fd8-77896c124e3c.png)

Perfil: Proponente
![image](https://user-images.githubusercontent.com/37881003/39149834-ccc92b9c-4716-11e8-9808-dd7575a2d5f0.png)

3.2- Quando é realizada a diligência “Somente itens recusados”, a opção de incluir novos comprovantes de despesas aparece após fazer correções em comprovantes de despesas recusados. Tal opção, deveria aparecer somente quando fosse realizada a diligência “Todos os itens orçamentários”.

Selecionando Diligência – Somente Itens Recusados
Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39149845-d6be2a6c-4716-11e8-92c9-579beb5ed151.png)

Perfil proponente:

![image](https://user-images.githubusercontent.com/37881003/39149856-dddd50ca-4716-11e8-83de-40f5866cf339.png)

Perfil proponente:

![image](https://user-images.githubusercontent.com/37881003/39149875-ed393e1c-4716-11e8-8c53-a1e1c5ce8a9e.png)

Perfil proponente:

![image](https://user-images.githubusercontent.com/37881003/39149889-f656c91a-4716-11e8-8ce3-db58414f378d.png)

Perfil proponente:

![image](https://user-images.githubusercontent.com/37881003/39149906-ff8cc340-4716-11e8-97a2-18924fec8579.png)

3.3. Quando é realizada a “Diligência – Somente itens recusados”, o seguinte erro está aparecendo em alguns comprovantes recusados ao escolher a opção de editá-los: Erro: DateTime::_construct(): Failed to parse time string (28/06/2017) at position 0 (2): Unexpected character. 

Selecionando Diligência – Somente Itens Recusados
Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39149920-0975a0d4-4717-11e8-98cb-3b7c982343fb.png)

Perfil proponente:

![image](https://user-images.githubusercontent.com/37881003/39149928-11913a58-4717-11e8-8e15-80aebad93071.png)

Perfil proponente:

![image](https://user-images.githubusercontent.com/37881003/39149945-20377af4-4717-11e8-92e4-f1ba294aff79.png)

3.4. Perfil: Proponente

Na Diligência – Todos os itens orçamentários, o preenchimento do campo "Data do Pagamento" está sendo apagado quando o comprovante de despesa recusado retorna para o proponente corrigi-lo.

Antes de realizar a diligência, o campo Data do Pagamento está preenchido.

Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39149958-2ba48f58-4717-11e8-901d-945ac20bf840.png)

Selecionando Diligência – Todos os itens orçamentários
Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39149972-34d7e2dc-4717-11e8-8f5f-f5db4704ea3f.png)

Quando o projeto é diligenciado, o preenchimento do campo Data de Pagamento é apagado.

Perfil: Proponente

![image](https://user-images.githubusercontent.com/37881003/39149987-3fbe11bc-4717-11e8-915c-e7e7d5fb5eb0.png)

3.5. Botão voltar ao visualizar a resposta de diligência está sem ação:
Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39149999-49040b5a-4717-11e8-8a14-0c32d18060e5.png)

Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39150009-509856b4-4717-11e8-9cb7-632f573fe449.png)

Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![image](https://user-images.githubusercontent.com/37881003/39150022-58dad414-4717-11e8-983c-39cc574685ff.png)

3.6. Opções de diligências não aparecem quando é escolhida a opção de análise por amostragem.

Solucionado.

**Comment by DouglasMinC** [comment]
Novas ocorrências – Constatadas após alterações feitas em 24/04

1. Ao se realizar a diligência “Todos os itens orçamentários” a situação do projeto não é alterada para E17.

![image](https://user-images.githubusercontent.com/37881003/39264913-5941afb4-489c-11e8-8a85-8c0f44b967d7.png)
Figura 1


![image](https://user-images.githubusercontent.com/37881003/39262938-3bb84246-4897-11e8-8128-e52996945c72.png)
Figura 2

2. Ao salvar alguma alteração de registro do comprovante de despesa (Figuras 3 e 4), a tela para inserir um novo documento aparece (Figura 5). O correto seria permanecer na tela Comprovar Pagamento (Figura 3)  para que alterações em outros comprovantes de despesas recusados fossem feitas. Ocorrência relativa a diligência “Todos os itens orçamentários”.

![image](https://user-images.githubusercontent.com/37881003/39264706-ed054b80-489b-11e8-9bcb-8f86051e7be3.png)
Figura 3

![image](https://user-images.githubusercontent.com/37881003/39264293-eb6afd3e-489a-11e8-8f01-1b7db3d640cd.png)
Figura 4

![image](https://user-images.githubusercontent.com/37881003/39264517-672b4be0-489b-11e8-94c2-ab7b48fe2d3a.png)
Figura 5

**Comment by wouerner** [comment]
Subi as alterações do item 2 e ao realizar diligencia mudar a situação do projeto para 'E17', por favor testar em homologação

**Comment by DouglasMinC** [comment]
**Ocorrências pendentes - 27/04/2018 -  Issue 729**   


**3.4**. 
Perfil: Proponente

Na Diligência – Todos os itens orçamentários, o preenchimento do campo "Data do Pagamento" está sendo apagado quando o comprovante de despesa recusado retorna para o proponente corrigi-lo.

Antes de realizar a diligência, o campo Data do Pagamento está preenchido.

Perfil: SEFIC/ARQ – Técnico de Prestação de Contas

![39149958-2ba48f58-4717-11e8-901d-945ac20bf840](https://user-images.githubusercontent.com/37881003/39378784-bd1b2648-4a2f-11e8-90cd-a1e1a43a0cd1.png)

Selecionando Diligência – Todos os itens orçamentários
Perfil: SEFIC/ARQ – Técnico de Prestação de Contas


![39149972-34d7e2dc-4717-11e8-8f5f-f5db4704ea3f](https://user-images.githubusercontent.com/37881003/39378813-d1612cec-4a2f-11e8-9619-827f0ed02623.png)

Quando o projeto é diligenciado, o preenchimento do campo Data de Pagamento é apagado.

Perfil: Proponente

![39149987-3fbe11bc-4717-11e8-915c-e7e7d5fb5eb0](https://user-images.githubusercontent.com/37881003/39378843-e5c25878-4a2f-11e8-9743-b195c1391dfa.png)

**Bug 1**:

Quando o proponente responde à diligencia, o projeto permanece em "E17 - Diligenciado Prestação de Contas" ao retornar para  o perfil SEFIC/ARQ Técnico de Prestação de Contas. 
No fluxo normal, a situação do projeto deveria ser alterada para "E30 - Análise de resposta de diligência".

Obs.: Bug ocorre no tipo de diligência "Todos os comprovantes", na opção "Somente itens recusados" está correto.

**Bug 2**:

Ao salvar alguma alteração de registro do comprovante de despesa (Figuras 1 e 2), a tela para inserir um novo documento aparece (Figura 3). O correto seria permanecer na tela Comprovar Pagamento (Figura 1) para que alterações em outros comprovantes de despesas recusados fossem feitas. Ocorrência relativa a diligência “Todos os itens orçamentários”.


![39264706-ed054b80-489b-11e8-9bcb-8f86051e7be3](https://user-images.githubusercontent.com/37881003/39379414-85f135de-4a31-11e8-8681-7a529f943377.png)

Figura 1


![39264293-eb6afd3e-489a-11e8-8f01-1b7db3d640cd](https://user-images.githubusercontent.com/37881003/39379431-94a87a38-4a31-11e8-8e4e-d60159fd1031.png)

Figura 2

![39264517-672b4be0-489b-11e8-94c2-ab7b48fe2d3a](https://user-images.githubusercontent.com/37881003/39379440-a0c64da4-4a31-11e8-8190-bd4426fb6ce7.png)

Figura 3

**Comment by wouerner** [comment]
em atendimento.

**Comment by DouglasMinC** [comment]
**Bug - 02/05/2018**

**Bug: Erro na substituição de comprovante de despesa.**

Perfil: SEFIC/ARQ - Técnico de Prestação de Contas
Tipo de Diligência: Todos os itens orçamentários

![image](https://user-images.githubusercontent.com/37881003/39580815-6bb7de32-4ec0-11e8-9bba-d4a6cf1038d3.png)

Perfil: Proponente
![image](https://user-images.githubusercontent.com/37881003/39580981-e8acbce6-4ec0-11e8-97c6-bf9d18231037.png)

Perfil: Proponente
![image](https://user-images.githubusercontent.com/37881003/39581120-3bceb74e-4ec1-11e8-8cb4-dac47c983d69.png)

![image](https://user-images.githubusercontent.com/37881003/39581276-9019e288-4ec1-11e8-84b0-1561ecb6519a.png)


Ao selecionar um novo comprovante de despesa para substituir o atual, o seguinte erro aparece:
![image](https://user-images.githubusercontent.com/37881003/39581411-e23fceb0-4ec1-11e8-95be-3ecc01d3a4d6.png)

Perfil: SEFIC/ARQ - Técnico de Prestação de Contas
Tipo de Diligência: Somente Itens Recusados

![image](https://user-images.githubusercontent.com/37881003/39581687-8c084c92-4ec2-11e8-98e5-2a2095fc6408.png)

Perfil: Proponente
![image](https://user-images.githubusercontent.com/37881003/39581783-bc2aea24-4ec2-11e8-940e-a12dc69dcdcf.png)


![image](https://user-images.githubusercontent.com/37881003/39581849-eb567aca-4ec2-11e8-9ad9-02a7521cbf80.png)

Ao selecionar um novo comprovante de despesa para substituir o atual, o seguinte erro aparece:
![image](https://user-images.githubusercontent.com/37881003/39581913-0e89c650-4ec3-11e8-8f23-2c84263e73c9.png)
