### ISSUE TITLE
[Estabilização] - PRESTAÇÃO DE CONTAS - SEGURANÇA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#730]
~~Para um mesmo item de custo, há diferença entre o valor da “Comprovação Validada” apresentado na “Planilha Orçamentária Comprovada” e o valor apresentado na tela de análise do item.~~ referente a issue #864

~~Erro no cálculo do valor da “Comprovação Validada” quando aplicado o filtro “Impugnados”: Comprovação Validada > Valor Comprovado. Colocar comprovação Impugnada no lugar de Comprovada.~~ referente a issue #839

Possibilidade de acessar o painel de distribuição de projeto para análise (funcionalidade dos perfis de Chefe de Divisão e Coordenador de Prestação de Contas) pelo perfil de Técnico de Prestação de Contas (Inserindo o endereço salic.cultura.gov.br/realizarprestacaodecontas/painel). -  problema de segurança

~~Separação dos projetos físicos dos virtuais no sistema. Colocar um filtro “físico” e “virtual” na tela de Relatórios – Projetos.~~ referente a issue: #841

**Comment by wouerner** [comment]
@romulomb  homologar por favor.

**Comment by romulomb** [comment]
HOMOLOGADO..

Obrigado.
