### ISSUE TITLE
[Estabilização] - ATUALIZAÇÃO DE PORTARIA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#734]
Perfil : Técnico de Portaria (SAV/CGAV/CAP ou SEFIC/SACAV)

Menu : Análise --> Atualização de portaria

![Tela.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c6222e5f-fb1f-4a53-8e19-a2cdc37e491e)

**Comment by wouerner** [comment]
@romulomb Na tela acima o erro e do link:  Analise >> **Gerar publicação para o DOU**. 

Não consegui reproduzir o erro ainda.

Tem alguma outra informação sobre esse erro?
