### ISSUE TITLE
[Admissibilidade] Agencia bancária

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#738]
O sistema está permitindo o envio de propostas com qualquer informação no campo onde o proponente deve informar o n° da agência bancária. 

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/f177da9c-d717-43bf-b01b-3de128ff94cc)

**Comment by clebersantos** [comment]
correção no campo agência da proposta disponível em hmg.

**Comment by romulomb** [comment]
**HOMOLOGADO**

**SUBIR PARA PRODUÇÃO**

**OBRIGADO**
