### ISSUE TITLE
[Estabilização] - REMANEJAMENTO DE 50%

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#742]
Perfil do proponente.

A explicação esta na tela anexada.

Pronac - 162567  
Proponente  - POLOBH PROMOCOES EIRELLI EPP

![Remanejamento_50_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d80b2afa-e59c-45b8-8b86-a28730a2afc4)

**Comment by fernao** [comment]
duplicada com #966, já resolvida.
