### ISSUE TITLE
[Admissibilidade] - AJUSTES

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#778]
**PERFIL DO PROPONENTE**

Menu lateral : Enquadramento

* [x]  **1.  Ao clicar no botão remover a tela quebra**
![admis_4.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d7b84d35-b486-4314-a59c-819071d6453d)
![admis_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a925397a-5e3c-41ac-b7f9-f15c1540887b)

* [x] **2. Após enviar o recurso, ao clicar no botão de download a tela quebra.**
![admis_6.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2625dd08-b057-4209-bb14-b7a0dc7f80a9)
![admis_5.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/29e8fbc8-a69f-491c-8dd8-441b9015a16b)

**PERFIL DO COORDENADOR-GERAL**

* [x] **Ao clicar no botão de download a tela quebra.**
![admis_7.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/ce47981e-eeab-4303-8456-4aa5ebbc3a0f)
![admis_8.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/ecf7cfd1-f769-495b-bd51-483978011a95)

* [x] **O recurso impetrado pelo proponente foi deferido pelo coordenador.**
Portanto a aplicação deveria ter gravado a sugestão de enquadramento do proponente.
![admis_9.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c1f07cc2-6fa7-435f-8aa7-61c01762fd59)

* [x] **Quando a sugestão de enquadramento final for a mesma sugerida pelo proponente a aplicação deverá liberar o botão de transformar em projeto.**
![admis_12.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/64d0bba1-7de2-477f-ba51-6de7fb11a260)

* [x] **Quando a sugestão de enquadramento final for pelo artigo 18 liberar a aplicação deverá liberar  o botão de transformação de projeto.**
![Admis_16.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8ebf54d8-c664-42b3-ae5d-5e31ececa2ec)

**VISUALIZAÇÃO DA PROPOSTA**

* [x] **Não está abrindo o local de realização**
![admis_11.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d51fe011-c685-449e-9aed-3add34ebf8d7)

**Comment by vinnyfs89** [comment]
@romulomb Estou analisando esse erro. Aparentemente no banco existe uma trigger acionada no DELETE que chama a tabela tbArquivoImagem_OLD e não consegue acessa-la.

**Comment by romulomb** [comment]
Adicionei mais alguns itens no card.

**Comment by vinnyfs89** [comment]
@romulomb ajustes disponíveis em homologação. Pode verificar, por gentileza?

**Comment by romulomb** [comment]
PERFIL COORDENADOR-GERAL 

Ao finalizar a avaliação do recurso a tela quebra.
Nesse caso o proponente tinha desistido do prazo recursal.

![admis_13..png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f5d77ed4-dbb0-420a-89ed-39746d4966ae)

**Comment by vinnyfs89** [comment]
@romulomb Assim que chegar ao Minc, vou verificar.

**Comment by romulomb** [comment]
A TELA QUEBROU PORQUE CLIQUE EM FINALIZAR SEM DIGITAR A JUSTIFICATIVA.

Não consigo transformar está dando pau o sei.

**Comment by boletocosta** [comment]
Bom dia!

=============================================
Vamos começar pelo que acredito serem comportamentos incorretos:
=============================================

*Perfil componente de comissão:*

https://hmg.salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas

**1**. Coluna Recurso apresenta informação número 1 quando a proposta é enviada pelo Coordenador de Admissibilidade.

**2**. Quando o componente de comissão encaminha para o Coordenador Geral também cai na caixa do Coordenador de Admissibilidade. E se o Coordenador de Admissibilidade enquadrada de novo ele pode encaminhar novamente para CNIC e isso não pode acontecer. Além disso, quando o Coordenador de Admissibilidade enquadrou pela segunda vez a proposta apareceu duplicada no perfil Coordenador Geral.

*Perfil Coordenador Geral e de Admissibilidade:*

https://hmg.salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas

**3**. Coluna Recurso não está apresentando as informações corretas. Só aparece a informação “ 1 - Pedido de Reconsideração” para todos os tipos de situação:
•	Coluna Recurso apresenta informação número 1 quando proposta é enviada pelo Componente de Comissão. 
•	Coluna Recurso apresenta informação número 1 quando proponente desiste do prazo recursal.
•	Coluna Recurso apresenta informação número 1 quando proponente apresenta algum recurso. 

**4**. Quando o proponente desiste do prazo recursal abre a opção para avaliar o recurso (deferir ou indeferir) como se fosse um recurso mesmo. Na verdade deveria apenas liberar o botão para transformar, pois não houve recurso.

**5**. Quando o recurso do proponente é deferido o enquadramento não é alterado (permanece o mesmo antes do recurso).

**6**. Não há registro do parecer de deferimento ou indeferimento do recurso na proposta ou no projeto (tem que ficar salvo e registrado).

**7**. Erro ao tentar transformar em projeto: Arquivo WSDL não encontrado! Verifique: http://seitreinamento.cultura.gov.br/sei/controlador_ws.php?servico=sei

=============================
Agora vamos para as sugestões de melhoria:
=============================

**1**. Em todos os perfis quando uma proposta for arquivada copiar o texto do arquivamento e gravar no histórico de avaliações como se fosse uma avaliação. Assim evitamos o retrabalho de ter que primeiro gravar uma avaliação e depois gravar o arquivamento, pois o arquivamento já contaria como uma avaliação. 

**2**. Na listagem de propostas para o proponente incluir na coluna situação um alerta quando a proposta foi enquadrada em um artigo diferente e que o prazo para recurso está aberto. Atualmente a situação não muda (permanece como proposta em análise final).

**3**. Trocar o nome do botão AVALIAR para DILIGENCIAR, pois na prática a avaliação só acaba sendo usada para isso mesmo. Se o projeto não for diligenciado ele será enquadrado.

**Comment by AdmissibilidadeSAV** [comment]
Além dos relatados acima pelo André, tem mais esses que observei:

1) Nos perfis Coordenador de Admissibilidade, Componente da Comissão e Coordenador-geral de Admissibilidade e Aprovação na tela de enquadrar está trazendo como preenchimento padrão o enquadramento do proponente e não o do último perfil avaliador.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/0b513a3e-0d5a-45d6-893d-6d3ae34c0cd2)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/fe4c6caa-b9a6-4036-b670-fca92f0e0a69)

2) No perfil de Coordenador de Admissibilidade e Coordenador-geral de Admissibilidade e Aprovação está aparecendo a opção de transformar a proposta em projeto antes mesmo de enquadrar, encaminhar para CNIC, ou seja, antes de completar o fluxo de enquadramentos necessários.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/51dac45e-9ac5-4cc8-b3a2-a1a2c87511bd)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/bd510c17-ef00-4edf-a54d-63376f9310b2)

3) No perfil do proponente quando selecionar o tipo de solicitação “Desistência do prazo recursal” não precisa aparecer campo para justificativa, somente quando quiser apresentar recurso.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/a51ac191-14dd-4858-92f9-ccb7f48f3c5d)

Deveria ser algo parecido com a tela de análise do desarquivamento:

Para desistência de prazo recursal sem campo para justificativa:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/059f56e9-c69d-42e0-a0cc-5786239132cc)

Para Recurso:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/bbe00b26-f8b6-4f47-8526-c830d0ea2200)

4) No perfil de Componente da Comissão quando a proposta é enquadrada em área diferente da que o proponente solicitou ou que o técnico e coordenador enquadraram, após ser encaminhada para outro componente avaliar a proposta some.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/f1bbe281-80
21-4f91-86ba-ef4a9c12db09)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/87cfd42c-a154-485b-a1c8-27d82c4f1d93)

E não está caindo na caixa do titular da área (no caso abaixo de Música) e também na de nenhum outro.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/d9bd8e9c-842a-40ea-84ea-a80ac2f2ad7f)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/d94046d1-d86c-46a7-bfd3-eff5fcb840d0)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/72553f42-d424-45bc-9e80-978debaac73f)

E o fato do Coordenador de Admissibilidade não ter um painel para acompanhar as propostas encaminhadas para enquadramento pela CNIC gera insegurança, pois a proposta pode sumir sem que saibamos.

5) Em complementação ao que o André colocou, quando o proponente encaminha a desistência do prazo recursal abre um menu de avaliar recurso na qual aparece para deferir ou indeferir e motivar que ao meu ver não tem necessidade de análise, deveria só ficar registrado no histórico da proposta a data e horário e a informação de que houve a desistência do prazo recursal e não abrir o menu de recurso para avaliação.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/87330ab5-ef7d-426f-b8db-d8832b713f7f)

**Comment by boletocosta** [comment]
Boa tarde!

Dos erros que foram apontados anteriormente ainda não foram resolvidos:

Perfil componente de comissão: https://hmg.salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas

**1**. Coluna Recurso apresenta informação número 1 quando a proposta é enviada pelo Coordenador de Admissibilidade.

**2**. Quando o componente de comissão encaminha para o Coordenador Geral também cai na caixa do Coordenador de Admissibilidade. E se o Coordenador de Admissibilidade enquadrada de novo ele pode encaminhar novamente para CNIC e isso não pode acontecer. Além disso, quando o Coordenador de Admissibilidade enquadrou pela segunda vez a proposta apareceu duplicada no perfil Coordenador Geral.

Perfil Coordenador Geral e de Admissibilidade:
https://hmg.salic.cultura.gov.br/admissibilidade/admissibilidade/listar-propostas

**3**. Quando o recurso do proponente é deferido o enquadramento não é alterado (permanece o mesmo antes do recurso).

**4**. Está aparecendo a opção de transformar a proposta em projeto antes mesmo de enquadrar, encaminhar para CNIC, ou seja, antes de completar o fluxo de enquadramentos necessários.

**Comment by vinnyfs89** [comment]
Ok. Vou verificar.

**Comment by vinnyfs89** [comment]
### André( @boletocosta ):
Sobre os itens mencionados:

1. Não consegui reproduzir esse item. Pode abrir uma nova issue detalhando essa informação(prints, links, perfil...) ?
2. É considerada uma melhoria no fluxo de admissibilidade. Pode abrir uma nova Issue para issue.
3. Não consegui reproduzir esse item. Pode abrir uma nova issue detalhando essa informação(prints, links, perfil...) ?
4. Conforme meu comentário anterior e solicitação anterior do Rômulo no início dessa issue, assim que a proposta estiver enquadrada no artigo correto automaticamente deveria liberar o botão para transformar em projeto. Itens fora desse escopo devem ser abertos em uma nova Issue com a nova definição.

Por favor, alinhem com o Rômulo primeiramente. Ok?
