### ISSUE TITLE
[Readequações] Transferência de recursos - Liberar link do menu

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#782]
Regra para liberação do link de readequação de transferência de recursos:

* Somente projetos com valor a comprovar podem transferir recursos

**Comment by romulomb** [comment]
NÃO ENCONTREI O LINK PARA HOMOLOGAR.

**Comment by fernao** [comment]
@romulomb             
O link para realizar uma readequação de transferência de recursos somente abre quando há condições para um projeto transferir e possuir projetos recebedores disponíveis.

**Comment by clebersantos** [comment]
Disponível em homologação.
