### ISSUE TITLE
[Readequação] Interface da criação de  readequação de transferência de recursos

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#783]
Interface da criação de  readequação de transferência de recursos

* [x] Tela básica
* [x] Informações do projeto
* [x] Criação / edição de readequação
* [x] Adição / remoção de projetos recebedores

**Comment by fernao** [comment]
pronac da lista de projetos recebedores não exibe logo após adicionar

**Comment by fernao** [comment]
Adicionar formatação de moeda

**Comment by romulomb** [comment]
ATUALIZAR O BANCO DE HOMOLOGAÇÃO PARA GERAR DADOS QUE  PERMITA HOMOLOGAR A FUNCIONALIDADE.

**Comment by fernao** [comment]
Adicionada funcionalidade de excluir readequação de transferência de recursos
