### ISSUE TITLE
[Readequação] Transferência de recursos - interface de aprovação de recursos

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#785]
Lado MinC: interface de aprovação de recursos

**Comment by fernao** [comment]
não necessário

**Comment by fernao** [comment]
@romulomb:
O fluxo e as telas já funcionam corretamente para readequações comuns. Cabe decidir quais especificidades serão adicionaras à tela de análise do técnico.

Sugestão:
- listar projetos, área e valores destinados

**Comment by fernao** [comment]
ocultar solicitação de readequação na visualização do técnico

**Comment by fernao** [comment]
Adicionar formatação de moeda

**Comment by romulomb** [comment]
ATUALIZAR O BANCO DE HOMOLOGAÇÃO PARA GERAR DADOS QUE  PERMITA HOMOLOGAR A FUNCIONALIDADE.
