### ISSUE TITLE
[Readequação] Backend de executar transferência de saldos quando aprovada

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#787]
Backend de executar transferência de saldos quando aprovada

**Comment by romulomb** [comment]
Não sei o que homologar aqui.

**Comment by fernao** [comment]
Verificar se finaliza corretamente e grava dados corretamente na tabela tbProjetoRecebedorRecurso

**Comment by romulomb** [comment]
ATUALIZAR O BANCO DE HOMOLOGAÇÃO PARA GERAR DADOS QUE  PERMITA HOMOLOGAR A FUNCIONALIDADE.
