### ISSUE TITLE
[Readequação] Avaliação - Plano de Distribuição

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#791]
Eu como técnico de acompanhamento, desejo avaliar o plano de distribuição detalhado atualizado na readequação.

- [x] adicionar novo modelo na tela de Técnico de acompanhamento
- [x] adicionar novo modelo na tela de Coordenador de acompanhamento
- [x] atualizar botões para o estilo do material design
- [x] quando o coordenador de acompanhamento finalizar a avaliação da readequação, se a solicitação for deferida o sistema deve atualizar as tabelas de planoDistribuicaoProduto e a tbDetalhaPlanoDistribuicao com os novos valores
- [x] no painel de readequações analisadas, remover a opção de enviar para CNIC da listagem e mover para uma tela própria

**Comment by clebersantos** [comment]
Issue disponível para homologação. @romulomb, @thais_mendess, @Romulo_Menho e @boletocosta.

**Comment by romulomb** [comment]
**PERFIL DO PROPONENTE**
O botão EDITAR no detalhamento não está funcionando a tela vem em branco,
![plano_1](https://user-images.githubusercontent.com/32374573/40518240-feb82e28-5f8f-11e8-8ee0-1217e2e13276.png)

A exclusão deverá solicitada somente quando for aprovada originalmente e não quando digitada na readequação.
![plano_2](https://user-images.githubusercontent.com/32374573/40518424-f85b578e-5f90-11e8-9730-535dbc4a600e.png)

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**
![plano_3](https://user-images.githubusercontent.com/32374573/40518761-8faa6868-5f92-11e8-8a05-fbee758c7bad.png)

Permitiu enviar sem justificativa
![plano_4](https://user-images.githubusercontent.com/32374573/40518851-f164a08c-5f92-11e8-883b-9bbbe24ed51a.png)

O botão FINALIZAR desapareceu do painel do Coordenador de Acompanhado após a análise do técnico.  
É muito difícil enviar projeto readequado à CNIC.
![plano_5](https://user-images.githubusercontent.com/32374573/40519201-b6ee6ab2-5f94-11e8-855b-a20cd603066d.png)

**NÃO CONSEGUI FINALIZAR A READEQUAÇÃO**

**Comment by clebersantos** [comment]
@romulomb e @romulo_menho, na parte da avaliaçao, o campo finalizar não aparecia devido ao tamanho da sua tela e o tamanho da tabela de listagem. Removi a opção de `encaminhar para CNIC` da listagem e criei uma tela própria para o envio.

Pode testar novamente?

**Comment by AdmissibilidadeSAV** [comment]
No perfil de Coordenador de Acompanhamento, após a análise do Técnico, quando clico em Finalizar aparece a tela abaixo:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/24811273-d823-4173-8bfa-7fc7ea2f05e9)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV Corrigido. Pode testar novamente?

**Comment by AdmissibilidadeSAV** [comment]
Ok, a finalização da readequação foi corrigida.

Porém, quando consulto o projeto para verificar se atualizou o Plano de distribuição (Outras informações/Plano de Distribuição) não dá para visualizar os detalhamentos apenas o Resumo. O Pronac é o 172229.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/b4a7770b-5bee-4719-8d37-b96edb75decb)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV e @thais_mendess, o erro reportado ocorria apenas no ambiente de homologação, o problema já foi corrigido. 

Tendo em vista que a tela e o erro reportado não fazem parte do módulo de readequação, estou elevando a estimativa desta tarefa em 4 pontos. #ReavaliarEstimativa

Pode fazer o teste novamente?

**Comment by AdmissibilidadeSAV** [comment]
Testei e está ok, também testei todas as telas que o @romulomb reportou erro e está tudo ok.

**Comment by romulomb** [comment]
HOMOLOGADO,

SUBIR PARA A PRODUÇÃO PRO GENTILEZA.
