### ISSUE TITLE
Alterar e ajustar as consultas do menu lateral

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#800]
A alteração consiste somente nos dados complementares do projeto localizado no menu lateral outras informações.

Tarefas:

**1. Retirar as informações do Período de execução conforme a tela**
![Menu_Lateral_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/63aff388-15ed-426f-8503-fdbc0d4f9b45)

**2. Incluir Três novos itens:**

   a. Objetivos que sairá da tela inicial e irá para esse menu lateral;

   b.  Justificativa que também sairá da tela principal e será um novo item desse menu lateral.

   c. Custos vinculados que entrará nesse menu lateral.
       
 **Query da recuperar os custos vinculados**

 SELECT a.idProjeto,a.idPlanilhaItem,b.Descricao as dsItem,a.dtCadastro,a.pcCalculo as Percentual
FROM sac.dbo.tbCustosVinculados a
INNER JOIN sac.dbo.tbPlanilhaItens b on (a.idPlanilhaItem = b.idPlanilhaItens)
WHERE a.idProjeto = [ID DA PROPOSTA] 
ORDER BY dsItem

**Comment by wouerner** [comment]
@romulomb @Romulo_Menho , preciso que faça o seu detalhamento dessa demanda.

**Comment by romulomb** [comment]
Definição na issue

**Comment by RuanHerculano** [comment]
Feito e enviado para homologação. @romulomb

**Comment by RuanHerculano** [comment]
Feature enviada pra homologação @romulomb

**Comment by romulomb** [comment]
**AJUSTE**

O item da consulta  **Custos Vinculados* está retornando a informação incorreta. Ajustei a query para facilitar o retorno da informação. A query anterior  trabalha com o idProjeto ou seja no nº da proposta e a aplicação está usando o idpronac para retornar a informação. Com a query ajustada a aplicação retornará corretamente a informação com a chamada pelo idpronac.

SELECT c.IdPRONAC,a.idProjeto,a.idPlanilhaItem,b.Descricao as dsItem,a.dtCadastro,a.pcCalculo as Percentual 
FROM sac.dbo.tbCustosVinculados    a 
INNER JOIN sac.dbo.tbPlanilhaItens b on (a.idPlanilhaItem = b.idPlanilhaItens) 
INNER JOIN sac.dbo.Projetos        c on (a.idProjeto      = c.idProjeto)
WHERE c.IdPRONAC = 214995 ORDER BY dsItem

Ajuste de layout do custos vinculados conforme figura abaixo.

![Dados.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/33bb2bb1-1b2c-4601-8e52-9df8eff394f9)

---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------

**MELHORIA**

1. Remover o bloco **Última Tramitação** da tela principal.
![UltimaTramitacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/7aa5faf2-fc1e-43ab-a863-dbb663670853)

2.  Inserir o bloco **Última Tramitação** dentro do menu **Dados complementares do projetos** antes do item objetivos com o título **Última Tramitação** e com a mesma formatação da tela inicial conforme a tela do item 1.

Segue a query que retornará a informação

SELECT sac.dbo.fnNomeUsuario(idUsuarioEmissor)  as Emissor,DtTramitacaoEnvio,
       sac.dbo.fnNomeUsuario(idUsuarioReceptor) as Receptor,Situacao as Estado,dtTramitacaoRecebida,Destino,meDespacho 
FROM SAC.dbo.vwTramitarProjeto WHERE idPronac = [idPronac]

**Comment by romulomb** [comment]
Ajuste na definição

**Comment by RuanHerculano** [comment]
@romulomb ajustei no código para que os dados de "Custos Vinculados" sejam buscados pelo "idPronac", o "Inner Join" com a tabela de projetos já pode ser retirado.

**Comment by romulomb** [comment]
Nesse caso não tem como pegar o custos vinculados sem o INNER JOIN.

Está retornando a informação incorreta.

Pronac  178894

**Deveria retornar**

Custos de Administração - 15%

Custos de Divulgação - 10%

Remuneração para captação de recursos - 10%

**Retornou**

Custos de Administração	15%

Custos de Divulgação	30%

Remuneração para captação de recursos	10%

**Comment by romulomb** [comment]
HOMOLOGADO.

**Comment by romulomb** [comment]
ESTÁ HOMOLOGADO E NÃO SUBIU PARA PRODUÇÃO.
