### ISSUE TITLE
implementar a funcionalidade que permitirá o proponente alterar o projeto na diligência do parecerista

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#811]

**Comment by decko** [comment]
@romulomb @romulo_menho por favor, detalhe esta issue para que possamos estimar corretamente.

**Comment by romulomb** [comment]
Essa tarefa entrou na negociação da assinatura digital e tinha dessa pacote,

Gostaria de saber se voltou para esse pacote.

**Comment by romulomb** [comment]
ISSUE FECHADA PORQUE NÃO ESTÁ MAIS NA SPRINT, UMA VEZ QUE ENTROU NA NEGOCIAÇÃO DA ASSINATURA DIGITAL DA READEQUAÇÃO.
