### ISSUE TITLE
Análise Planilha orçamentária

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#814]
### 1. Utilizar o mesmo formato da análise de todos os comprovantes. ###

 Para facilitar foi criado a store procedure **spComprovacaoFinanceiraProjeto(idpronac,Margem)**, onde a margem poderá ser :
a. 100 - para analisar todos os comprovantes (geral)

b. 99 - nível de confiança com margem de erro de 1%

c. 95 - nível de confiança com margem de erro de 2,5%

d. 90 - nível de confiança com margem de erro de 5%.

**e. persistir as mesma regras da análise completa porque a única diferença é a quantidade de comprovações a serem analisadas.**

**Check List**
- [x] Colocar novo layout da planilha

- [x] Criar nova consulta com os dados da planilha 

### 2.  Botão de voltar com  as abas expandidias. ###

Para facilitar a navegabilidade do usuário, o botão de "voltar" deve retornar para a tela de planilha orçamentária, com a aba no qual está o último comprovante que o usuário acessou expandida.

## Testes
**Testes Internos por** @volthier

**Comment by wouerner** [comment]
Pra estimar eu preciso do detalhamento. @romulomb

**Comment by romulomb** [comment]
Essa issue não estava em impedimento ontem à noite. Ela entrou agora.

**Comment by romulomb** [comment]
Detalhamento na issue

**Comment by RuanHerculano** [comment]
@guiamado @decko @wouerner, A issue #814 teve alteração no valor estimado por conta da nova spComprovacaoFinanceiraProjeto, onde a mesma vai precisar de uma análise para que possamos desenvolver a funcionalidade de forma correta, e também o desenvolvimento do novo layout para se readequar as novas informações apresentadas. Justificando assim o aumento da pontuação da issue.

**Comment by pauli10** [comment]
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/a21f4b63-495d-4d9b-8dba-73f2aeb9412e)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/8e583ca3-6946-447d-9b18-538e1ea05dde)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/41ce2eb4-16ec-40d1-8cc5-71f1c9fedb0a)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/1e8d46bd-0115-4dbe-abaa-3bac4ff524ee)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/48ce4916-131e-44dc-a8a2-df5249538ead)

**Comment by romulomb** [comment]
Segue para ajuste.

**Comment by pauli10** [comment]
O comentário desta tela pode desconsiderar, pois agora faremos o controle pelo botão no canto direito dentro de cada item.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/545a0e51-828c-454f-99c7-d1b561e08396)

**Comment by pauli10** [comment]
Os valores aprovados, comprovados e a comprovar estão diferentes na tela de análise do item e na tela inicial da análise.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/0be5046a-f721-4744-9e3a-dbe6aaa2ed33)
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/b5a1ad02-db99-4b4a-bace-574f06ac33ff)

Alguns dos erros da tela abaixo já estão registrados em telas de comentários acima
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/98c8a0ac-218b-4966-8753-7b036736c762)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/31a1953a-f38f-48da-aa37-ebdbf09344f5)

Divergência entre o valor Autorizado p/ Captar e a planilha associada a ele:
Caso 1:
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/e0490266-362a-4dff-8786-75723308f290)
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/718b9b62-e7db-4138-9ff2-03a74fe7c006)
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/aa6178a6-6828-4369-a391-d4559c3de8a0)

Caso 2:
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/a7059a70-97d7-476e-bf97-98e1e7228af6)
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/679cad5f-747e-43d0-a437-f641b0b65c1a)
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/453f54cd-7cdc-4d03-9f93-9f69d9a3b5d0)

Valor Comprovado maior do que o Valor Aprovado:
Pronac: 16-0064
Esse erro já havia sido corrigido em outro momento e foi homologado fazendo testes no projeto QuerMuseu. Peço que o Rômulo observe essa questão, uma vez que levanta a insegurança quando digo que algumas soluções são realizadas caso a caso.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/c2542347-a42c-47dd-bbcc-6cb6c7d9c735)

Pronac: 14-13995
Foram aprovados dois itens orçamentários “Mídia Radiofônica”:
Esse erro também já havia sido corrigido. Portanto, como foi falado na última reunião (do dia 13/08/2018), ratifico que as soluções estão sendo executadas no caso a caso. Peço o olhar especial, principalmente do Rômulo, pois a homologação fica impossível dessa forma.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/916afeb7-e04a-46c9-8786-7c50ef55398e)
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/968baa36-b747-4380-a696-d5db3e294401)

Ao abrir o primeiro item,  observa-se que foram incluídos dois comprovantes cuja soma é maior do que o valor aprovado:
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/7be0cf5c-641f-4981-bb36-00c843291e27)

Ao abrir o segundo item, observa-se a repetição de informações e comprovantes do primeiro item:
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/0752f48e-8594-44b5-a919-b31f19226f99)

**Comment by wouerner** [comment]
16 0064 e 12 8616 -> pronac para verificação em Homologação.

**Comment by pauli10** [comment]
Manter a data do envio da prestação de contas com a formatação correta.

**Comment by pauli10** [comment]
A data de emissão do documento ainda está aparecendo a data atual.

**Comment by romulomb** [comment]
Pessoal, alguns projetos mais antigos não tem esse campo alimentado, ou seja está com valor da data de envio é igual a null, talvez seja o motivo de estar trazendo a data atual.
