### ISSUE TITLE
Laudos e assinatura digital

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#815]
**PERFIL DO TÉCNICO**

Ao terminar o parecer o sistema deverá geral o documento para que o técnico possa assinar.

O ato administrativo para essa caso é o 622 - Parecer de Avaliação Financeira.

As informações do documento a ser gerado será a que for digitado na tela abaixo com a manifestação final do técnico
![Parecer_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/1ddf1ec2-2be4-4216-ac6f-3808ac53d10b)

**PERFIL DO CHEFE DE DIVISÃO**

As funcionalidades desse perfil passarão para o perfil de Coordenador de Prestação de Contas

**PERFIL DO COORDENADOR DE PRESTAÇÃO DE CONTAS**

**Comment by wouerner** [comment]
Pra estimar, eu preciso do detalhamento. @romulomb

**Comment by romulomb** [comment]
Essa issue não estava em impedimento ontem à noite. Ela entrou agora.

**Comment by vinnyfs89** [comment]
Dica :

SQL pata obter informações de Assinatura sobre o Tipo de Ato Administrativo:
```
select TbAtoAdministrativo.idTipoDoAto,
  sac.dbo.TbAtoAdministrativo.idOrdemDaAssinatura,
--   sac.dbo.TbAtoAdministrativo.idOrgaoDoAssinante,
--   sac.dbo.TbAtoAdministrativo.idOrgaoSuperiorDoAssinante,
  Orgaos.Sigla as OrgaoPerfil,
  OrgaoSuperior.Sigla as OrgaoPerfilSuperior,
  Tabelas.dbo.Grupos.gru_nome
from sac.dbo.TbAtoAdministrativo
 inner join Tabelas.dbo.Grupos on Grupos.gru_codigo = TbAtoAdministrativo.idPerfilDoAssinante
 inner join sac.dbo.Orgaos on Orgaos.Codigo = TbAtoAdministrativo.idOrgaoDoAssinante
 inner join sac.dbo.Orgaos OrgaoSuperior on OrgaoSuperior.Codigo = TbAtoAdministrativo.idOrgaoSuperiorDoAssinante
where idTipoDoAto = [identificadorDoTipoDoAtoAdministrativo]
```

**Comment by vinnyfs89** [comment]
Apesar de não ter sido solicitado, foi criado um item de menu para ir diretamente para a lista de documentos para assinar filtrados pelo tipo de assinatura de Laudo de Prestação de Contas (622)

**Comment by pauli10** [comment]
@vinnyfs89 e @Romulo_Menho  , quando clico em emitir parecer mostra página não encontrada. Acho que isso impossibilita testar esta issue. Em assinatura- gerenciar ou visualizar assinatura- não há nenhum registro pq não tem nenhum parecer emitido. 
Tem alguma ideia de como assinar sem ter que emitir parecer?
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/a57339ba-455a-4d41-ad12-05afd21726de)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/5dfd4da1-9cea-487d-9347-1e0e1005d51c)

**Comment by romulomb** [comment]
Segue para ajuste.

**Comment by vinnyfs89** [comment]
O @wouerner está verificando.

**Comment by wouerner** [comment]
Vou fazer o testes, e verificar o fluxo.

**Comment by pauli10** [comment]
O @romulomb melhorará a especificação neste final de semana (21 e 22/07).

**Comment by romulomb** [comment]
**ISSUE SUBSTITUÍDA PELA 1065**
