### ISSUE TITLE
CONSULTAR DADOS DO PROJETO

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#822]
**Esta tarefa é composta por três fases.**
* [x] 1. Alterar a consulta da tela principal; e
* [x] 2.  Alterar o menu lateral para convênio

-------------------------------------------------------------------------------------------------

**FASE 1 - ALTERAR A CONSULTA DA TELA PRINCIPAL**

A consulta da tela principal deverá ser **renderizada** conforme o mecanismo do projeto. 
Para os mecanismos  **2 (FNC)  ou  6(outras fontes)** deverá utilizar as opções abaixo:

a) Utilizar o **SELECT** abaixo para retornar as informações que serão utilizadas na renderização.

**SELECT idPronac,Pronac,NomeProjeto,CNPJ_CPF,Proponente,UfProjeto,idMecanismo,Mecanismo,Area,Segmento,Processo,DtConvenioPrimeiraVigencia,
       DtConvenioUltimaVigencia,NrConvenio,DtConvenio,DtConvenioPublicacao,ResumoProjeto,Objeto,DtSituacao,Situacao,ProvidenciaTomada,
	   LocalizacaoAtual,DtArquivamento,CaixaInicio,CaixaFinal,SolicitadoCusteio,SolicitadoCapital,vlTotalSolicitado,
	   ConcedidoCusteio,ConcedidoCapital,Contrapartida,vlTotalAprovado,ValorConvenio

FROM vwConsultarDadosDoProjetoFNC 
WHERE IdPRONAC = 208904**

b) **O formato da consulta deverá ser conforme a tela abaixo**.
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b2022012-f4de-4a75-9674-5d0cfa2e0121)

**OBSERVAÇOES:
1) O bloco com o título **Arquivado definitivamente** deverá ser mostrado somente quando os atributo **DtArquivamento, CaixaInicio e CaixaFinal** não forem nulos.
2) O alinhamento dos campos e labels deverá ser exatamente conforme a tela anexada. 

------------------------------------------------------------------------------------------------------------------

A consulta da tela principal deverá ser **renderizada** conforme o mecanismo do projeto. 
Para mecanismos **DIFERENTE** 2 (FNC)  ou  6(outras fontes) deverá utilizar as opções abaixo:

SELECT idPronac,Pronac,NomeProjeto,CNPJ_CPF,Proponente,UfProjeto,idMecanismo,Mecanismo,Area,Segmento,Enquadramento,idPreProjeto,DataFixa,
       Processo,ProrrogacaoAutomatica,PlanoExecucaoImediata,DtInicioCaptacao,DtFimCaptacao,DtInicioExecucao,DtFimExecucao,
	   TipoPortariaVigente,NrPortariaVigente,DtPublicacaoPortariaVigente,AgenciaBancaria,ContaCaptacao,ContaMovimentacao,
	   ContaBancariaLiberada,DtLiberacaoDaConta,ResumoProjeto,DtSituacao,Situacao,ProvidenciaTomada,LocalizacaoAtual,DtArquivamento,
	   CaixaInicio,CaixaFinal,vlSolicitadoOriginal,vlOutrasFontes,vlProposta,vlAprovado,vlProjeto,vlAdequadoAExecucao,vlHomologado,
	   vlAExecutar,vlCaptado,vlTransferido,vlRecebido,vlSaldoACaptar,PercentualCaptado,vlComprovado,vlAComprovar,PercentualComprovado

FROM vwConsultarDadosDoProjeto 

WHERE idPronac = 189786

b) **O formato da consulta deverá ser conforme a tela abaixo**.
![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/db86a200-408d-437e-80b5-d40007880080)

**OBSERVAÇOES:
1) O bloco com o título **Arquivado definitivamente** deverá ser mostrado somente quando os atributo **DtArquivamento, CaixaInicio e CaixaFinal** não forem nulos.
2) O alinhamento dos campos e labels deverá ser exatamente conforme a tela anexada.

**Comment by clebersantos** [comment]
@romulomb, para os projetos diferentes do Mecenato terá um menu específico? Pode detalhar quais serão as opções?

**Comment by clebersantos** [comment]
@romulomb e @Romulo_Menho, para os projetos diferentes do Mecenato terão um menu específico? Pode detalhar quais serão as opções?

**Comment by romulomb** [comment]
**AJUSTE NA QUERY PARA RENDERIZAÇÃO DO INCENTIVO FISCAL FEDERAL**

SELECT idPronac,Pronac,NomeProjeto,CNPJ_CPF,Proponente,UfProjeto,idMecanismo,Mecanismo,Area,Segmento,idPreProjeto,Enquadramento,DataFixa,Processo,ProrrogacaoAutomatica,PlanoExecucaoImediata,
       DtInicioCaptacao,DtFimCaptacao,DtInicioExecucao,DtFimExecucao,TipoPortariaVigente,NrPortariaVigente,DtPublicacaoPortariaVigente,AgenciaBancaria,ContaCaptacao,ContaMovimentacao,
	   ContaBancariaLiberada,DtLiberacaoDaConta,ResumoProjeto,DtSituacao,Situacao,ProvidenciaTomada,LocalizacaoAtual,DtArquivamento,CaixaInicio,CaixaFinal,Normativo,dtPublicacaoNormativo,
	   dtRevogacaoNormativo,FaseProjeto,dtInicioFase,dtFinalFase,vlSolicitadoOriginal,vlOutrasFontesPropostaOriginal,vlTotalPropostaOriginal,vlAutorizado,vlAutorizadoOutrasFontes,vlTotalAutorizado,
	   vlAdequadoIncentivo,vlAdequadoOutrasFontes,vlTotalAdequado,vlHomologadoIncentivo,vlHomologadoOutrasFontes,vlTotalHomologado,vlReadequadoIncentivo,vlReadequadoOutrasFontes,vlTotalReadequado,
	   vlCaptado,vlTransferido,vlRecebido,vlSaldoACaptar,PercentualCaptado,vlComprovado,vlAComprovar,PercentualComprovado
 FROM vwConsultarDadosDoProjeto WHERE IdPRONAC = 216409


**AJUSTE NO LAYOUT  DO INCENTIVO FISCAL FEDERAL**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/fe5d0bf1-77e8-41fc-8cbc-1bc867f79798)

**Comment by clebersantos** [comment]
Aumentando 20 pontos na tarefa, em razão das alterações da view e do template.

#ReavaliarEstimativa

**Comment by clebersantos** [comment]
@romulomb, conforme conversamos, preciso do detalhamento das páginas que serão chamadas pelos links, inclusive das planilhas.

**Comment by clebersantos** [comment]
@romulomb, finalizei todas as demandas dessa issue. Ficou pendente a definição das planilhas aprovada para captação (IN anterior à 2017), homologada e readequada. Estou colocando o card na coluna de impedimentos, tendo em vista que as outras atividades já foram finalizadas.

**Comment by romulomb** [comment]
Segue a sp que montará as planilhas homologadas e as readequadas.

EXEC **spRenderizarPlanilhas**  [idPronac], [TipoPlanilha]

Para planilha homologada o parâmetro TipoPlanilha deverá ser igual a **AP**;

Para planilha readequada o parâmetro TipoPlanilha deverá ser igual a **RE**;

**Comment by clebersantos** [comment]
@romulomb planilhas homologada e readequada disponível no ambiente de homologação.

**Comment by clebersantos** [comment]
@romulomb planilhas homologada e readequada disponíveis no ambiente de homologação.

**Comment by clebersantos** [comment]
@romulomb, subi mais uma versão para homologação. Já com os valores da proposta original e valor autorizado com a soma da planilha congelada da proposta.

**Comment by romulomb** [comment]
Valores das planilhas homologada e readequada não estão corretos.

**Comment by clebersantos** [comment]
@romulomb, os valores da planilha homologada e readequada são da query que migrei da view.

**Comment by clebersantos** [comment]
@romulomb, como os valores são gerados da view migrada, tenho que avaliar onde o erro está ocorrendo. Os projetos que consultei estão corretos. Pode detalhar melhor o problema, informando os projetos que estão com inconsistência e os valores corretos? 

Preciso dessas informações para dar continuidade na demanda.

**Comment by romulomb** [comment]
@clebersantos PRONAC 17 7492

**Comment by clebersantos** [comment]
Aplicado a regra: quando a planilha é homologada ou readequada, o valor total da planilha é a soma da coluna vlAprovado. Os valores do Pronac informados estão corretos após aplicação da regra. Card para homologação novamente.

**Comment by clebersantos** [comment]
@romulomb, as alterações solicitadas foram realizadas.

**Comment by clebersantos** [comment]
Valor homologado atualizado.

**Comment by AdmissibilidadeSAV** [comment]
O pronac 171583 já foi autorizado a captar recursos, porém, não aparece em Valores a linha correspondente a **"Autorizado p/ Captar"**

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/fafaa243-cdb0-4a35-8692-d6b390466257)

**Comment by clebersantos** [comment]
Atualizado. 

Se não aparecer, pode ser cache da página. Atualize a página usando 'ctrl+shift+r' se tiver usando o Chrome.

**Comment by AdmissibilidadeSAV** [comment]
O pronac 171583 agora está ok (apareceu o "Autorizado p/ Captar"), porém, consultando outro projeto o de pronac: 161713 deparei com outro problema, no campo "Solicitação da proposta original" o valor solicitado o correto é R$ 1.497.560,00 e não R$ 1.496.479,20 como consta lá. Esse projeto não tem recurso de outras fontes e aparece o valor de R$ 1.080,80, que verificando melhor para entender a tramitação do projeto, constatei que esse valor corresponde ao valor reduzido na fase de análise técnica inicial.

Já em "Autorizado p/ Captar" apareceu os valores zerados.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/5616a0a6-3220-4cad-a147-29b4c761ffa7)

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV o valor autorizado foi corrigido.

Sobre o valor da proposta original, o @romulomb tem que ajustar `fnVlSolicitadoOriginal` no banco de dados.

Pode verificar se está ok?

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos O valor autorizado não está mais zerado, mas está trazendo o valor solicitado e não o valor que foi autorizado a captar.

**Comment by clebersantos** [comment]
@romulomb pode verificar esses valores?

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV, o @romulomb atualizou os valores e o código já está disponível em produção. Tendo em vista que essa demanda já está em produção essa issue será fechada. 

Se existir algum erro, será necessário abrir uma nova issue.
