### ISSUE TITLE
[Readequação] Transferência de recursos:  implementar regra de transferência de recursos condicionada a área e tipo

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#824]
* [x] Interface: implementar regra de transferência de recursos condicionada a área e tipo
* [x] Backend: consulta de projetos do mesmo proponente
* [x] Backend: consulta de projetos de outros proponentes

**Regras:**
Dado um projeto transferidor, quero obter uma lista de projetos possíveis a receber.
Pode receber de proponentes diferentes se for 'patrimônio' ou 'museu e memória'. Nos outros casos, é do mesmo proponente.

art. 28:

    não homologação: transferência para um único projeto do mesmo proponente
    não homologado 'patrimônio' ou 'museu e memória': pode ser transferido para outros projetos de qualquer proponente

art. 29:
§ 3o. : projeto pode requerer transferência dos recursos captados (antes da emissão do cartão e início da execução financeira - regra de liberação de link)

art. 42:

    recursos remanescentes: podem ser transferidos para planos anuais, plurianuais ou ação continuada, do mesmo proponente, desde que o projeto anterior seja encerrado

**Comment by fernao** [comment]
@romulomb Em quais condições um projeto é considerado APTO a receber recursos ?

**Comment by fernao** [comment]
@romulomb Uma questão surgiu da implementação da regra acima:

Ao aplicar a regra, não consegui encontrar nenhum projeto apto a transferir que possuísse um projeto sequer apto a receber. Logo, percebi que fica meio sem sentido o proponente conseguir acessar a funcionalidade de Transferir Recursos apenas considerando a aptidão a transferir.

Traduzindo para uma história de uso:
Sou um proponente. Tenho um projeto com saldo a comprovar; logo, ele pode transferir. Esse projeto não é das áreas de Patrimônio e Memória, logo só posso transferir para projetos em que também sou proponente. E não há nenhum projeto nessas condições.

Questão: casos como esse deveriam ter a funcionalidade travada já na liberação de links? 

Ticket relacionado: #782

**Comment by romulomb** [comment]
Correto, se não preenche as condições também não precisam ter essa funcionalidade à disposição.

Se tiver vão tentar usar e o técnico terá o trabalho de recusar.

Sua avaliação está correta.

**Comment by fernao** [comment]
então isso adiciona essa complexidade à fnLiberarLinks, que já estava fechada. Vou reabrir a #782

**Comment by romulomb** [comment]
ATUALIZAR O BANCO DE HOMOLOGAÇÃO PARA GERAR DADOS QUE  PERMITA HOMOLOGAR A FUNCIONALIDADE.
