### ISSUE TITLE
[READEQUAÇÃO] - SOLICITAÇÕES GERAIS

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#829]
A finalidade do card é realizar ajustes no módulo de readequação.

O fluxo abaixo descreve as fases desse processo.

[https://app.zenhub.com/files/104502087/0f2523df-f85c-49f7-a1dc-56a491815972/download](https://app.zenhub.com/files/104502087/0f2523df-f85c-49f7-a1dc-56a491815972/download)

A readequação parte de uma solicitação do proponente pelo seu **ESCRTIÓRIO VIRTUAL DO PROPONENTE**  que deverá ser avaliada pelo Coordenador de Acompanhamento e decidirá se defere, indefere ou devolve ao proponente.

No caso do deferimento a solicitação segue para análise e emissão de parecer técnico.

---------------------------------------------------------------------------------------------------------------

# **ESCRITÓRIO VIRTUAL DO PROPONENTE**

Será efetuado as alterações elencadas abaixo.

**1. Alteração do menu lateral de readequação que será conforme descrito abaixo**.
![Readequacao_Menu.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/693e3a4b-259c-4bc3-95d7-425f73d6a1a3)

**2. As opções que deverão contemplar as  readequações Diversas**:

a. Acessibilidade

b. Agência Bancária

c. Alteração de Proponente

d. Alteração de Razão Social

e. Democratização de Acesso

f. Especificação Técnica

g. Estratégia de Execução

h. Etapas de Trabalho

i. Ficha Técnica

j. Impacto Ambiental

k. Justificativa

l. Nome do Projeto

m. Objetivos

n. Período de Execução

o. Resumo do Projeto

q. Sinopse da Obra

**QUERY PARA CARREGAR O COMBO DAS SOLICITAÇÕES GERAIS**

SELECT idTipoReadequacao, dsReadequacao 
  FROM SAC.dbo.tbtiporeadequacao AS a 
 WHERE     siReadequacao = 0
       AND stEstado = 0
       AND idTipoReadequacao NOT IN (SELECT idTipoReadequacao FROM SAC.dbo.tbReadequacao WHERE idPronac = 210674 AND stEstado = 0)
 ORDER BY 2 ASC

**Regras**
O projeto será liberado para solicitar as readequações diversas após ter sido Homologado para executar ou seja ser apreciado pela CNIC.

**3. Os itens abaixo comporão também o menu de readequação mas terão regras diferentes para serem exibidos**

r. Local de Realização

s. Planilha Orçamentária

t. Plano de Distribuição

u. Remanejamento até 50 %

v. Transferência de Recursos

z. Saldo de Aplicação

z. Solicitações Diversas

---------------------------------------------------------------------------------------------------------------

# **ANÁLISE DA SOLICITAÇÃO PELO MINC**

As rotinas de análise já estão implementadas mas é necessário ajustar os layouts para os novos padrões.

**Comment by romulomb** [comment]
Atualizado

**Comment by clebersantos** [comment]
O que mudou?

**Comment by vinnyfs89** [comment]
@romulomb quais ações customizadas que as duas( **653 - Parecer Técnico de Readequação de Projeto e 654 - Parecer Técnico de Ajuste de Projeto**) assinaturas devem possuir?
Exemplo: 
- Finalizar
- Devolver

A tela de lista de projetos para assinatura deverá seguir os mesmo moldes da tela de Assinatura para Enquadramento?

**Comment by clebersantos** [comment]
@romulomb, o menu lateral, no item Readequação, em consultar dados do projeto , deverá ficar assim?
```
Readequação
 - Local de Realização
 - Planilha Orçamentária
 - Plano de Distribuição
 - Remanejamento até 50 %
 - Transferência de Recursos
 - Saldo de Aplicação
 - Diversas
```

Para Plano de Distribuição e Local de Realização, existe alguma regra específica?

**Comment by romulomb** [comment]
Para Plano de Distribuição e Local de Realização, existe alguma regra específica?

Será a mesma regra que libera o link para Solicitações Gerais.
