### ISSUE TITLE
[Admissibilidade] Botão encaminhar

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#831]
No perfil de Coordenador de Admissibilidade após enquadrar uma proposta não está aparecendo o botão de encaminhar para o Componente da Comissão.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/bc60c361-cc7d-447a-bc96-b69cae9ed3f9)

http://salic.cultura.gov.br/admissibilidade/admissibilidade/exibirpropostacultural?idPreProjeto=279933&realizar_analise=sim

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Thaís, o Botão não aparece para encaminhar porque na regra atual do sistema, é necessário ter ao menos uma distribuição ativa. 

**Exemplo:** Do técnico para o coordenador > Coordenador p/ próximo Perfil. Criarei uma regra que permita executar essa ação à partir do Coordenador de admissibilidade, sem possuir distribuição.

Pelo o que investiguei sobre os dados da Issue que você informou, foram realizadas mais de uma sugestão de enquadramento, uma por técnico de admissibilidade outra por coordenador de admissibilidade. A diferença é que a proposta não tinha sido encaminhada para o Coordenador de Admissibilidade.

Para tratar esse cenário, fiz a seguinte melhoria:

:zap: Avaliação de Proposta: Adição de tratamento para para liberar opção de encaminhar proposta para quando ainda não houver distribuições para Coordenador de Admissibilidade

Já está disponível em **homologação** para que valide. Assim que der o "ok", já podemos fazer o deployment para ambiente de produção.
