### ISSUE TITLE
[Admissibilidade] Publicizar enquadramento

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#834]
No perfil de proponente não está aparecendo no menu lateral esquerdo o campo "Enquadramento" e a proposta já teve enquadramento do Coordenador-geral de Admissibilidade e Aprovação.

Tela do Coordenador-geral de Admissibilidade e Aprovação contendo todos os enquadramentos:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/a68592db-5128-4952-b3f1-daa09a1a1a7b)

Tela do Proponente:
![Admis. 1.jpg](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/63d7a145-6eeb-45e1-9140-ebaf6d4e5336)

http://salic.cultura.gov.br/admissibilidade/admissibilidade/exibirpropostacultural?idPreProjeto=279933&realizar_analise=sim

**Comment by AdmissibilidadeSAV** [comment]
@AdmissibilidadeSAV @vinnyfs89

**Comment by AdmissibilidadeSAV** [comment]
Ao realizar mais alguns testes descobri que quando o enquadramento final (Coordenador-geral de Admissibilidade e Aprovação) é o mesmo que o proponente preencheu ao enviar a proposta o sistema entende que não é necessário dar a opção de visualização do enquadramento, bem como desistência do prazo recursal e recurso, nesse caso, o sistema deveria liberar o botão de transformar a proposta em projeto.

**Comment by vinnyfs89** [comment]
![captura de tela de 2018-05-15 16-09-56](https://user-images.githubusercontent.com/3949238/40078284-801d08e0-585a-11e8-8b00-053995261afc.png)
Essas são as regras atuais para saber se o recurso foi liberado.

**Comment by romulomb** [comment]
# **REGRAS DE LIBERAR O BOTÃO TRANSFORMAR**

1. A sugestão de enquadramento deverá ser avaliado por todos os perfis envolvidos, ou seja, perfil de técnico de admissibilidade, coordenador de admissibilidade , componente da comissão e coordenador-geral;
2. Além da regra nº 1 e quando a solicitação de enquadramento de proponente é igual a solicitação de enquadramento final;
3. Além da regra nº 1 e quando o proponente desiste do prazo recursal;
4 Além da regra nº 1 e após avaliação de 1º recursos e a desistência do 2º recursos;
5.Além da regra nº 1 e após avaliação de 2º recursos.

**Comment by vinnyfs89** [comment]
Bom não consegui reproduzir o erro.Amanhã verificarei direto no banco de dados de homologação para checar se ao indeferir uma **Avaliação de Recurso do Proponente** não está dando a possibilidade do proponente entrar com recurso. 

Lembrando que só é possível executar essa operação de dar a possibilidade de entrar com recurso, na sugestão de enquadramento dada pelo coordenador geral de admissibilidade, 1 vez de acordo com as regras que o Rômulo especificou.

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89, as regras colocadas na issue #647 não estão valendo mais? O Rômulo mudou alguma coisa? Lá está escrito que “Em caso de indeferimento, o proponente será oportunizado entrando com um novo recurso".

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Essa regra está valendo sim, foi o que comentei anteriormente. Caso seja a primeira vez, ele terá a oportunidade de fazer um novo recurso. Caso seja indeferido novamente será enquadrado no que o avaliador decidiou na avaliação.

**Comment by vinnyfs89** [comment]
Lembrando que foi identificado que o erro ocorreu porque foi clicado mais de uma vez no botão finalizar e não havia tratamento para quando a avaliação do recurso da proposta já estivesse realizado.

O ajuste já foi disponibilizado em ambiente de homologação para ser testado novamente. Após um um feedback de homologaão podemos concluir essa issue. 

Obrigado.

**Comment by AdmissibilidadeSAV** [comment]
**1** Testando aqui descobri que o Coordenador-geral ao avaliar o recurso tem que clicar em salvar primeiro para depois clicar em finalizar, caso contrário não irá aparecer para o proponente a opção de apresentar um novo recurso. Todas as outras vezes estava clicando apenas em finalizar e pelo que você e o Rômulo verificaram no banco de dados essa ação do botão finalizar só estava salvando um rascunho, acho que precisa rever isso então.

Outra coisa, quando o sistema abre para o proponente propor um novo recurso tem que aparecer a avaliação do primeiro recurso para o proponente saber porque o mesmo foi negado, mas acho que já está trabalhando nisso no card #835, onde o Rômulo sugeriu uma correção na tela.      

Olha como aparece na tela do proponente:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/d80dd354-5799-4201-a0af-0af9163b7685)        

**2** Quando o enquadramento final é o mesmo do proponente ainda não está aparecendo o botão de transformar em projeto.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/e6d25c4d-465a-423b-b14e-9ed33568b2b8)

**Comment by vinnyfs89** [comment]
- O **Item 1** já está sendo tratado na Issue #835. 
- Acabei de corrigir o **Item 2** e disponibilizei no ambiente de homologação. 

Pode verificar, por gentileza?

**Comment by vinnyfs89** [comment]
Podemos fechar essa Issue?

**Comment by AdmissibilidadeSAV** [comment]
Sim.
