### ISSUE TITLE
[Admissibilidade] Recurso de enquadramento

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#835]
Quando o Coordenador-Geral de Admissibilidade e Aprovação nega o recurso de enquadramento não aparece para o proponente que o recurso foi negado, bem como o motivo, a tela do proponente fica congelada com o recurso que foi encaminhado.

Tela do Proponente:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/ad4b8dd7-d383-41f5-bd2b-673d8f2e247f)

Tela do Coordenador-geral contendo a avaliação do recurso:
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/f1dc4e96-81e-431f-8797-625eb300869e)

**Comment by AdmissibilidadeSAV** [comment]
Tela do Coordenador-geral contendo a avaliação do recurso: 
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/bac9c2ce-7c5c-49cf-a81b-61cdbb162c96)

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV para esse proponente houve um segundo indeferimento?

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89 Não, nem apareceu para o proponente a avaliação do recurso muito menos deu a chance de apresentar um novo recurso.

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Thaís, acabei de analisar o número da proposta que você informou diretamente no banco de dados.

![captura de tela de 2018-05-16 11-51-46](https://user-images.githubusercontent.com/3949238/40124776-a9aa0046-58ff-11e8-9b7c-0b5e588cad8d.png)

![captura de tela de 2018-05-16 11-51-30](https://user-images.githubusercontent.com/3949238/40124777-a9d25320-58ff-11e8-8b60-e04a89cbce3e.png)

De acordo com as imagens acima você apenas salvou a avaliação do recurso, faltou enviar. O @romulomb também identificou a mesma situação no banco e dados.

Quando ela é enviada é que são disparados os gatilhos para executar as ações das sugestões de enquadramento.

**Comment by vinnyfs89** [comment]
![recurso_historico.gif](https://images.zenhubusercontent.com/5a4f8333a016c5b034bc22bc/b9f75290-ba3a-48e0-8f6e-fb4717114ceb)

Recurso criado e disponibilizado em ambiente de homologação.
Favor homologar.

**Comment by AdmissibilidadeSAV** [comment]
A sugestão de correção do @romulomb de criar o histórico de enquadramentos está ok, só ficou pendente a questão no perfil de Coordenador-geral de Admissibilidade e Aprovação na avaliação do recurso ter que salvar antes de clicar em Finalizar, que foi detalhado no card #863, para concluir e subir para produção.

**Comment by vinnyfs89** [comment]
Podemos fechar essa issue, então?

**Comment by AdmissibilidadeSAV** [comment]
Pode encerrar esse card.
