### ISSUE TITLE
Divergência entre valores de "Comprovação Validada"

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#838]
Para um mesmo item de custo, há diferença entre o valor da "Comprovação Validada" apresentado na Planilha Orçamentária comprovada (Figura 1) e o valor apresentado na tela de análise do item (Figura 2).

Obs.: Diferença verificada em todos os filtros: Aguardando análise, Avaliado, Impugnados e Todos.

Exemplo: Item de custo Curador.

![image](https://user-images.githubusercontent.com/37881003/40074935-6f788a0e-5851-11e8-9543-0ade7e448622.png)
 Figura 1. Valor "Comprovação Validada" - Planilha Orçamentária comprovada

![image](https://user-images.githubusercontent.com/37881003/40075098-ca444cca-5851-11e8-8b2e-b1d0b691fb36.png)
Figura 2. Valor "Comprovação Validada" - Análise do item

**Comment by wouerner** [comment]
#839 e #838 -> complementares, será aplicado a mesma solução nos dois casos.

**Comment by pauli10** [comment]
Com a #890, as issues #838 e #839 foram solucionadas. Portanto, homologadas.
