### ISSUE TITLE
Erro no cálculo do valor da Comprovação Validada - Filtro Impugnados

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#839]
Erro no cálculo do valor da "Comprovação Validada" quando aplicado o filtro Impugnados:

Comprovação validada > Valor comprovado. 

Obs.: Substituir o _label_  Comprovação Validada pelo _label_ Comprovação Impugnada.

Exemplo:

![image](https://user-images.githubusercontent.com/37881003/40075756-8114a322-5853-11e8-8459-bdb1de938d55.png)

Após clicar em analisar:

![image](https://user-images.githubusercontent.com/37881003/40075826-b5415e6a-5853-11e8-90bf-91b668525a36.png)

Comprovação validada > Valor comprovado : (R$ 24.332,12 > R$ 5.000,00)

Relacionada à Issue #838 !

**Comment by wouerner** [comment]
#839 e #838 -> complementares, será aplicado a mesma solução nos dois casos.

**Comment by wouerner** [comment]
Usados 18 pontos dessa issue @decko

**Comment by pauli10** [comment]
Com a #890, a #838 e #839 foram solucionadas. Portanto, homologadas.
