### ISSUE TITLE
Separação entre projetos "físicos" e "virtuais"

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#841]
Separação entre projetos físicos e virtuais com base na forma da realização da prestação da contas. 

Inserir filtro "físico"/"virtual" na tela  "Gerar Relatório Análise/Projeto":

![image](https://user-images.githubusercontent.com/37881003/40076485-59453a9e-5855-11e8-996d-f343f33cbf8b.png)

Tela  "Gerar Relatório Análise/Projeto":

![image](https://user-images.githubusercontent.com/37881003/40076518-729d5a12-5855-11e8-8e33-eab30a5103c8.png)

**Comment by wouerner** [comment]
@romulomb @Romulo_Menho , preciso que faça o seu detalhamento, pois o detalhamento acima não condiz com o que conversamos anteriormente.

**Comment by romulomb** [comment]
Essa issue não estava em impedimento ontem à noite. Ela entrou agora.

**Comment by wouerner** [comment]
Preciso de uma posição sobre essa issue? Até o momento não foi detalhada, como foi @DouglasMinC  que criou, você pode fechar ela ou detalhar qual seria o problema.

Falta quais perfis vão acessar, onde vai ficar esse filtro, acredito que isso deveria fica na tela de analise do técnico não em relatórios.

**Comment by romulomb** [comment]
**PERFIL DO COORDENADOR / COORDENADOR - GERAL DE PRESTAÇÃO DE CONTAS**

Inserir um novo link no menu **Prestação de Contas** com o nome **Análise Financeira Virtual**, conforme a tela abaixo.
![AnaliseFinanceira.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2aa1253f-5870-480b-96cb-c3bb615bec73)

**O painel é o mesmo utilizado quando clico no menu superior Prestação de Contas --> Analisar  Prestação de Contas.**

**QUERY para carregar o painel de Análise Financeira Virtual**

SELECT IdPRONAC,Pronac,NomeProjeto,cdArea,dsArea,cdSegmento,dsSegmento,cdSituacao,Situacao,cdOrgao,dsMecanismo,dsSituacaoEncPrestContas,idAgenteDestino,nmTecnico,dtInicioEncaminhamento,
       dtFimEncaminhamento,qtDiasEmAnalise,idSituacaoEncPrestContas
FROM sac.dbo.vwAnaliseFinanceiraVirtual
WHERE cdOrgao = [ORGAO DO USUARIO LOGADO]

**Comment by Pedro-Philipe** [comment]
@romulomb @DouglasMinC Só para confirmar, os perfis são os de SEFIC/ARQ - Coordenador - Geral de Prestação de contas e mais algum outro? Não entendi muito bem, obrigado.

**Comment by romulomb** [comment]
Os perfis estão no comentário acima.

SEFIC/ARQ para SEFIC

SAV/CEP  para SAV

**Comment by Pedro-Philipe** [comment]
@romulomb Estou 2 dúvidas:

1 - O fluxo da funcionalidade é exatamente o mesmo Prestação de Contas --> Analisar Prestação de Contas, ou possui alguma peculiaridade?

2 - A view (vwAnaliseFinanceiraVirtual) não me retorna nenhum projeto para que eu possa testar fielmente.

Obs: transcrevi a view para o código, alterações eu preciso alterar diretamente no salic.
Obrigado!

**Comment by romulomb** [comment]
1 - O fluxo da funcionalidade é exatamente o mesmo Prestação de Contas --> Analisar Prestação de Contas, ou possui alguma peculiaridade?

**Sim, conforme definido acima**

2 - A view (vwAnaliseFinanceiraVirtual) não me retorna nenhum projeto para que eu possa testar fielmente.

SELECT IdPRONAC,Pronac,NomeProjeto,cdArea,dsArea,cdSegmento,dsSegmento,cdSituacao,Situacao,cdOrgao,dsMecanismo,dsSituacaoEncPrestContas,idAgenteDestino,nmTecnico,dtInicioEncaminhamento, 
dtFimEncaminhamento,qtDiasEmAnalise,idSituacaoEncPrestContas 
FROM sac.dbo.vwAnaliseFinanceiraVirtual 
WHERE cdOrgao = 303


**RETORNA 172 REGISTROS**

**Comment by Pedro-Philipe** [comment]
@romulomb Obrigado, sobre a segunda pergunta eu estava usando o código do Grupo e não do Orgão. Erro meu.

**Comment by romulomb** [comment]
**COPIAR TODAS AS FUNCIONALIDADES DO PAINEL ANALISAR PRESTAÇÃO DE CONTAS**

**Comment by Pedro-Philipe** [comment]
@romulomb a coluna de quantidade de dias em análise se encontra sempre zerada, os valores de dtInicioEncaminhamento e dtFimEncaminhamento são sempre iguais:

```DATEDIFF(DAY,J.dtInicioEncaminhamento,J.dtFimEncaminhamento) as qtDiasEmAnalise```

E também possui um Projeto com número de dias negativo.

**Comment by romulomb** [comment]
@Pedro-Philipe  A view serve para todo a contexto.

No painel **Aguardando análise** os campos citados não serão utilizados, mesmo porque ainda não houve nenhum encaminhamento.

No painel **Em análise** esses campos já estarão preenchidos porque os projetos já foram enviados aos técnicos.

Portanto não há nenhum problema se a query está retornando null quando não há distriuição.

**Comment by Pedro-Philipe** [comment]
@romulomb Para fazer a filtragem para cada aba filtrei pelo ```J.idSituacaoEncPrestContas``` em cada situação. A divergencia dos dados ocorreu mesmo filtrando para cada painel específico.

**Comment by romulomb** [comment]
**AJUSTES**

Remover os seguintes campos abaixo do painel.

Área

Segmento

Mecanismo

Consulta AECI.

Incluir em todos painel o campos **Prioridades**

Ao clicar no link Prioridades mostrar a informações das Prioridades.

**Comment by romulomb** [comment]
@Pedro-Philipe  

**PERGUNTA**

Pedro Philipe Oliveira, [09.07.18 19:38]
Pauliane Sobre a issue 841, saberia me informar como funciona a consultoria para a conjur? Nos projetos em analisar prestação de contas não me lista nenhum destinatário.

**RESPOSTA**

Pode **ELIMINAR** essa funcionalidade ´porque não usaremos mais.

**Comment by pauli10** [comment]
@Pedroeoq , no filtro "Em análise" teremos que acrescentar o botão "encaminhar para análise". Ele já existe no filtro aguardando análise e analisados.

**Comment by Pedro-Philipe** [comment]
@pauli10 Funcionalidade já se encontra em homologação. Como essa funcionalidade foi migrada de um código muito legado, pode haver alguns bugs de fluxo, recomendo visualizar se os projetos estão tramitando da forma que deveria ser em outros lugares do sistema. **O botão de visualização do projeto será feito, apenas estou esperando o Cleber terminar um componente que fará isso mais facilmente.** 

##### Obrigado!

**Comment by pauli10** [comment]
@Pedro-Philipe, Quando eu encaminho para um técnico não fica registrado no histórico.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/2efbeb4f-7490-4d32-b4b3-5fc98671a85b)

A situação E68 não pode entrar no filtro "Em análise".
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/f2a35e62-f53c-4467-8e77-b04ab91d8748)

A situação E27 não pode entrar no filtro "Analisados".
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/84902a4b-bb6b-4da7-b690-b4353ab6cf8e)

O botão voltar da tela de Laudo final remete à tela dos dados iniciais do projeto.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/2a725444-6fba-4615-805f-e9f0ba9dea43)

O projeto encaminhado não aparece no painel do técnico.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/e926fba0-ae66-42be-b357-ce24ca0695c6)

**Comment by Pedro-Philipe** [comment]
Alteração de estimativa devido alterações nas consultas e análise de impacto no resto do fluxo

**Comment by Pedro-Philipe** [comment]
@pauli10 Poderia homologar novamente? Sobre o botão de voltar, ele segue o fluxo de outra tela que eu não conheço, eu coloquei o link abrindo em outra janela, serve para você?

**Comment by pauli10** [comment]
Gostaria de testar se o fluxo segue corretamente até o filtro "Analisados", mas ocorre erro na tela de análise.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/875e17d6-f958-409c-af7a-9e89853631ae)

A data do envio está diferente na análise financeira virtual e na tela do histórico.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/861d1657-6855-433f-9e7b-83b7aeb78c4a)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/cdd8571a-4651-4468-b296-e1e20cabfdfe)

Mudar a nomenclatura "Chefe de Divisão" para "Coordenador".
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/b8320fc8-4601-42a8-858e-7cfcd4257c6a)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/fc58dda8-b1df-4d2b-bb3b-9c64cf4c0191)

Quando devolvo, como técnica, para o chefe de divisão, o Pronac some dos dois perfis. Devolvi o Pronac 00 1051 do Rômulo perfil de técnico para o Rômulo perfil de coordenador. Não acho mais o projeto.

**Comment by Pedro-Philipe** [comment]
@pauli10 Devido a obscuridade do resto do fluxo, vou tratar a demanda como impedida até esclarecermos para não haver retrabalho.

@romulomb Como será o resto do fluxo dos projetos relacionados a essa issue?

**Comment by Pedro-Philipe** [comment]
@romulomb : Alterar Orgaodestino de 132 para 125.

Confirma essa informação de acordo com oq vc me falou ontem a noite?

**Comment by Pedro-Philipe** [comment]
Estava indo para 124, alterei para 125.

Já está em homolog @romulomb

**Comment by pauli10** [comment]
@romulomb , precisa atualizar as situações conforme combinado no fluxo para elas aparecerem nos filtros corretos. 

@Pedro-Philipe 
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42
e92/5abc1919-4332-4271-badc-8a38d68e7634)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/2315e569-07c8-4573-8439-302e8dbb14a2)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/9b85c9d9-65e6-4d76-9b97-5ae572cc1f23)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/e119c868-a4b1-440a-a005-30b260f5c0ad)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/4ec37167-1032-4da9-9775-68cfc2c8928c)

**Comment by romulomb** [comment]
Segue para ajuste.

**Comment by Pedro-Philipe** [comment]
A funcionalidade foi testada com o perfil errado **SEFIC/ARQ - Protocolo**. É bem capaz da sessão do seu perfil ter caído durante os teste, e a aplicação não conseguiu mais fazer nenhuma ação. O fluxo correto é a plataforma nem mesmo deixar acessar com esse perfil.

_**Os perfis corretos para acessarem essa tela, estão no corpo da issue.**_


![canva-photo-editor.png](https://images.zenhubusercontent.com/5a58ea374b5806bc2bc288bf/88109d76-8d37-451e-b475-b7eead041971)

**Comment by Pedro-Philipe** [comment]
@pauli10 Sobre o botão de voltar relatado na pagina do laudo, ele é relacionado a outro fluxo, por isso ele volta para outra página. Como medida paleativa, eu tinha colocado para abrir em outra aba, mas já que há uma necessidade importante, vou trabalhar esse cima desse botão, porém terei de abrir outra issue já que é de outro fluxo/funcionalidade.

**Comment by pauli10** [comment]
@Pedro-Philipe 
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/3daa2724-7156-4f8d-b8a2-a2c3025743b4)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/e7485b07-45eb-4e0f-8666-8a962559f6f0)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/7c36af42-3a4f-44f7-bd45-370cf4ef80fe)

**Comment by romulomb** [comment]
Ajustes a serem feitos estão registrado acima.

**Comment by Pedro-Philipe** [comment]
@pauli10  Sobre os pontos relatados na issue 841, os problemas relatados sobre, data e paginação possuem alguns pesares
Em relação as datas: Segundo o @romulomb  as datas nessa visualização são datas inseridas de teste, geralmente aparece a data atual, é o comportamento que acontece quando não possui valor. Isso não irá acontecer em um ambiente normal.

Em relação a paginação: A paginação dinâmica carregando os dados toda vez que é alterada a listagem possui o problema de divisão na ultima página em todas as telas que usem esse tipo de recurso. O que ele faz é preencher os dados da penultima página na página final. Recentemente já analisamos algumas formas de solucionar esse problema, vamos abrir outra issue como débito técnico, pois se trata de um problema da tecnologia em que o salic foi feita, juntamente com o tipo de banco.

**Comment by Pedro-Philipe** [comment]
@romulomb @pauli10 Todas as funcionalidades do escopo inicial dessa issue foram atendidas? Caso esteja tudo ok, me avisem para eu fechar a issue. Obrigado

**Comment by Pedro-Philipe** [comment]
@pauli10 situações das telas:
Aguardando análise: E68
Em análise: E27, E17, E20, E30
Analisados: E20 e E30

**Comment by romulomb** [comment]
HOMOLOGADO E FECHADO

**NOVAS FUNCIONALIDADES NA ISSUE 1065**
