### ISSUE TITLE
[Admissibilidade] - TEXTO DE E-MAIL ENVIADO AO PROPONENTE

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#842]
**TROCAR O ASSUNTO DO E-MAIL QUE É ENVIADO AO PROPONENTE APÓS A SUGESTÃO FINAL DE ENQUADRAMENTO.**

Assunto : Proposta XXXX - Sugestão de Enquadramento

**TROCAR O TEXTO DO E-MAIL QUE É ENVIADO AO PROPONENTE APÓS A SUGESTÃO FINAL DE ENQUADRAMENTO.**

Senhor(a) Proponente,

Conforme dispõe o artigo 24 da Instrução Normativa nº 05/2017 do MinC, informamos que sua proposta será enquadrada nos termos da Lei nº 8.313/1991.

Caso discorde do enquadramento poderá solicitar sua revisão acessando a proposta no Salic e clicando no item “enquadramento” localizado no menu lateral esquerdo.

Mensagem automática gerada pelo Sistema Salic. Favor NÃO RESPONDER.

Atenciosamente,

Ministério da Cultura

---------------------------------------------------------------------------------------------------------

**REGRA**
Somente enviar e-mail quando a sugestão  de enquadramento for diferente da solicitada pelo proponente.

**Comment by vinnyfs89** [comment]
@romulomb Rômulo você acha interessante incluir o número da proposta do proponente no e-mail para facilitar o acesso?

**Comment by vinnyfs89** [comment]
Ah sim, já tem no título...

**Comment by vinnyfs89** [comment]
@romulomb feito. Publicado no ambiente de homologação. Pode verificar, por favor?

**Comment by romulomb** [comment]
* [ ] - Retirar os caracteres de do assunto e do corpo/texto do e-mail.

* [ ] - Formatar o corpo/texto do e-mail

![Email.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8deb23f2-5d5c-4b84-a87f-44bef36c0dbb)

**Comment by vinnyfs89** [comment]
@romulomb Beleza

**Comment by vinnyfs89** [comment]
Correção realizada e disponível em ambiente de homologação. Favor verificar.

**Comment by romulomb** [comment]
Ainda continua com caracteres de controle.

![Email.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2ac89bb5-3820-4c00-95e5-897f6c4ddcc1)

**Comment by vinnyfs89** [comment]
@romulomb Acabei de ajustar e subir novamente para ambiente de homologação.
