### ISSUE TITLE
Novo layout da lista de Pagamentos

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#844]
**Historia:**
* Eu como proponente gostaria de visualizar a lista de pagamentos conforme print screen:
   - Com as informações da tela anterior.

![salic_tela](https://user-images.githubusercontent.com/287287/40136304-e5e95066-591d-11e8-9005-c5fb48aa8203.png)

Checklist:
- [x] Criar botão na tela anterior.
- [x] Criar controller com nome "pagamento" no modulo de prestacao-contas.
- [x] Criar dentro da pasta views/scripts para pagamento.
- [x] Criar arquivo [nome].vue.js na pasta /public/scripts/prestacao-contas/

**Comment by wouerner** [comment]
Repriorizada de 30 para 50, os estagiarios tiveram um imprevisto.

**Comment by guiamado** [comment]
- [ ] Arrumar Conta no Valor A Comprovar (Valor Aprovado - Valor Comprovado)
- [ ] Colocar um card com valor total a Comprovar
- [ ] Colocar um botão ao invés de utilizar o link no nome

**Comment by guiamado** [comment]
Novo layout de pagamento da Comprovação financeira, disponível em Homologação. Os itens podem estar diferentes pois o modelo antigo está trazendo algumas informações erradas, e o cálculo do Valor a Comprovar subirá em breve para Homologação. Favor Testar.

**Comment by romulomb** [comment]
Algumas observações de layout na figura anexada.

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/877ccc41-9b5b-43be-8d29-4af5c6958397)

**Comment by pauli10** [comment]
Algumas observações de layout na figura anexada.

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/877ccc41-9b5b-43be-8d29-4af5c6958397)

**Comment by guiamado** [comment]
Uma nova atualização foi feita no layout, corrigindo algumas demandas que foram solicitadas, e estão disponíveis em Homologação. Referente à issue #844

**Comment by romulomb** [comment]
NA SUBIDA DO NOVO LAYOUT DE COMPROVAÇÃO MATARAM A TELA DE COMPROVAÇÃO CORRETA.

**OS DADOS DE COMPROVAÇÃO DE PAGAMENTO E DE COMPROVAÇÃO DE DESPESA DEVEM ESTAR SEPARADOS.**

**CONFORME A TELA  QUE  ESTAVA ANTES DESSA ALTERAÇÃO**

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6fc3adac-0f01-424f-88c7-9f2653667ade)

**Comment by romulomb** [comment]
**REABERTA PORQUE NÃO FOI ATENDIDA**.

**Comment by pauli10** [comment]
Foi orientado ao @RuanHerculano abrir uma nova issue. Sugiro que esta demanda permaneça na issue 844, uma vez que diz respeito ao momento de prestar contas e comprovação financeira.

**Comment by pauli10** [comment]
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/73f372f6-4a07-45fe-a165-165a150ecd63)

**Comment by romulomb** [comment]
Segue para ajuste.

**Comment by wouerner** [comment]
Os erros que relatou @romulomb, vou tratar desses erroe na issue #1080, por isso vou fechar essa issue.
