### ISSUE TITLE
[Admissibilidade] Enquadramento de proposta

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#851]
Ao clicar numa proposta para enquadrar (em qualquer perfil avaliador), no campo justificativa de enquadramento aparece que o máximo de caracteres é 8000, porém, quando salvei um texto de 1098 caracteres, salvou apenas 198 caracteres e cortou o restante do texto inserido. Segue abaixo os prints das telas:

![Enquadramento - texto completo.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/7de9fd86-006b-43ad-a10d-70b9d88d0cf6)

![texto salvo no enquadramento.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/4430e058-dda2-44ad-91b9-89d015cd3f98)

![Texto salvo no historico.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/e28c3e3b-98db-4409-b5aa-573fb9cd9bd5)

** É necessário que aumente a quantidade de caracteres de 198 para pelo menos 1000.

http://salic.cultura.gov.br/admissibilidade/enquadramento-proposta/sugerir-enquadramento?id_preprojeto=278643

**Comment by vinnyfs89** [comment]
Thaís, item corrigido e disponibilizado em ambiente de homologação. Pode verificar por gentileza?

**Comment by vinnyfs89** [comment]
Thaís o item abaixo foi realizado para que esteja de acordo com o que solicitou:

- :zap: Avaliação da proposta: Ajuste de layout de tabela de histórico de 
sugestões de enquadramento para que esteja compatível com a leitura 
da motivação do enquadramento.

O ajuste foi feito e já está disponível no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
Excelente!!! Homologado.

**Comment by vinnyfs89** [comment]
Item publicado no ambiente de Produção. Versão Salic v4.1.6.
