### ISSUE TITLE
[HOTFIX] - READEQUAÇÃO

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#855]
O sistema está mandado para publicação remanejamento orçamentário.

Nesse caso não é para publicar porque não teve alteração de valor.

Tem que FINALIZAR a readequação e trocar a planilha

![Remanejamento.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/21f013ba-72ac-4285-a3f3-16192eff8dbe)

**Comment by fernao** [comment]
@romulomb : Possui algum pronac para verificação? Ocorre com todos os remanejamentos ou somente com o exemplo em questão?

**Comment by fernao** [comment]
Identificado que nos casos de soma zero, o resultado da spTipoDeReadequacaoOrcamentaria retorna vazio. O resultado é necessário para a correta tomada de decisão dentro do método de finalização, que sendo assim, segue para publicação de portaria, gerando o bug.

A situação foi passada para @romulomb para verificação da citada stored procedure.

**Comment by romulomb** [comment]
Após testes não foi encontrado nenhum problema na stored procedure spTipoDeReadequacaoOrcamentaria.

**PROBEMA IDENTIFICADO**

Quando a readequação orçamentária é um remanejamento o sistema não está finalizando a readequação e trocando a planilha. A aplicação se comporta como se foi uma readequação de complementação ou de redução.

Nesse caso a aplicação deverá executar as seguintes operação ao clicar no botão FINALIZAR:
1. Na tabela tbReadequação alterar os atributos: 
    a. siEncaminhamento para 15;
    b. stEstado para 1.
2. Após atualizar os atributos na tabela tbReadequacao executar a store procedure spAtivarPlanilhaOrcamentaria para efetuar a troca de planilhas.

**Comment by romulomb** [comment]
SP verificada e adicionadas rotinas para aumentar o grau de precisão da sp
