### ISSUE TITLE
[Admissibilidade] Texto de e-mail de Arquivamento

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#861]
O proponente quando a proposta é arquivada está recebendo e-mail com caracteres no corpo/texto que  também está sem formatação, conforme pode verificar abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/2860486b-bc0b-4560-bff2-5672e4f90704)

**Comment by guiamado** [comment]
Olá, qual é o perfil que arquiva a proposta?

**Comment by AdmissibilidadeSAV** [comment]
@guiamado Coordenador de Admissibilidade.

**Comment by guiamado** [comment]
Obrigado @AdmissibilidadeSAV

**Comment by romulomb** [comment]
Formatar o texto de e-mail e soltar linhas.

![email.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8e5e300a-1d8b-4a13-9081-f54b066a0d39)
