### ISSUE TITLE
[Admissibilidade] Recurso enquadramento Salvar/Finalizar

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#863]
No perfil do Coordenador-Geral de Admissibilidade e Aprovação o botão finalizar depende de clicar antes no botão salvar, só quando é feito isso é que o fluxo funciona direitinho. Necessito que corrija a ação do botão finalizar para que não necessite de salvar antes de enviar ou só habilite o botão finalizar após clicar no botão salvar.

Tela de análise do recurso após finalizar sem antes clicar em salvar:
![Coord Geral após ana recurso.JPG](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/804a72dd-c0bb-4d94-a81c-8aaa4e5f40be)

Tela do proponente sem possibilidade de enviar o 2° recurso:
![Propon após anal 1° recurso.JPG](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/23bd1d01-2605-4b7a-b6ca-1d1f188e0d56)

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV  item corrigido. Ambiente de homologação atualizado. Pode verificar por gentileza?

**Comment by AdmissibilidadeSAV** [comment]
Homologado.
