### ISSUE TITLE
Troca de valores aprovados entre itens de custos

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#864]
**Fase:** Comprovação inicial pelo proponente 

**Relato do proponente:** 

_"O valor total do item "professor" é de R$ 134.400,00, mas o sistema está apontando o valor de R$ 14.400,00, que é referente ao item "assistente administrativo". Por conta desse erro no sistema, eu não consigo lançar as notas de professor porque aparece uma mensagem de que o valor que quero lançar é maior que o valor orçado."_

**Screenshots enviados pelo proponente:**

![image](https://user-images.githubusercontent.com/37881003/40364255-3cf7d088-5da8-11e8-9840-b68095d3000a.png)

![image](https://user-images.githubusercontent.com/37881003/40364269-42461b76-5da8-11e8-8239-e04f7ba7cf56.png)

**Checklist:**

- [ ] Comprovação de um valor acima do valor aprovado do item de custo.

- [ ] Quando a comprovação é referente a pagamento no exterior, a aplicação não lista nos itens comprovados, não permitindo a edição ou exclusão da comprovação.

- [ ] Ajustar a formatação da data de emissão.

**Comment by romulomb** [comment]
Segue em telas o relato do proponente feito hoje dia 30/05/2018 as 11h.
![Novo Salic1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/6c37d250-0358-4c74-a85a-36f2194db5d1)

![Novo Salic2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/b6f4a7ac-93a1-46c9-9596-b1be3317cba9)

![Novo Salic3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d3c2250a-2023-49a7-bef5-edb8b4e58836)

**Comment by wouerner** [comment]
@romulomb Esses prints contam a versão antiga do sistema, favor conferir o radape. esta 4.1.8

**Comment by romulomb** [comment]
**PROBLEMA IDENTIFICADO**

PERFIL DO PROPONENTE.

REALIZAR COMPROVAÇÃO FINANCEIRA.

1. Quando a comprovação é referente a pagamento no exterior, a aplicação não lista nos itens comprovados, não permitindo a edição ou exclusão da comprovação.

2. Ajustar a formatação da data de emissão.

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/82b00b48-a6b5-4ba0-b7a9-50f810ef24e1)

**Comment by pauli10** [comment]
PROBLEMA IDENTIFICADO

PERFIL DO PROPONENTE.

REALIZAR COMPROVAÇÃO FINANCEIRA.

Quando uma comprovação é realizada no valor exato do item de custo, ou seja, zerando o valor a comprovar, o sistema não permite a prestação de conta e acusa que o valor comprovado está maior que o aprovado. Só deixa comprovar com pelo menos um centavo a menos.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/13f8e9e7-66cd-44ff-bae0-05c9e7d1a0c0)

**Comment by wouerner** [comment]
reestimada de 35 para 40, por causa desses erros tecnicos listados acima. @decko

**Comment by pauli10** [comment]
PROBLEMA QUE JÁ HAVIA SIDO SOLUCIONADO, VOLTOU

PERFIL DO PROPONENTE.

REALIZAR COMPROVAÇÃO FINANCEIRA.

O sistema permite a comprovação de um valor acima do valor aprovado do item de custo. Pronac exemplificativo que ainda está em fase de execução é o 17 1416.

**Comment by wouerner** [comment]
Estou bloqueado da VPN, por isso até a normalização dessas questões com infraestrutura do MinC, fica essa demanda parada.

**Comment by wouerner** [comment]
solução em homologação.

**Comment by wouerner** [comment]
solução em homologação #2.

**Comment by wouerner** [comment]
Finalizado.
