### ISSUE TITLE
Valores aprovados e comprovados iguais para todos os itens de custo

### ISSUE THREAD

**Issue by DouglasMinC** [culturagovbr/salic-minc#865]
Na diligência tipo "Todos os itens orçamentários", todos os itens de custo aparecem para o proponente, na tela Comprovar Pagamento, possuindo valores aprovados e totais comprovados iguais:

Exemplo:

![image](https://user-images.githubusercontent.com/37881003/40367561-23d198d4-5db0-11e8-83fe-cb8d36ae5f55.png)

Repetição de valores: 

![image](https://user-images.githubusercontent.com/37881003/40367409-b2873634-5daf-11e8-8146-7378a7287c8c.png)

![image](https://user-images.githubusercontent.com/37881003/40367441-cfe9561c-5daf-11e8-86e8-a4a5eb46751b.png)

![image](https://user-images.githubusercontent.com/37881003/40367470-e44998c4-5daf-11e8-92db-a3fe87b912fa.png)

**Comment by wouerner** [comment]
@romulomb  homologar por favor.

**Comment by romulomb** [comment]
Segue a minha contribuição.

![presT_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/29bd438c-bb2a-4413-8737-d4d06297cb67)

![Prest_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a92785f7-d1b3-4cc1-b84d-f45046a2dbac)

![prest_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/dbd84de9-b6b6-4b74-b9b8-7c0e7970db58)

![prest_4.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/1fea97b4-8106-4168-be73-dacfeec060ce)

**Comment by romulomb** [comment]
BUG. 
![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/da488ac8-ef81-4a3e-950d-1c2e2cd34077)

**HOTFIXX - URGENTE** Proponente não consegue comprovar e alguns já estão inadimplente. 

**A ouvidoria está solicitando uma posição até o final da tarde.**

**Comment by wouerner** [comment]
@romulomb  @Romulo_Menho, posição : **está em analise**. apesar de ser um hotfix, não tenho capacidade de resolver isso até a tarde.

**Comment by wouerner** [comment]
@Romulo_Menho  @romulomb, todas as imagens que você comentou eu transportei para issue: #890, pois as imagens são da analise do técnico de prestação de contas.
