### ISSUE TITLE
[Readequação] Assinatura Digital

### ISSUE THREAD

**Issue by clebersantos** [culturagovbr/salic-minc#873]
**Assinatura digital**

A finalidade do card e implementar o fluxo de assinatura digital.

O fluxo abaixo descreve as fases desse processo.

[https://app.zenhub.com/files/104502087/0f2523df-f85c-49f7-a1dc-56a491815972/download](https://app.zenhub.com/files/104502087/0f2523df-f85c-49f7-a1dc-56a491815972/download)

A readequação parte de uma solicitação do proponente pelo seu **ESCRTIÓRIO VIRTUAL DO PROPONENTE**  que deverá ser avaliada pelo Coordenador de Acompanhamento e decidirá se defere, indefere ou devolve ao proponente.

No caso do deferimento a solicitação segue para análise e emissão de parecer técnico.
Para contemplar fora criados dois atos adminitrativo: 653, 654 e 655.

O **653 - Parecer Técnico de Readequação de Projeto - Vinculadas** - para projetos que serão publicados avaliados pelas unidades vinculadas, com cinco assinaturas que deverão chegar até o Secretário.

O **654 - Parecer Técnico de Ajuste de Projeto** - para projetos que não serão publicados , com três assinaturas que deverão chegar até o Coordenador-Geral de Acompanhamento.

O **655 - Parecer Técnico de Readequação de Projeto - MinC** - para projetos que serão publicados avaliados pelos técnicos da SEFIC/SAV, com cinco assinaturas que deverão chegar até o Secretário.

Além disso deverão ser realizados ajustes para readequações que serão publicadas no DOU.

**Formato do documento gerado para assinatura**

[https://app.zenhub.com/files/104502087/84da12fa-5595-40c9-90a0-50da9ee84fe6/download](https://app.zenhub.com/files/104502087/84da12fa-5595-40c9-90a0-50da9ee84fe6/download)

 **As rotinas de análise já estão implementadas restando acoplar o módulo de assinatura digital.**

-----------------------------------------------------------------------------------------------------------------

**Comment by vinnyfs89** [comment]
@romulomb quais ações customizadas que as duas( 653 - Parecer Técnico de Readequação de Projeto e 654 - Parecer Técnico de Ajuste de Projeto) assinaturas devem possuir? Exemplo:

Finalizar
Devolver
A tela de lista de projetos para assinatura deverá seguir os mesmo moldes da tela de Assinatura para Enquadramento?

**Comment by vinnyfs89** [comment]
## Dados Técnicos

Rômulo( @romulomb ) , pode verificar por favor se os scripts abaixo para criação dos dois tipos de atos administrativos no ambiente de desenvolvimento estão corretos? Eu exportei do banco de dados de homologação.

```
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (45, 654, 287, 272, 121, 1, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (46, 654, 267, 272, 122, 2, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (47, 654, 268, 272, 123, 3, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (48, 653, 287, 92, 94, 1, 1, 92);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (49, 653, 265, 92, 93, 2, 1, 92);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (50, 653, 289, 92, 154, 3, 1, 92);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (51, 653, 285, 341, 148, 1, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idAtoAdministrativo, idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (52, 653, 262, 251, 149, 2, 1, 251);
```

**Comment by romulomb** [comment]
@vinnyfs89 Vinni

**Comment by vinnyfs89** [comment]
Acabei de pegar os dados de homolog e executei no banco de desenvolvimento. Os dados atualizados são:

```
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (654, 287, 272, 121, 1, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (654, 267, 272, 122, 2, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (654, 268, 272, 123, 3, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (653, 287, 92, 94, 1, 1, 92);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (653, 265, 92, 93, 2, 1, 92);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (653, 289, 92, 154, 3, 1, 92);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (653, 285, 341, 148, 4, 1, 251);
INSERT INTO SAC.dbo.TbAtoAdministrativo (idTipoDoAto, idCargoDoAssinante, idOrgaoDoAssinante, idPerfilDoAssinante, idOrdemDaAssinatura, stEstado, idOrgaoSuperiorDoAssinante) VALUES (653, 262, 251, 149, 5, 1, 251);
```

**Comment by vinnyfs89** [comment]
@romulomb Seguindo o diagrama que você mandou no início da Issue não foi possível identificar o momento onde deve ser iniciado o fluxo de assinatura.

Além disso, é possível informar se Haverá alguma situação para identificar que o projeto Cultural pode ser encaminhado para assinatura na fase de readequação para os tipos dos atos administrativos 653 e 654?

**Comment by vinnyfs89** [comment]
O @fernao me mostrou uma listagem que talvez poderia ser onde você estaria imaginando. Seria essa abaixo?

```
Técnico de Acompanhamento > Acompanhamento > Avaliar Readequações

url : /readequacao/readequacoes/painel-readequacoes
```

Caso adicionemos outra opção de ação dentro da lista, existe alguma situação ou regra que podemos filtrar se o projeto já permite encaminhamento para assinatura ou não?

**Comment by vinnyfs89** [comment]
Outra dúvida que tenho é como diferenciar quando criar um Documento de assinatura e iniciar o fluxo de assinatura para os Tipos de Atos Admnistrativos **653** e **654**.

**Comment by romulomb** [comment]
@vinnyfs89    Acho que deveria ser na tela aonde o técnico gera o parecer técnico.

Lembrando que toda vez que o técnico alterar o parecer, um novo documento deverá ser gerado para ser Assinado. e o antigo apagado.

![Assinatura_2.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bbcbe38f-ba8c-4887-958d-8f631d19f44d)

**Comment by vinnyfs89** [comment]
@romulomb Ok. Pode descrever, por favor, o que eu preciso fazer para chegar nessa tela e como diferenciar a criação de documento à partir dos dois tipos de atos adminsitrativos mencionados?

**Comment by vinnyfs89** [comment]
@romulomb Ok. Pode descrever, por favor:
- O que eu preciso fazer para chegar nessa tela e como diferenciar a criação de documento à partir dos dois tipos de atos administrativos mencionados?
- Qual Documento à partir do tipo do Ato Administrativo que deve ser criado inicialmente?
- O Template para ambos não terá diferenciação de títulos? Caso possua, quais serão?

**Comment by vinnyfs89** [comment]
@romulomb Além dos itens que listei acima e notei que você adicionou o conteúdo abaixo na descrição da Issue. Pode detalhar os passos que preciso fazer para chegar no cenário ?

```
PERFIL DO TÉCNICO DE ACOMPANHAMENTO
Existem readequações que deverão ser publicadas no Diário Oficial do União - D.O.U. Essas deverão seguir o fluxo de assinatura até o Secretário, as demais até o Coordenador - Geral de Acompanhamento.

As readequações relacionadas abaixo deverão ser publicadas no D.O.U.

Tipo : 2 -	Planilha Orçamentária

Tipo : 3 - Alteração de Razão Social

Tipo : 10 - Alteração de Proponente

Tipo : 12 - Nome do Projeto
Tipo : 15	- Resumo do Projeto

Os tipo de readequação estão registrados na tabela tbTipoReadequacao.
```

Lembrando que é interessante que tenhamos o que é solicitado como comentário nas Issues, para garantir a rastreabilidade. :+1:

**Comment by romulomb** [comment]
Estou detalhando, prefiro no corpo de issue porque fica tudo no mesmo lugar e mais organizado.  Mas farei os comentários sempre que atualizar a issue.

**Comment by romulomb** [comment]
Definição no corpo da issue.

Qualquer dúvida estou à disposição

**Comment by vinnyfs89** [comment]
@romulomb Notei que você adicionou mais um tipo de ato administrativo. Você atualizou o banco de homologação com as ordens de assinatura para esse novo tipo de ato administrativo?

**Comment by vinnyfs89** [comment]
@vinnyfs89 @romulomb ao criar um Documento para Assinatura, que será o mesmo template para os 3 tipos de acordo com o que você especificou na Issue, qual o id do Ato de gestão que deve ser armazenado?

**Comment by romulomb** [comment]
O idParecer já esta na query que preparei para vc recuperar o que vai no documento

**Comment by vinnyfs89** [comment]
Ok, estava utilizando NULL como padrão, mas utilizarei o idParecer. Atualmente estou trabalhando na estruturação da assinatura para o Módulo de Readequação para que consiga comportar os 3 fluxos de assinatura utilizando o mesmo template de documento que esse módulo precisará conter.
Qualquer novidade vou mantendo contato.
Obrigado.

**Comment by romulomb** [comment]
@vinnyfs89      ao criar um Documento para Assinatura, que será o mesmo template para os 3 tipos de acordo com o que você especificou na Issue, qual o id do Ato de gestão que deve ser armazenado?

idiReadequacao

**Comment by romulomb** [comment]
@vinnyfs89      Atualmente estou trabalhando na estruturação da assinatura para o Módulo de Readequação para que consiga comportar os 3 fluxos de assinatura utilizando o mesmo template de documento que esse módulo precisará conter. Qualquer novidade vou mantendo contato. Obrigado.

Não é idParecer e sim **idReadequacao**

Tinha me equivocado anteriormente.

**Comment by vinnyfs89** [comment]
De acordo com as regras levantadas com a ajuda do @romulomb e com a adição de mais um fluxo de assinatura para o módulo de Readequação. Estamos investindo tempo e esforço na estruturação desse módulo para que consigamos criar, reutilizar e testar o que foi solicitado.

**Comment by romulomb** [comment]
@vinnyfs89      Fiz um ajuste na definição no corpo da issue mostrando COMO DISTINGUIR O ATO ADMINISTRATIVO

**Comment by vinnyfs89** [comment]
Beleza, @romulomb . Reuni todas as informações obtidas e transformei essa Issue em uma épica . Para facilitar o controle e entregas os itens solicitados nessa Issue foram divididos em novas Issues. Para todas, foram vinculadas a essa Issue principal (epic) e definidas pontos de estimativas.
