### ISSUE TITLE
[HOTFIX] Enquadramento

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#874]
### Hotfix
1. Ao transformar proposta em projeto a aplicação deve buscar automaticamente a última sugestão de enquadramento que o @romulomb nomeou de "Enquadramento Final" e devemos inserir um registro de enquadramento do PROJETO.
2. Feito isso a situação do Projeto deve ser alterada de 'B01' para 'B04'

### Melhoria
1. Eliminar a regra que restringe o encaminhamento de projeto para assinatura de 10 dias.

~~Quando um proposta é transformada em projeto ela aparece no menu Admissibilidade/Enquadramento e não está trazendo o texto da justificativa do enquadramento final da proposta realizado pelo Coordenador-geral de Admissibilidade e Aprovação, ou seja, o Coordenador de Admissibilidade terá que inserir uma justificativa de enquadramento qualquer, visto que não aparece o histórico de enquadramentos feito na fase de proposta.~~
----------

~~Se o enquadramento final é realizado pelo Coordenador-geral de Admissibilidade e Aprovação não faz sentido que apareça nessa tela de enquadramento no perfil do Coordenador de Admissibilidade, deverá aparecer direto no perfil do Coordenador-geral de Admissibilidade e Aprovação.~~

~~Sugestão:~~
~~1) O sistema tem que trazer o texto da justificativa do enquadramento final ao transformar a proposta em projeto.~~
~~2) Deverá inserir no perfil de Coordenador-geral de Admissibilidade e Aprovação no menu Admissibilidade, logo abaixo de Avaliação, o item de menu "Enquadramento" (o mesmo que tem no perfil do Coordenador de Admissibilidade) e ao transformar a proposta em projeto ele aparecerá em ambos os perfis, permitindo também ao Coordenador-geral edite ou acrescente no texto de enquadramento sem ter que devolver para o Coordenador fazer o que ele na verdade queria/poderia fazer.~~

~~Perfil Coordenador de Admissibilidade - Tela de Enquadramento sem texto da justificativa na fase de proposta~~
~~![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/5328074d-bf16-412e-9483-6a1fe1395703)~~

~~![Inserir o item Enquad.JPG](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/eb5ffe16-fec4-46f8-80b1-2b669ca23e20)~~

**Comment by AdmissibilidadeSAV** [comment]
@romulomb conforme solicitado ontem!

**Comment by romulomb** [comment]
@AdmissibilidadeSAV Obrigado, Thais. Vini é um Hotfix.

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89 conversando agora a tarde com o @romulomb e @boletocosta achamos melhor ao invés de inserir o item de menu Enquadramento no perfil do Coordenador-geral de Admissibilidade e Aprovação, apenas fazer com que a proposta quando transformada em projeto traga o enquadramento final e já entre no painel de "Encaminhar para assinatura" (menu Admissibilidade), e para isso acredito que ele precisa mudar a situação automaticamente para B04 ao invés de B01.

**Comment by clebersantos** [comment]
Como tem hotfix e melhoria no mesmo card, sugiro separar esse em dois cards.

**Comment by romulomb** [comment]
Não abriremos novas issues conforme ajustamos ontem. Precisamos atender a solicitação da Thais.

**Comment by vinnyfs89** [comment]
Tudo bem, portanto o que devemos atender nessa Issue seria:

1. Ao transformar proposta em projeto a aplicação deve buscar automaticamente a última sugestão de enquadramento que o @romulomb nomeou de "Enquadramento Final" e devemos inserir um registro de enquadramento do PROJETO. 
2. Feito isso a situação do Projeto deve ser alterada de 'B01' para 'B04'

A melhoria seria:
1. Eliminar a regra que restringe o encaminhamento de projeto para assinatura de 10 dias.

Estão de acordo?

**Comment by boletocosta** [comment]
De acordo!

**Comment by romulomb** [comment]
Isso. 

Ficaria melhor ainda se já gerasse o documento a ser assinado. Mas isso é melhoria.

Thais é André concordando. Pra tá ok.

**Comment by vinnyfs89** [comment]
Pessoal, item corrigido e disponível no ambiente de homologação. Por gentileza, verificar.

**Comment by romulomb** [comment]
Não consigo homologar.

Quando tento transformar dá acesso negado.

Acho que tem haver com o SEI.

**Comment by vinnyfs89** [comment]
@boletocosta Tudo indica que é como houveram mudanças no SEI de homologação, lá ainda não está liberado o acesso para as máquinas de homologação. O nome do serviço é: gerarProcedimento

**Comment by vinnyfs89** [comment]
@vinnyfs89 Enviei uma mensagem para o Christian para que nos ajude, assim que tiver um retorno eu aviso.

**Comment by vinnyfs89** [comment]
Tentei entrar em contato com Heisson pelo telegram e informei os IPs do ambiente de homologação para que ele verifique o que está limitando o acesso do Salic ao SEI.

Qualquer novidade eu incluo aqui.

**Comment by boletocosta** [comment]
Pessoal, como não temos previsão de quando esse acesso será normalizado, sugiro subir e "testar" em produção mesmo devido à urgência. O que acham @AdmissibilidadeSAV e @romulomb?

**Comment by romulomb** [comment]
@boletocosta Concordo

**Comment by vinnyfs89** [comment]
@romulomb Combinado então, subo agora

**Comment by romulomb** [comment]
A situação correta não é **B02**

Na tabela Enquadramento no atributo  **Observacao** deverá conter a última sugestão de enquadramento.  Que aparecerá no documento gerado para assinatura.

**Comment by romulomb** [comment]
Outro ajuste.

![Enquadramento.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bd38514e-f837-403a-8574-904453385368)

**Comment by decko** [comment]
Srs. ficamos na dúvida aqui. A situação correta é a B02 ou B04? @boletocosta e @romulomb

**Comment by AdmissibilidadeSAV** [comment]
@decko Para o projeto ir para o menu Encaminhar para assinatura, a situação deve ser B02. Anteriormente havia falado em B04, pois pensei que ela fosse direto para o menu Assinatura no perfil de Coordenador-geral.

**Comment by vinnyfs89** [comment]
Pessoal, o ajuste para transformar em "B02" ao invés de "B04" e utilizar a última sugestão de enquadramento como enquadramento do projeto foram realizadas e já estão disponíveis em produção. 

Por gentileza, verificar.

**Comment by boletocosta** [comment]
Tudo certo. Pode encerrar a issue! =)
