### ISSUE TITLE
Analise dos comprovantes.

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#890]
![1fea97b4-8106-4168-be73-dacfeec060ce](https://user-images.githubusercontent.com/287287/40716088-300fe112-63de-11e8-8b5c-0bc3ab706ade.png)
![29bd438c-bb2a-4413-8737-d4d06297cb67](https://user-images.githubusercontent.com/287287/40716089-304114e4-63de-11e8-976c-728864e3f1e1.png)
![a92785f7-d1b3-4cc1-b84d-f45046a2dbac](https://user-images.githubusercontent.com/287287/40716090-3069e324-63de-11e8-8325-2b3e88a0c141.png)
![dbd84de9-b6b6-4b74-b9b8-7c0e7970db58](https://user-images.githubusercontent.com/287287/40716091-3093a6be-63de-11e8-8a2b-162c9c054be0.png)

**Comment by romulomb** [comment]
@pauli10  Pauli tem como homologar essa issue?

**Comment by pauli10** [comment]
@RuanHerculano , sugiro estas melhorias:
Trocar palavra e formatar valores
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/6f313e6d-9ab6-4437-ac02-bce8d498181d)

Corrigir ortografia
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/43461ea1-c81c-432f-9fce-337ad46685f5)

Botão voltar precisa remeter a tela aberta
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/b26690da-f952-4222-9a6b-58158ce5c83b)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/444f2958-7dca-433b-9627-4a6d0ee5d4b8)

Qq dúvida, estou à disposição!

**Comment by RuanHerculano** [comment]
ajustes feitos @pauli10

**Comment by pauli10** [comment]
Homologado.

**Comment by romulomb** [comment]
**REABERTA PORQUE NÃO FOI HOMOLOGADA AINDA**

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f9d9fe2f-52f3-48c6-aba1-8a4b7e37bd44)

**Comment by pauli10** [comment]
@RuanHerculano e @decko  , ainda continuam os mesmos erros.

O botão "Voltar" dentro do item precisa remeter a tela com os itens abertos e marcados os que já foram vistos.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/3f294398-f171-4911-bc1e-81f433e57d5b)

![image.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f9d9fe2f-52f3-48c6-aba1-8a4b7e37bd44)

**Comment by RuanHerculano** [comment]
@pauli10 @romulomb O botão de voltar com as abas expandidas vai ser colocado na nova tela de prestação de contas, tendo em vista que a tela atual deve desaparecer para dar espaço ao novo layout. Essa funcionalidade está contida na task #814. Adicionei  essa funcionalidade na descrição da issue #814.

**Comment by wouerner** [comment]
Homologado com area.
