### ISSUE TITLE
[HOTFIX] Excluir proposta

### ISSUE THREAD

**Issue by AdmissibilidadeSAV** [culturagovbr/salic-minc#891]
O proponente quando tenta Excluir uma proposta aparece a mensagem: "Você não tem permissão para acessar essa Proposta!", mesmo ele sendo o dirigente.

Proposta/Listar/clica em cima do n° da proposta/ no menu lateral esquerdo clica na opção "Excluir"

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/c785db0a-0b66-4368-a665-ecf5b37654ec)

OBS: Estou recebendo solicitações no salic todos os dias reportando esse erro.

**Comment by AdmissibilidadeSAV** [comment]
@romulomb conforme solicitado.

**Comment by romulomb** [comment]
Alguém verificar esse HOTFIX.

**Comment by clebersantos** [comment]
Vou verificar.

**Comment by romulomb** [comment]
@clebersantos Valeu, obrigado

**Comment by clebersantos** [comment]
@AdmissibilidadeSAV e @romulomb, correção disponível para homologação.

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos Homologado.

**Comment by romulomb** [comment]
Subir por gentileza para a produção.

Muito obrigado pelo pronto atendimento.

**Comment by clebersantos** [comment]
Correção disponível em produção.

**Comment by romulomb** [comment]
@clebersantos Valeu, muito obrigado
