### ISSUE TITLE
[Readequação] Assinatura Digital - Assinatura para o ato 654 - Parecer Técnico de Ajuste de Projeto

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#898]
Issue derivada da Epica #873

A readequação parte de uma solicitação do proponente pelo seu ESCRTIÓRIO VIRTUAL DO PROPONENTE que deverá ser avaliada pelo Coordenador de Acompanhamento e decidirá se defere, indefere ou devolve ao proponente.

Assinatura para o ato 654 - Parecer Técnico de Ajuste de Projeto - para projetos que não serão publicados , com três assinaturas que deverão chegar até o Coordenador-Geral de Acompanhamento.

**O FLUXO DE ASSINATURA para o ato administrativo 654 - Parecer Técnico de Ajuste de Projeto** é o seguinte.

**PERFIL TÉCNICO DE ACOMPANHAMENTO**

1. Técnico de Acompanhamento realiza a análise e emite o parecer técnico. 

2. Após Finalizar o parecer a aplicação deverá gerar automaticamente o documento a ser assinado. 

3. Após assinar o documento deverá ser encaminhado automaticamente para o Coordenador de Acompanhamento.

![Assinatura_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f353732e-6174-485e-9a7a-1a6c1d485ff1)

**PERFIL COORDENADOR DE ACOMPANHAMENTO**

1.  Após Finalizar o parecer a aplicação deverá trazer automaticamente o documento a ser assinado. 

2. Após assinar o documento deverá ser encaminhado automaticamente para o perfil de Coordenador Geral de Acompanhamento

![Assinatura_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6a18565-48ca-402c-9c4d-dfbaf6ce2f0c)

-----------

**QUERY QUE RETORNA A INFORMAÇÃO DO PARECER TÉCNICO**

```
SELECT a.idPronac, c.idParecer,c.DtParecer,
       CASE
         WHEN c.TipoParecer = '1' THEN 'Desfavorável'
         WHEN c.TipoParecer = '2' THEN 'Favorável'
	   END as PosicionamentoTecnico
		 ,CAST(c.ResumoParecer AS TEXT) as ParecerTecnico 
  FROM sac.dbo.tbReadequacao a
  INNER JOIN SAC.dbo.tbReadequacaoXParecer b on (a.idReadequacao = b.idReadequacao)
  INNER JOIN SAC.dbo.Parecer c on (b.idParecer = c.IdParecer)
 WHERE     a.idTipoReadequacao = [IDTIPOREADEQUACAO]
       AND a.stEstado = 0
	   AND a.stAtendimento = 'D'
	   AND a.siEncaminhamento = 4
       AND a.idPronac = [IDPRONAC]
```
-----------

**COMO DISTINGUIR O ATO ADMINISTRATIVO** 

Se o **órgão superior do  analista for diferente de 160 e de 251** o ato administrativo será **653** - Parecer Técnico de Readequação de Projeto - Vinculadas

Quando  o **órgão superior do  analista for igual a  160 ou 251** o ato administrativo será **655** - Parecer Técnico de Readequação de Projeto - MinC

-------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------

**ATO 654 - PARECER TÉCNICO DE AJUSTE DE PROJETO**

Esse ato administrativo é para três assinaturas. Nele assinarão** o técnico, o coordenador de acompanhamento e o coordenador-geral de Acompanhamento e Execução**.

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO TÉCNICO DE ACOMPNHAMENTO.**

Nesse perfil não existe a opção **DEVOLVER** porque é o técnico de acompanhamento gera o documento a ser assinado.

**FINALIZAR**

Ao finalizar o técnico estará transferindo o parecer assinado para o Coordenador de Acompanhamento, que poderá ser da SAV ou da SEFIC.

O que sinaliza para o sistema essa transferência de posse é o atributo **siEncaminhamento**** da tabela **tbReadequação.** que deverá ser preenchido com o valor **10**- Devolvido pelo Técnico para o Coordenador.

A mudança do siEncaminhamento nesse caso transfere a posse do projeto para o perfil do coordenador de acompanhamento.

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

O coordenador de acompanhamento de posse do parecer concorda ou não com o parecer.

Se concordar deverá assinar e finalizar o parecer. 

Essa ação deverá transferir a posse do parecer para o coordenador geral de acompanhamento e execução.

O que sinaliza para o sistema essa transferência de posse  é o atributo **siEncaminhamento**** da tabela **tbReadequação.** que deverá ser preenchido com o valor **18**- Solicitação encaminhada ao coordenador-geral.

A mudança do siEncaminhamento nesse caso transfere a posse do projeto para o perfil do coordenador-geral de acompanhamento execução.

**OBERVAÇÃO IMPORTANTE**

**Todas as atualizações de tabelas que hoje o sistema executa no perfil do coordenador de acompanhamento quando é clicado o botão FINALIZAR deverão ser transferida para o perfil de coordenador-geral de acompanhamento e execução.**

Se coordenador de acompanhamento  não concordar devolverá o parecer para o técnico para nova análise e emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado** com o valor **4**- Solicitação encaminhada ao  técnico

**Essa ação inutilizará o parecer assinado pelo o técnico.**

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR-GERAL DE ACOMPANHAMENTO EXECUÇÃO**

O coordenador-geral de acompanhamento e execução de posse do parecer concorda ou não com o parecer.

Se concordar deverá assinar e finalizar o parecer. 

Essa ação deverá  atualizar as tabelas que hoje o sistema executa no perfil do coordenador de acompanhamento quando é clicado o botão FINALIZAR

O que sinaliza para o sistema a finalização da readequação são os atributos **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **15**- Solicitação finalizada pelo MinC e o atributo **stEstado** que deverá ser atualizado com o valor igual a **1**.

Se coordenador-geral de acompanhamento e execução  não concordar devolverá o parecer para o técnico para nova análise e emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **4**- Solicitação encaminhada ao  técnico

**Essa ação inutilizará o parecer assinado pelo o técnico.**

**Comment by vinnyfs89** [comment]
@romulomb Preciso saber detalhadamente quais ações devem ser tomadas quando forem acionadas as opções abaixo para este Tipo de Ato Administrativo:
- Finalizar
- Devolver

**Comment by romulomb** [comment]
DEFINIÇÃO NO CORPO DA ISSUE.

**Comment by vinnyfs89** [comment]
Checklist de Itens Para acompanhamento de conclusã dessa Issue:

**PERFIL TÉCNICO DE ACOMPANHAMENTO**

- [x] 1. Técnico de Acompanhamento realiza a análise e emite o parecer técnico. 
- [x] 2. Após Finalizar o parecer a aplicação deverá gerar automaticamente o documento a ser assinado. 
- [x] 3. Após assinar o documento deverá ser encaminhado automaticamente para o Coordenador de Acompanhamento.

![Assinatura_3.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f353732e-6174-485e-9a7a-1a6c1d485ff1)

**PERFIL COORDENADOR DE ACOMPANHAMENTO**

- [x] 1.  Após Finalizar o parecer a aplicação deverá trazer automaticamente o documento a ser assinado. 

- [x] 2. Após assinar o documento deverá ser encaminhado automaticamente para o perfil de Coordenador Geral de Acompanhamento

![Assinatura_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6a18565-48ca-402c-9c4d-dfbaf6ce2f0c)

-----------

**QUERY QUE RETORNA A INFORMAÇÃO DO PARECER TÉCNICO**
-----------
**ATO 654 - PARECER TÉCNICO DE AJUSTE DE PROJETO**

Esse ato administrativo é para três assinaturas. Nele assinarão o técnico, o coordenador de acompanhamento e o coordenador-geral de Acompanhamento e Execução.
-----------
**PERFIL DO PARECERISTA.**

- [x] Nesse perfil não existe a opção **DEVOLVER** porque é o parecerista de gera o documento a ser assinado.

**FINALIZAR**

- [x] Ao finalizar o técnico estará transferindo o parecer assinado para o Coordenador de Acompanhamento, que poderá ser da SAV ou da SEFIC.

- [ ] O que sinaliza para o sistema essa transferência de posse é o atributo **siEncaminhamento**** da tabela **tbReadequação.** que deverá ser preenchido com o valor **10**- Devolvido pelo Técnico para o Coordenador.

A mudança do siEncaminhamento nesse caso transfere a posse do projeto para o perfil do coordenador de acompanhamento.
--------
**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

- [ ] O coordenador de acompanhamento de posse do parecer concorda ou não com o parecer.
Se concordar deverá assinar e finalizar o parecer. 
- [ ] Essa ação deverá transferir a posse do parecer para o coordenador geral de acompanhamento e execução.
- [ ] O que sinaliza para o sistema essa transferência de posse  é o atributo **siEncaminhamento**** da tabela **tbReadequação.** que deverá ser preenchido com o valor **18** - Solicitação encaminhada ao coordenador-geral.

A mudança do siEncaminhamento nesse caso transfere a posse do projeto para o perfil do coordenador-geral de acompanhamento execução.

**OBERVAÇÃO IMPORTANTE**

- [ ] **Todas as atualizações de tabelas que hoje o sistema executa no perfil do coordenador de acompanhamento quando é clicado o botão FINALIZAR deverão ser transferida para o perfil de coordenador-geral de acompanhamento e execução.**

- [ ] Se coordenador de acompanhamento  não concordar devolverá o parecer para o técnico para nova análise e emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

- [ ] O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado** com o valor **4**- Solicitação encaminhada ao  técnico

**Essa ação inutilizará o parecer assinado pelo o técnico.**
-------------------------------------------------------------------------------------------------------------------
**PERFIL DO COORDENADOR-GERAL DE ACOMPANHAMENTO EXECUÇÃO**

O coordenador-geral de acompanhamento e execução de posse do parecer concorda ou não com o parecer.

Se concordar deverá assinar e finalizar o parecer. 

- [ ] Essa ação deverá  atualizar as tabelas que hoje o sistema executa no perfil do coordenador de acompanhamento quando é clicado o botão FINALIZAR

- [ ] O que sinaliza para o sistema a finalização da readequação são os atributos **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **15**- Solicitação finalizada pelo MinC e o atributo **stEstado** que deverá ser atualizado com o valor igual a **1**.


- [ ] Se coordenador-geral de acompanhamento e execução  não concordar devolverá o parecer para o técnico para nova análise e emissão de parecer. 

- [ ]  Essa ação  devolverá a posse do parecer para o técnico.

- [ ] O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **4**- Solicitação encaminhada ao  técnico

**Essa ação inutilizará o parecer assinado pelo o técnico.**

**Comment by vinnyfs89** [comment]
@romulomb Sobre o comentário abaixo, que é o mesmo tratado no ato administrativo 653, posso manter o mesmo que você nos orientou na última reunião, certo? Caso realmente seja necessário remover essa ação, por gentileza informar todos os locais e perfis que essa ação é visível atualmente.

```
Todas as atualizações de tabelas que hoje o sistema executa no perfil do coordenador de acompanhamento quando é clicado o botão FINALIZAR deverão ser transferida para o perfil de coordenador-geral de acompanhamento e execução.
```

**Comment by vinnyfs89** [comment]
Rômulo, você especificou a situação que deve ser alterada como "Parecerista", mas ao analisar no banco de dados o correto não seria "Técnico de acompanhamento"?

**Comment by romulomb** [comment]
@vinnyfs89 
O código do **siEncaminhamento = 4** é o mesmo para Técnico e Parecrerista porque os dois executam o mesmo trabalho, mas em unidades diferentes.

**Comment by vinnyfs89** [comment]
Conforme conversamos, "Aonde ler Parecerista passa a ler Técnico de Acompanhamento"

**Comment by romulomb** [comment]
Corrigido no corpo da issue

**Comment by romulomb** [comment]
**PERGUNTA**

Rômulo, você especificou a situação que deve ser alterada como "Parecerista", mas ao analisar no banco de dados o correto não seria "Técnico de acompanhamento"?

**RESPOSTA**

Técnico de Acompanhamento

**Comment by vinnyfs89** [comment]
Rômulo, notei que vocÊ não solicitou alteração de 'stEstado' para a tabela tbReadequacao nessa Issue para nenhuma ação. Realmente não é necessário alterar?

**Comment by vinnyfs89** [comment]
Issue reestimada.

**Comment by romulomb** [comment]
**REFORÇANDO**


OBERVAÇÃO IMPORTANTE
Todas as atualizações de tabelas que hoje o sistema executa no **perfil do coordenador de acompanhamento** quando é clicado o botão **FINALIZAR** deverão ser transferida para o perfil de **coordenador-geral de acompanhamento e execução**.

**Comment by AdmissibilidadeSAV** [comment]
No perfil de Técnico de Acompanhamento fiz a análise do Pronac: 145475, quando cliquei em finalizar apareceu o documento gerado sem a opção de assinatura, daí fui no menu de Assinatura entrei em Gerenciar assinaturas e Gerenciar assinaturas-readequação e o documento não apareceu para ser assinado.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/947b0bb6-d0bf-4bd8-a43a-e395b5cf5bc3)

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/0b9f42ed-cbe1-43b2-a9a1-68b23a9cc8e5)

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89 Thaís Mendes:
01444542117. Pelo que andei testando outros projetos, só foi com esse que não apareceu na tela abaixo do documento a opção de assinar.

**Comment by AdmissibilidadeSAV** [comment]
Quando o técnico finaliza a análise o documento aparece com o título errado conforme pode verificar abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/60bd5c42-fae8-46d8-994a-f2c7eb433508)

Ao invés de ser Parecer de Homologação para Execução do Projeto deverá ser **Parecer Técnico de Ajuste de Projeto.**

**Comment by vinnyfs89** [comment]
Ajustado e disponível no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
Quando o técnico finaliza a análise de readequação o documento para assinatura está sem título.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/e7cd90d0-89e3-414b-b949-4e7b62aa9cea)

**Comment by AdmissibilidadeSAV** [comment]
As assinaturas estão ok, para finalizar essa issue acredito que só é necessário que após a última assinatura (Coordenador-geral de Acompanhamento e Execução) a providência tomada seja alterada para **"Readequação analisada pela área técnica".**

**Comment by vinnyfs89** [comment]
Ajuste realizado e disponível no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
No documento preciso que insira o Tipo de Solicitação, tenho notado que tem proponentes que solicitam várias tipos de readequações/ajustes no projeto e pra quem está assinando é importante saber o que foi solicitado. Até mesmo depois quando consulta o projeto nos documentos assinados não tem como saber qual é a solicitação que foi analisada naquele parecer.

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/74fdc02b-f51d-452c-8ba6-596b2f4b1ebb)

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Pode dar como homologada essa issue E abrir uma nova com essa solicitação, por gentileza?

**Comment by marcusvinicus** [comment]
Reforçando o pedido do Vini, quando for fazer solicitações de coisas que não estava na especificação inicial, o ideal que é que homologue a issue baseado no que se tinha solciitado e abra uma nova issue com a melhoria que vc gostaria que estivesse. Assim melhoramos a entrada em produção do que já ta desenvolvido. e já tem uma valor para o usuário.

**Comment by AdmissibilidadeSAV** [comment]
@vinnyfs89 conforme solicitado abri a issue #1114, porém, recomendo que não suba essa funcionalidade para produção sem a finalização da nova que abri.

**Comment by AdmissibilidadeSAV** [comment]
Homologada.
