### ISSUE TITLE
[Readequação] Assinatura Digital - Assinatura para o ato 655 - Parecer Técnico de Readequação de Projeto - MinC

### ISSUE THREAD

**Issue by vinnyfs89** [culturagovbr/salic-minc#899]
Issue derivada da Epica #873

A readequação parte de uma solicitação do proponente pelo seu ESCRTIÓRIO VIRTUAL DO PROPONENTE que deverá ser avaliada pelo Coordenador de Acompanhamento e decidirá se defere, indefere ou devolve ao proponente.

O **655 - Parecer Técnico de Readequação de Projeto - MinC** - para projetos que serão publicados avaliados pelos técnicos da SEFIC/SAV, com cinco assinaturas que deverão chegar até o Secretário.

**O FLUXO DE ASSINATURA para o ato administrativo 655 - Parecer Técnico de Readequação de Projeto - MinC** é o seguinte.

**PERFIL TÉCNICO DE ACOMPANHAMENTO**

1. Técnico de Acompanhamento realiza a análise e emite o parecer técnico. 

2. Após Finalizar o parecer a aplicação deverá gerar automaticamente o documento a ser assinado. 

3. Após assinar o documento deverá ser encaminhado automaticamente para o Coordenador de Acompanhamento.

![Assinatura_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/9a6c8b28-d2de-454c-8326-311f9f1ba5c8)

**PERFIL COORDENADOR DE ACOMPANHAMENTO**

1.  Após Finalizar o parecer a aplicação deverá trazer automaticamente o documento a ser assinado. 

2. Após assinar o documento deverá ser encaminhado automaticamente para o perfil de Coordenador Geral de Acompanhamento

![Assinatura_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6a18565-48ca-402c-9c4d-dfbaf6ce2f0c)

**DEMAIS PERFIS DE DIRETOR E SECRETÁRIO**

1. Adicionar no menu a opção de assinar parecer de readequação

-----------

**QUERY QUE RETORNA A INFORMAÇÃO DO PARECER TÉCNICO**

```
SELECT a.idPronac, c.idParecer,c.DtParecer,
       CASE
         WHEN c.TipoParecer = '1' THEN 'Desfavorável'
         WHEN c.TipoParecer = '2' THEN 'Favorável'
	   END as PosicionamentoTecnico
		 ,CAST(c.ResumoParecer AS TEXT) as ParecerTecnico 
  FROM sac.dbo.tbReadequacao a
  INNER JOIN SAC.dbo.tbReadequacaoXParecer b on (a.idReadequacao = b.idReadequacao)
  INNER JOIN SAC.dbo.Parecer c on (b.idParecer = c.IdParecer)
 WHERE     a.idTipoReadequacao = [IDTIPOREADEQUACAO]
       AND a.stEstado = 0
	   AND a.stAtendimento = 'D'
	   AND a.siEncaminhamento = 4
       AND a.idPronac = [IDPRONAC]
```
-----------

**COMO DISTINGUIR O ATO ADMINISTRATIVO** 

Se o **órgão superior do  analista for diferente de 160 e de 251** o ato administrativo será **653** - Parecer Técnico de Readequação de Projeto - Vinculadas

Quando  o **órgão superior do  analista for igual a  160 ou 251** o ato administrativo será **655** - Parecer Técnico de Readequação de Projeto - MinC

-------------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------------

**ATO 655 - PARECER TÉCNICO DE READEQUAÇÃO DE PROJETO - MINC**

Esse ato administrativo é para **cinco** assinaturas porque o caso requer publicação no Diário Oficial da União. 

Assinarão o ato administrativo o técnico, o coordenador de acompanhamento e o coordenador-geral de Acompanhamento e Execução, o diretor e o secretário.

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO TÉCNICO.**

Nesse perfil não existe a opção **DEVOLVER** porque  o técnico é o responsável pelo geração do documento a ser assinado.

**FINALIZAR**

Ao finalizar, o técnico estará transferindo o parecer assinado para o Coordenador de Acompanhamento, 

O que sinaliza para o sistema a transferência da posse é o atributo **siEncaminhamento** na tabela **tbReadequação.** que deverá ser preenchido com o valor **10**- Devolvido pelo Técnico para o Coordenador.

A mudança do siEncaminhamento nesse caso transfere a posse do projeto para o perfil do coordenador de acompanhamento.

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

O coordenador de acompanhamento de posse do parecer deverá concordar ou discordar do parecer técnico.

Se **CONCORDAR** deverá assinar e finalizar o parecer. 

A ação de **FINALIZAR**  transferirá a posse do parecer para o coordenador geral de acompanhamento e execução.

O que sinaliza para o sistema a transferência da posse  é o atributo **siEncaminhamento**** na tabela **tbReadequação.** que deverá ser preenchido com o valor **18**- Solicitação encaminhada ao coordenador-geral.

A mudança do siEncaminhamento  transfere a posse do projeto para o perfil do coordenador-geral de acompanhamento execução.

Se **DISCORDAR** do parecer, o coordenador de acompanhamento devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** na tabela **tbReadequação.** que deverá ser atualizado** com o valor **4**- Solicitação encaminhada ao  técnico

**S O M E N T E  ESSA AÇÃO INUTILIZARÁ O PARECER ASSINADO PELO TÉCNICO**

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR-GERAL DE ACOMPANHAMENTO EXECUÇÃO**

O coordenador-geral de acompanhamento e execução de posse do parecer deverá concordar ou discordar do parecer técnico.

Se **CONCORDAR** deverá assinar e finalizar o parecer. 

A ação de **FINALIZAR**  transferirá a posse do parecer para o diretor.

Nesse perfil, são duas as sinalizações para o sistema que indicará a transferência de posse do parecer:

1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser preenchido com o valor **19**- Solicitação encaminhada ao diretor.

2. o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **682** para a SAV e **341** para SEFIC

A mudança do siEncaminhamento e do orgao  transfere a posse do projeto para o perfil diretor.

Se **DISCORDAR** do parecer, o coordenador-geral de acompanhamento e execução  devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **21**-Solicitação devolvida ao coordenador pelo coordenador-geral

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO DIRETOR**

O diretor de posse do parecer  deverá concordar ou discordar do parecer técnico.

Se **CONCORDAR** deverá assinar e finalizar o parecer. 

A ação de **FINALIZAR**  transferirá a posse do parecer para o secretário.

Nesse perfil, são duas as sinalizações para o sistema que indicará a transferência de posse do parecer:

1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser preenchido com o valor **20**- Solicitação encaminhada ao secretario.

2. o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **160** para a SAV e **251** SEFIC

A mudança do siEncaminhamento e do orgao  transfere a posse do projeto para o perfil secretário.

Se **DISCORDAR** do parecer, o diretor  devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

Nesse perfil, são duas as sinalizações para o sistema que indicará a devolução do parecer para o técnico:

1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **22**- Solicitação devolvida ao coordenador pelo diretor.

2.  o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **171** para a SAV e **262**  para a SEFIC

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO SECRETÁRIO**

O secretário de posse do documento concordará ou não com o parecer.

Se **CONCORDAR** deverá assinar e finalizar o parecer. 

**A AÇÃO DE FINALIZAR DEVERÁ EXECUTAR TODAS AS  AÇÕES QUE A VERSÃO ATUAL EXECUTA NO PERFIL DE COORDENADOR DE ACOMPANHAMENTO QUANDO É ACIONADO O BOTÃO F I N A L I Z A R**

Se **DISCORDAR** do parecer, o secretário devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

 Essa ação  devolverá a posse do parecer para o técnico.

Nesse perfil, são duas as sinalizações para o sistema que indicará a devolução do parecer para o técnico:

1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **23**- Solicitação devolvida ao coordenador pelo secretário.

2.  o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **171** para a SAV e **262**  para a SEFIC

**Comment by vinnyfs89** [comment]
@romulomb Preciso saber detalhadamente quais ações devem ser tomadas quando forem acionadas as opções abaixo para este Tipo de Ato Administrativo:
- Finalizar
- Devolver

**Comment by romulomb** [comment]
DEFINIÇÃO NO CORPO DA ISSUE.

**Comment by vinnyfs89** [comment]
Criando Checklist:

**O FLUXO DE ASSINATURA para o ato administrativo 655 - Parecer Técnico de Readequação de Projeto - MinC** é o seguinte.

**PERFIL TÉCNICO DE ACOMPANHAMENTO**

- [ ] 1. Técnico de Acompanhamento realiza a análise e emite o parecer técnico. 

- [ ] 2. Após Finalizar o parecer a aplicação deverá gerar automaticamente o documento a ser assinado. 

- [ ] 3. Após assinar o documento deverá ser encaminhado automaticamente para o Coordenador de Acompanhamento.

![Assinatura_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/9a6c8b28-d2de-454c-8326-311f9f1ba5c8)

**PERFIL COORDENADOR DE ACOMPANHAMENTO**

- [ ] 1.  Após Finalizar o parecer a aplicação deverá trazer automaticamente o documento a ser assinado. 

- [ ] 2. Após assinar o documento deverá ser encaminhado automaticamente para o perfil de Coordenador Geral de Acompanhamento

![Assinatura_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6a18565-48ca-402c-9c4d-dfbaf6ce2f0c)

**DEMAIS PERFIS DE DIRETOR E SECRETÁRIO**

- [ ] 1. Adicionar no menu a opção de assinar parecer de readequação

-----------
**COMO DISTINGUIR O ATO ADMINISTRATIVO** 

Se o **órgão superior do  analista for diferente de 160 e de 251** o ato administrativo será **653** - Parecer Técnico de Readequação de Projeto - Vinculadas

Quando  o **órgão superior do  analista for igual a  160 ou 251** o ato administrativo será **655** - Parecer Técnico de Readequação de Projeto - MinC
-------------------------------------------------------------------------------------------------------------------

**ATO 655 - PARECER TÉCNICO DE READEQUAÇÃO DE PROJETO - MINC**

Esse ato administrativo é para **cinco** assinaturas porque o caso requer publicação no Diário Oficial da União. 

Assinarão o ato administrativo o técnico, o coordenador de acompanhamento e o coordenador-geral de Acompanhamento e Execução, o diretor e o secretário.
-------------------------------------------------------------------------------------------------------------------

**PERFIL DO TÉCNICO.**

Nesse perfil não existe a opção **DEVOLVER** porque  o técnico é o responsável pelo geração do documento a ser assinado.

**FINALIZAR**

- [ ] Ao finalizar, o técnico estará transferindo o parecer assinado para o Coordenador de Acompanhamento, 

- [ ] O que sinaliza para o sistema a transferência da posse é o atributo **siEncaminhamento** na tabela **tbReadequação.** que deverá ser preenchido com o valor **10**- Devolvido pelo Técnico para o Coordenador.

- [ ] A mudança do siEncaminhamento nesse caso transfere a posse do projeto para o perfil do coordenador de acompanhamento.

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

O coordenador de acompanhamento de posse do parecer deverá concordar ou discordar do parecer técnico.

- [ ] Se **CONCORDAR** deverá assinar e finalizar o parecer. 

- [ ] A ação de **FINALIZAR**  transferirá a posse do parecer para o coordenador geral de acompanhamento e execução.

- [ ] O que sinaliza para o sistema a transferência da posse  é o atributo **siEncaminhamento**** na tabela **tbReadequação.** que deverá ser preenchido com o valor **18**- Solicitação encaminhada ao coordenador-geral.

A mudança do siEncaminhamento  transfere a posse do projeto para o perfil do coordenador-geral de acompanhamento execução.

- [ ] Se **DISCORDAR** do parecer, o coordenador de acompanhamento devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

- [ ]  Essa ação  devolverá a posse do parecer para o técnico.

- [ ] O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** na tabela **tbReadequação.** que deverá ser atualizado** com o valor **4**- Solicitação encaminhada ao  técnico

- [ ] **S O M E N T E  ESSA AÇÃO INUTILIZARÁ O PARECER ASSINADO PELO TÉCNICO**

-------------------------------------------------------------------------------------------------------------------

**PERFIL DO COORDENADOR-GERAL DE ACOMPANHAMENTO EXECUÇÃO**

O coordenador-geral de acompanhamento e execução de posse do parecer deverá concordar ou discordar do parecer técnico.

- [ ] Se **CONCORDAR** deverá assinar e finalizar o parecer. 

- [ ] A ação de **FINALIZAR**  transferirá a posse do parecer para o diretor.

Nesse perfil, são duas as sinalizações para o sistema que indicará a transferência de posse do parecer:

- [ ] 1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser preenchido com o valor **19**- Solicitação encaminhada ao diretor.

- [ ] 2. o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **682** para a SAV e **341** para SEFIC

- [ ] A mudança do siEncaminhamento e do orgao  transfere a posse do projeto para o perfil diretor.

- [ ] Se **DISCORDAR** do parecer, o coordenador-geral de acompanhamento e execução  devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

- [ ]  Essa ação  devolverá a posse do parecer para o técnico.

- [ ] O que sinaliza para o sistema essa devolução  é o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **21**-Solicitação devolvida ao coordenador pelo coordenador-geral
--------------------------------------------------------------------------------------------------------------
**PERFIL DO DIRETOR**
O diretor de posse do parecer  deverá concordar ou discordar do parecer técnico.

- [ ] Se **CONCORDAR** deverá assinar e finalizar o parecer. 

- [ ] A ação de **FINALIZAR**  transferirá a posse do parecer para o secretário.

- [ ] Nesse perfil, são duas as sinalizações para o sistema que indicará a transferência de posse do parecer:

- [ ] 1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser preenchido com o valor **20**- Solicitação encaminhada ao secretario.

- [ ] 2. o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **160** para a SAV e **251** SEFIC

- [ ] A mudança do siEncaminhamento e do orgao  transfere a posse do projeto para o perfil secretário.

- [ ] Se **DISCORDAR** do parecer, o diretor  devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

- [ ]  Essa ação  devolverá a posse do parecer para o técnico.

Nesse perfil, são duas as sinalizações para o sistema que indicará a devolução do parecer para o técnico:

- [ ] 1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **22**- Solicitação devolvida ao coordenador pelo diretor.

- [ ] 2.  o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **171** para a SAV e **262**  para a SEFIC
-------------------------------------------------------------------------------------------------------------------

**PERFIL DO SECRETÁRIO**

O secretário de posse do documento concordará ou não com o parecer.

- [ ] Se **CONCORDAR** deverá assinar e finalizar o parecer. 

- [ ] **A AÇÃO DE FINALIZAR DEVERÁ EXECUTAR TODAS AS  AÇÕES QUE A VERSÃO ATUAL EXECUTA NO PERFIL DE COORDENADOR DE ACOMPANHAMENTO QUANDO É ACIONADO O BOTÃO F I N A L I Z A R**

- [ ] Se **DISCORDAR** do parecer, o secretário devolverá  para o técnico para uma nova análise e uma nova emissão de parecer. 

- [ ]  Essa ação  devolverá a posse do parecer para o técnico.

Nesse perfil, são duas as sinalizações para o sistema que indicará a devolução do parecer para o técnico:

- [ ] 1. o atributo **siEncaminhamento** da tabela **tbReadequação.** que deverá ser atualizado com o valor **23**- Solicitação devolvida ao coordenador pelo secretário.

- [ ] 2.  o atributo **Orgao** da tabela **Projetos**  devera ser alterado  conforme a secretaria do emitente do paracer. Sendo **171** para a SAV e **262**  para a SEFIC

**Comment by AdmissibilidadeSAV** [comment]
No perfil de Técnico de Acompanhamento quando clico em finalizar a análise de readequação de Planilha orçamentária o botão está sem ação, e deveria após a finalização do parecer a aplicação  trazer automaticamente o documento a ser assinado. Testei com os pronacs: 177473 e 164912, sem sucesso.

**Comment by vinnyfs89** [comment]
Item ajustado e disponível no ambiente de homologação. Por gentileza, verificar.

**Comment by AdmissibilidadeSAV** [comment]
**1)** Após assinatura do parecerista apareceu a tela abaixo:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/8bbb633a-f4b3-4f45-8f87-1c398c7dd1b8)

**2)** Após clicar em voltar constatei que o parecer foi assinado e encaminhado para o perfil de coordenador de parecer que quando assinou o documento também apareceu a tela acima reportada.

Ainda no perfil de Coordenador de Parecer quando listei os projetos analisados, visando finalizar a análise da readequação apareceu a tela abaixo e quando cliquei no opção "sim" o botão está sem ação, impedindo o envio da análise para assinatura do Presidente da Vinculada:

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/2b42ee07-d1db-4736-a21d-60877140b30f)

**Comment by vinnyfs89** [comment]
Ajuste realizado e disponível no ambiente de homologação.

**Comment by AdmissibilidadeSAV** [comment]
Após assinatura do Secretário apareceu a tela abaixo: 

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/c6d508e3-ac36-488b-9f7a-4098a7f16e59)

Concluindo o fluxo de assinaturas o projeto deverá retornar para a localização que demandou a análise da solicitação de readequação, visto que o Secretário assinou e o projeto permaneceu no órgão superior "SEFIC".

![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/607a8a61-e5d6-47fd-974c-ab36e34b4ac6)

**Comment by vinnyfs89** [comment]
Prezados,

Referente ao botão "Assinar" conforme conversamos com o Rômulo em reunião, para esses casos, como são poucos ele concordou em apenas redistribuir para que o fluxo onde o Documento de Assinatura é criado.

Os demais ajustes foram realizados e a nova versão está disponível no ambiente de homologação.

Por gentileza, verificar.

**Comment by vinnyfs89** [comment]
@AdmissibilidadeSAV Fiz de acordo com o workflow desenhado pelo @Romulo_Menho . Romulo, pode verificar, por gentileza?
