### ISSUE TITLE
[Admissibilidade] Histórico de Arquivamentos e Desarquivamentos

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#902]
Como gestor publico, gostaria de ter acesso ao histórico de arquivamentos e solicitações de desarquivamento de uma determinada proposta.

Segundo @boletocosta:

_deveria ser criado um campo de histórico de desarquivamento (igual existe para histórico de avaliações e enquadramento)_

**Comment by clebersantos** [comment]
@Pedro-Philipe e @wouerner essa funcionalidade já foi desenvolvida?

**Comment by Pedro-Philipe** [comment]
Não faz sentido ter um histórico de arquivamento já que esse registro só pode ser único, apenas 1 recurso de desarquivamento por proposta. Sendo possível visualizar todo tramite de solicitacoes/repostas na tela de desarquivamento.
