### ISSUE TITLE
[Admissibilidade] Lista de Solicitações de Desarquivamento separada por órgão.

### ISSUE THREAD

**Issue by decko** [culturagovbr/salic-minc#903]
Relacionada a #292.

Como gestor público, gostaria de visualizar uma lista de propostas com solicitações de desarquivamento, separadas por órgão. 

Segundo @admissibilidadeSAV:
_Ficou ótimo, mas uma coisa importante que ficou faltando é aparecer as propostas separadas por órgão, no meu perfil aparece tanto as da SAV como da SEFIC, quando deveria aparecer só as que foram classificadas como Audiovisual._
![fea72eda-5745-44e8-ae32-65a4cf53b327.png](https://images.zenhubusercontent.com/5a296d9c8a75884b908a445d/3ba7be92-10fe-4c88-9800-92bb3067159c)

Segundo @romulomb:
_Para separar as propostas SAV e da SEFIC, utilize o atributo AreaAbrangencia da tabela PreProjeto.
AreaAbrangencia = 0 -- proposta da SAV
AreaAbrangencia = 1 -- proposta da SEFIC
Acrescentar campo de pesquisa pelo nº da proposta._

**Comment by Pedro-Philipe** [comment]
@AdmissibilidadeSAV Issue aguardando homologação

**Comment by AdmissibilidadeSAV** [comment]
Está invertido, no perfil de Coordenador de Admissibilidade da SEFIC está aparecendo as propostas da SAV e no perfil de Coordenador de Admissibilidade da SAV está aparecendo as propostas da SEFIC.

**Painel da SAV**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/6a416ccf-7655-4f8f-98ca-b37129d0c40d)

**Painel da SEFIC**
![image.png](https://images.zenhubusercontent.com/5a671cee4b5806bc2bc3eb88/a6a04cd7-e753-459f-928c-18bc938e5758)
