### ISSUE TITLE
[HOTFIX] RECURSO

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#904]
1. Em todos os perfis a tela está quebrando.

2. Nem o parecerista e nem o conselheiro consegue cortar os itens orçamentários

**Comment by fernao** [comment]
* itens 1 e 2: quebra de tela - publicada em hmg correção de urls de redirecionamento
* item 3: em verificação

**Comment by romulomb** [comment]
itens 1 e 2: quebra de tela  - HOMOLOGADO

**Comment by fernao** [comment]
item 3: subi para homologação

**Comment by romulomb** [comment]
@fernao Tem certza?  Não consegui

**Comment by fernao** [comment]
item 3: liberando links de edição de planilha

**Comment by romulomb** [comment]
HOMOLOGADO 

SUBIR POR GENTILEZA PARA PRODUÇÃO.

OBRIGADO.
