### ISSUE TITLE
[BUG] - PRESTAÇÃO DE CONTAS

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#905]
Perfil de técnico, coordenador e coordenador geral de prestação de contas.

Manutenção --> Localização Física do Projeto
![PREST_2.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/2b8d155b-6839-4fdb-be91-b57bfaaff9a3)

A aplicação está com os campos de input congelados.
![PREST_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bfaf79a0-b2f7-4bd6-a99c-3cbacf9c714b)

**Comment by guiamado** [comment]
Foi percebido durante a correção do bug, que ele constava em todos os perfis que possuiam esta opção, mas já foi corrigido. Favor Testar.
@romulomb @pauli10 Disponível em homologação.
