### ISSUE TITLE
[Readequação] Saldo de aplicação - liberar link

### ISSUE THREAD

**Issue by fernao** [culturagovbr/salic-minc#914]
Liberar link para saldo de aplicação

**Comment by fernao** [comment]
Regras:
* Idênticas as das outras planilhas. Se tiver alguma sendo executada os links das outras planilhas não deverão ser liberados.
* Se captação >= 100%

**Comment by fernao** [comment]
Aumentei a complexidade devido à regra de verificação das readequações de planilha em andamento, pois agora são 3 tipos de planilhas que não podem ser executadas simultaneamente.

**Comment by romulomb** [comment]
Liberou o link para um projeto com captação inferior a 100% conforme a imagem abaixo.

![Saldo.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/a6d388da-9d18-4ad6-8a89-9837dab4d285)

**Comment by fernao** [comment]
Corrigido, favor verificar.

**Comment by romulomb** [comment]
ATUALIZAR O BANCO DE HOMOLOGAÇÃO PARA GERAR DADOS QUE  PERMITA HOMOLOGAR A FUNCIONALIDADE.
