### ISSUE TITLE
[HOTFIX] [ADMISSIBILIDADE] Desarquivamento de propostas

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#923]
Conforme conversa com Rômulo precisamos de três ajustes relacionados ao desarquivamento de propostas:

**1)** Propostas arquivadas automaticamente pelo sistema (quando o proponente não responde uma diligência no prazo de 40 dias) não aparecem na listagem de  propostas arquivadas para o proponente pedir o desarquivamento.  A situação desejada é que as propostas arquivadas automaticamente pelo sistema também fiquem disponíveis para o proponente solicitar o desarquivamento.

**2)** A avaliação que consta o indeferimento de um pedido de desarquivamento não fica registrada corretamente (parece que o campo está limitando a quantidade de caracteres).   Uma curiosidade: no perfil da SAV esse erro não acontece, mas no perfil da SEFIC sim.

Segue o caminho e o print da tela: 

Perfil Coordenador de Admissibilidade->Admissibilidade->Desarquivamento->Reprovadas-> Na coluna visualizar clicar na justificativa desejada-> Observar que o campo avaliação consta um texto limitado, que é diferente daquele que foi gravado.

Print de exemplo com a proposta 279245:	![Capturar.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/d9a7d11a-25db-4119-ba99-56f7120f2243)

**3)** Quando indeferimos um pedido de desarquivamento o proponente não consegue visualizar a avaliação que contém nossa motivação para negar o pedido. O proponente só consegue saber que o pedido foi negado. Quando ele clica no "olhinho" da coluna motivo do arquivamento só aparece o motivo que gerou o arquivamento da proposta, mas não a avaliação do pedido de desarquivamento. A situação desejada é que uma nova coluna seja acrescentada para conter um ícone que leve a avaliação do pedido de desarquivamento quando este é negado.

Segue o caminho e o print da tela: 

Perfil proponente->Proposta->Arquivadas

Print de exemplo: ![Capturar2.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/d31bb4cb-f073-46ad-9d88-fbeef3ce02dc)

Por enquanto é isso pessoal! 

Obrigado.

**Comment by boletocosta** [comment]
@romulomb  Issue criada conforme solicitado.

**Comment by romulomb** [comment]
HOTFIX

**Comment by clebersantos** [comment]
Sugiro separar o que é MELHORIA e HOTFIX em cards diferentes.

Para melhor entendimento do nosso fluxo de trabalho:
 - HOTFIX é para pequenas correções que devem ser aplicadas imeditamente no ambiente de produção, quanto maior as alterações maior é o risco de termos efeitos colaterais.
 - MELHORIA são ttarefas que geralmente demoram mais de um dia para serem feitas e necessitam de testes e validações no ambiente de homologação.

Podem separar?

**Comment by boletocosta** [comment]
Para mim todos os itens são HOTFIX, mas não sei o que o @romulomb acha...

**Comment by romulomb** [comment]
Sim pode separar

**Comment by romulomb** [comment]
JÁ SEPAREI.

**Comment by Pedro-Philipe** [comment]
@romulomb O primeiro ponto possui dessa issue possui uma espécie de cron que arquiva automaticamente as propostas, porém é necessário também gravar em outra tabela para poder recorrer ao recurso. Saberia me informar o nome dessa função/sp no banco?

**Comment by Pedro-Philipe** [comment]
@boletocosta @romulomb As alterações já estão em homologação, ficando pendente apenas resposta do Rômulo sobre a rotina de arquivamento para dar continuidade.

**Comment by Pedro-Philipe** [comment]
Sp para arquivar automaticamente: paArquivarProposta

**Comment by romulomb** [comment]
ROTINA IMPLEMENTADA.

**Comment by boletocosta** [comment]
Boa tarde.

Essa issue subiu para produção?  Os erros continuam....

**Comment by boletocosta** [comment]
Bom dia....

Essa issue subiu para produção? Os erros continuam....
