### ISSUE TITLE
[HOTFIX] - READEQUAÇÃO - SOLICITAÇÃO GERAIS

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#927]
O proponente está tentando inserir um solicitação de alteração de resumo.

A aplicação só está aceitando 300 caracteres e deveria aceita 1.000 caracteres.

Veja tela anexada.

![Resumo.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/4da785dc-1ef3-42aa-8ea0-c3c69a9a0d6d)

**Comment by clebersantos** [comment]
@romulomb esse erro deve ser corrigido imediatamente em produção?

**Comment by romulomb** [comment]
Sim
