### ISSUE TITLE
Erro ao salvar comprovante de fornecedor internacional

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#932]
Erro ao salvar comprovante de fornecedor internacional.

> PROBLEMA IDENTIFICADO
> 
> PERFIL DO PROPONENTE.
> 
> REALIZAR COMPROVAÇÃO FINANCEIRA.
> 
>     Quando a comprovação é referente a pagamento no exterior, a aplicação não lista nos itens comprovados, não permitindo a edição ou exclusão da comprovação.
> 
>     Ajustar a formatação da data de emissão.
> 

![pc-erro1](https://user-images.githubusercontent.com/287287/41247846-9f1aa410-6d85-11e8-82f8-a817ba6b1b6a.png)

**Comment by wouerner** [comment]
@wouerner Pauliane esse vai ser a issue. Qualquer coisa que quiser adicionar a mais nisso pode colocar nela.

**Comment by pauli10** [comment]
1. Quando coloca-se um fornecedor internacional o campo de preencher CPF/CNPJ não some, o que deveria acontecer. Estava sim antes e era o correto.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/d96ecb82-681a-4d31-b59f-e08906e11ade)

Os campos em destaque devem desaparecer.

2. "Tipo de Documento" deve estar acima das opções "Invoice" e "Outros".
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/ee5f2306-fd5f-4e50-bd3f-666abf9384f6)

3. Quando tenta-se anexar o comprovante de fornecedor internacional, acusa erro.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/2d8116b4-a8e9-4808-ae53-2eaa38f04a8f)

**Comment by wouerner** [comment]
32 -> 50 pontos, os erros em salvar dados dos comprovantes internacionais, está mais complexo que pensado inicialmente, os dados antigos estão sendo salvos em colunas erradas dentro do banco de dados, outro problema é que a cada novo comprovante se faz necessário  cadastrar um novo fornecedor, mesmo que já tenha cadastro ele anteriormente. A listagem e exclusão desses comprovantes  também não estão funcionando.

**Comment by wouerner** [comment]
Ajustes iniciais feitos.

**Comment by pauli10** [comment]
Todos os erros continuam:
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/554a2981-8cb5-4753-9777-84d97e3fdd39)

Qd é colocado um CNPJ para teste, acontece o mesmo erro.
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/5bc30107-645f-4ec1-9603-ab3129316802)

**Comment by romulomb** [comment]
**OBSERVAÇÃO**

Já foram corrigidos os dados do cadastro do fornecedor internacional e a query que monta grid que permite ao proponente  **EDITAR** e *EXCLUIR** a comprovação.

**Comment by wouerner** [comment]
Tivemos algumas alterações nas views de dos itens, demandando uma nova analise e refatoração. de 50 para 70.

**Comment by romulomb** [comment]
@wouerner Se a aplicação estiver utilizando a view os ajustes nela feita não altera nenhum código.

**Comment by wouerner** [comment]
Mas eu já tinha feito algumas alterações nessa  **view**, para trazer alguns colunas adicionais. Quando vc Atualizou a view apagou essas colunas, por esse motivo e vou ter que alterar a aplicação. E sim o sistema usa essa view.

**Comment by pauli10** [comment]
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/579ffeb8-32ff-429b-b635-9abbdf264bb2)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/19e6d038-8b0f-4a46-a218-9e1e1ff33848)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/0ac3b8fe-445e-4abe-b020-694af028d600)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/65078eb6-4d00-46b5-aa61-b3301ce145f7)

**Comment by romulomb** [comment]
Segue para ajuste.

**Comment by wouerner** [comment]
Estou ajustando.

**Comment by romulomb** [comment]
Não está gravando o fornecedor internacional.

**Comment by pauli10** [comment]
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/b01a5e87-6e19-487e-92a1-ef0baf79fbb8)

**Comment by romulomb** [comment]
Se precisa de ajudar par montar o Select de  comprovantes internacionais é só enviar a query.

**Comment by wouerner** [comment]
Bom dia, fiz alguns testes e achei um bug, por favor, testar novamente.

**Comment by pauli10** [comment]
Este erro continua:
![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/39e12e6c-d6aa-47d2-81b7-8bca5300fc49)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/7793a275-9bb0-453e-a317-4731ee4e680f)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/abb3b555-ce47-4913-bd9e-b3609c8d86bd)

![image.png](https://images.zenhubusercontent.com/5b0454f14b5806bc2bd42e92/81487968-d608-4b01-85e5-36d5f4bbeed7)

**Comment by romulomb** [comment]
NÃO ESTA FUNCIONANDO.

OU ENTÃO NÃO SUBIU.

**Comment by romulomb** [comment]
**AJUSTE IMPORTANTE ANTES DA SUBIDA DA NOVA VERSÃO**

Na comprovação financeira a aplicação está permitindo a inclusão de comprovante sem fornecedor cadastrado nas nossas bases.

Não está abrindo o formulário para cadastrar o fornecedor.

Sei que tem uma issue para um novo formulário de cadastro do fornecedor, mas acho prudente deixar o formulário antigo até o novo ficar disponível.

![comprovacao_1.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/d9619762-8388-42e8-b6f3-d4a1e8b8df45)
