### ISSUE TITLE
Documentação Modulo prestação de contas.

### ISSUE THREAD

**Issue by wouerner** [culturagovbr/salic-minc#964]
* Check List Documentação Prestação de Contas
- [x] lista de projetos ->Escolher o proponente 
- [x] Analisar situação do projeto -> E13 ,E12, E17
- [x] Consultar dados do projeto -> Realizar Comprovaçao
- [x] escolher um item de custo 
- [x] comprovar  pagamento ->o valor comprovado não pode passar do valor aprovado

**Comment by marcosvanille** [comment]
a documentação já esta desenvolvida.
