### ISSUE TITLE
[HOTFIX] - SOLICITAR DESARQUIVAMENTO DE PROPOSTA.

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#965]
PERFIL PROPONENTE.

Ao listar propostas arquivadas a tela congela.
![desarquivar.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/8b2aa5cf-8190-4477-b572-bc47bdc77d6d)

**NA HOMOLOGAÇÃO FUNCIONA PERFEITAMENTE**

**Comment by clebersantos** [comment]
@romulomb, fiz os testes com o mesmo proponente e funcionou. Pode solicitar mais informações do erro? Navegador utilizado, por exemplo.

![Screenshot from 2018-06-20 14-28-15.png](https://images.zenhubusercontent.com/5a4f83d7a016c5b034bc22d3/45caca63-c42e-4b1e-beaf-f7b92641a52b)

**Comment by boletocosta** [comment]
@clebersantos, pelo usuário logado no print que vc mandou deduzo que vc testou em homologação. 

Contudo, em homolog funciona perfeitamente... conforme já descrito na issue. 

O problema está na produção.

**Comment by clebersantos** [comment]
@boletocosta, fiz o teste no ambiente de desenvolvimento. 

Para realizar o teste utilizei o banco de dados de homologação, atualizado ontem (19/06), com os mesmos dados de produção. Não há diferença de código e dados com o ambiente de produção. Por este motivo, o mais provável é que tenha algo relacionado com o ambiente do usuário.

**Comment by romulomb** [comment]
@AdmissibilidadeSAV Thais tem como homologar essa issue?

@boletocosta André tem como homologar essa issue?

**Comment by AdmissibilidadeSAV** [comment]
@romulomb Segunda-feira darei uma olhada, hoje ainda estava sem conseguir cadastrar proponente nem pude testar.

**Comment by AdmissibilidadeSAV** [comment]
Testando aqui no ambiente de produção (que é onde foi relatado o problema) consegui listar as propostas arquivadas normalmente. Por mim está homologada.

@boletocosta por favor verifique.

**Comment by boletocosta** [comment]
Estranho... o erro continua para alguns CPFs, mas para outros funciona normal.
Exemplo: 36898553810 funcionou, mas 08768653689 o erro continua.
Creio que o mesmo está acontecendo para os proponentes, pois alguns conseguem visualizar as propostas arquivadas, outros continuam relatando o erro.
Não sei o que pode estar acontecendo....

**Comment by clebersantos** [comment]
@boletocosta @Pedroeoq acho que esse erro pode estar relacionando com o bug que vc corrigiu no arquivamento. Pode verificar?

**Comment by Pedro-Philipe** [comment]
@boletocosta Sim

**Comment by Pedro-Philipe** [comment]
Problema causado por um bug relacionado a falta de gravação do MotivoArquivamento em PreProjetoArquivado. Analisando com o @romulomb forma de corrigir os projetos afetados.

**Comment by boletocosta** [comment]
Alguma novidade? Erro foi corrigido?  Subiu para produção?

Na homologação funciona, mas em produção ainda estamos com o problema...

**Comment by Pedro-Philipe** [comment]
@romulomb Seguiremos o fluxo que comentei com você executando o script no banco ?

**Comment by donbarata** [comment]
Aqui o erro persiste. E só na conta que há um projeto arquivado. Os proponentes sem projeto arquivado carregam completamente. Já esse:

![e969fdcd-93a6-4eba-8f45-d98d2b3e5976](https://user-images.githubusercontent.com/40779099/42227129-2e89a53c-7eb7-11e8-9630-ab0590639269.png)

**Comment by boletocosta** [comment]
Bom dia.

Alguma novidade? Erro foi corrigido? Subiu para produção?

Na homologação funciona, mas em produção ainda estamos com o problema..

**Comment by Pedro-Philipe** [comment]
@boletocosta @boletocosta, já testou em hmg para poder subir?

**Comment by boletocosta** [comment]
Em homolog funciona. Pode subir
