### ISSUE TITLE
[HOTFIX] - REMANEJAMENTO DE 50%

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#966]
VEJA A TELA ANEXADA.

![Remanejamento.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/eae32f97-cf3a-4b4a-8433-f332f1356cda)

PRONAC 17-2212

PROPONENTE : Associação Cultural Lirius

**Comment by romulomb** [comment]
AINDA CONTINUA  O PROBLEMA.

PRONAC PARA TESTAR **176260** - Liga Independente das Escolas de Samba de São Paulo

É só tentar finalizar. 

**ESTÁ APRESENTANADO DIFERENÇA DE R$ 0,01.**

**Comment by romulomb** [comment]
**HOMOLOGADO**


Por gentileza subir para a produção.

**Comment by romulomb** [comment]
ESTÁ ISSUE SUBIU PARA PRODUÇÃO?

**Comment by clebersantos** [comment]
@romulomb Sim. 

https://github.com/culturagovbr/salic-minc/releases/tag/v4.1.17
