### ISSUE TITLE
[BUG] - CADASTRAR PROPONENTE

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#981]
Esse problema ocorre somente no ambiente de homologação.

![tela.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/480000bc-3388-4c04-ba37-5322d0ac5d86)

**Comment by marcusvinicus** [comment]
@Heron está tratando. Problema com sincronização dos bancos
