### ISSUE TITLE
[HOTFIX] - COMPROVAÇÃO FINANCEIRA

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#983]
**Perfil do Proponente**

A aplicação está trazendo a planilha errada para comprovar.

No pronac **158856 - AMA Santos Dumont - 2016** - ASSOCIACAO ACAO EM MOVIMENTO ARTISTICOS DE SANTOS DUMONT - AMASD.

O valor aprovado é R$ 310.000,00 e o sistema traz uma planilha de R$ 549.641,49.

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/3ca4e906-6043-4898-8301-34cfe1ace0a7)

**Comment by romulomb** [comment]
Posso ajudar se me mandarem a query que está sendo utilizada.

**Comment by romulomb** [comment]
**PESSOAL ESSE HOTFIX É URGENTÍSSIMO, O SISTEMA ESTÁ APRESENTANDO A PLANILHA ERRADA PARA COMPROVAÇÃO.**

Segue mais um PRONAC  131493 - Restauração dos elementos artísticos móveis e integrados da Igreja de Santana

 PROPONENTE - Paróquia do Santíssimo Sacramento e Sant´Ana

**Valor aprovado R$ 5.497.020,38** e o sistema apresenta um planilha para **comprovar de R$  	R$ 10.469.387,42**.

**OBSERVAÇÃO: ACHO QUE A QUERY NÃO ESTA COM A RESTRIÇÃO DE PLANILHA ATIVA OU SEJA STATIVO = 'S'**

**Comment by clebersantos** [comment]
@romulomb, após uma longa análise, verifiquei que o erro estava relacionando à uma função no banco de dados (`fnVlAprovado_Fonte_Produto_Etapa_Local_Item`) utilizada na query para obter o valor aprovado do item. Substitui a função pelo código: 
`CONVERT(DECIMAL(38,2), ISNULL((a.qtItem * a.nrOcorrencia * a.vlUnitario),0)) as vlAprovado`  e os valores ficaram corretos.

Estou disponibilizando no ambiente de homologação para análise.

Corrigi também a ordenação dos itens, mantendo o padrão das planilhas do sistema.

**Comment by romulomb** [comment]
Como lhe disse o erro persiste.

Utilize a view que lhe encaminhei que funcionará

![comprovacao.png](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/f1335d06-efcb-42bb-b989-4fddbada0687)

**Comment by clebersantos** [comment]
@romulomb, conforme conversamos apenas utilizar a view `vwComprovacaoFinanceiraProjeto` não resolve o problema. O sistema utiliza informações como o atributo `idPlanilhaAprovacao` que a view não retorna. Para remover este campo tenho que refatorar a aplicação, mas estou resolvendo isso. 

Obrigado

**Comment by clebersantos** [comment]
@romulomb, conforme conversamos, apenas utilizar a view `vwComprovacaoFinanceiraProjeto` não resolve o problema. O sistema utiliza informações que a view não retorna, como o atributo `idPlanilhaAprovacao`. Para remover este campo tenho que refatorar a aplicação. Estou analisando a view e a aplicação para encontrar a melhor solução.

Obrigado

**Comment by clebersantos** [comment]
@romulomb, conforme conversamos, apenas utilizar a view `vwComprovacaoFinanceiraProjeto` não resolve o problema. O sistema utiliza informações que a view não retorna, como o atributo `idPlanilhaAprovacao`. Para remover este campo tenho que refatorar a aplicação. Estou analisando a view e a aplicação para encontrar a melhor solução.

Obrigado

**Comment by clebersantos** [comment]
Com ajuda do @romulomb, a listagem dos itens aprovados para comprovação foi atualizada. 

Funcionalidade disponível para homologação.

**Comment by romulomb** [comment]
HOMOLOGADO.


PODE SUBIR PARA PRODUÇÃO


OBRIGADO.

**Comment by clebersantos** [comment]
@romulomb Disponível em produção.

**Comment by pauli10** [comment]
@romulomb e @clebersantos , fechamos esta issue, mas continuamos com erro no Pronac 13 1493. Apenas o 158856 foi corrigido.

Estamos com diferentes valores aprovados nas mais diversas telas: página inicial, planilha aprovada e planilha comprovada. Conforme telas abaixo:
![image](https://user-images.githubusercontent.com/39531450/42098169-74810ece-7b90-11e8-8189-65871d5d7b3a.png)

![image](https://user-images.githubusercontent.com/39531450/42098216-9b6b709c-7b90-11e8-9439-42da20344a06.png)

![image](https://user-images.githubusercontent.com/39531450/42098228-a9713898-7b90-11e8-819b-3af30899f511.png)

**Comment by clebersantos** [comment]
@pauli10 Pauliane, esse erro não tem relação com esta issue.

Conversei com o @Romulo_Menho  e ele está verificando o problema na planilha aprovada,  pois é uma SP(stored procedure) que monta a planilha.

O problema em consultar dados do projeto é de uma tela que ainda está em desenvolvimento. Você pode verificar em produção que o valor está correto.
