### ISSUE TITLE
[HOTFIX] - ÁREA E SEGMENTO AO TRANSFORMAR

### ISSUE THREAD

**Issue by boletocosta** [culturagovbr/salic-minc#984]
Conforme solicitado pelo @romulomb, segue a descrição do comportamento atual e de como ele deveria ser:

**COMPORTAMENTO ATUAL**

Ao transformar uma proposta em projeto o sistema grava a área e o segmento apresentado pelo proponente no cadastro do produto principal.

Print da tela:  ![Capturar.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/b74a5a0d-99a1-438a-bd2d-2d7a0f519665)

**COMPORTAMENTO ESPERADO**

Ao transformar uma proposta em projeto o sistema deverá gravar a área e o segmento **na tabela Projetos** sugerido pelo coordenador geral de admissibilidade e aprovação ou seja:

1. pegar o atributo **id_area** e o atributo **id_segmento** da tabela **sugestao_enquadramento** .

2. grava nos atributos **Area** e **Segmento** na tabela **Projetos**.

Print da tela: ![Captura2r.JPG](https://images.zenhubusercontent.com/5a6249b64b5806bc2bc377bf/8f98a09f-03aa-4303-a6f5-2cb5368b2706)

Proposta para testar na homologação:  280206 - Manutenção do Museu Inimá de Paula - 2019

**Comment by AdmissibilidadeSAV** [comment]
@clebersantos Verifiquei e está ok.

**Comment by boletocosta** [comment]
Homologado!

**Comment by clebersantos** [comment]
Pode subir para produção?

**Comment by boletocosta** [comment]
Pode subir
