### ISSUE TITLE
[HOTFIX] - PLANO DE DISTRIBUIÇÃO

### ISSUE THREAD

**Issue by romulomb** [culturagovbr/salic-minc#993]
**PERFIL DO COORDENADOR DE ACOMPANHAMENTO**

Ao finalizar o parecer a tela quebra.

**Painel de Analisados**

PRONAC - 158439 - JUCA: o canto de simbinga

![Redeaquacao.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/bb563ff5-3812-47a7-8d12-8e56dad4321d)

![Quebrou.jpg](https://images.zenhubusercontent.com/5ab2cd464b5806bc2bcbd789/c03b6886-a725-454a-b8b2-4de117d8b5cf)

**PERFIL DO PROPONETE**

Ao tentar enviar a tela quebra

[https://app.zenhub.com/files/104502087/83bbe043-fc7d-4e79-8ba1-71b6ad1ef6d7/download](https://app.zenhub.com/files/104502087/83bbe043-fc7d-4e79-8ba1-71b6ad1ef6d7/download)

**Comment by clebersantos** [comment]
O problema reportado ocorre devido a um erro da readequação do plano de distribuição, desenvolvido para projetos anteriores à IN 2017.

Preciso de um pouco mais de tempo para analisar o impacto da correção.

Na análise inicial verifiquei que o sistema gravava o valor da coluna `precoUnitarioNormal da tabela `PlanoDistribuicaoProduto` na coluna `vlUnitarioNormal` da tabela `tbPlanoDistribuicao`. 

Já desenvolvi um possível solução, mas é necessário alguns testes antes de disponibilizar para teste.

**Comment by clebersantos** [comment]
Após análise, constatei que o sistema está gravando corretamente os valores, haja vista que o plano de distribuição dos projetos anteriores à IN 2017 utilizam a coluna `vlUnitarioNormal` para gravar o valor do preço unitário normal do produto. O erro acontece porque a coluna `precoUnitarioNormal` não aceita `NULL` e no caso citado anteriormente deverá ser `NULL` ou `0` (zero).

@romulomb o que você acha melhor? Remover a restrição (`NOT NULL`) da coluna ou atribuir zero na aplicação?

**Comment by romulomb** [comment]
Concordei com a argumentação .
