### ISSUE TITLE
Erro na exibição de listagem da área de projetos arquivados

### ISSUE THREAD

**Issue by donbarata** [culturagovbr/salic-minc#994]
Não é possível visualizar a lista de projetos de um dos meus cadastros de proponente. Como posso sanar isto?

![e969fdcd-93a6-4eba-8f45-d98d2b3e5976](https://user-images.githubusercontent.com/40779099/42192931-43c64a74-7e42-11e8-84b1-b9a7d6e8542a.png)

**Comment by Pedro-Philipe** [comment]
@donbarata O problema relatado já foi registrado anteriormente, e está em andamento na issue #965. Vou fechar essa issue para evitar duplicação. Favor acompanhar a outra issue, obrigado.

**Comment by romulomb** [comment]
RESOLVIDO
